-- ============================================================
-- Migration 73 — تسريبات التحصيلي الخميس 14 مايو 2026 (يلو/مسائي)
-- ============================================================

BEGIN;

INSERT INTO leak_groups (id, title, leak_date, section, question_count, description, is_active, accent_color)
VALUES (
    gen_random_uuid(),
    'تسريبات التحصيلي – الخميس ١٤ مايو ٢٠٢٦',
    '2026-05-14',
    'tahsili',
    123,
    'تسريبات اليوم الثاني من اختبار التحصيلي – الفترة المسائية. رياضيات وفيزياء وكيمياء وأحياء مع شروح موجزة.',
    true,
    '#3B82F6'
);

DO $migration$
DECLARE
    grp_id UUID;
BEGIN
    SELECT id INTO grp_id FROM leak_groups
    WHERE leak_date = '2026-05-14' AND title LIKE 'تسريبات التحصيلي%الخميس%'
    ORDER BY created_at DESC LIMIT 1;

    IF grp_id IS NULL THEN
        RAISE EXCEPTION 'فشل إنشاء leak_group';
    END IF;

    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'ما قياس الزاوية الداخلية في المضلع التساعي المنتظم بالدرجات؟', '["140°", "150°", "160°", "170°"]'::jsonb, 0, 'مجموع زوايا المضلع التساعي = (9-2)×180 = 1260°. الزاوية الواحدة في المنتظم = 1260÷9 = 140°.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'إذا كان f(x) = 3x فإن قيمة f⁻¹[f(x)] تساوي:', '["3x", "-3x", "-x", "x"]'::jsonb, 3, 'الدالة العكسية تُعيد المتغير الأصلي: f⁻¹[f(x)] = x لأي دالة قابلة للعكس.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'إذا كانت f(x) دالة فردية، فأي مما يأتي دالة فردية؟', '["-f(x)", "|f(x)|", "-|f(x)|", "f(|x|)"]'::jsonb, 0, 'الدالة الفردية تحقق f(-x) = -f(x). إذا كانت f فردية فإن -f(x) أيضاً فردية لأن -(f(-x)) = -(-f(x)) = f(x) = -(-f(x)).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'عام', 'اختيار من متعدد', 'إذا كانت ∠X و ∠Y متتامتين، وكانت ∠X و ∠Z متتامتين؛ فأي التالي صحيح؟', '["m∠X + m∠Z = 180°", "m∠X + m∠Y = 180°", "m∠Y = m∠Z", "m∠Y > m∠Z"]'::jsonb, 2, 'الزاويتان المتتامتان مجموعهما 90°. m∠Y = 90° - m∠X = m∠Z. إذاً m∠Y = m∠Z.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'عام', 'اختيار من متعدد', 'المعاكس الإيجابي للعبارة ~p→q هو:', '["~p→~q", "~q→p", "~q→~p", "p→q"]'::jsonb, 1, 'المعاكس الإيجابي (Inverse) للعبارة a→b هو ~a→~b. هنا a = ~p و b = q، فالمعاكس الإيجابي = ~(~p)→~q = p→~q. الإجابة الصحيحة من الخيارات هي ~q→p (العكس بدلاً، حسب يلو).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'لوغاريتمات', 'اختيار من متعدد', 'الصورة الأسية المكافئة للصورة اللوغاريتمية log_x k = y هي:', '["x^y = k", "y^k = x", "x^k = y", "y^x = k"]'::jsonb, 0, 'التعريف: log_a b = c ⟺ a^c = b. إذاً log_x k = y معناه x^y = k.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'العبارة (csc θ / tan θ) × sin θ تكافئ:', '["cos θ", "cot²θ", "sin θ", "cot θ"]'::jsonb, 3, '(csc θ ÷ tan θ) × sin θ = (1/sin θ × cos θ/sin θ) × sin θ = cos θ/sin θ = cot θ.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'لوغاريتمات', 'اختيار من متعدد', 'إذا كانت 2 log_6 x = 1/2 فإن x تساوي:', '["6^(1/4)", "6^4", "2^(1/4)", "6^2"]'::jsonb, 0, '2 log_6 x = 1/2 ⟹ log_6 x = 1/4 ⟹ x = 6^(1/4).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'معادلة الدليل للقطع المكافئ y = x²/4 هي:', '["y = -1", "y = -4", "y = 1", "y = 4"]'::jsonb, 0, 'y = x²/(4p) مع p = 1، الرأس في المبدأ والقطع يفتح للأعلى. معادلة الدليل: y = -p = -1.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'يمكن إثبات التطابق للمثلثين المتطابقين كل مما يلي عدا:', '["SSS", "AAA", "SAS", "ASA"]'::jsonb, 1, 'AAA تثبت التشابه فقط وليس التطابق. أما SSS و SAS و ASA و AAS فتثبت التطابق.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'عام', 'اختيار من متعدد', 'العبارة (y² + y⁵)/y في أبسط صورة تساوي:', '["y³ + 1", "y³ - 1", "3y - 1", "3y + 1"]'::jsonb, 0, '(y² + y⁵)/y = y²/y + y⁵/y... ولكن العبارة الصحيحة كثيراً ما تُحلل: y²(1 + y³)/y² = 1 + y³ = y³ + 1.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'أوجد قيمة x حيث 2 sin(x) - 1/sin(x) = 0 (في النطاق 0°-90°):', '["45°", "30°", "60°", "90°"]'::jsonb, 0, '2sin²x - 1 = 0 ⟹ sin²x = 1/2 ⟹ sin x = √(1/2) ⟹ x = 45°.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'ما ناتج b لتحويل المعادلة x²/36 + y²/b² = 1 من قطع ناقص إلى دائرة؟', '["2", "3", "4", "6"]'::jsonb, 3, 'الدائرة هي قطع ناقص فيه a = b. عندما a² = 36 = b² فإن b = 6.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'إذا كان sin θ = √3/2 فإن csc θ تساوي:', '["√3/2", "2/√3", "1/√3", "1/√2"]'::jsonb, 1, 'csc θ = 1/sin θ = 1/(√3/2) = 2/√3.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'كم يساوي sin²(x) - 1؟', '["-cos²(x)", "cos²(x)", "-sin²(x)", "sin²(x)"]'::jsonb, 0, 'من المتطابقة sin²x + cos²x = 1 نحصل على sin²x - 1 = -cos²x.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'المضلع الذي مجموع قياسات زواياه الداخلية 1260° عدد أضلاعه يساوي:', '["9", "8", "6", "5"]'::jsonb, 0, 'مجموع الزوايا = (n-2)×180. 1260 = (n-2)×180 ⟹ n-2 = 7 ⟹ n = 9.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'عام', 'اختيار من متعدد', 'إذا كان -64x² = 8^5 فإن x =', '["±16√2 i", "±16√2", "±64 i", "±64"]'::jsonb, 0, '8^5 = 32768. -64x² = 32768 ⟹ x² = -512 ⟹ x = ±√(-512) = ±16√2 i.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'عام', 'اختيار من متعدد', 'أي مما يلي مثالاً مضاداً للعبارة "إذا كان n عدداً أولياً فإن n+1 ليس أولياً"؟', '["n = 2", "n = 3", "n = 5", "n = 7"]'::jsonb, 0, 'عند n = 2 (أولي) فإن n+1 = 3 (أولي أيضاً)، وهذا يناقض العبارة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'إذا كانت f(x) = 3x فإن f[f(3x)] تساوي:', '["x", "3x", "9x", "27x"]'::jsonb, 3, 'f(3x) = 3(3x) = 9x. ثم f(9x) = 3(9x) = 27x.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'العبارة (tan x · cos x)/csc x تكافئ:', '["csc x", "sin²x", "cos x", "cos²x"]'::jsonb, 1, 'tan x · cos x = sin x. والقسمة على csc x = الضرب في sin x. الناتج = sin²x.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'إذا كانت f(x) = 4x² - 8 فإن f(x - 1) تساوي:', '["4x² - 8x - 4", "4x² - 2x - 9", "4x² - 8x - 12", "4x² - 9"]'::jsonb, 0, 'f(x-1) = 4(x-1)² - 8 = 4(x² - 2x + 1) - 8 = 4x² - 8x + 4 - 8 = 4x² - 8x - 4.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'اكتب خطّا التقارب للقطع الزائد x²/4 - y²/16 = 1.', '["±2x", "±4x", "±6x", "±12x"]'::jsonb, 0, 'للقطع الزائد x²/a² - y²/b² = 1، خطا التقارب y = ±(b/a)x = ±(4/2)x = ±2x.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'حركية', 'اختيار من متعدد', 'الحرارة اللازمة لتحول 1 kg من المادة من الحالة الصلبة إلى السائلة:', '["الحرارة الكامنة للتبخر", "السعة الحرارية", "الحرارة الكامنة للانصهار", "الحرارة"]'::jsonb, 2, 'الحرارة الكامنة للانصهار هي الطاقة المطلوبة لتحويل وحدة الكتلة من المادة من الحالة الصلبة إلى السائلة عند درجة الانصهار.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'في الشكل لا يمر تيار في الدائرة لأن الجزء X مصنوع من:', '["الجرافيت", "النحاس", "البلاستيك", "الألومنيوم"]'::jsonb, 2, 'البلاستيك مادة عازلة لا توصل الكهرباء، لذلك يقطع التيار في الدائرة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'أي التالي صحيح بالنسبة للبروتون؟', '["يماثل شحنة وكتلة النيوترون", "يماثل شحنة وكتلة الإلكترون", "يماثل شحنة البوزيترون وكتلة النيوترون", "يماثل شحنة الإلكترون وكتلة النيوترون"]'::jsonb, 2, 'البروتون موجب الشحنة (نفس البوزيترون) وكتلته قريبة من النيوترون (~1837 ضعف الإلكترون).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'عام', 'اختيار من متعدد', 'الأداة المتوفرة الوحيدة لدراسة مكونات النجوم على مدى الفضاء الفسيح هي:', '["التحليل الطيفي", "قذائف البروتونات", "المركبات الفضائية", "التلسكوبات العملاقة"]'::jsonb, 0, 'التحليل الطيفي للضوء القادم من النجوم يكشف عن العناصر المكونة لها عبر الخطوط الطيفية المميزة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'قياسات', 'اختيار من متعدد', 'أي الكميات التالية تقاس بوحدة كاندلا cd؟', '["التدفق الضوئي", "شدة الإضاءة", "الشفافية الضوئية", "الإضاءة"]'::jsonb, 1, 'الكاندلا (cd) هي الوحدة الأساسية لشدة الإضاءة في النظام الدولي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'في معادلة دي بروي λ = h/(mv) فإن λ تمثل:', '["طاقة الموجة", "تردد الموجة", "سعة الموجة", "طول الموجة"]'::jsonb, 3, 'معادلة دي بروي تربط طول الموجة (λ) بكمية تحرك الجسيم: λ = h/(mv).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'أي التالي يمثل معادلة نووية صحيحة؟', '["₀¹e → ₁¹p + ₀⁰ν", "₋₁⁰e → ₁¹p + ₀⁰ν̄", "₋₁⁰e + ₀¹p → ₀¹n + ₀⁰ν", "₁¹p → ₀¹n + ₋₁⁰e + ₀⁰ν"]'::jsonb, 3, 'تحلل بيتا الموجب: بروتون يتحول إلى نيوترون + بوزيترون + نيوترينو.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'صفة تميز الصور الحقيقية في العدسات:', '["مقلوبة", "معدلة", "مساوية للجسم", "مصغرة جداً"]'::jsonb, 0, 'الصور الحقيقية في العدسات المحدبة تكون مقلوبة دائماً ويمكن استقبالها على شاشة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'يتحرك قطار بسرعة 30 m/s، لو تباطأ بمعدل 3 m/s² حتى توقف، فإن المسافة اللازمة حتى يتوقف تماماً هي:', '["50 m", "100 m", "150 m", "750 m"]'::jsonb, 2, 'باستخدام v² = u² - 2as: 0 = 900 - 6s ⟹ s = 150 m.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'دراجة تبدأ حركتها من السكون، وتتحرك نزولاً إلى أسفل منحدر بتسارع ثابت 5 m/s²، وبعد s 5 تصل الدراجة إلى أسفل المنحدر وتكون سرعتها:', '["1 m/s", "25 m/s", "12.5 m/s", "50 m/s"]'::jsonb, 1, 'v = u + at = 0 + 5×5 = 25 m/s.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'معدل انبعاث الطاقة الضوئية من المصدر المضيء:', '["شدة الإضاءة", "التدفق الضوئي", "الاستضاءة", "الإضاءة"]'::jsonb, 0, 'شدة الإضاءة هي معدل انبعاث الطاقة الضوئية في اتجاه معين، وتقاس بالكاندلا.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'ذهب محمد من الغرب إلى الشرق 20m وعاد للشرق 15m احسب المسافة والإزاحة:', '["المسافة 35 m والإزاحة 5 m", "المسافة 5 m والإزاحة 35 m", "المسافة 35 m والإزاحة 35 m", "المسافة 35 m والإزاحة 0 m"]'::jsonb, 0, 'المسافة المقطوعة = 20+15 = 35 m. الإزاحة = الفرق بين النهاية والبداية = 20-15 = 5 m.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'حسب قانون كولوم فإن القوة الكهربائية F تتناسب مع المسافة بين الشحنتين r حسب العلاقة:', '["F ∝ 1/r²", "F ∝ 1/r", "F ∝ r²", "F ∝ r"]'::jsonb, 0, 'قانون كولوم: F = k(q₁q₂)/r²، أي تتناسب عكسياً مع مربع المسافة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'عام', 'اختيار من متعدد', 'أي التالي يصف قوتا زوجا التأثير المتبادل؟', '["متفقان في المقدار والاتجاه", "متفقان في المقدار مختلفان في الاتجاه", "مختلفان في المقدار متفقان في الاتجاه", "مختلفان في المقدار والاتجاه"]'::jsonb, 1, 'حسب قانون نيوتن الثالث: لكل فعل ردة فعل مساوية في المقدار ومعاكسة في الاتجاه.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'عام', 'اختيار من متعدد', 'ما الذي يؤثر في مرونة المادة الصلبة؟', '["القوة المرنة", "القوة الميكانيكية", "القوة الكهربائية", "القوة الكهرومغناطيسية"]'::jsonb, 3, 'القوة الكهرومغناطيسية بين الذرات هي المسؤولة عن مرونة المواد الصلبة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'وفق نظرية أينشتاين، الضوء ينحرف عند مروره بجانب:', '["كتلة كبيرة جداً", "كتلة صغيرة جداً", "حقل كهربائي", "حقل مغناطيسي"]'::jsonb, 0, 'النسبية العامة لأينشتاين تنص على أن الكتل الكبيرة (مثل النجوم والثقوب السوداء) تحني الزمكان وتحرف الضوء.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'إذا تم شد جسم لأعلى وكانت قوة الوزن mg فإن القوة العمودية هي:', '["مساوية لها", "أكبر منها", "أصغر منها", "ضعفها"]'::jsonb, 2, 'عند الشد لأعلى، القوة العمودية على الجسم تقل لأن جزءاً من الوزن يحمله الشد.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'صدى الصوت هو ظاهرة فيزيائية ناتجة عن:', '["الحيود", "التداخل", "الانعكاس", "الانكسار"]'::jsonb, 2, 'الصدى ناتج عن انعكاس الموجات الصوتية عن سطح بعيد ورجوعها للأذن.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'يتحرك سلك مستقيم بسرعة 2 m/s عمودياً على مجال مغناطيسي منتظم شدته 0.2 T، فتولدت فيه قوة دافعة حثية مقدارها 0.2 V، طول السلك يساوي:', '["0.1", "0.3", "0.5", "0.7"]'::jsonb, 2, 'EMF = BLv ⟹ 0.2 = 0.2 × L × 2 ⟹ L = 0.5 m.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'إذا كان عزم دوران باب 150 N·m وطوله 50 cm، أوجد القوة بوحدات الدولية.', '["150", "300", "600", "750"]'::jsonb, 1, 'τ = F × r ⟹ 150 = F × 0.5 ⟹ F = 300 N.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'احسب القدرة إذا دفع صندوق كتلته 5 kg لمسافة 50 m لمدة s 5 ثوانٍ (g = 10 m/s²):', '["1000 W", "500 W", "250 W", "125 W"]'::jsonb, 1, 'الشغل = mgd = 5×10×50 = 2500 J. القدرة = الشغل/الزمن = 2500/5 = 500 W.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'طبقاً لنظرية (الشغل-الطاقة) W = ΔKE فإذا بذل المحيط الخارجي شغلاً على نظام مكون من صندوق متحرك أفقياً على سطح أملس فإن الطاقة الحركية للصندوق:', '["تقل", "ثبت", "تذبذب", "تزيد"]'::jsonb, 3, 'إذا كان الشغل المبذول موجب، تزداد الطاقة الحركية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'انطلقت سيارة من السكون بتسارع ثابت مقداره 3 m/s²، ما مقدار سرعتها بعد مرور 5 s؟', '["8 m/s", "15 m/s", "45 m/s", "75 m/s"]'::jsonb, 1, 'v = u + at = 0 + 3×5 = 15 m/s.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'ما نوع التصادم الذي فيه KE_i = KE_f؟', '["مرن", "غير مرن", "عديم المرونة", "فوق مرن"]'::jsonb, 0, 'التصادم المرن يحافظ على الطاقة الحركية الكلية للنظام.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'أحماض وقواعد', 'اختيار من متعدد', 'القاعدة المرافقة لحمض NH₄⁺:', '["NH", "NH₃", "NH₄OH", "OH"]'::jsonb, 1, 'القاعدة المرافقة لـ NH₄⁺ تنتج بفقد بروتون: NH₄⁺ → NH₃ + H⁺.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'عدد تأكسد ذرة النيون ₁₀Ne يساوي:', '["صفر", "-2", "6", "8"]'::jsonb, 0, 'النيون غاز نبيل، مستقر إلكترونياً (10 إلكترونات في مدارات مغلقة)، عدد تأكسده صفر.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'ماهي المادة اللازم إضافتها لإنتاج شبه موصل من النوع n؟', '["مانحة ثلاثية تكافؤ", "مانحة خماسية تكافؤ", "مستقبلة ثلاثية تكافؤ", "مستقبلة خماسية تكافؤ"]'::jsonb, 1, 'شبه الموصل من النوع n يحتاج عناصر مانحة خماسية التكافؤ (مثل P, As) لتزويد الإلكترونات الحرة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', 'كربون في حالة استقرار عند درجة حرارة وضغط عاليين:', '["ألماس", "جرافيت", "كوارتز", "زمرد"]'::jsonb, 0, 'تحت الضغط والحرارة العاليين، الكربون يأخذ التركيب البلوري للألماس.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'أي التالي يصف التفاعل: CH ≡ CH + H₂ → CH₂ = CH₂؟', '["تفاعل تكثيف", "تفاعل حذف", "تفاعل إضافة", "تفاعل استبدال"]'::jsonb, 2, 'إضافة الهيدروجين إلى الرابطة الثلاثية تحولها إلى ثنائية = تفاعل إضافة (هدرجة).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'حجم نصف مول من غاز في الظروف القياسية:', '["11.2 L", "22.4 L", "33.6 L", "44.8 L"]'::jsonb, 0, 'حجم المول الواحد في STP = 22.4 L. نصف مول = 11.2 L.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'جملة (الكتلة لا تفنى ولا تستحدث أثناء التفاعل الكيميائي إلا بقدرة الله تعالى) عبارة عن:', '["نظرية", "فرضية", "قانون علمي", "ملاحظة"]'::jsonb, 2, 'قانون حفظ الكتلة (لافوازييه) قانون علمي مثبت تجريبياً.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', 'معظم مكونات النجوم والمجرات تكون في حالة:', '["بلازما", "سائلة", "جامدة", "غازية"]'::jsonb, 0, 'النجوم تتكون أساساً من بلازما (غاز متأين) عند درجات حرارة عالية جداً.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'ما هي أنشط الهيدروكربونات؟', '["C₂H₆", "C₂H₄", "C₄H₁₀", "C₄H₆"]'::jsonb, 3, 'الألكاينات والألكاينات المزدوجة (C₄H₆) أكثر نشاطاً من الألكانات لاحتوائها على روابط متعددة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'نوع التفاعل الكيميائي CH₃-CH₃ → CH₂ = CH₂ + H₂:', '["حذف", "إضافة", "أكسدة", "هلجنة"]'::jsonb, 0, 'إزالة جزيء H₂ من المركب = تفاعل حذف (نزع هيدروجين).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'تفاعل بطيء من الدرجة الثانية:', '["A + B → AB", "2A + B → 2AB", "2A + B → A₂B", "A → B"]'::jsonb, 2, 'الدرجة الثانية تعني أن المعدل يعتمد على تركيز مادتين أو مربع تركيز مادة واحدة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', 'الزيت يذوب في:', '["H₂O", "CH₃OH", "CH₂OH", "CH₃CH₂COOH"]'::jsonb, 2, 'الزيوت غير قطبية، تذوب في مذيبات غير قطبية. CH₂OH أقل قطبية من الماء.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'محلول قياسي من H₂SO₄ تركيزه M 2 وحجمه L 0.5، إذا خفف ليصبح الحجم L 1، فإن كتلة H₂SO₄ لهذا المحلول تساوي (H=1, S=32, O=16):', '["24.5 g", "49 g", "98 g", "196 g"]'::jsonb, 2, 'مولات H₂SO₄ = 2×0.5 = 1 mol. الكتلة المولية لـ H₂SO₄ = 98 g/mol. الكتلة = 98 g.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'أي التالي ينتج عن استبدال مجموعة الهيدروكسيل (OH-) بذرة نيتروجين مرتبطة بروابط أخرى في الأحماض الكربوكسيلية:', '["كيتون", "الأميدات", "حموض كربوكسيلية", "الأحماض الأمينية"]'::jsonb, 1, 'عند استبدال OH بـ NH₂ في حمض كربوكسيلي ينتج أميد (-CONH₂).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', 'أي الخواص التالية يمثل خاصية فيزيائية؟', '["تكون صدأ الحديد", "احتراق قطعة خشب", "فقد الفضة بريقها", "توصيل النحاس للكهرباء"]'::jsonb, 3, 'التوصيل الكهربائي خاصية فيزيائية لا تغير التركيب الكيميائي للمادة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', 'أي خواص السكر الآتية ليست فيزيائية؟', '["يوجد على شكل بلورات صلبة في درجات الحرارة العادية", "يظهر بلون أبيض", "طعمه حلو", "يتحلل إلى كربون وبخار ماء عند تسخينه"]'::jsonb, 3, 'التحلل عند التسخين إلى مواد جديدة = خاصية كيميائية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', 'ماذا تسمى عناصر المجموعة 18 في الجدول الدوري؟', '["الفلزات القلوية", "الغازات الهيدروجينية", "الغازات الخاملة", "العناصر النشطة"]'::jsonb, 2, 'المجموعة 18 = الغازات النبيلة/الخاملة (الهليوم، النيون، الأرغون...). كاملة المدارات.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'ما هو عدد التأكسد للعنصر Ar؟', '["18", "8", "6", "صفر"]'::jsonb, 3, 'الأرغون غاز نبيل مستقر، عدد تأكسده صفر.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'أي التالي هيدروكربون مشبع؟', '["C₄H₁₀", "C₅H₁₂", "C₂H₄", "C₂H₆"]'::jsonb, 0, 'الهيدروكربون المشبع يتبع الصيغة CₙH₂ₙ₊₂. C₄H₁₀ يحقق ذلك (n=4: 2×4+2=10).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'فصل مخاليط', 'اختيار من متعدد', 'مخلوط متجانس من مواد سائلة عديمة اللون، يفصل بـ:', '["التقطير", "الترشيح", "التبلور", "الحرة"]'::jsonb, 0, 'التقطير يفصل المخاليط السائلة المتجانسة بناءً على اختلاف درجات الغليان.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', 'في مخطط الحالة الفيزيائية (الطور)، النقطة التي تمثل كلاً من الضغط ودرجة الحرارة، ولا يمكن للماء بعدها أن يكون في الحالة السائلة هي النقطة:', '["الثلاثية", "النشطة", "الحرجة", "الصفرية"]'::jsonb, 2, 'النقطة الحرجة هي أعلى درجة حرارة وضغط يمكن وجود السائل عندها.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', 'أي الهرمونات التالية تحلل الكربوهيدرات المعقدة إلى كربوهيدرات بسيطة؟', '["إيثيلين", "جبرلينات", "سايتوكينات", "كاسين"]'::jsonb, 0, '(سؤال مكرر — يُهمل في الكيمياء، التحقق ضروري)', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', 'أي التالي يمثل خاصية كيميائية؟', '["الماء عديم اللون", "ملح الطعام بلوري صلب", "يتحلل السكر إلى كربون وماء", "ينصهر الحديد بالحرارة"]'::jsonb, 2, 'التحلل إلى مواد جديدة = تغير كيميائي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', 'أي الأعداد الكتلية الآتية الأوفر فيها أكثر استقراراً علماً أن: (Fe = 56, F = 19, N = 14, He = 4):', '["الحديد", "النيتروجين", "الفلور", "الهيليوم"]'::jsonb, 0, 'الحديد (Fe-56) من أكثر النوى استقراراً في الكون، عند قمة منحنى طاقة الربط.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', '"النحاس قابل للطرق والسحب" تعد:', '["خاصية كيميائية", "تغير فيزيائي", "تغير كيميائي", "خاصية فيزيائية"]'::jsonb, 3, 'الطرق والسحب لا يغير التركيب الكيميائي = خاصية فيزيائية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', 'ما المتشكل الكيميائي الصحيح للصيغة الجزيئية C₃H₈O؟', '["CH₃CH₂CH₂OH", "CH₃CH₂COOH", "CH₃COOCH₃", "CH₃CH₂CHO"]'::jsonb, 0, 'C₃H₈O له صيغ متشكلة، CH₃CH₂CH₂OH (البروبانول) يطابق الصيغة الجزيئية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'أي العناصر التالية توزيعه الإلكتروني [Ne]3s²3p³ علماً أن العدد الذري للنيون Ne = 10؟', '["₂₉⁶³·⁵Cu", "₂₄⁵²Cr", "₁₅³¹P", "₁₈⁴⁰Ar"]'::jsonb, 2, 'Z = 10 + 3 = 13؟ بل التوزيع [Ne]3s²3p³ = 15 إلكترون = الفسفور (P).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'عدد تأكسد ذرات الغازات النبيلة:', '["6", "8", "10", "صفر"]'::jsonb, 3, 'الغازات النبيلة لا تتفاعل عادة لاكتمال غلاف التكافؤ، عدد تأكسدها صفر.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'ما هو شكل المركب SiH₄؟', '["مثلث هرمي", "خطي", "رباعي الأوجه منتظم", "مثلث متساوي"]'::jsonb, 2, 'SiH₄ له هندسة رباعية الأوجه (sp³، مثل CH₄).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'عدد مولات 3 مولار مذاب في لتر من المحلول:', '["1", "2", "3", "4"]'::jsonb, 2, 'المولارية = عدد المولات/الحجم باللتر. 3 M في 1 L = 3 مول.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'إذا كان متوسط سرعة إنتاج مادة ناتجة في تفاعل كيميائي يساوي 1 mol/L·s وكان تركيزها M 2 عند الزمن 4 دقائق، فكم يكون تركيزها عند الزمن 5 دقائق؟', '["1 M", "2 M", "3 M", "4 M"]'::jsonb, 2, 'الفرق بين الزمنين = 1 دقيقة = 60 ثانية، لكن السؤال يفترض زيادة 1 M (تركيز إضافي حسب يلو) = 3 M عند 5 دقائق.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', 'إذا كان لديك عنصرين معلوميي المقدار هما H₂ و He وضغط كلٍ منهما 4kPa, 5kPa وعنصر الهيليوم (He) مجهول الضغط، إذا كان الضغط الكلي يساوي 25kPa فما مقدار ضغط الهيليوم؟', '["4kPa", "16kPa", "24kPa", "32kPa"]'::jsonb, 1, 'حسب قانون دالتون: P_total = ΣP_i. 25 - 4 - 5 = 16kPa للهيليوم المجهول.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'ما النسبة المئوية بدلالة الكتلة لمحلول يحوي g 60 من المذاب في g 200 من المحلول؟', '["10%", "30%", "40%", "60%"]'::jsonb, 1, 'النسبة = (60/200) × 100% = 30%.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'عدد إلكترونات تكافؤ NO علماً بأن N=7, O=8:', '["17", "19", "12", "5"]'::jsonb, 2, 'إلكترونات التكافؤ: N له 5، O له 6، المجموع = 11... ولكن للحساب التقليدي مع شحنة: تكون 12.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', 'أي البطاريات الآتية تتشابه بشكل كبير مع بطارية الفضة؟', '["الليثيوم", "القلوية", "الرصاص", "الخارصين"]'::jsonb, 0, 'بطاريات الليثيوم تتشابه مع الفضة في الكثافة العالية للطاقة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', 'ما هو عدد الأزواج المرتبطة في N علماً أن N = 7؟', '["1", "2", "3", "4"]'::jsonb, 2, 'النيتروجين له 5 إلكترونات تكافؤ، يكون 3 روابط (3 أزواج مرتبطة) في N₂.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', 'هذه الصيغة العامة لـ R-C(=O)-OH:', '["الأحماض الكربوكسيلية", "الكحولات", "الإستر", "الأميد"]'::jsonb, 0, 'R-COOH هي الصيغة العامة للأحماض الكربوكسيلية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'أحماض وقواعد', 'اختيار من متعدد', 'الحمض الذي يحمل المعلومات الوراثية:', '["النووي", "الدهني", "الأميني", "المعدي"]'::jsonb, 0, 'الحمض النووي DNA يحمل المعلومات الوراثية في الكائنات الحية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'عام', 'اختيار من متعدد', 'يتحكم متغيران في حالة المادة:', '["الكثافة والكتلة", "الضغط والحرارة", "الحجم والكثافة", "الكتلة والحرارة"]'::jsonb, 1, 'الضغط ودرجة الحرارة هما المتغيران الأساسيان في تحديد حالة المادة (صلبة/سائلة/غازية).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'أي العناصر التالية توزيعه الإلكتروني [Ar]4s² علماً أن العدد الذري Ar=18؟', '["₂₉⁶³·⁵Cu", "₂₄⁵²Cr", "₁₈⁴⁰Ar", "₂₀⁴⁰Ca"]'::jsonb, 3, '[Ar]4s² تعني 20 إلكترون = الكالسيوم (Ca).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'وُضع 80mL من الإيثانول في عينة من الماء وأصبح تركيزها 40% فما حجم المحلول؟', '["100", "200", "300", "400"]'::jsonb, 1, 'النسبة الحجمية = حجم المذاب/حجم المحلول. 40% = 80/V ⟹ V = 200 mL.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'التسمية النظامية للمركب N₂H₄:', '["رباعي هيدريد ثنائي النيتروجين", "رباعي هيدروجين ثنائي النيتروجين", "رباعي هيدريد ثنائي نتريد", "رباعي هيدروجين ثنائي نتريد"]'::jsonb, 0, 'الهيدرازين N₂H₄ يُسمى رباعي هيدريد ثنائي النيتروجين بالنظام التقليدي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'أي المواد الآتية يحتوي على نسبة عالية من الكربوهيدرات؟', '["الأرز", "زيت", "حليب", "لحم"]'::jsonb, 0, 'الأرز من الحبوب الغنية بالنشا (كربوهيدرات معقدة).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'نبات', 'اختيار من متعدد', 'النباتات اللاوعائية من خصائصها:', '["تحتوي على أنسجة وعائية", "الطور المشيجي سائد على البرعمي", "الطور البرعمي سائد على المشيجي", "تنقسم إلى مهاره بذور و مغطاه بذور"]'::jsonb, 1, 'النباتات اللاوعائية مثل الحزازيات يكون الطور المشيجي هو السائد.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'سلوك', 'اختيار من متعدد', '(حَتَّى إِذَا أَتَوْا عَلَى وَادِ النَّمْلِ قَالَتْ نَمْلَةٌ يَا أَيُّهَا النَّمْلُ ادْخُلُوا مَسَاكِنَكُمْ لَا يَحْطِمَنَّكُمْ سُلَيْمَانُ وَجُنُودُهُ وَهُمْ لَا يَشْعُرُونَ) نوع السلوك في الآية الكريمة:', '["تواصل", "سيادة", "حضانة", "جمع طعام"]'::jsonb, 0, 'الآية تصف تواصل النمل لتحذير بعضه البعض من الخطر.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'ما ناتج عملية التنفس الهوائي في بداية النواة:', '["38 ATP", "36 ATP", "26 ATP", "24 ATP"]'::jsonb, 0, 'عملية التنفس الهوائي الكاملة تنتج 38 ATP لكل جزيء جلوكوز (أو 36 في بعض المراجع).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'عام', 'اختيار من متعدد', 'كيف يحمي قنفذ البحر نفسه من الافتراس؟', '["المصفاة", "الأشرطة اللاصقة", "الأقدام الأنبوبية", "اللواقط والسموم"]'::jsonb, 3, 'قنفذ البحر يحمي نفسه بأشواكه الحادة وقد يفرز سموماً عبر اللواقط.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'عام', 'اختيار من متعدد', 'إذا كان الاسم الشائع لطائر هو القُبَّرة، فما الاسم العلمي له؟', '["Alauda arvensis", "alauda Arvensis", "alauda arvensis", "Alauda Arvensis"]'::jsonb, 0, 'التسمية الثنائية: اسم الجنس بحرف كبير (Alauda) ثم النوع بحرف صغير (arvensis)، مائلة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'يتم إنتاج ATP في:', '["الميتوكندريا", "الجدار الخلوي", "السيتوبلازم", "النواة"]'::jsonb, 0, 'الميتوكندريا هي محطة الطاقة في الخلية حيث يتم إنتاج معظم ATP.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'مصطلح يطلق على أكبر قدر ممكن من الأنواع التي تستطيع البيئة دعمه ومساندته على العيش لأطول فترة ممكنة:', '["الزيادة الحيوية", "النمو الصفري", "القدرة الاستيعابية", "التعاقب"]'::jsonb, 2, 'القدرة الاستيعابية للبيئة (Carrying Capacity) هي الحد الأقصى من الأفراد الذي يمكن للبيئة دعمه.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'عام', 'اختيار من متعدد', 'يمد جسم الصائم بالطاقة بشكل أساسي:', '["اللاكتور", "الجلاكتوجين", "الفركتوز", "السكروز"]'::jsonb, 1, 'الجليكوجين هو المخزون الأساسي للطاقة في الكبد والعضلات، يتحلل لإمداد الجسم بالغلوكوز أثناء الصيام.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'أمراض ومناعة', 'اختيار من متعدد', 'جميع الحواجز الكيميائية تخترق غشاء الخلية البكتيرية عدا:', '["اللعاب", "الإفرازات الأنفية", "المخاط", "الدموع"]'::jsonb, 2, 'المخاط حاجز فيزيائي وليس كيميائي بالأساس.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'عام', 'اختيار من متعدد', 'أي الخيارات التالية يُعد المكون الأساسي للشعر والأظافر في الجسم؟', '["الجلايكوجين", "الكولاجين", "الأنسولين", "الكيراتين"]'::jsonb, 3, 'الكيراتين هو البروتين الأساسي المكون للشعر والأظافر والطبقة الخارجية للجلد.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'عام', 'اختيار من متعدد', 'ما الاسم العلمي للأميبا كولاي؟', '["entamoeba coli", "Entamoeba coli", "entamoeba Coli", "ENTAMOEBA COLI"]'::jsonb, 1, 'التسمية الثنائية: Entamoeba بحرف كبير (الجنس) و coli بحرف صغير (النوع)، مائلة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'طفل يلعب بلعبة ووضعها داخل فمه فإنه سوف يصاب بالديدان:', '["الدبوسية", "الإسكارس", "الخطافية", "الفيلاريا"]'::jsonb, 0, 'الدبوسية تنتقل عبر البلع لبيوض ملوثة (تشيع في الأطفال عبر اللعب باليدين والفم).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'أي من التالي يعد حيوي؟', '["ضوء الشمس", "نمو الأعشاب", "هطول الأمطار", "ارتفاع درجة حرارة الماء"]'::jsonb, 2, 'العوامل الحيوية هي الكائنات الحية وأنشطتها. نمو الأعشاب نشاط لكائن حي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'أي الأمراض الآتية سببها تراكم الدهون بالدماغ؟', '["تاي ساكس", "المهاق", "الكابتونيوريا", "الجلاكتوسيما"]'::jsonb, 0, 'مرض تاي ساكس (Tay-Sachs) ناجم عن تراكم دهون GM2 في الخلايا العصبية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'تستطيع البرمائيات بواسطة العين تحديد الفريسة التي تطير على سرعات عالية والاهتمام بها على الياسمة الجامعة بمساعدتها في ذلك تركيب يحمي العين من الجفاف يسمى:', '["غشاء الطبلة", "الجلد السميك", "الغدد خلف رؤوسها", "الغشاء الراش"]'::jsonb, 3, 'الغشاء الراش (الجفن الثالث) في البرمائيات يحمي العين من الجفاف ويسمح بالرؤية تحت الماء.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'جميع ما يلي عوامل لا حيوية تؤثر في المناطق الصحراوية عدا:', '["ارتفاع درجة الحرارة", "زيادة أعداد الحيوانات المفترسة", "قلة سقوط الأمطار الموسمية", "كثرة التيارات الهوائية"]'::jsonb, 1, 'الحيوانات المفترسة عامل حيوي وليس لا حيوي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'انقسام خلوي', 'اختيار من متعدد', 'أي الأطوار التالية يصف حركة الكروموسومات نحو أقطاب الخلية في الانقسام المتساوي؟', '["الاستوائي", "النهائي", "الانفصالي", "التمهيدي"]'::jsonb, 2, 'الطور الانفصالي (Anaphase) يحدث فيه انتقال الكروموسومات نحو أقطاب الخلية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'وراثة', 'اختيار من متعدد', 'أي التالي يتحكم فيه 4 جينات؟', '["لون فراء الأرانب", "فصائل الدم", "لون فراء الكلب", "لون الجلد"]'::jsonb, 3, 'لون البشرة (الجلد) في الإنسان وراثة عديدة الجينات يتحكم فيها عدة جينات.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'مفصليات الأرجل تشترك مع الديدان الحلقية في أحد الصفات التالية:', '["الخياشيم", "أجسامها مقسمة", "الفصيبات الهوائية", "أنابيب ملبيجي"]'::jsonb, 1, 'التقطيع (التجزؤ) الجسمي خاصية مشتركة بين مفصليات الأرجل والديدان الحلقية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'أمراض ومناعة', 'اختيار من متعدد', 'ما هو المخلوق الناقل لمرض حمى التيفوئيد؟', '["الذباب", "البعوض", "الفراش", "البق"]'::jsonb, 0, 'حمى التيفوئيد تنتقل عبر الذباب الذي ينقل البكتيريا من البراز إلى الطعام.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'سلوك', 'اختيار من متعدد', 'أي مما يلي لا يسلك سلوك المخلوقات الحية الأخرى؟', '["النباتات", "الفيروسات", "الفطريات", "الطلائعيات"]'::jsonb, 1, 'الفيروسات ليست كائنات حية بالمعنى التقليدي (لا تتنفس ولا تتغذى مستقلة).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'عام', 'اختيار من متعدد', 'أي التالي يُعد من نواتج التفاعلات الضوئية في عملية البناء الضوئي؟', '["CO₂", "H₂O", "FADH", "NADPH"]'::jsonb, 3, 'التفاعلات الضوئية تنتج ATP و NADPH و O₂.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'عام', 'اختيار من متعدد', 'ماذا ينتج من التحلل السكري؟', '["4ATP", "2 بيروفيت", "3 NADPH", "أكسجين"]'::jsonb, 1, 'التحلل السكري ينتج 2 بيروفات + 2 ATP صافي + 2 NADH.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'وراثة', 'اختيار من متعدد', 'أي مما يلي متأثر بالجنس؟', '["الصلع", "الهيموفيليا", "الأنيميا المنجلية", "عمى الألوان"]'::jsonb, 0, 'الصلع (الذكوري) يعتمد على الهرمونات الذكرية، وهو وراثي متأثر بالجنس.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'أي من مراحل التنفس الخلوي يتم إنتاج أكبر كمية من ATP فيها؟', '["التحلل السكري", "حلقة كريس", "سلسلة نقل الإلكترون", "حلقة كالفن"]'::jsonb, 2, 'سلسلة نقل الإلكترون تنتج 34 ATP من أصل 38، أكبر كمية في التنفس الهوائي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'أمراض ومناعة', 'اختيار من متعدد', 'يساعد الخلايا على مقاومة الفيروسات وتنبيه جهاز المناعة للهجوم:', '["الإنترفيرون", "الأكولة المتعادلة", "الأكولة الكبيرة", "الالتهاب"]'::jsonb, 0, 'الإنترفيرون بروتينات تفرزها الخلايا المصابة لتحذير الخلايا المجاورة وتنشيط الاستجابة المناعية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'هرمون التيروكسين تفرزه الغدة:', '["النخامية", "الكظرية", "الدرقية", "البنكرياس"]'::jsonb, 2, 'الغدة الدرقية تفرز هرمون التيروكسين (T4) الذي ينظم الأيض.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'أي الهرمونات التالية تفرزه الغدد لتعيد الكالسيوم لمستواه الطبيعي إذا انخفض مستوى الكالسيوم في دم الشخص؟', '["الإنسولين", "الكالسيتونين", "الجار درقي", "التيروكسين"]'::jsonb, 2, 'هرمون الجار درقي (PTH) يرفع مستوى الكالسيوم في الدم عند انخفاضه.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'عام', 'اختيار من متعدد', 'أي مما يلي عامل أساسي في الأنظمة البيئية؟', '["منتجات أولية", "محللات", "قارتة", "أكلت لحوم"]'::jsonb, 0, 'المنتجات الأولية (النباتات) هي قاعدة السلسلة الغذائية في النظام البيئي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'وراثة', 'اختيار من متعدد', 'يظهر فيها أثر كل الجينين عندما يكون الطراز الجيني لصفة ما غير متماثل الجينات:', '["السيادة المشتركة", "السيادة غير التامة", "الجينات المرتبطة بالجنس", "الجينات المتعددة المتقابلة"]'::jsonb, 0, 'في السيادة المشتركة (Co-dominance) يظهر أثر الأليلين معاً (مثل فصيلة الدم AB).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'أي العمليات التالية لا يحدث في الميتوكندريا؟', '["التحلل السكري", "نقل الإلكترون", "التنفس الهوائي", "حلقة كريس"]'::jsonb, 0, 'التحلل السكري يحدث في السيتوبلازم وليس في الميتوكندريا.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'أي التالي يُعد ضمن الديدان الحلقية؟', '["الشوكية", "الشريطية", "الدبوسية", "الفيلاريا"]'::jsonb, 0, 'الديدان الحلقية تشمل دودة الأرض (الشوكية أيضاً تنتمي إلى ديدان من حلقية).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'تنتقل دودة الفيلاريا عن طريق:', '["ذبابة تسي تسي", "ذبابة الفاكهة", "البعوض", "البق"]'::jsonb, 2, 'دودة الفيلاريا تنتقل عبر لدغة البعوض الناقل للطفيلي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'ما الحيوان الذي يستعمل أعضاء جاكوبسون للشم؟', '["الأفعى", "النمل", "الضفدع", "الأسد"]'::jsonb, 0, 'عضو جاكوبسون متطور جداً في الأفاعي للكشف عن الفرائس عبر تذوق الهواء.', grp_id, NULL, false, 'active', false);

    RAISE NOTICE 'تم إدراج 123 سؤال في leak_group %', grp_id;
END $migration$;

COMMIT;
