-- 99: Day 5 morning (hamma) — batch 5: chemistry (18 questions, pages 100-117)

BEGIN;

INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'كم إلكتروناً تفقده ذرّة الحديد الواحدة في التفاعل: 2Fe(s) + 3Cr²⁺(aq) → 3Cr(s) + 2Fe³⁺(aq)؟', '["1", "3", "4", "6"]'::jsonb, 1, 'في النواتج Fe³⁺ تحوّل من Fe إلى Fe³⁺ أي فقد 3 إلكترونات (التغيّر من 0 إلى +3 = أكسدة). يفقد كل ذرة حديد 3 إلكترونات.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'يُعدّ حمض الكبريتيك H₂SO₄..', '["محلولاً", "مركّباً", "مخلوطاً متجانساً", "مخلوطاً غروياً"]'::jsonb, 1, 'H₂SO₄ مادة نقية مكوّنة من اتحاد كيميائي بين الهيدروجين والكبريت والأكسجين بنسب محدّدة، فهو مركّب كيميائي. ليس مخلوطاً لأنه غير قابل للفصل بطرق فيزيائية.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'الحدّ الأقصى لعدد الإلكترونات في المستوى الرئيس الثاني (n=2):', '["2", "8", "16", "32"]'::jsonb, 1, 'العدد الأقصى = 2n². عند n=2: 2(2)² = 2(4) = 8 إلكترونات (تتوزّع: 2 في 2s + 6 في 2p).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'ما نوع التفاعل: 2Li(s) + 2H₂O(l) → 2LiOH(aq) + H₂(g)؟', '["إحلال بسيط", "تفكّك", "تكوين", "احتراق"]'::jsonb, 0, 'عنصر الليثيوم (Li) يحلّ محلّ الهيدروجين في الماء، فيتكوّن هيدروكسيد الليثيوم وغاز الهيدروجين. هذا تفاعل إحلال بسيط (Single Replacement).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'الأشعّة المكوّنة من إلكترون له شحنة سالبة أحادية هي:', '["فوق البنفسجية", "ألفا", "جاما", "بيتا"]'::jsonb, 3, 'جسيمات بيتا (β⁻) هي إلكترونات سريعة تنبعث من النواة عند تحوّل نيوترون إلى بروتون. شحنتها سالبة أحادية. ألفا = نواة هيليوم (+2)، جاما = موجات كهرومغناطيسية (لا شحنة).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'أحماض وقواعد', 'اختيار من متعدد', 'حسب قاعدة لويس، يُعتبر المركّب AlCl₃ (علماً بأن Al=13، Cl=17)..', '["حمضاً", "قاعدة", "متعادلاً", "متردّداً"]'::jsonb, 0, 'حسب لويس: الحمض = مستقبِل لزوج إلكترونات، والقاعدة = مانح. AlCl₃ يحوي ذرّة ألمنيوم بـ6 إلكترونات تكافؤ فقط (مدار p غير ممتلئ)، فيستقبل زوج إلكترونات → حمض لويس.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'عند فتح علبة مشروب غازي يُسمع صوت قوي. ما الغاز المتصاعد؟', '["CO₂", "H₂O", "O₂", "H₂"]'::jsonb, 0, 'المشروبات الغازية تذوب فيها كميات كبيرة من غاز ثاني أكسيد الكربون CO₂ تحت ضغط عالٍ. عند الفتح ينخفض الضغط فينطلق CO₂ ويسبّب الصوت والفقاعات.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'فيزياء نووية', 'اختيار من متعدد', 'جسيمات نووية تشبه نواة ذرّة الهيليوم، شحنتها موجبة وتتحرّك بسرعة عالية. هذه الجسيمات تسمّى:', '["بيتا", "ألفا", "جاما", "بروتون"]'::jsonb, 1, 'جسيمات ألفا (α) عبارة عن نواة هيليوم ⁴₂He (بروتونان ونيوترونان)، شحنتها +2 وتنبعث في تحلّل ألفا للنوى الثقيلة.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'خروج غاز CO₂ عند فتح المشروبات الغازية يطبّق قانون..', '["بويل", "شارل", "جاي لوساك", "هنري"]'::jsonb, 3, 'قانون هنري: ذوبانية الغاز في السائل تتناسب طردياً مع ضغطه الجزئي. عند الفتح ينخفض ضغط CO₂ فوق السائل فتقل ذوبانيته → يخرج كفقاعات.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'ما الصيغة الكيميائية الصحيحة لأيون البيركلورات؟', '["ClO₄⁻", "ClO₃⁻", "ClO₂⁻", "ClO⁻"]'::jsonb, 0, 'تسمية أيونات الكلور الأكسجينية: ClO⁻ هيبوكلوريت، ClO₂⁻ كلوريت، ClO₃⁻ كلورات، ClO₄⁻ بيركلورات (perchlorate). البادئة (بير-) تعني أعلى حالة تأكسد للكلور +7.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'ما العامل المختزَل في تفاعل الأكسدة والاختزال؟', '["المادة التي تأكسدت", "المادة الأقلّ كهروسالبية", "المادة الأقلّ نشاطاً", "المادة المستقبِلة للإلكترونات"]'::jsonb, 0, 'العامل المختزِل (Reducing Agent) هو المادة التي تتأكسد (تفقد إلكترونات) وتختزل غيرها. مثال: في 2Fe + 3Cr²⁺ → 3Cr + 2Fe³⁺، الحديد تأكسد فهو العامل المختزِل.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'إذا تفاعل 40 مل من البيوتانول مع 460 مل من الماء، فاحسب النسبة المئوية بدلالة الحجم.', '["0.9%", "24%", "8%", "0.2%"]'::jsonb, 2, 'الحجم الكلي = 40 + 460 = 500 مل. النسبة الحجمية للبيوتانول = (40 / 500) × 100% = 8%.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'أيّ التالي يُستخدم مع محلول قاعدة قوية في عملية إنتاج الصابون (التصبّن)؟', '["الستيرويد", "اللبيد", "الجلسريد الثلاثي", "البروتين"]'::jsonb, 2, 'التصبّن (Saponification) تفاعل الجلسريد الثلاثي (دهون/زيوت) مع قاعدة قوية (NaOH أو KOH) لإنتاج صابون (ملح صوديوم/بوتاسيوم للأحماض الدهنية) وغليسرول.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'إذا تفاعل 10 g من العنصر A مع 30 g من العنصر B وتفاعلهما تامّ، فما النسبة المئوية بالكتلة للعنصر A؟', '["5%", "15%", "25%", "45%"]'::jsonb, 2, 'الكتلة الكلية = 10 + 30 = 40 جم. النسبة المئوية للعنصر A بالكتلة = (10 / 40) × 100% = 25%.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'ما عدد مولات CO₂ الناتجة عن احتراق 10 مول من C₃H₈ وفقاً للمعادلة: C₃H₈ + 5O₂ → 3CO₂ + 4H₂O؟', '["3 mol", "5 mol", "10 mol", "30 mol"]'::jsonb, 3, 'النسبة المولية حسب المعادلة: 1 مول C₃H₈ ينتج 3 مول CO₂. إذاً 10 مول C₃H₈ تنتج 10 × 3 = 30 مول CO₂.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'أيّ التالي يُعدّ تفاعلاً طارداً للحرارة (Exothermic)؟', '["تسامي", "تبخّر", "انصهار", "تكثّف"]'::jsonb, 3, 'التكثّف تحوّل الغاز إلى سائل، يطلق طاقة (حرارة) للمحيط. التسامي والتبخّر والانصهار كلها تتطلّب امتصاص حرارة (تفاعلات ماصّة).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'ما الصيغة الكيميائية لأكسيد الذهب III؟', '["Au₂O₃", "AuO", "AuO₃", "Au₃O₂"]'::jsonb, 0, 'الذهب III يعني عدد تأكسد Au = +3. الأكسجين O²⁻. للتعادل: 2Au³⁺ + 3O²⁻ → Au₂O₃ (مجموع شحنات: +6 = -6).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'عدد تأكسد الكروم في الأيون Cr₂O₇²⁻:', '["+12", "−12", "+6", "−6"]'::jsonb, 2, 'مجموع أعداد التأكسد = شحنة الأيون. ليكن x = عدد تأكسد Cr. للأكسجين -2. 2x + 7(−2) = −2 → 2x − 14 = −2 → 2x = 12 → x = +6 لكل ذرّة كروم.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);

COMMIT;
