-- ═══════════════════════════════════════════════════════════════
-- تسريبات القدرات – الخميس ٢٧ أغسطس ٢٠٢٦
-- 107 سؤالاً: كمي 58 + لفظي 49 (منها 16 في قطع استيعاب)
-- آمن لإعادة التشغيل: guard على وجود أسئلة المجموعة
-- ═══════════════════════════════════════════════════════════════
BEGIN;

INSERT INTO leak_groups (id, title, leak_date, section, question_count, description, is_active, accent_color)
VALUES ('ad270826-2026-4c00-9d00-270820260001', 'تسريبات القدرات – الخميس ٢٧ أغسطس ٢٠٢٦', '2026-08-27', 'mixed', 107, 'أسئلة اختبار القدرات المحوسب ليوم الخميس ٢٧ أغسطس ٢٠٢٦ (١٥ ربيع الأول ١٤٤٨) — القسمان الكمي واللفظي مع الشروح.', true, '#7C3AED')
ON CONFLICT (id) DO NOTHING;

DO $mig$
BEGIN
IF EXISTS (SELECT 1 FROM questions WHERE leak_group_id = 'ad270826-2026-4c00-9d00-270820260001') THEN
  RAISE NOTICE 'أسئلة المجموعة موجودة مسبقاً — تخطي الإدراج';
ELSE
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'خمسة أعداد: متوسط أول ٣ أعداد منها يساوي ١٠، ومتوسط آخر عددين يساوي ١٥. ما متوسط الأعداد الخمسة؟', '["١١", "١٢", "١٢٫٥", "١٣"]'::jsonb, 1, 'مجموع الثلاثة الأولى = ٣٠ ومجموع الأخيرين = ٣٠، فمجموع الخمسة = ٦٠ والمتوسط = ٦٠ ÷ ٥ = ١٢.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'باعت مكتبة ثُمن عدد كتب التاريخ واشترت ١٠ كتب جديدة، فأصبح عدد كتب التاريخ بالمكتبة ٥٢. كم كان عدد كتب التاريخ الأصلي؟', '["٣٢", "٤٨", "٦٠", "٦٤"]'::jsonb, 1, 'بعد بيع الثُمن يبقى (٧/٨)س، ومع العشرة الجديدة: (٧/٨)س + ١٠ = ٥٢، فيكون (٧/٨)س = ٤٢ ومنها س = ٤٨.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'مربع محيطه = ٢٠ سم، قارن بين:
القيمة الأولى: مساحة المربع
القيمة الثانية: ٢٥ سم²', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 2, 'ضلع المربع = ٢٠ ÷ ٤ = ٥ سم، ومساحته = ٢٥ سم²؛ فالقيمتان متساويتان.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'هند تقرأ ٥٠ صفحة في ٢٠ دقيقة، كم صفحة تقرأ في ٤ ساعات؟', '["٢٠٠", "٤٠٠", "٦٠٠", "٨٠٠"]'::jsonb, 2, '٤ ساعات = ٢٤٠ دقيقة أي ١٢ فترة مدة كل منها ٢٠ دقيقة، فتقرأ ١٢ × ٥٠ = ٦٠٠ صفحة.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: متوازي أضلاع قاعدته ٩ سم وضلعه المائل ١٠ سم ومساحته ٧٢ سم²، وبداخله مستطيل يصل بين القاعدتين. أوجد مساحة المستطيل.', '["٤٨", "٣٦", "٢٤", "١٢"]'::jsonb, 2, 'ارتفاع المتوازي = ٧٢ ÷ ٩ = ٨ سم. الإزاحة الأفقية للضلع المائل = √(١٠² − ٨²) = ٦ سم، فعرض المستطيل الواقع بين القاعدتين = ٩ − ٦ = ٣ سم، ومساحته = ٣ × ٨ = ٢٤ سم².', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug27_q05_pgram_rect.png', 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'نادٍ به ٥٠ مشتركًا: ٣٠ منهم مشتركون في كرة القدم، و٢٦ مشتركون في السباحة، و٦ غير مشتركين في كرة القدم ولا السباحة. كم عدد المشتركين في كرة القدم والسباحة معًا؟', '["صفر", "١٢", "٤", "٦"]'::jsonb, 1, 'المشتركون في نشاط واحد على الأقل = ٥٠ − ٦ = ٤٤. بالجمع: ٣٠ + ٢٦ = ٥٦ وفيه ازدواج قدره ٥٦ − ٤٤ = ١٢، وهم المشتركون في الاثنين معًا.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'مصاريف مدرسة ١٠٠٠٠ ريال وزادت المصاريف ٢٠٪، ويوجد خصم ٥٪ للطلاب الإخوة. كم المصاريف التي يدفعها أب لولدين؟', '["٢٤٠٠٠", "٢٣٠٠٠", "٢٢٨٠٠", "٢٢٧٥٠"]'::jsonb, 2, 'بعد الزيادة: ١٠٠٠٠ × ١٫٢ = ١٢٠٠٠ للطالب، ولولدين ٢٤٠٠٠. بعد خصم ٥٪: ٢٤٠٠٠ × ٠٫٩٥ = ٢٢٨٠٠ ريال.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', '(ن + ن) × ن × (ن − ن) = .....', '["ن", "ن³", "صفر", "١"]'::jsonb, 2, 'العامل الأخير (ن − ن) = صفر، وأي ضرب في الصفر ناتجه صفر مهما كانت بقية العوامل.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: مربع طول ضلعه ٨ سم قُطع من ركنه العلوي مثلث، فبقي من الضلع العلوي ٤ سم ومن الضلع الجانبي ٥ سم. أوجد مساحة الجزء المظلل.', '["٥٠", "٥٦", "٥٨", "٦٠"]'::jsonb, 2, 'ساقا المثلث المقطوع: ٨ − ٤ = ٤ سم أفقيًا و٨ − ٥ = ٣ سم رأسيًا، فمساحته = ٤ × ٣ ÷ ٢ = ٦. المظلل = ٦٤ − ٦ = ٥٨ سم².', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug27_q10_square_cut.png', 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'هناك ٥ بيوت، وكل بيت فيه ٥ أقفاص، وكل قفص فيه ٥ عصافير، وكل عصفور يأكل ٥ حبات قمح. كم حبة قمح أكلتها العصافير؟', '["٦٥٠", "٦٢٥", "٧٠٠", "٧٨٠"]'::jsonb, 1, 'عدد العصافير = ٥ × ٥ × ٥ = ١٢٥ عصفورًا، وتأكل ١٢٥ × ٥ = ٦٢٥ حبة، وهي ٥⁴.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', '(٦⁸ ÷ ٦³) ÷ (٢⁵ × ٣⁴) = .....', '["١", "٢", "٣", "٤"]'::jsonb, 2, 'البسط = ٦⁵ = ٢⁵ × ٣⁵. بالقسمة على ٢⁵ × ٣⁴ تُحذف ٢⁵ ويبقى ٣⁵ ÷ ٣⁴ = ٣.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'المربع الأول محيطه ١٢ سم، ونصف محيط المربع الثاني = ٨ سم. قارن بين:
القيمة الأولى: مساحة المربع الأول
القيمة الثانية: نصف مساحة المربع الثاني', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'الأول: ضلعه ٣ ومساحته ٩. الثاني: محيطه ١٦ فضلعه ٤ ومساحته ١٦ ونصفها ٨. القيمة الأولى ٩ أكبر.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', '(٥⁷ + ٥⁷) ÷ ٥⁷ = ..... — احسب الناتج مباشرة.', '["٢", "٢ × ٥⁷", "١", "٥⁷"]'::jsonb, 0, 'البسط = ٢ × ٥⁷، وبالقسمة على ٥⁷ يبقى ٢.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'ما العدد الذي إذا أضفت له نصفه وربعه أصبح الناتج ٢٨؟', '["١٤", "١٨", "١٦", "١٢"]'::jsonb, 2, 'س + س/٢ + س/٤ = (٧/٤)س = ٢٨، ومنها س = ١٦.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'ثلاثة أعداد مجموعها ٩٦: العدد الأكبر يساوي ٣ أمثال العدد الأصغر، والعدد الأوسط مثلا العدد الأصغر. ما العدد الأصغر؟', '["١٢", "١٤", "١٦", "١٨"]'::jsonb, 2, 'لو الأصغر س فالأعداد س و٢س و٣س ومجموعها ٦س = ٩٦، فيكون س = ١٦.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', '(٦٦٦/٥٥٥) ÷ [(٤٤٤/٥٥٥) ÷ (٤٤٤/٣٣٣)] = .....', '["٢", "٣", "٤", "٥"]'::jsonb, 0, 'داخل القوسين: (٤٤٤/٥٥٥) × (٣٣٣/٤٤٤) = ٣٣٣/٥٥٥ = ٣/٥. ثم (٦/٥) ÷ (٣/٥) = ٢.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'عددان مكونان من رقمين، آحاد أحدهما يساوي عشرات الآخر والعكس، والفرق بين العددين = ١٨. ما أحد هذين العددين؟', '["٧٤", "٦٤", "٨٥", "٩٤"]'::jsonb, 1, 'فرق العددين المتعاكسي الرقمين = ٩ × (فرق الرقمين) = ١٨، ففرق الرقمين ٢. الوحيد من الخيارات الذي يحقق ذلك ٦٤ (٦٤ − ٤٦ = ١٨).', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'سلمى لديها أختان: الأولى أكبر منها بـ٨ سنوات، والأخرى أصغر منها بـ٣ سنوات. فإذا كان حاصل ضرب عمري الأختين = ٤٢، فما عمر سلمى؟', '["٥", "٦", "٧", "٨"]'::jsonb, 1, 'لو عمر سلمى س: (س + ٨)(س − ٣) = ٤٢. بالتجربة من الخيارات: عند س = ٦ يكون ١٤ × ٣ = ٤٢. فعمر سلمى ٦ سنوات.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'إذا كانت الزاويتان (٦س)° و(٤س − ٢٠)° متكاملتين، فما قيمة س؟', '["٢٠", "٢٢", "٢٤", "٢٥"]'::jsonb, 0, 'التكامل مجموعه ١٨٠: ٦س + ٤س − ٢٠ = ١٨٠، أي ١٠س = ٢٠٠ فتكون س = ٢٠.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: شبه منحرف قاعدته العلوية ٥ وارتفاعه ٣، وقاعدته السفلية مقسومة ثلاثة أجزاء متساوية طول كل منها ٥. أوجد مساحة الشكل.', '["١٥", "٣٠", "٤٥", "٦٠"]'::jsonb, 1, 'القاعدة السفلية = ٣ × ٥ = ١٥. مساحة شبه المنحرف = (مجموع القاعدتين ÷ ٢) × الارتفاع = (٥ + ١٥) ÷ ٢ × ٣ = ٣٠.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug27_q21_trapezoid.png', 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'اشترى محمد ١٥ قلمًا وسعر القلم ٢ ريال، إذا خُصم له ١٠٪ فكم دفع بعد الخصم؟', '["٢٨", "٢٧", "٢٥", "٢٤"]'::jsonb, 1, 'الثمن قبل الخصم = ١٥ × ٢ = ٣٠ ريالًا، وبعد خصم ١٠٪: ٣٠ × ٠٫٩ = ٢٧ ريالًا.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان: سعر فستان + ٥٠٠ ريال = ٥ أمثال سعره − ٩٠٠ ريال، فما سعر الفستان؟', '["٢٥٠", "٣٠٠", "٣٥٠", "٤٠٠"]'::jsonb, 2, 'س + ٥٠٠ = ٥س − ٩٠٠، فيكون ٤س = ١٤٠٠ ومنها س = ٣٥٠ ريالًا.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: متوازي أضلاع رُسم من رأسه العلوي عمود على القاعدة وخط مائل يصنع مع العمود زاوية ٥٠°. أوجد قيمة س.', '["٥٠", "٩٠", "١٤٠", "١٥٠"]'::jsonb, 2, 'في المثلث المكون من العمود والمائل وجزء القاعدة: الزاوية الثالثة عند قدم المائل = ١٨٠ − ٩٠ − ٥٠ = ٤٠°. وس مجاورة لها على القاعدة: س = ١٨٠ − ٤٠ = ١٤٠°.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug27_q24_pgram_50.png', 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'أي مما يلي عدد غير أولي؟', '["٨٩", "٧٧", "٥٣", "٣٧"]'::jsonb, 1, '٧٧ = ٧ × ١١ فليس أوليًا، وبقية الخيارات أعداد أولية.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'المقدار ٢٧^(١/٦) يساوي:', '["٣^٠٫٧٥", "٣^٠٫٦", "٣^٠٫٥", "٣^٠٫٢٥"]'::jsonb, 2, '٢٧ = ٣³، فيكون ٢٧^(١/٦) = ٣^(٣/٦) = ٣^(١/٢) = ٣^٠٫٥.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: م مركز الدائرة، والقطعة ب جـ الخارجة على امتداد نصف القطر تساوي الوتر أ ب، وقياس الزاوية بين الوتر أ ب والاتجاه نحو المركز عند ب = ٥٠°. أوجد قيمة س.', '["١٥", "٢٠", "٢٥", "٣٠"]'::jsonb, 2, 'الزاوية أ ب جـ مجاورة للزاوية ٥٠° على مستقيم فهي ١٣٠°. والمثلث أ ب جـ متطابق الضلعين (أ ب = ب جـ)، فزاويتاه المتساويتان: س = (١٨٠ − ١٣٠) ÷ ٢ = ٢٥°.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug27_q28_circle_isosceles.png', 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'دائرة قطرها = ٧، قارن بين:
القيمة الأولى: محيط الدائرة ÷ ٢٤
القيمة الثانية: (٢٤ ÷ ٧ط)^(−١)', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 2, 'المحيط = ٧ط فالقيمة الأولى = ٧ط/٢٤. والقيمة الثانية مقلوب ٢٤/٧ط أي ٧ط/٢٤ نفسها؛ متساويتان.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان الخزان مملوءًا إلى نصفه ووزنه ٢٥٠ كجم، وإذا ملئ إلى ثلاثة أرباعه كان وزنه ٣٠٠ كجم، فما وزن الخزان وهو فارغ؟', '["٧٠", "١٠٠", "١٢٠", "١٥٠"]'::jsonb, 3, 'الفرق بين الحالتين ربع الحمولة = ٣٠٠ − ٢٥٠ = ٥٠ كجم، فالحمولة الكاملة ٢٠٠ كجم ونصفها ١٠٠. وزن الخزان الفارغ = ٢٥٠ − ١٠٠ = ١٥٠ كجم.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'ثلاثة أعداد فردية متتالية مجموعها ٥٧. ما مجموع العددين الأول والثاني؟', '["٤٠", "٣٨", "٣٤", "٣٦"]'::jsonb, 3, 'الأوسط = ٥٧ ÷ ٣ = ١٩، فالأعداد ١٧ و١٩ و٢١، ومجموع الأول والثاني = ٣٦.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'رُمي مكعب أرقام عدة مرات فكانت التكرارات: النتيجة ١ ظهرت مرتين، و٢ ثلاث مرات، و٣ مرتين، و٤ لم تظهر، و٥ ثماني مرات، و٦ خمس مرات. ما التكرار النسبي لظهور النتيجة ٣؟', '["٠٫٣", "٠٫٢", "٠٫١٥", "٠٫١"]'::jsonb, 3, 'مجموع الرميات = ٢ + ٣ + ٢ + ٠ + ٨ + ٥ = ٢٠، والتكرار النسبي للنتيجة ٣ = ٢ ÷ ٢٠ = ٠٫١.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'أصغر عدد فردي مكون من ٣ أرقام − أكبر عدد زوجي مكون من رقمين = .....', '["٥", "٧", "١", "٣"]'::jsonb, 3, 'أصغر فردي من ثلاث خانات ١٠١، وأكبر زوجي من خانتين ٩٨، والفرق = ٣.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: قارن بين:
القيمة الأولى: مساحة المستطيل
القيمة الثانية: مساحة شبه المنحرف', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 3, 'شبه المنحرف معلومة أبعاده (قاعدتان ٢ و٤ وارتفاع ٢) فمساحته ٦، أما المستطيل فعرضه غير معلوم؛ فلا يمكن الحسم والمعطيات غير كافية.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug27_q32_rect_vs_trap.png', 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'مثلث أطوال أضلاعه ١٢ و١٣ و√(س + ١)، ومحيطه ٢٨. قارن بين:
القيمة الأولى: (س ÷ ٢) + ١
القيمة الثانية: √(س + ١) ÷ ٢', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'الضلع الثالث = ٢٨ − ٢٥ = ٣، أي √(س + ١) = ٣ ومنها س = ٨. الأولى = ٤ + ١ = ٥ والثانية = ٣ ÷ ٢ = ١٫٥؛ فالأولى أكبر.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug27_q33_tri_sqrt.png', 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', '٦٤ − ١٦ ÷ (٢ × ٤) = .....', '["٦", "٤٨", "٦٢", "٦٠"]'::jsonb, 2, 'القوس أولًا: ٢ × ٤ = ٨، ثم القسمة: ١٦ ÷ ٨ = ٢، وأخيرًا ٦٤ − ٢ = ٦٢.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'النسبة المئوية المكافئة للكسر ١/٣ هي:', '["٣٠٪", "٣٣٫٣٪", "٣٫٣٪", "٣٪"]'::jsonb, 1, '١ ÷ ٣ = ٠٫٣٣٣...، أي ما يعادل ٣٣٫٣٪ تقريبًا (ثلث المئة).', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: مثلث مرسوم على شبكة إحداثية تدريج كل وحدة فيها ٠٫٥. أوجد مساحة المثلث.', '["١", "٠٫٧٥", "٠٫٥", "٠٫٢٥"]'::jsonb, 2, 'قاعدة المثلث وحدتان على الشبكة أي ١، وارتفاعه وحدتان أي ١. المساحة = ١ × ١ ÷ ٢ = ٠٫٥.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug27_q36_grid_triangle.png', 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: راية مستطيلة بقصة مثلثية في أسفلها، فيها زاويتان قائمتان أعلاها، وزاويتا ٦٩° و٧٣° عند طرفيها السفليين. أوجد قياس الزاوية س عند رأس القصة.', '["١٢٠", "٧٣", "٦٩", "١٤٢"]'::jsonb, 3, 'الشكل خماسي مجموع زواياه الداخلية ٥٤٠°. الزاوية الداخلية عند رأس القصة = ٥٤٠ − (٩٠ + ٩٠ + ٦٩ + ٧٣) = ٢١٨° وهي منعكسة، فالزاوية س = ٣٦٠ − ٢١٨ = ١٤٢°.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug27_q37_flag.png', 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'التحليل', 'اختيار من متعدد', 'يبين الجدول أخطاء كتابة الحروف: كل صف يمثل الحرف الصحيح، وكل عمود الحرف الذي كُتب خطأً بدلًا منه. ما أكثر حرف كُتب خطأً؟', '["B", "N", "W", "R"]'::jsonb, 2, 'نجمع كل عمود لنعرف كم مرة حل الحرف خطأً محل غيره: عمود W = ٧ + ١ + ١٠ + ٨ + ٦ = ٣٢ وهو الأعلى بين الأعمدة.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug27_q38_letters_table.png', 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'نسبة النساء إلى الرجال ٥ : ٢ وعدد النساء ٣٠، ونسبة الرجال إلى الأطفال ٣ : ٧. قارن بين:
القيمة الأولى: عدد الأطفال
القيمة الثانية: ٢٤ طفلًا', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'الرجال = ٣٠ × ٢ ÷ ٥ = ١٢، والأطفال = ١٢ × ٧ ÷ ٣ = ٢٨، وهو أكبر من ٢٤.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'عمر نواف أصغر من عمر محمد بأربع سنوات، وعمره يساوي ٧/٨ من عمر محمد. كم عمر نواف؟', '["٣٢", "٢٤", "٢٨", "٣٦"]'::jsonb, 2, 'الفرق ٤ سنوات يمثل ١/٨ من عمر محمد، فعمر محمد ٣٢ وعمر نواف = ٣٢ − ٤ = ٢٨ سنة.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: مجموع قياسات الزوايا الخارجية للمثلث س + ص + ع
القيمة الثانية: ٣٦٠', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 2, 'مجموع الزوايا الخارجية لأي مضلع محدب — والمثلث منها — يساوي ٣٦٠° دائمًا؛ فالقيمتان متساويتان.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug27_q41_exterior.png', 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: مثلث كبير متطابق الضلعين قياس زاوية رأسه س، ومثلث صغير متساوي الأضلاع معلق أسفل قاعدته. فإذا كانت م زاوية قاعدة المثلث الكبير و ن زاوية المثلث الصغير عند النقطة نفسها، وكان م + ن = ١٠٠، فأوجد قيمة س.', '["٤٠", "٦٠", "٨٠", "١٠٠"]'::jsonb, 3, 'المثلث الصغير متساوي الأضلاع فزاويته ن = ٦٠°، ومنها م = ١٠٠ − ٦٠ = ٤٠°. وللتطابق زاويتا قاعدة الكبير ٤٠ و٤٠، فزاوية الرأس س = ١٨٠ − ٨٠ = ١٠٠°.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug27_q42_two_triangles.png', 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان ن و م عددين أكبر من الصفر، قارن بين:
القيمة الأولى: م + ن
القيمة الثانية: م × ن', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 3, 'لا قاعدة عامة: عند م = ن = ١ يكون الجمع ٢ أكبر من الضرب ١، وعند م = ن = ٣ يكون الضرب ٩ أكبر من الجمع ٦؛ فالمعطيات غير كافية.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'يبين الشكل أعداد الطلاب حسب أطوالهم. عند أي طول يكون عدد الطلاب الأقل؟', '["١٣٠", "١٤٠", "١٥٠", "١٦٠"]'::jsonb, 0, 'الأعمدة: ١٣٠ عنده ١٠ طلاب وهو الأدنى، مقابل ١٥ و٢٥ و٢٠ و٣٥ لبقية الأطوال.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug27_q44_heights_bars.png', 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان س³ = ٤٨، قارن بين:
القيمة الأولى: س²
القيمة الثانية: ١٥', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, 'نرفع الطرفين للتكعيب الموحد: س⁶ = ٤٨² = ٢٣٠٤، أي س² = ∛٢٣٠٤. و١٥ = ∛٣٣٧٥، و٢٣٠٤ أصغر من ٣٣٧٥؛ فالقيمة الثانية أكبر.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان ٤٦ ≤ ص ≤ ١٢٩٦، و ٢٤ ≤ س ≤ ٣٦، فما أكبر قيمة للمقدار ص ÷ س؟', '["٣٦", "٥٤", "٤٨", "٦٠"]'::jsonb, 1, 'الكسر يكبر بأكبر بسط وأصغر مقام: ١٢٩٦ ÷ ٢٤ = ٥٤.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'نصف العدد ٢^٥٠ يساوي:', '["٢^٤٨", "٢^٤٩", "٢^٥١", "٢^٥٢"]'::jsonb, 1, 'القسمة على ٢ تنقص الأس واحدًا: ٢^٥٠ ÷ ٢ = ٢^٤٩.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'يبين القطاع الدائري توزيع أشخاص حسب تخطيطهم للمستقبل: يخططون دائمًا ٤٠٪، ولأسبوع ٢٥٪، ولأشهر ٢٠٪، ولسنوات ١٠٪، ولا يخططون ٥٪. ما نسبة الذين يخططون دائمًا إلى الذين يخططون لأسبوع؟', '["٤ : ١", "٢ : ١", "٨ : ٥", "٥ : ٨"]'::jsonb, 2, 'النسبة = ٤٠ : ٢٥، وبالقسمة على ٥ تصبح ٨ : ٥.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug27_q47_planning_pie.png', 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ١ − [١ ÷ (١ − ١/٣)]
القيمة الثانية: ١/٢', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, 'المقام الداخلي = ٢/٣، فيكون ١ ÷ (٢/٣) = ٣/٢. القيمة الأولى = ١ − ١٫٥ = −٠٫٥ وهي أصغر من ٠٫٥.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ١٧^(٢س) ÷ ١٧^س
القيمة الثانية: ١٧^(س/٢)', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 3, 'الأولى تختصر إلى ١٧^س. والمقارنة بين ١٧^س و١٧^(س/٢) تتوقف على إشارة س: تتساويان عند س = ٠ وتتفاوتان بخلاف ذلك؛ فالمعطيات غير كافية.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ١١٠ كجم
القيمة الثانية: ١ طن', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, 'الطن = ١٠٠٠ كجم، وهو أكبر من ١١٠ كجم.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان (١/٨)^(س + ١) = ٦٤^(١ − س)، فأوجد قيمة س.', '["٢", "١", "٣", "٤"]'::jsonb, 2, 'نوحد الأساس ٢: الطرف الأول ٢^(−٣س − ٣) والثاني ٢^(٦ − ٦س). بمساواة الأسين: −٣س − ٣ = ٦ − ٦س، فيكون ٣س = ٩ ومنها س = ٣.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ١ ÷ (٥/٣)
القيمة الثانية: (٣/٥) ÷ (٥/٣)²', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'الأولى = ٣/٥ = ٠٫٦. الثانية = ٠٫٦ ÷ (٢٥/٩) = ٠٫٦ × ٩ ÷ ٢٥ = ٠٫٢١٦؛ فالأولى أكبر.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: مستقيمان متقاطعان، والزاويتان المتقابلتان بالرأس قياساهما (٣س)° و٣٠°. أوجد قيمة س.', '["١٠", "٣", "٣٠", "٥"]'::jsonb, 0, 'المتقابلتان بالرأس متساويتان: ٣س = ٣٠ فتكون س = ١٠.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug27_q53_vertical_angles.png', 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'كان ما مع إبراهيم إلى ما مع حمزة بنسبة ٥ : ٤، فإذا أعطى إبراهيم ريالين لحمزة أصبحا متساويين. كم كان مع إبراهيم؟', '["٢٠", "١٠", "١٨", "١٦"]'::jsonb, 0, 'نفرض الوحدة ك: مع إبراهيم ٥ك ومع حمزة ٤ك. بعد نقل ريالين: ٥ك − ٢ = ٤ك + ٢ فيكون ك = ٤، ومع إبراهيم ٥ × ٤ = ٢٠ ريالًا.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'كانت درجات فهد في بعض المواد: ١٣، ١٤، ٢٣، ٢٥، ٢٥. فكم سيكون معدله بهذه المواد؟', '["٢٣", "٢٥", "١٤", "٢٠"]'::jsonb, 3, 'المجموع = ١٣ + ١٤ + ٢٣ + ٢٥ + ٢٥ = ١٠٠، والمعدل = ١٠٠ ÷ ٥ = ٢٠.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'إذا كان محمد يقطع الدورة الكاملة في ٦٤ ثانية، قارن بين:
القيمة الأولى: زمن ١٠ دورات
القيمة الثانية: ١٠ دقائق', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'زمن ١٠ دورات = ٦٤٠ ثانية، و١٠ دقائق = ٦٠٠ ثانية؛ فالأولى أكبر.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'عجلة تدور (ل) دورة في (١/أ) ساعة، كم عدد الدورات التي تدورها في (ن) ساعة؟', '["(أ + ل) ÷ ن", "ل × أ × ن", "ل × أ", "(أ × ل) ÷ ن"]'::jsonb, 1, 'معدل الدوران = ل دورة لكل (١/أ) ساعة = ل × أ دورة في الساعة، وفي (ن) ساعة تدور ل × أ × ن دورة.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'محدود : شائع', '["مشهور : ناجح", "قليل : نافع", "مرن : قاس", "سريع : عاجل"]'::jsonb, 2, 'المحدود ضد الشائع المنتشر، والمرن ضد القاسي؛ علاقة تضاد. أما سريع : عاجل فترادف.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'تؤدة : تأنٍّ', '["مكوث : بقاء", "يقظة : رشد", "جهل : علم", "معرفة : سفر"]'::jsonb, 0, 'التؤدة هي التأني فالعلاقة ترادف، ومثلها المكوث والبقاء.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'حاد : مثلم', '["واسع : عميق", "طويل : ممتد", "كريم : بخيل", "حليم : صادق"]'::jsonb, 2, 'الحاد ضد المثلم (الذي ذهب حده)، والكريم ضد البخيل؛ تضاد بين صفتين.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'عقرب : سم', '["نخلة : تمر", "هواء : مكيف", "حرارة : فرن", "رضا : سرور"]'::jsonb, 0, 'العقرب مصدر يخرج منه السم، والنخلة مصدر يخرج منه التمر. أما هواء : مكيف وحرارة : فرن فمعكوسان.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'سائق : قيادة', '["ضابط : أمن", "ملعقة : الأكل", "معلم : مدرسة", "فلاح : محراث"]'::jsonb, 0, 'السائق مهمته القيادة والضابط مهمته الأمن؛ صاحب مهنة ومسؤوليته. أما معلم : مدرسة فمع مكان العمل.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'ثوب : بدن', '["علم : نور", "تقوى : روح", "إيمان : جنة", "غطاء : سرير"]'::jsonb, 1, 'الثوب لباس البدن والتقوى لباس الروح؛ ساتر وما يستره على المعنى الحسي والمعنوي.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'معلم : مدير', '["موظف : وزير", "وكيل : كاتب", "أب : أخ", "أم : ابن"]'::jsonb, 0, 'المدير يعلو المعلم في السلم الوظيفي كما يعلو الوزير الموظف؛ علاقة تدرج رئاسي.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'رف : دولاب', '["جبهة : رأس", "رمش : حاجب", "كتاب : مطبعة", "كهرباء : مولد"]'::jsonb, 0, 'الرف جزء من الدولاب والجبهة جزء من الرأس. أما الرمش والحاجب فجزءان متجاوران لا جزء من كل.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'دعاء : استجابة', '["دواء : استفادة", "عطاء : استزادة", "نداء : استغاثة", "حرب : سلام"]'::jsonb, 0, 'الدعاء يُرجى من ورائه الاستجابة، والدواء تُرجى منه الاستفادة والشفاء. أما نداء : استغاثة فالاستغاثة سبب النداء لا ثمرته.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'ليس كل خوف ....... وليس كل تهور .......', '["جبن – شجاعة", "ضعف – قوة", "حذر – إقدام", "هلع – حكمة"]'::jsonb, 0, 'الجملة تصحح خلطًا شائعًا: الخوف لا يعني الجبن دائمًا، والتهور ليس شجاعة.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'ينتظر الإنسان ....... سريعًا؛ لأن نفسه مجبولة على .......', '["الثواب – العجلة", "العطاء – الكرم", "المدح – الخير", "الأجر – التردد"]'::jsonb, 0, 'تعليل استعجال الثواب بطبيعة النفس البشرية المجبولة على العجلة.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'السخاء والكرم ....... عيوب المرء، والبخل ....... كل غطاء.', '["تخفي – تواريها", "يغطي – يكشف", "يجمل – يستر", "يمحو – يصنع"]'::jsonb, 1, 'المقابلة بين أثر الكرم وأثر البخل: الكرم يغطي العيوب، والبخل يكشف كل غطاء.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'إذا أردت أن يستجيب الله دعاءك في ....... فادعُه في .......', '["الشدائد – الكربات", "الضراء – السراء", "المحن – البلايا", "الليل – النهار"]'::jsonb, 1, 'المعنى المأثور: تعرف إلى الله في الرخاء يعرفك في الشدة؛ فالزوج المتقابل الصحيح: الضراء – السراء.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'لا يتصف ....... إلا .......', '["بالحقد – دنيء", "بالضغينة – عظيم", "بالنعم – كريم", "بالفضل – لئيم"]'::jsonb, 0, 'الحقد صفة ذم لا يتصف بها إلا دنيء النفس؛ فالزوج المستقيم معنًى: بالحقد – دنيء.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'كلما بذلت ....... من الجهد زادت صعوبة .......', '["الكثير – اليقين", "القليل – الاستسلام", "اليسير – الاستسلام", "القليل – المواجهة"]'::jsonb, 3, 'قلة الجهد تراكم الصعاب فتشتد المواجهة لاحقًا؛ فالزوج المتسق: القليل – المواجهة.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'المال يُحفظ بطريقتين: جمعه من غير ....... وإنفاقه من غير .......', '["ظلم – سرف", "بخل – حساب", "جهد – فائدة", "كسب – علم"]'::jsonb, 0, 'آفة الجمع الظلم وآفة الإنفاق الإسراف؛ فحفظ المال بجمعه من غير ظلم وإنفاقه من غير سرف.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«غالبًا ما يعود العقاب البدني بالإيجابية على الطفل حيث يكون مشاكسًا ومقاومًا للتوجيهات»', '["غالبًا", "بالإيجابية", "مشاكسًا", "مقاومًا"]'::jsonb, 1, 'تتمة الجملة تصف أثرًا سيئًا (مشاكسة ومقاومة)، فالعقاب البدني يعود بالسلبية لا بالإيجابية.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«كلما ازداد استعمال البئر نقص عطاؤها»', '["استعمال", "البئر", "نقص", "عطاؤها"]'::jsonb, 2, 'البئر يزيد ماؤها مع كثرة الاستقاء منها كما في المثل المعروف؛ فالصواب: زاد عطاؤها.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«من أظلم خصال الحسد أنه يقتل الحاسد قبل أن يصل إلى المحسود»', '["أظلم", "يقتل", "الحاسد", "المحسود"]'::jsonb, 0, 'المفارقة أن الحسد يبدأ بصاحبه فيؤذيه قبل المحسود، وهذا عدل لا ظلم؛ فالصواب: من أعدل خصال الحسد.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«صديق السوء حسن المظهر طيب المخبر»', '["السوء", "المظهر", "طيب", "المخبر"]'::jsonb, 2, 'صديق السوء يجمّل ظاهره ويخفي باطنًا فاسدًا؛ فوصف مخبره بالطيب ينقض المعنى، والصواب: خبيث المخبر.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«الصحافة بوق السلام وصوت الأمة وسيف الحق القاطع وملاذ المظلوم ولجام الجبان»', '["الصحافة", "الأمة", "المظلوم", "الجبان"]'::jsonb, 3, 'السياق يعدد أدوار الصحافة في نصرة الحق وكبح الباطل؛ والذي يُكبح باللجام هو الظالم لا الجبان.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«تستطيع أن تكسب تفاعل الجمهور من خلال تحييدهم»', '["تستطيع", "تفاعل", "الجمهور", "تحييدهم"]'::jsonb, 3, 'التحييد إبعاد للجمهور عن المشاركة وهو نقيض كسب التفاعل؛ فالصواب: من خلال تحفيزهم.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«الطالب المجتهد، سواء أحضر الامتحان أو لم يحضره لن ينجح»', '["الطالب", "المجتهد", "الامتحان", "ينجح"]'::jsonb, 1, 'الحكم بعدم النجاح في الحالين لا يستقيم إلا مع المهمل؛ فوصف الطالب بالمجتهد هو الخطأ.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«الجدية في العمل تزيد فرصة إطالة الوقت واستثماره»', '["الجدية", "العمل", "فرصة", "إطالة"]'::jsonb, 3, 'الوقت لا يطول بالجدية، وإنما يُحسن استغلاله واستثماره؛ فالصواب: استغلال الوقت.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«إذا كانت الحمية مفيدة للنفس فإن الحمية الاجتماعية مفيدة للناس»', '["الحمية", "للنفس", "الاجتماعية", "للناس"]'::jsonb, 1, 'الحمية الغذائية نفعها يقع على الجسم، وبها يستقيم التوازي مع نفع الحمية الاجتماعية للناس؛ فالصواب: مفيدة للجسم.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["تركيا", "فلسطين", "العراق", "الأردن"]'::jsonb, 0, 'فلسطين والعراق والأردن دول عربية، أما تركيا فليست عربية.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["ركض", "جري", "هرولة", "وثب"]'::jsonb, 3, 'الركض والجري والهرولة حركة متواصلة على الأرض، أما الوثب فقفز.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["ذهب", "فضة", "ألماس", "لؤلؤ"]'::jsonb, 3, 'الذهب والفضة والألماس تُستخرج من باطن الأرض، أما اللؤلؤ فيُستخرج من المحار في البحر.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["كوبا", "أوكرانيا", "كندا", "أمريكا"]'::jsonb, 1, 'كوبا وكندا وأمريكا في القارة الأمريكية، أما أوكرانيا ففي أوروبا.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["سكين", "ملعقة", "شوكة", "خلاط"]'::jsonb, 3, 'السكين والملعقة والشوكة أدوات مائدة يدوية، أما الخلاط فجهاز كهربائي.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["الاجتهاد", "الشهادة", "البيانات", "المعلومات"]'::jsonb, 0, 'الشهادة والبيانات والمعلومات أشياء موثقة مكتوبة، أما الاجتهاد فسلوك وعمل.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["يجري", "يمشي", "يقفز", "يطير"]'::jsonb, 3, 'الجري والمشي والقفز حركات على الأرض، أما الطيران ففي الهواء.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["كسل", "تعب", "إرهاق", "إنهاك"]'::jsonb, 0, 'التعب والإرهاق والإنهاك تنتج عن بذل الجهد، أما الكسل ففتور من غير جهد.', NULL, 'ad270826-2026-4c00-9d00-270820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'علاقة جملة (قد حدث ما خاف منه) بما قبلها:', '["استدراك", "نتيجة", "سبب", "تتمة لها"]'::jsonb, 1, 'فشل العمليات الاثنتي عشرة انتهى إلى وقوع ما كان يخافه؛ فالجملة نتيجة لما قبلها.', NULL, 'ad270826-2026-4c00-9d00-270820260001', 'e1a82701-2026-4c00-9d00-000000000001', 'كان الدكتور سميث مؤمنًا بأن البصر نعمة كبيرة، ويتمنى ألا يفقد بصره وكان يكرر هذه الجملة دائمًا. لكن حينما تجاوز الستين من عمره بدأ بصره يضعف وشعر بالغبش على عينيه وأصبحت عيناه لا يمكنهما التفريق بين بعض الأشياء، فذهب إلى الطبيب وكانت الفاجعة؛ حيث اكتشف الطبيب أنه قد فقد إحدى عينيه وأن بصره يضعف مع الوقت وأنه سيصاب بالعمى في العين الثانية. قام بإجراء ١٢ عملية جراحية على أمل أن يعود له بصره لكن لم يحدث، وقد حدث ما خاف منه حيث فقد العين الثانية. تعايش سميث مع فقدان بصره وتيقن أن العقل هو أهم شيء حتى لو فقد جميع حواسه.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'ماذا يستفاد من النص؟', '["التأقلم مع كل الظروف", "الحرص على العلاج المبكر", "تجنب إجراء العمليات", "الخوف من المستقبل"]'::jsonb, 0, 'خاتمة النص أن سميث تعايش مع فقد بصره وأدرك قيمة عقله؛ فالعبرة هي التأقلم مع الظروف مهما اشتدت.', NULL, 'ad270826-2026-4c00-9d00-270820260001', 'e1a82701-2026-4c00-9d00-000000000001', 'كان الدكتور سميث مؤمنًا بأن البصر نعمة كبيرة، ويتمنى ألا يفقد بصره وكان يكرر هذه الجملة دائمًا. لكن حينما تجاوز الستين من عمره بدأ بصره يضعف وشعر بالغبش على عينيه وأصبحت عيناه لا يمكنهما التفريق بين بعض الأشياء، فذهب إلى الطبيب وكانت الفاجعة؛ حيث اكتشف الطبيب أنه قد فقد إحدى عينيه وأن بصره يضعف مع الوقت وأنه سيصاب بالعمى في العين الثانية. قام بإجراء ١٢ عملية جراحية على أمل أن يعود له بصره لكن لم يحدث، وقد حدث ما خاف منه حيث فقد العين الثانية. تعايش سميث مع فقدان بصره وتيقن أن العقل هو أهم شيء حتى لو فقد جميع حواسه.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يدل النص على أن الدكتور سميث فقد نظره:', '["طبيعيًا", "متوقعًا", "بشكل مفاجئ", "تدريجيًا"]'::jsonb, 3, 'بدأ الأمر بضعف وغبش ثم فقد عين فالأخرى؛ وهذا فقدان تدريجي لا مفاجئ.', NULL, 'ad270826-2026-4c00-9d00-270820260001', 'e1a82701-2026-4c00-9d00-000000000001', 'كان الدكتور سميث مؤمنًا بأن البصر نعمة كبيرة، ويتمنى ألا يفقد بصره وكان يكرر هذه الجملة دائمًا. لكن حينما تجاوز الستين من عمره بدأ بصره يضعف وشعر بالغبش على عينيه وأصبحت عيناه لا يمكنهما التفريق بين بعض الأشياء، فذهب إلى الطبيب وكانت الفاجعة؛ حيث اكتشف الطبيب أنه قد فقد إحدى عينيه وأن بصره يضعف مع الوقت وأنه سيصاب بالعمى في العين الثانية. قام بإجراء ١٢ عملية جراحية على أمل أن يعود له بصره لكن لم يحدث، وقد حدث ما خاف منه حيث فقد العين الثانية. تعايش سميث مع فقدان بصره وتيقن أن العقل هو أهم شيء حتى لو فقد جميع حواسه.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'معنى (دائمًا) في النص:', '["التكرار", "الثبات", "الخلود", "المبالغة"]'::jsonb, 0, 'كان يكرر الجملة مرة بعد مرة؛ فدلالة «دائمًا» هنا التكرار.', NULL, 'ad270826-2026-4c00-9d00-270820260001', 'e1a82701-2026-4c00-9d00-000000000001', 'كان الدكتور سميث مؤمنًا بأن البصر نعمة كبيرة، ويتمنى ألا يفقد بصره وكان يكرر هذه الجملة دائمًا. لكن حينما تجاوز الستين من عمره بدأ بصره يضعف وشعر بالغبش على عينيه وأصبحت عيناه لا يمكنهما التفريق بين بعض الأشياء، فذهب إلى الطبيب وكانت الفاجعة؛ حيث اكتشف الطبيب أنه قد فقد إحدى عينيه وأن بصره يضعف مع الوقت وأنه سيصاب بالعمى في العين الثانية. قام بإجراء ١٢ عملية جراحية على أمل أن يعود له بصره لكن لم يحدث، وقد حدث ما خاف منه حيث فقد العين الثانية. تعايش سميث مع فقدان بصره وتيقن أن العقل هو أهم شيء حتى لو فقد جميع حواسه.', 4, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'وفقًا للنص، كيف يُصبَر على البلاء؟', '["الاحتساب", "الشكوى", "التجاهل", "الانعزال"]'::jsonb, 0, 'تعايش سميث مع الفقد راضيًا متيقنًا بما بقي له من نعم، وهذا هو الصبر بالاحتساب.', NULL, 'ad270826-2026-4c00-9d00-270820260001', 'e1a82701-2026-4c00-9d00-000000000001', 'كان الدكتور سميث مؤمنًا بأن البصر نعمة كبيرة، ويتمنى ألا يفقد بصره وكان يكرر هذه الجملة دائمًا. لكن حينما تجاوز الستين من عمره بدأ بصره يضعف وشعر بالغبش على عينيه وأصبحت عيناه لا يمكنهما التفريق بين بعض الأشياء، فذهب إلى الطبيب وكانت الفاجعة؛ حيث اكتشف الطبيب أنه قد فقد إحدى عينيه وأن بصره يضعف مع الوقت وأنه سيصاب بالعمى في العين الثانية. قام بإجراء ١٢ عملية جراحية على أمل أن يعود له بصره لكن لم يحدث، وقد حدث ما خاف منه حيث فقد العين الثانية. تعايش سميث مع فقدان بصره وتيقن أن العقل هو أهم شيء حتى لو فقد جميع حواسه.', 5, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'علاقة جملة (الذين لم يتجاوز أعمارهم العام) بجملة (الأطفال الرضع):', '["تأكيد على مدلولها", "نتيجة", "تخصيص عمومها", "تكرار المعنى"]'::jsonb, 2, 'الرضع لفظ عام، وتحديد من لم يتجاوزوا العام يخصص هذا العموم بفئة أدق.', NULL, 'ad270826-2026-4c00-9d00-270820260001', 'e1a82702-2026-4c00-9d00-000000000002', 'كشفت دراسة حديثة أن الحوادث المرورية تعد السبب الأكبر لوفيات الرضع بالمملكة بنسبة تصل إلى ٤٠٪، موضحة أن ٥٠٪ من الوفيات في حوادث السيارات تحدث لأطفال لم يتجاوز عمرهم العام، وتحدث نتيجة تجاهل استخدام المقاعد المخصصة وأحزمة الأمان؛ حيث وصلت حوادث المرور في السعودية إلى خمسة أضعاف نسبة الحوادث في أمريكا وكندا، وتزيد عن بريطانيا تسعة أضعاف، وذلك بسبب قلة الوعي وعدم الالتزام بالأنظمة والقوانين المرورية مع العاطفة الجامحة تجاه الأطفال إلا أن الموت لا يتناسب معها. وأضافت الدراسة الموسعة التي أجراها كرسي أرامكو للسلامة المرورية بجامعة الإمام عبد الرحمن بن فيصل أن مقاعد الأطفال تخفض نسبة الوفيات عند الرضع بنسبة ٧١٪، كما تقلل الإصابات والاحتياج للعلاج بالمستشفى بنسبة ٦٩٪.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يفهم من النص أن أقل دولة في حوادث المرور للأطفال:', '["بريطانيا", "كندا", "أمريكا وكندا", "السعودية"]'::jsonb, 0, 'حوادث السعودية خمسة أضعاف أمريكا وكندا وتسعة أضعاف بريطانيا؛ فالأقل نسبةً بريطانيا.', NULL, 'ad270826-2026-4c00-9d00-270820260001', 'e1a82702-2026-4c00-9d00-000000000002', 'كشفت دراسة حديثة أن الحوادث المرورية تعد السبب الأكبر لوفيات الرضع بالمملكة بنسبة تصل إلى ٤٠٪، موضحة أن ٥٠٪ من الوفيات في حوادث السيارات تحدث لأطفال لم يتجاوز عمرهم العام، وتحدث نتيجة تجاهل استخدام المقاعد المخصصة وأحزمة الأمان؛ حيث وصلت حوادث المرور في السعودية إلى خمسة أضعاف نسبة الحوادث في أمريكا وكندا، وتزيد عن بريطانيا تسعة أضعاف، وذلك بسبب قلة الوعي وعدم الالتزام بالأنظمة والقوانين المرورية مع العاطفة الجامحة تجاه الأطفال إلا أن الموت لا يتناسب معها. وأضافت الدراسة الموسعة التي أجراها كرسي أرامكو للسلامة المرورية بجامعة الإمام عبد الرحمن بن فيصل أن مقاعد الأطفال تخفض نسبة الوفيات عند الرضع بنسبة ٧١٪، كما تقلل الإصابات والاحتياج للعلاج بالمستشفى بنسبة ٦٩٪.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'الضمير في كلمة (معها) يعود على:', '["العاطفة", "السلامة", "الحوادث", "الأطفال"]'::jsonb, 0, 'التقدير: الموت لا يتناسب مع تلك العاطفة الجامحة تجاه الأطفال.', NULL, 'ad270826-2026-4c00-9d00-270820260001', 'e1a82702-2026-4c00-9d00-000000000002', 'كشفت دراسة حديثة أن الحوادث المرورية تعد السبب الأكبر لوفيات الرضع بالمملكة بنسبة تصل إلى ٤٠٪، موضحة أن ٥٠٪ من الوفيات في حوادث السيارات تحدث لأطفال لم يتجاوز عمرهم العام، وتحدث نتيجة تجاهل استخدام المقاعد المخصصة وأحزمة الأمان؛ حيث وصلت حوادث المرور في السعودية إلى خمسة أضعاف نسبة الحوادث في أمريكا وكندا، وتزيد عن بريطانيا تسعة أضعاف، وذلك بسبب قلة الوعي وعدم الالتزام بالأنظمة والقوانين المرورية مع العاطفة الجامحة تجاه الأطفال إلا أن الموت لا يتناسب معها. وأضافت الدراسة الموسعة التي أجراها كرسي أرامكو للسلامة المرورية بجامعة الإمام عبد الرحمن بن فيصل أن مقاعد الأطفال تخفض نسبة الوفيات عند الرضع بنسبة ٧١٪، كما تقلل الإصابات والاحتياج للعلاج بالمستشفى بنسبة ٦٩٪.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'العنوان المناسب للنص:', '["حزام الأمان", "الحوادث في السعودية", "حوادث وأخطاء", "جفاء المشاعر"]'::jsonb, 1, 'النص يدور حول أرقام الحوادث المرورية في السعودية وأثر مقاعد الأطفال فيها؛ فأقرب العناوين: الحوادث في السعودية.', NULL, 'ad270826-2026-4c00-9d00-270820260001', 'e1a82702-2026-4c00-9d00-000000000002', 'كشفت دراسة حديثة أن الحوادث المرورية تعد السبب الأكبر لوفيات الرضع بالمملكة بنسبة تصل إلى ٤٠٪، موضحة أن ٥٠٪ من الوفيات في حوادث السيارات تحدث لأطفال لم يتجاوز عمرهم العام، وتحدث نتيجة تجاهل استخدام المقاعد المخصصة وأحزمة الأمان؛ حيث وصلت حوادث المرور في السعودية إلى خمسة أضعاف نسبة الحوادث في أمريكا وكندا، وتزيد عن بريطانيا تسعة أضعاف، وذلك بسبب قلة الوعي وعدم الالتزام بالأنظمة والقوانين المرورية مع العاطفة الجامحة تجاه الأطفال إلا أن الموت لا يتناسب معها. وأضافت الدراسة الموسعة التي أجراها كرسي أرامكو للسلامة المرورية بجامعة الإمام عبد الرحمن بن فيصل أن مقاعد الأطفال تخفض نسبة الوفيات عند الرضع بنسبة ٧١٪، كما تقلل الإصابات والاحتياج للعلاج بالمستشفى بنسبة ٦٩٪.', 4, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'أي الآتي خاطئ بالنسبة لما ركزت عليه الهيئة التي تراقب حقوق الموظف؟', '["الحالة الصحية للموظف", "التقيد بوقت العمل", "أوقات رسائل البريد الإلكتروني", "الحرص على متابعة إنجاز الأعمال"]'::jsonb, 3, 'تركيز الهيئة على حماية وقت الموظف وصحته لا على مراقبة إنجازه؛ فمتابعة إنجاز الأعمال ليست مما ركزت عليه.', NULL, 'ad270826-2026-4c00-9d00-270820260001', 'e1a82703-2026-4c00-9d00-000000000003', 'قامت شركة بي إم سي بتشغيل موظفيها عن بعد بسبب قلة المكاتب، ووجدت أن نتائج العمل عن بعد أحسن من الحضوري؛ فقد زادت إنتاجية الموظفين في العمل عن بعد لأن الشخص يصبح مدير نفسه ويشعر بالمسؤولية. وهذا جعل الهيئة التي تراقب حقوق الموظف تغير المديرين وتعلمهم: أوقات رسائل البريد الإلكتروني، وإخبار الموظف بعدم تجاوز وقت العمل، ومنعه من العمل في منتصف الليل وما إلى ذلك، ومراعاة الحالة الصحية للموظف.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'أي مما يلي لم تحققه شركة بي إم سي نتيجة العمل عن بعد؟', '["زيادة الإنتاجية", "التطور", "خفض التكاليف", "تقليل الرواتب"]'::jsonb, 3, 'النص ذكر زيادة الإنتاجية وتحسن النتائج وقلة الحاجة للمكاتب، ولم يذكر أي مساس بالرواتب.', NULL, 'ad270826-2026-4c00-9d00-270820260001', 'e1a82703-2026-4c00-9d00-000000000003', 'قامت شركة بي إم سي بتشغيل موظفيها عن بعد بسبب قلة المكاتب، ووجدت أن نتائج العمل عن بعد أحسن من الحضوري؛ فقد زادت إنتاجية الموظفين في العمل عن بعد لأن الشخص يصبح مدير نفسه ويشعر بالمسؤولية. وهذا جعل الهيئة التي تراقب حقوق الموظف تغير المديرين وتعلمهم: أوقات رسائل البريد الإلكتروني، وإخبار الموظف بعدم تجاوز وقت العمل، ومنعه من العمل في منتصف الليل وما إلى ذلك، ومراعاة الحالة الصحية للموظف.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'ما الكلمة التي يمكن حذفها من النص دون إخلال بالمعنى؟', '["الناس", "لينير", "طريقهم", "فاعترضهم"]'::jsonb, 2, 'قولنا «لينير للناس» مكتفٍ بمعناه، وحذف «طريقهم» لا يخل بالمقصود.', NULL, 'ad270826-2026-4c00-9d00-270820260001', 'e1a82704-2026-4c00-9d00-000000000004', 'هذا ما صنع المسلمون المجاهدون؛ نزل عليهم المصباح الهادي في حراء والدنيا تتخبط في الظلماء، فحملناه لينير للناس طريقهم، فاعترضهم الآخرون.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يقصد بـ(الظلماء):', '["الظلام", "الجهل", "الحروب", "البغضاء"]'::jsonb, 1, 'الظلماء هنا رمز لما كانت عليه الدنيا قبل نزول الوحي، وهو ظلام الجهل والضلال.', NULL, 'ad270826-2026-4c00-9d00-270820260001', 'e1a82704-2026-4c00-9d00-000000000004', 'هذا ما صنع المسلمون المجاهدون؛ نزل عليهم المصباح الهادي في حراء والدنيا تتخبط في الظلماء، فحملناه لينير للناس طريقهم، فاعترضهم الآخرون.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'الضمير في كلمة (فحملناه) يعود على:', '["المصباح", "المسلمين", "حراء", "الظلماء"]'::jsonb, 0, 'المحمول لينير الطريق هو المصباح الهادي المذكور قبلها.', NULL, 'ad270826-2026-4c00-9d00-270820260001', 'e1a82704-2026-4c00-9d00-000000000004', 'هذا ما صنع المسلمون المجاهدون؛ نزل عليهم المصباح الهادي في حراء والدنيا تتخبط في الظلماء، فحملناه لينير للناس طريقهم، فاعترضهم الآخرون.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'من أولى زوجات النبي صلى الله عليه وسلم؟', '["خديجة", "عائشة", "حفصة", "سودة"]'::jsonb, 0, 'النص صريح: تزوج النبي صلى الله عليه وسلم السيدة خديجة بنت خويلد وهي أولى زوجاته.', NULL, 'ad270826-2026-4c00-9d00-270820260001', 'e1a82705-2026-4c00-9d00-000000000005', '١- كان النبي محمد صلى الله عليه وسلم قبل بعثته النبوية يُعرف في قومه بسمعة طيبة وأخلاق كريمة، فقد لُقب بالصادق الأمين نظرًا لصدق حديثه وأمانته في كل أموره. وكان الناس يتجمعون حوله للاستماع إلى كلامه الحكيم وأخلاقه الفاضلة، حيث كان مثلًا أعلى في الصدق والأمانة والشجاعة والكرم.
٢- بعد أن بلغ النبي صلى الله عليه وسلم الأربعين من عمره جاءه الوحي من الله سبحانه وتعالى في غار حراء، وكان هذا الحدث علامة فارقة في حياة النبي وأمته، حيث بدأ الدعوة إلى الإسلام. واجه النبي صلى الله عليه وسلم في بداية دعوته الكثير من الصعاب والمعارضة من قومه، إلا أنه صبر وثابر في سبيل نشر دعوة الإسلام. وقد تزوج النبي صلى الله عليه وسلم السيدة خديجة بنت خويلد وهي أولى زوجاته، والتي آمنت به ودعمته في دعوته.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'نوع النص:', '["ترجمة", "سيرة", "مقال", "قصة"]'::jsonb, 1, 'النص يعرض حياة النبي صلى الله عليه وسلم قبل البعثة وبعدها عرضًا تاريخيًا متسلسلًا، وهذا هو فن السيرة.', NULL, 'ad270826-2026-4c00-9d00-270820260001', 'e1a82705-2026-4c00-9d00-000000000005', '١- كان النبي محمد صلى الله عليه وسلم قبل بعثته النبوية يُعرف في قومه بسمعة طيبة وأخلاق كريمة، فقد لُقب بالصادق الأمين نظرًا لصدق حديثه وأمانته في كل أموره. وكان الناس يتجمعون حوله للاستماع إلى كلامه الحكيم وأخلاقه الفاضلة، حيث كان مثلًا أعلى في الصدق والأمانة والشجاعة والكرم.
٢- بعد أن بلغ النبي صلى الله عليه وسلم الأربعين من عمره جاءه الوحي من الله سبحانه وتعالى في غار حراء، وكان هذا الحدث علامة فارقة في حياة النبي وأمته، حيث بدأ الدعوة إلى الإسلام. واجه النبي صلى الله عليه وسلم في بداية دعوته الكثير من الصعاب والمعارضة من قومه، إلا أنه صبر وثابر في سبيل نشر دعوة الإسلام. وقد تزوج النبي صلى الله عليه وسلم السيدة خديجة بنت خويلد وهي أولى زوجاته، والتي آمنت به ودعمته في دعوته.', 2, 'active', false);
END IF;
END
$mig$;

-- مزامنة العداد مع الواقع
UPDATE leak_groups
SET question_count = (SELECT COUNT(*) FROM questions WHERE leak_group_id = 'ad270826-2026-4c00-9d00-270820260001')
WHERE id = 'ad270826-2026-4c00-9d00-270820260001';

-- تحقق نهائي
DO $chk$
DECLARE n INT; nq INT; nv INT; np INT;
BEGIN
  SELECT COUNT(*) INTO n FROM questions WHERE leak_group_id = 'ad270826-2026-4c00-9d00-270820260001';
  SELECT COUNT(*) INTO nq FROM questions WHERE leak_group_id = 'ad270826-2026-4c00-9d00-270820260001' AND section = 'quant';
  SELECT COUNT(*) INTO nv FROM questions WHERE leak_group_id = 'ad270826-2026-4c00-9d00-270820260001' AND section = 'verbal';
  SELECT COUNT(*) INTO np FROM questions WHERE leak_group_id = 'ad270826-2026-4c00-9d00-270820260001' AND passage_id IS NOT NULL;
  RAISE NOTICE 'إجمالي: % — كمي: % — لفظي: % — قطع: %', n, nq, nv, np;
  IF n <> 107 THEN RAISE EXCEPTION 'عدد الأسئلة % لا يطابق المتوقع 107', n; END IF;
  IF nq <> 58 OR nv <> 49 THEN RAISE EXCEPTION 'توزيع كمي/لفظي غير مطابق'; END IF;
END
$chk$;

COMMIT;