-- 100: Day 5 morning (hamma) — batch 6: chemistry + biology unique (9 questions, pages 118-190)
-- High duplicate rate with Sunday evening yelo — kept only confidently unique questions.

BEGIN;

INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'الزيت يذوب في..', '["الماء", "البنزين", "حمض عضوي", "الأسيتون"]'::jsonb, 1, 'قاعدة ''المثل يذيب المثل'': الزيت مادة غير قطبية ويذوب في المذيبات غير القطبية مثل البنزين. الماء قطبي فلا يذيب الزيت.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'عند مقارنة الإلكترون بالبروتون من حيث الشحنة والكتلة:', '["مختلفان في الشحنة والكتلة", "متساويان في الشحنة والكتلة", "متساويان في الشحنة ومختلفان في الكتلة", "متساويان في الكتلة ومختلفان في الشحنة"]'::jsonb, 2, 'الإلكترون شحنته −1 والبروتون +1 (متساويان في المقدار، مختلفان في الإشارة). أمّا الكتلة فالبروتون أثقل من الإلكترون بنحو 1836 مرّة. الجواب الأدقّ: متساويان في مقدار الشحنة (الإشارة مختلفة)، مختلفان في الكتلة.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'ما نوع التفاعل: NH₄NO₃ ⟶ (حرارة) N₂O + 2H₂O؟', '["تفكّك", "احتراق", "تكوين", "إحلال بسيط"]'::jsonb, 0, 'مادة واحدة (NH₄NO₃) تتحلّل بالحرارة إلى مادتين أو أكثر (N₂O + H₂O) → تفاعل تفكّك (Decomposition).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'وراثة', 'اختيار من متعدد', 'سبب طفرة الكروموسوم X الهشّ هو:', '["استبدال", "إضافة", "حذف", "تكرار (Trinucleotide Repeat Expansion)"]'::jsonb, 3, 'متلازمة الكروموسوم X الهشّ ناتجة عن تكرار غير طبيعي للنيوكليوتيدات الثلاثية (CGG repeats) في جين FMR1 على الكروموسوم X. كلّما زاد التكرار زادت شدّة الأعراض (تخلّف عقلي وراثي).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'سلوك', 'اختيار من متعدد', 'في سباقات الفروسية يُلاحظ عدم تأثر الخيول من الحضور الجماهيري. ما اسم هذا السلوك؟', '["تعلّماً كلاسيكياً شرطياً", "تعلّماً إجرائياً شرطياً", "مطبوعاً", "تعوّداً"]'::jsonb, 3, 'التعوّد (Habituation): إذا تكرّر مثير لا يحمل خطراً ولا فائدة، يفقد الكائن استجابته له. الخيول تعتاد على الجماهير بعد التكرار فلا تستجيب لها.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'بُنيت قاعدة تشارجاف على كميات الأدنين والجوانين والثايمين والسايتوسين في DNA. ما نتائجها؟', '["A > T، C > G", "A = T، C = G", "A = T، C > G", "A < T، C = G"]'::jsonb, 1, 'قاعدة تشارجاف: في الـDNA كمية الأدنين تساوي كمية الثايمين (A = T)، وكمية الجوانين تساوي كمية السايتوسين (C = G). هذا أساس مهم لبنية الشريط المزدوج (A يرتبط بـ T بـ2 روابط هيدروجينية، G بـ C بـ3 روابط).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'أيّ التالي لا يستخدم في عملية الهضم؟', '["المعدة", "الفم", "الأمعاء الدقيقة", "الأمعاء الغليظة"]'::jsonb, 3, 'الأمعاء الغليظة لا تشارك في هضم الطعام؛ وظيفتها الأساسية امتصاص الماء والأملاح وتشكيل البراز. الفم والمعدة والأمعاء الدقيقة كلها أعضاء هضمية فعّالة.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'أيّ الزواحف التالية ليس لديه جفن متحرّك؟', '["الورل", "الأفعى", "الضب", "الحرباء"]'::jsonb, 1, 'الأفاعي ليس لديها جفون متحرّكة؛ بدلاً من ذلك تحوي عيونها قشرة شفافة (Brille) تحميها وتُستبدَل عند الانسلاخ. باقي الزواحف (الورل، الضب، الحرباء) لديها جفون عادية.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'أيّ التالي ليس موجوداً في النباتات؟', '["سيليلوز", "جلوكوز", "سكروز", "لاكتوز"]'::jsonb, 3, 'اللاكتوز سكّر ثنائي يُوجد حصراً في حليب الثدييات (مكوّن من جلوكوز + جالاكتوز). السيليلوز والجلوكوز والسكروز كلها سكّريات نباتية شائعة (السيليلوز في جدران الخلايا، والسكروز في النسغ).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);

COMMIT;
