-- ═══════════════════════════════════════════════════════════════
-- تسريبات القدرات – الأربعاء ٩ سبتمبر ٢٠٢٦
-- 50 سؤالاً: كمي 23 + لفظي 27 (منها 5 في قطع استيعاب)
-- آمن لإعادة التشغيل: guard على وجود أسئلة المجموعة
-- ═══════════════════════════════════════════════════════════════
BEGIN;

INSERT INTO leak_groups (id, title, leak_date, section, question_count, description, is_active, accent_color)
VALUES ('ad090926-2026-4c00-9d00-090920260001', 'تسريبات القدرات – الأربعاء ٩ سبتمبر ٢٠٢٦', '2026-09-09', 'mixed', 50, 'أسئلة اختبار القدرات المحوسب ليوم الأربعاء ٩ سبتمبر ٢٠٢٦ (٢٧ ربيع الأول ١٤٤٨) — القسمان الكمي واللفظي مع الشروح.', true, '#7C3AED')
ON CONFLICT (id) DO NOTHING;

DO $mig$
BEGIN
IF EXISTS (SELECT 1 FROM questions WHERE leak_group_id = 'ad090926-2026-4c00-9d00-090920260001') THEN
  RAISE NOTICE 'أسئلة المجموعة موجودة مسبقاً — تخطي الإدراج';
ELSE
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان √(س³) = ٣٤٣، فما قيمة س؟', '["٧", "٤٩", "٩٨", "٣٤٣"]'::jsonb, 1, '٣٤٣ = ٧³، فـس³ = ٣٤٣² = ٧⁶ ومنها س = ٧² = ٤٩. تحقق: ٤٩³ = ٧⁶ وجذره التربيعي ٧³ = ٣٤٣.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان ١٠ قطع فضية + قطعة ذهبية = ٣ قطع ذهبية، قارن بين:
القيمة الأولى: قطعة واحدة ذهبية
القيمة الثانية: ٥ قطع فضية', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 2, 'من المعادلة: ١٠ فضية = ٣ ذهبية − ١ ذهبية = ٢ ذهبية، فالذهبية الواحدة = ٥ فضية؛ القيمتان متساويتان.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: متوازي أضلاع ظُلّل فيه مثلث قاعدته نصف قاعدة المتوازي وارتفاعه يساوي ارتفاع المتوازي. ما نسبة مساحة المثلث المظلل إلى مساحة الشكل كله؟', '["١/٢", "١/٣", "١/٤", "١/٨"]'::jsonb, 2, 'مساحة المتوازي = القاعدة × الارتفاع، ومساحة المثلث = ½ × (نصف القاعدة) × الارتفاع = ربع مساحة المتوازي.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep09_q003_pgram.png', 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: مربع مساحته ١٠٠ سم²، رُسم على ضلعه العلوي مثلث متساوي الساقين قاعدته هي ذلك الضلع ومساحته ١٠ سم². أوجد طول القطعة الواصلة من أحد رأسي القاعدة السفلية للمربع إلى رأس المثلث.', '["١٢", "٥", "١٣", "١٥"]'::jsonb, 2, 'ضلع المربع = ١٠ سم. ارتفاع المثلث = ٢ × ١٠ ÷ ١٠ = ٢ سم، فرأس المثلث يبعد ١٢ سم عن القاعدة السفلية رأسيًا و٥ سم أفقيًا عن الركن. الطول = √(١٢² + ٥²) = ١٣ سم.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep09_q004_house.png', 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان أ = ١/ب، وب = ١/ج، وج = ١/د، ود = √٦٤ ÷ √٤٩، فأوجد قيمة (أ + ج) × د.', '["٣/٢", "٢", "٧/٨", "٨/٧"]'::jsonb, 1, 'د = ٨/٧، فـج = ٧/٨، وب = ٨/٧، وأ = ٧/٨. إذًا (أ + ج) × د = (٧/٨ + ٧/٨) × (٨/٧) = (١٤/٨) × (٨/٧) = ٢.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'مستطيل طول ضلعيه المتقابلين ٤ص + ٨ و٢٠س − ١٦، وطول ضلعيه الآخرين س² وص. إذا كان أحد بعديه عددًا فرديًا، فأوجد محيطه.', '["٥٦", "٨٨", "١٠٦", "١١٦"]'::jsonb, 2, 'من تساوي الأضلاع المتقابلة: ص = س²، و٤ص + ٨ = ٢٠س − ١٦. بالتعويض: ٤س² − ٢٠س + ٢٤ = ٠ أي س² − ٥س + ٦ = ٠، فـس = ٢ أو ٣. البعد الفردي يتحقق عند س = ٣ (ص = ٩)، والبعد الآخر = ٤ × ٩ + ٨ = ٤٤، فالمحيط = ٢ × (٩ + ٤٤) = ١٠٦.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'مثلثان متشابهان على هيئة الفراشة: طولا ضلعين متناظرين ١٢ و٥، والضلعان المتناظران الآخران طولاهما ٢س − ٢ وس − ٢ على الترتيب. أوجد قيمة س.', '["٥", "٦", "٧", "٨"]'::jsonb, 2, 'من التشابه: ١٢/٥ = (٢س − ٢)/(س − ٢)، أي ١٢س − ٢٤ = ١٠س − ١٠، ومنها ٢س = ١٤ فتكون س = ٧.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ١/٢٩٩ + ١/٣٩٩
القيمة الثانية: ١/٣٣', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, 'كل كسر في القيمة الأولى أصغر من ١/٢٠٠، فمجموعهما أصغر من ٢/٢٠٠ = ١/١٠٠، وهذا أصغر من ١/٣٣.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'إذا زادت س بنسبة ٢٠٪ ونقصت ص بنسبة ٢٠٪ فأصبحتا متساويتين، فأوجد نسبة س إلى ص.', '["٢ : ١", "٣ : ١", "٢ : ٣", "٤ : ١"]'::jsonb, 2, '١٫٢س = ٠٫٨ص، فـس/ص = ٠٫٨/١٫٢ = ٢/٣، أي س : ص = ٢ : ٣.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', '(١١)² − (١٠)² = .....', '["٢٠", "٢١", "٢٢", "٢٣"]'::jsonb, 1, 'الفرق بين مربعين = (١١ − ١٠)(١١ + ١٠) = ١ × ٢١ = ٢١.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'التحليل', 'اختيار من متعدد', 'أوجد نصف الحد الخامس للمتتابعة: ١١، ٢٢، ٤٤، ٨٨، .....', '["٤٤", "٨٨", "١٧٦", "٣٥٢"]'::jsonb, 1, 'كل حد ضعف الذي قبله، فالحد الخامس = ٨٨ × ٢ = ١٧٦، ونصفه = ٨٨.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'إيرادات ومصروفات أربع شركات بالملايين: الأولى ١٢٥ و٩٠، الثانية ١٣٥ و١١٥، الثالثة ١٤٠ و١١٥، الرابعة ٨٠ و٢٠. أي الشركات الأكثر ربحًا؟', '["الشركة الأولى", "الشركة الثانية", "الشركة الثالثة", "الشركة الرابعة"]'::jsonb, 3, 'الربح = الإيرادات − المصروفات: الأولى ٣٥، الثانية ٢٠، الثالثة ٢٥، الرابعة ٦٠؛ فالرابعة الأكثر ربحًا رغم أن إيراداتها الأقل.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'اشترى أحمد ٥٥ لترًا من الماء بمبلغ ٣٥ ريالًا، واشترى عمر ٦٠ لترًا بمبلغ ٣٦ ريالًا. قارن بين:
القيمة الأولى: سعر اللتر الواحد الذي اشتراه أحمد
القيمة الثانية: سعر اللتر الواحد الذي اشتراه عمر', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'سعر اللتر عند أحمد = ٣٥ ÷ ٥٥ ≈ ٠٫٦٤ ريال، وعند عمر = ٣٦ ÷ ٦٠ = ٠٫٦ ريال؛ فالقيمة الأولى أكبر.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'دائرة نصف قطرها ٤ مركزها نقطة الأصل. ظُلّلت القطعة الدائرية المحصورة بين القوس الواقع في الربع الثاني والوتر الواصل بين النقطتين (−٤، ٠) و(٠، ٤). احسب مساحة الجزء المظلل.', '["٤π − ٨", "٤π − ١٦", "٨π − ٨", "١٦π − ٨"]'::jsonb, 0, 'مساحة ربع الدائرة = ¼ × π × ٤² = ٤π. نطرح منها مساحة المثلث القائم الذي ضلعاه نصفا القطر: ½ × ٤ × ٤ = ٨. المظلل = ٤π − ٨.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep09_q014_segment.png', 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'التحليل', 'اختيار من متعدد', 'عمر أحمد أكبر من عمر خالد، وعمر سعود أصغر من عمر محمد، وعمر خالد أكبر من عمر محمد. قارن بين:
القيمة الأولى: عمر أحمد
القيمة الثانية: عمر سعود', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'نرتب: أحمد > خالد > محمد > سعود، فأحمد أكبر من سعود.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان أ + ب = ٥، وأ + ج = ٣، وب + ج = ٢، فأوجد قيمة ج.', '["٠", "١", "٢", "٣"]'::jsonb, 0, 'بجمع المعادلات: ٢(أ + ب + ج) = ١٠ فـأ + ب + ج = ٥. وبما أن أ + ب = ٥ فإن ج = ٠.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'محل يبيع ٦ بطاريات بـ٣٠٠ ريال. بكم يبيع ١٠ بطاريات بالسعر نفسه؟', '["٤٠٠", "٤٥٠", "٥٠٠", "٥٥٠"]'::jsonb, 2, 'سعر البطارية الواحدة = ٣٠٠ ÷ ٦ = ٥٠ ريالًا، فثمن ١٠ بطاريات = ٥٠٠ ريال.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'المثلثان أ د ج وأ ج ب متشابهان، فيهما أ د = ١٦ سم، وأ ج = ٢٤ سم، وأ ب = ٣٠ سم. أوجد طول د ج المناظر للضلع أ ب.', '["١٠", "١٢", "٢٠", "٢٤"]'::jsonb, 2, 'نسبة التشابه = أ د : أ ج = ١٦ : ٢٤ = ٢ : ٣، فـد ج = أ ب × (٢/٣) = ٣٠ × ٢/٣ = ٢٠ سم.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'التحليل', 'اختيار من متعدد', 'أوجد الحد التالي في المتتابعة: ٦، ١٨، ٢١، ٦٣، ٦٦، .....', '["٧١", "١٣٢", "١٢٩", "١٩٨"]'::jsonb, 3, 'النمط يتناوب: ضرب في ٣ ثم إضافة ٣: ٦ × ٣ = ١٨، ١٨ + ٣ = ٢١، ٢١ × ٣ = ٦٣، ٦٣ + ٣ = ٦٦، ثم ٦٦ × ٣ = ١٩٨.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا أعطى حمزة ٣ ريالات لإبراهيم أصبحت نسبة ما مع حمزة إلى ما مع إبراهيم ٢ : ١، وإذا أعطى إبراهيم لحمزة ريالين أصبحت النسبة ٣ : ١. كم المبلغ الذي مع حمزة؟', '["١٧", "٣٣", "٤٣", "٤٥"]'::jsonb, 2, 'لو مع حمزة ح ومع إبراهيم ب: (ح − ٣) = ٢(ب + ٣) و(ح + ٢) = ٣(ب − ٢). من الأولى ح = ٢ب + ٩، وبالتعويض في الثانية: ٢ب + ١١ = ٣ب − ٦ فـب = ١٧ وح = ٤٣.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'ما قيمة: ١ + ٢ + ٣ + ٤ + ٥ + ٦ + ٧ + ٦ + ٥ + ٤ + ٣ + ٢ + ١؟', '["٧ × ٨", "٧ × ٧", "٧ × ٦", "٧ × ٢"]'::jsonb, 1, 'مجموع ١ إلى ٧ = ٢٨، ومجموع ٦ إلى ١ = ٢١، والمجموع الكلي ٤٩ = ٧ × ٧ (قاعدة: مجموع الصعود إلى ن والهبوط منه = ن²).', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'مع شخص ٤٥ ريالًا: ورقة من فئة ٥ ريالات، وورقتان من فئة ١٠ ريالات، وورقة من فئة ٢٠ ريالًا. يريد شراء كتاب دون أن يُرجع له البائع باقيًا. ما عدد القيم الممكنة لثمن الكتاب؟', '["٨", "٩", "١٠", "١١"]'::jsonb, 1, 'المبالغ التي يمكن تكوينها من الأوراق: ٥، ١٠، ١٥، ٢٠، ٢٥، ٣٠، ٣٥، ٤٠، ٤٥ — تسع قيم مختلفة.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'ما العدد الذي سُدسه يساوي ٢٥/٣؟', '["٣٠", "٤٠", "٥٠", "٦٠"]'::jsonb, 2, 'العدد = ٦ × (٢٥/٣) = ٥٠.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'نعمة : نقمة', '["دراسة : إجازة", "جوع : شبع", "فرح : سرور", "كتاب : قلم"]'::jsonb, 1, 'النعمة ضد النقمة، والجوع ضد الشبع: علاقة تضاد.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'ضفدع : نقيق', '["ذئب : عواء", "نسر : ثغاء", "صهيل : حصان", "قط : نباح"]'::jsonb, 0, 'النقيق صوت الضفدع، والعواء صوت الذئب: كائن وصوته. أما «صهيل : حصان» فمعكوس، والثغاء للغنم لا للنسر.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'دكتور : جامعة', '["طبيب : مستشفى", "معلم : مدرسة", "حكم : مباراة", "مدير : إدارة"]'::jsonb, 1, 'الدكتور هنا هو أستاذ الجامعة الذي يعلّم فيها، كما يعلّم المعلم في المدرسة: من يعلّم ومكان تعليمه.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'نافذة : ستارة', '["قدر : غطاء", "جدار : دهان", "باب : مفتاح", "كتاب : قلم"]'::jsonb, 0, 'الستارة تحجب النافذة وتغطيها، والغطاء يغطي القدر: شيء وما يستره من الخارج.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'زاخر : مليء', '["شبيه : نظير", "سفيه : حقير", "أحمق : سخيف", "معتم : مضيء"]'::jsonb, 0, 'زاخر ومليء مترادفان، وكذلك شبيه ونظير: علاقة ترادف.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'القلم : العلم', '["السهم : الصيد", "السيارة : القيادة", "الجمل : التحمل", "الشدة : الصحراء"]'::jsonb, 0, 'القلم أداة يُطلب بها العلم، والسهم أداة يُطلب بها الصيد: أداة والغاية من استعمالها.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'رياح : هواء', '["طوفان : ماء", "كهرباء : صعق", "أرض : بركان", "سحاب : ثلج"]'::jsonb, 0, 'الرياح هواء متحرك بشدة، والطوفان ماء متدفق بشدة: الصورة العنيفة من العنصر نفسه.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'إن ....... العمل خير من ....... فيه.', '["إنجاز – المماطلة", "تأخير – تفريط", "تأجيل – الإسراع", "ترك – البدء"]'::jsonb, 0, 'المقابلة المستقيمة: إنجاز العمل خير من المماطلة فيه.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'إذا استطعت أن تلقى الله خميص البطن من ....... الناس، كافّ اللسان عن ....... فافعل.', '["صادق – اللهجة", "أموال – أعراضهم", "عالٍ – اليد", "خفي – النفس"]'::jsonb, 1, 'خميص البطن من أموال الناس أي لم يأكل منها حرامًا، وكافّ اللسان عن أعراضهم أي لم يغتبهم؛ فالزوج المناسب: أموال – أعراضهم.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'لن يراك الناس ....... إذا تجاهلت السفهاء، ولكن قد ....... بينكم عندما تحاول مواجهتهم.', '["متكبرًا – يخلطون", "متغطرسًا – يميزون", "متواضعًا – يمزحون", "حكيمًا – يفرقون"]'::jsonb, 0, 'تجاهل السفهاء لا يُعدّ كِبرًا، لكن مواجهتهم تجعل الناس يخلطون بينك وبينهم؛ فالزوج المناسب: متكبرًا – يخلطون.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'القرآن كتاب من الله يروي ....... عن الأنبياء في ....... بين الحق والباطل.', '["العبرة – القول", "القصص – الصراع", "الأحداث – الفرق", "الحكم – الخلاف"]'::jsonb, 1, 'القرآن يروي قصص الأنبياء في صراعهم بين الحق والباطل؛ فالزوج المستقيم: القصص – الصراع.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'النميمة لغة الجبان لأنه يحب مواجهة عدوه.', '["يحب", "النميمة", "الجبان", "عدوه"]'::jsonb, 0, 'الجبان يلجأ إلى النميمة لأنه يخاف مواجهة عدوه لا لأنه يحبها؛ فالخطأ في «يحب» وصوابها «يخاف».', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'الصمغ العربي يُستخرج من شجرة السنط بواسطة الملاعق الحادة.', '["الصمغ", "العربي", "السنط", "الملاعق"]'::jsonb, 3, 'الاستخراج من الشجرة يكون بأدوات حادة كالسكاكين لا بالملاعق؛ فالخطأ في «الملاعق».', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'من زاد عقله أوهم صاحبه أنه أوفر الناس عقلًا.', '["زاد", "أوهم", "أوفر", "عقلًا"]'::jsonb, 0, 'الذي يُوهم نفسه بأنه أوفر الناس عقلًا هو ناقص العقل لا زائده؛ فالخطأ في «زاد» وصوابها «نقص».', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'لا تمازح اللئيم فيحقد عليك، ولا الدنيء فيجترئ عليك.', '["اللئيم", "فيحقد", "الدنيء", "فيجترئ"]'::jsonb, 0, 'الحكمة المعروفة: لا تمازح الشريف فيحقد عليك ولا الدنيء فيجترئ عليك؛ فالمقابلة بين الشريف والدنيء، والخطأ في «اللئيم».', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'لا تكثر الكلام في مجلس فيه من يتمنون لك مواصلتك.', '["مواصلتك", "تكثر", "مجلس", "يتمنون"]'::jsonb, 0, 'من يكثر الكلام يتمنى جلساؤه سكوته لا مواصلته؛ فالخطأ في «مواصلتك» وصوابها «سكوتك».', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'يا أيها الشباب، لكم مسؤولية كبيرة، ونحن نضع فيكم شكًّا كبيرًا في أن تعلو همتنا علمًا.', '["مسؤولية", "شكًّا", "الشباب", "همتنا"]'::jsonb, 1, 'ما يوضع في الشباب هو الأمل والثقة لا الشك؛ فالخطأ في «شكًّا» وصوابها «أملًا».', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["يخت", "قارب", "غواصة", "سفينة"]'::jsonb, 2, 'اليخت والقارب والسفينة تسير على سطح الماء، أما الغواصة فتسير تحته.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["زواج", "عقد", "صهر", "مهر"]'::jsonb, 2, 'الزواج والعقد والمهر أمور وإجراءات تخص عملية الزواج، أما الصهر فشخص (قريب بالمصاهرة).', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["وادي", "هضاب", "جبال", "ربوة"]'::jsonb, 0, 'الهضاب والجبال والربوة تضاريس مرتفعة، أما الوادي فمنخفض.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["رف", "دولاب", "مكتبة", "معلاق"]'::jsonb, 2, 'الرف والدولاب والمعلاق قطع أثاث تُحفظ فيها الأشياء أو تُعلّق، أما المكتبة فمكان أو مجموعة كتب.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["فرس", "ناقة", "أتان", "زرافة"]'::jsonb, 3, 'الفرس والناقة والأتان أسماء تخص إناث حيوانات بعينها، أما الزرافة فاسم جنس للذكر والأنثى.', NULL, 'ad090926-2026-4c00-9d00-090920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'عبارة «من أهم المسائل الكبرى» تدل على:', '["أن هناك مسائل كبرى أخرى", "أنها المسألة الأكبر", "أن هناك مسائل أقل أهمية", "أنها مسألة طارئة"]'::jsonb, 0, 'قوله «من أهم المسائل الكبرى» يجعلها واحدة من عدة مسائل كبرى، فهناك مسائل كبرى أخرى غيرها.', NULL, 'ad090926-2026-4c00-9d00-090920260001', 'e1a90901-2026-4c00-9d00-000000000001', 'من المسائل الكبرى التي توجه إليها المدرسة المونتيسورية إعانة الطلاب والأطفال ليتعلموا استخدام مهاراتهم الإبداعية لابتكار حلول جديدة للمشكلات واستكشاف طرق جديدة للتعلم. وطريقة مونتيسوري، التي صاغتها الطبيبة والمعلمة الإيطالية ماريا مونتيسوري، تهدف إلى مساعدة الأطفال على تنمية حواسهم وقدراتهم العقلية والجسدية والروحية، ويعتمد هذا النظام على أدوات تعليمية محددة تساعد الطفل على التعلم الذاتي بعيدًا عن الحفظ عن ظهر قلب. ويقوم على أسس وقواعد تشجع احترام الفروق الفردية لكل طفل وتوفر بيئة آمنة ومحفزة للتفاعل الاجتماعي. وغالبًا ما تُطبق هذه الطريقة في مرحلة ما قبل المدرسة نظرًا لأهميتها في تعزيز نمو الطفولة المبكرة وبناء شخصية متوازنة.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'العنوان الأنسب للنص:', '["تنظيم الأطفال", "طريقة المدرسة المونتيسورية", "المدرسة المونتيسورية", "تربية الأطفال"]'::jsonb, 1, 'النص يشرح طريقة مونتيسوري: أهدافها وأدواتها وأسسها ومرحلة تطبيقها، فمحوره الطريقة نفسها لا المدرسة كمكان.', NULL, 'ad090926-2026-4c00-9d00-090920260001', 'e1a90901-2026-4c00-9d00-000000000001', 'من المسائل الكبرى التي توجه إليها المدرسة المونتيسورية إعانة الطلاب والأطفال ليتعلموا استخدام مهاراتهم الإبداعية لابتكار حلول جديدة للمشكلات واستكشاف طرق جديدة للتعلم. وطريقة مونتيسوري، التي صاغتها الطبيبة والمعلمة الإيطالية ماريا مونتيسوري، تهدف إلى مساعدة الأطفال على تنمية حواسهم وقدراتهم العقلية والجسدية والروحية، ويعتمد هذا النظام على أدوات تعليمية محددة تساعد الطفل على التعلم الذاتي بعيدًا عن الحفظ عن ظهر قلب. ويقوم على أسس وقواعد تشجع احترام الفروق الفردية لكل طفل وتوفر بيئة آمنة ومحفزة للتفاعل الاجتماعي. وغالبًا ما تُطبق هذه الطريقة في مرحلة ما قبل المدرسة نظرًا لأهميتها في تعزيز نمو الطفولة المبكرة وبناء شخصية متوازنة.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يُفهم من النص أن الحضارة:', '["مزيج عمراني", "مادية فقط", "نتاج عدة أصعدة", "منظور فكري"]'::jsonb, 2, 'النص يجمع في الحضارة المستوى الثقافي والعمراني والرصيد الروحي والفكري والجانب المادي، أي أنها نتاج عدة أصعدة.', NULL, 'ad090926-2026-4c00-9d00-090920260001', 'e1a90902-2026-4c00-9d00-000000000002', 'إن الحضارة هي التحصيل الضخم على المستوى الثقافي والعمراني لشعب من الشعوب، إلى جانب الرصيد الروحي والفكري وجانب المادية الحياتية.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'أي مما يلي لا يتوافق مع الفقرة؟', '["أخذ العالم بالرأي لأنه صادر من عالم ثقة", "العالم يعمل بالحقائق", "العالم يحكّم عقله قبل عاطفته", "الحياد مطلوب في التقييم"]'::jsonb, 0, 'الفقرة تجعل العالم محايدًا لا يعمل إلا بالحقائق حتى لو كانت ضد عالم كبير موثوق؛ فالأخذ بالرأي لمجرد صدوره عن عالم ثقة يناقضها.', NULL, 'ad090926-2026-4c00-9d00-090920260001', 'e1a90903-2026-4c00-9d00-000000000003', 'العالم دائمًا لا يعمل إلا بالحقائق ويكون محايدًا دائمًا، حتى لو كانت المسألة ضد عالم كبير وثقة؛ فهو يُحكّم عقله قبل عاطفته. ويجب على العلماء أن يكونوا حياديين في التقييم والرأي.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'أي الجمل الآتية تستعمل كلمة «موضوعية» بالمعنى المقصود في الفقرة؟', '["نظر القاضي في القضية بموضوعية", "الموضوعية كانت سبب نجاح الطالب", "ناقشت هذا الموضوع بإسهاب", "الموضوع مهم للجميع"]'::jsonb, 0, 'الموضوعية في الفقرة هي الحياد والحكم بالحقائق لا بالعاطفة، وهذا ما يفعله القاضي حين ينظر في القضية بموضوعية.', NULL, 'ad090926-2026-4c00-9d00-090920260001', 'e1a90903-2026-4c00-9d00-000000000003', 'العالم دائمًا لا يعمل إلا بالحقائق ويكون محايدًا دائمًا، حتى لو كانت المسألة ضد عالم كبير وثقة؛ فهو يُحكّم عقله قبل عاطفته. ويجب على العلماء أن يكونوا حياديين في التقييم والرأي.', 2, 'active', false);
END IF;
END
$mig$;

-- مزامنة العداد مع الواقع
UPDATE leak_groups
SET question_count = (SELECT COUNT(*) FROM questions WHERE leak_group_id = 'ad090926-2026-4c00-9d00-090920260001')
WHERE id = 'ad090926-2026-4c00-9d00-090920260001';

-- تحقق نهائي
DO $chk$
DECLARE n INT; nq INT; nv INT; np INT;
BEGIN
  SELECT COUNT(*) INTO n FROM questions WHERE leak_group_id = 'ad090926-2026-4c00-9d00-090920260001';
  SELECT COUNT(*) INTO nq FROM questions WHERE leak_group_id = 'ad090926-2026-4c00-9d00-090920260001' AND section = 'quant';
  SELECT COUNT(*) INTO nv FROM questions WHERE leak_group_id = 'ad090926-2026-4c00-9d00-090920260001' AND section = 'verbal';
  SELECT COUNT(*) INTO np FROM questions WHERE leak_group_id = 'ad090926-2026-4c00-9d00-090920260001' AND passage_id IS NOT NULL;
  RAISE NOTICE 'إجمالي: % — كمي: % — لفظي: % — قطع: %', n, nq, nv, np;
  IF n <> 50 THEN RAISE EXCEPTION 'عدد الأسئلة % لا يطابق المتوقع 50', n; END IF;
  IF nq <> 23 OR nv <> 27 THEN RAISE EXCEPTION 'توزيع كمي/لفظي غير مطابق'; END IF;
END
$chk$;

COMMIT;