-- 86: Day 5 evening (yelo) — batch 2: math + physics (22 questions)
-- Covers PDF pages 9-16 of the yelo Sun-evening PDF.

BEGIN;

INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'بسّط العبارة: 2/(1−i)', '["1", "i", "1+i", "i−1"]'::jsonb, 2, 'نضرب البسط والمقام في المرافق (1+i): 2(1+i)/[(1−i)(1+i)] = 2(1+i)/(1−i²) = 2(1+i)/2 = 1+i.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'إذا كان a و b متعامدان، وكان |a|=8 و |b|=4، فإن محصلتهما تساوي ..', '["4", "8", "4√5", "8√5"]'::jsonb, 2, 'للمتجهين المتعامدين: |a+b| = √(|a|² + |b|²) = √(64+16) = √80 = 4√5.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'ما الفترة التي تُمثّل المتباينة −3 ≤ x < 5؟', '["[−3,5]", "(−3,5)", "[−3,5)", "(−3,5]"]'::jsonb, 2, 'إشارة ≤ عند −3 تعني التضمين (قوس مربع)، وإشارة < عند 5 تعني الاستثناء (قوس عادي). إذاً: [−3, 5).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'إذا كان ABC ≅ EFG فأي التالي خطأ؟', '["m∠C = m∠G", "m∠A = m∠E", "AB ≅ EF", "AC ≅ FG"]'::jsonb, 3, 'في التطابق ABC ≅ EFG: A↔E و B↔F و C↔G. إذاً AC يقابل EG وليس FG. الخيار د خطأ.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'معيّن أنصاف قطريه (مسافة من المركز إلى الرأس) 8 و 6. أوجد طول ضلعه.', '["10", "8", "5", "6"]'::jsonb, 0, 'ضلع المعيّن = الوتر للمثلث القائم الذي ضلعاه نصفا القطرين. الضلع = √(8² + 6²) = √(64+36) = √100 = 10.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'لوغاريتمات', 'اختيار من متعدد', 'log₃5 + log₃7 يساوي ..', '["log₃35", "log₃12", "log₃(5/7)", "log₃(35/3)"]'::jsonb, 0, 'خاصية اللوغاريتم: log_a(m) + log_a(n) = log_a(m·n). إذاً log₃5 + log₃7 = log₃(5×7) = log₃35.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'إذا كان f(x) = (x²−x)/x²، فإذا كانت x = 0 فحدّد نوع عدم الاتصال:', '["لا نهائي", "لا نهائي قابل للإزالة", "قفزي", "قابل للإزالة"]'::jsonb, 0, 'بالقسمة: f(x) = 1 − 1/x. عند x→0 من اليمين: f→−∞، ومن اليسار: f→+∞. النهاية = ∞ → عدم اتصال لا نهائي (infinite discontinuity).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'الفيزياء', 'اختيار من متعدد', 'أربعة أصدقاء يصعدون درج في الوقت الموضح (أحمد 24s، خالد 20s، محمد 18s، سعيد 15s). إذا كان لهم الكتلة نفسها فأيهم أكبر قدرة؟', '["أحمد", "خالد", "محمد", "سعيد"]'::jsonb, 3, 'القدرة = الشغل/الزمن. الشغل المبذول واحد (الكتلة والارتفاع متساويان). أقل زمن = أكبر قدرة. سعيد بـ15s صاحب أقل زمن، فهو الأكبر قدرة.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'أي العبارات التالية ينطبق على الموجات الكهرومغناطيسية؟', '["إذا زاد ترددها نقصت طاقتها", "إذا زاد طولها الموجي زادت طاقتها", "إذا زاد طولها الموجي زاد ترددها", "إذا زاد طولها الموجي نقص ترددها"]'::jsonb, 3, 'العلاقة c = f·λ حيث c سرعة الضوء ثابتة. التردد والطول الموجي متناسبان عكسياً: زيادة الطول الموجي → نقص التردد، والعكس صحيح.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'احسب التسارع بوحدة m/s² لجسم تغيّرت سرعته من 5 m/s إلى 9.5 m/s خلال ثانية واحدة.', '["−14.5", "−4.5", "4.5", "14.5"]'::jsonb, 2, 'التسارع a = (Vₙ − Vᵢ)/t = (9.5 − 5)/1 = 4.5 m/s². إشارة موجبة لأن السرعة زادت.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'ظاهرة مميّزة لتعريف العناصر من خلال أطياف ضوئية ذات ترددات محددة:', '["التأثير الكهرومغناطيسي", "طيف الانبعاث الذري", "الإنبعاث الحراري", "السالبية الكهربائية"]'::jsonb, 1, 'كل عنصر له طيف انبعاث ذري فريد (أطياف خطية مميّزة). تُستخدم في علم الطيف لتعريف العناصر.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'وحدة قياس مستوى الصوت:', '["dB", "Hz", "lx", "V"]'::jsonb, 0, 'الديسيبل (dB) وحدة قياس شدة الصوت. Hz للتردد، lx للإضاءة، V للجهد الكهربائي.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'جسيمات سالبة تدور حول النواة:', '["إلكترونات", "بروتونات", "نيترونات", "بيتا"]'::jsonb, 0, 'الإلكترونات (شحنتها سالبة) تدور حول النواة في مدارات. البروتونات والنيوترونات داخل النواة.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'الفيزياء', 'اختيار من متعدد', 'الحمل الحراري يحدث في:', '["الموائع", "الموجات", "المعادن", "الغازات"]'::jsonb, 0, 'الحمل الحراري (convection) ينقل الحرارة عن طريق حركة جسيمات الموائع (السوائل والغازات). المعادن تنقل بالتوصيل لا الحمل.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'إنتاج ضوء يتذبذب في مستوى واحد:', '["الحيود", "التراكب", "التداخل", "الاستقطاب"]'::jsonb, 3, 'الاستقطاب (polarization) عملية تجعل الضوء يتذبذب في مستوى واحد فقط بدلاً من جميع الاتجاهات.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'الفيزياء', 'اختيار من متعدد', 'الطريقة الصحيحة لزيادة دقة المسطرة في مصنع البلاستيك:', '["زيادة عدد التدريجات في وحدة الطول", "زيادة عدد التدريجات في وحدة الطول", "زيادة طول المسطرة", "تقليل طول المسطرة"]'::jsonb, 0, 'دقة أداة القياس تتحسن بزيادة عدد التدريجات في وحدة الطول (تدريج أصغر = قراءة أدقّ).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'شحنة النيترونات:', '["سالبة", "موجبة", "متعادلة"]'::jsonb, 2, 'النيوترون جسيم متعادل كهربائياً (شحنته صفر). البروتون موجب والإلكترون سالب.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'أي العبارات التالية تصف الفوتون بشكل صحيح؟', '["للفوتون زخم وطاقة وليس له كتلة", "للفوتون زخم وكتلة وليس له طاقة", "للفوتون كتلة وطاقة وزخم", "للفوتون كتلة وطاقة وليس له زخم"]'::jsonb, 0, 'الفوتون له طاقة (E = hf) وزخم (p = h/λ)، لكن لا توجد له كتلة سكونية (كتلته الراحة = 0).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'أيٌّ مما يلي ليس من خصائص الموجة؟', '["طول الموجة", "سعة الموجة", "تردد الموجة", "كثافة الموجة"]'::jsonb, 3, 'خصائص الموجة الأساسية: الطول الموجي، السعة، التردد، السرعة، الدور. الكثافة ليست خاصية للموجة بل خاصية للوسط الذي تنتشر فيه.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'كمات الضوء تسمى:', '["فوتونات", "بروتونات", "إلكترونات", "نيوترونات"]'::jsonb, 0, 'الفوتون هو الكَم الأساسي للضوء — جسيم/موجة يحمل طاقة E = hf.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'الفيزياء', 'اختيار من متعدد', 'أي الكميات التالية متجهة؟', '["التسارع", "السرعة", "الزمن", "الكتلة"]'::jsonb, 0, 'التسارع كمية متجهة (له مقدار واتجاه). الزمن والكتلة كميات قياسية، والسرعة بمعنى speed (الكلمة الشائعة) قياسية.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'ما مصدر الأيونات في مطياف الكتلة؟', '["أيونات موجبة", "أيونات سالبة", "إلكترونات", "نيوترونات"]'::jsonb, 0, 'مطياف الكتلة يستخدم أيونات موجبة (تنتج من تأيين الذرات أو الجزيئات) ليتم فصلها وقياس كتلتها.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);

COMMIT;