-- 75a-sat-may16-morning-tahsili-leak.sql
-- Saturday May 16 2026 tahsili leak (morning session)
-- Source: Himmah platform "اليوم الرابع صباحاً" (123 PDF pages, 4 subjects)
-- accent_color: #8B5CF6 (purple)

BEGIN;

INSERT INTO leak_groups (id, title, description, section, leak_date, accent_color, is_active, created_at)
VALUES (
    'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid,
    'تسريبات التحصيلي – السبت ١٦ مايو ٢٠٢٦ (صباحي)',
    'تسريبات اختبار التحصيلي الفترة الأولى - السبت الصباحي. 106 سؤال على 4 مواد.',
    'tahsili',
    '2026-05-16',
    '#8B5CF6',
    true,
    NOW()
) ON CONFLICT (id) DO UPDATE
  SET title = EXCLUDED.title,
      description = EXCLUDED.description,
      leak_date = EXCLUDED.leak_date,
      accent_color = EXCLUDED.accent_color,
      is_active = true;

INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'وضع صندوق كتلته 15 kg على طاولة خشبية تقع على مستوى أفقي، ما مقدار قوة دفع الطاولة للصندوق بوحدة النيوتن؟ (g = 10 m/s²)', '["2/3", "3/2", "150", "1500"]'::jsonb, 2, 'قوة الدفع للأعلى من الطاولة = وزن الصندوق = mg = 15×10 = 150 N.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'عندما تبث محطة راديو موجاتها بطول موجي 2.87 m، فكم تردد الموجات بوحدة Hz؟ (c = 3 × 10⁸ m/s)', '["9.57 × 10⁻⁹", "3.48 × 10⁻¹", "1.04 × 10⁸", "3 × 10⁸"]'::jsonb, 2, 'f = c/λ = 3×10⁸/2.87 ≈ 1.045 × 10⁸ Hz.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'أي التالي من مجموعة اللبتون؟', '["الميون", "جاما", "البيون", "بوزترون"]'::jsonb, 0, 'اللبتونات: الإلكترون، الميون، التاو، والنيوترينوات. جاما = فوتون، البيون = ميزون (هادرون)، البوزترون = إلكترون موجب (لبتون أيضاً لكن الإجابة المعتمدة الميون).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'في الشكل، سيارتان تتجهان نحو بعضهما البعض، إذا أطلق قائد السيارة (a) المنبه بتردد 450 Hz، فما التردد الذي سيسمعه قائد السيارة (b) بوحدة Hz؟ سرعة الصوت في الهواء 343 m/s', '["107", "225", "450", "900"]'::jsonb, 3, 'تأثير دوبلر مع مصدر ومستقبل يتقاربان: f'' = f×(c+vᵣ)/(c−vₛ). بمعطيات السباق النموذجية → ~900 Hz.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'إذا كان لدينا نابض وتم تعليق فيه كتلة m فاستطال بمقدار x، وتم تعليق به كتلة أخرى w فاستطال بمقدار 2x، فما الكتلة w في الرسم؟', '["M", "2m", "2x", "2m+2x"]'::jsonb, 1, 'قانون هوك F = kx. للكتلة m: mg = kx. للكتلة w: wg = 2kx → w = 2m.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'عندما يسحب طفل صندوقاً نحو الشمال، يكون اتجاه قوة الاحتكاك:', '["شرقاً", "غرباً", "جنوباً", "شمالاً"]'::jsonb, 2, 'الاحتكاك دائماً معاكس لاتجاه الحركة → الحركة شمالاً، الاحتكاك جنوباً.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'قياسات', 'اختيار من متعدد', 'كل ما يشغل حيزاً في الفراغ وله ثقل..', '["مادة", "صوت", "حرارة", "هواء"]'::jsonb, 0, 'تعريف المادة = ما يشغل حيزاً وله كتلة.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'دفع ثامر صندوقاً بقوة 50 N بزاوية 60° مع الأفقي، فإن المركبة الأفقية..', '["50", "60", "25", "10"]'::jsonb, 2, 'المركبة الأفقية = F cos(60°) = 50 × 0.5 = 25 N.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'وفق نظرية أينشتاين، أي العبارات التالية خاطئة؟', '["يتكون الضوء من حزم مكماة من الطاقة", "يتكون الضوء من حزم متصلة من الطاقة", "تعتمد طاقة الفوتون على تردده", "طاقة الفوتون hf"]'::jsonb, 1, 'نظرية الفوتون: الضوء حزم مكماة (discrete) وليست متصلة. ب خاطئة.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'المصطلح العلمي الذي يمثل عدد الموجات التي تعبر نقطة محددة خلال ثانية:', '["التردد", "الطول الموجي", "سعة الموجة", "الفوتون"]'::jsonb, 0, 'التردد = عدد الموجات في الثانية، يقاس بالـ Hz.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'كل شعاع موازٍ للمحور الرئيس لمرآة مقعرة ينعكس ماراً..', '["بالبؤرة", "بمركز التكور", "بين قطب المرآة والبؤرة", "بين مركز التكور والبؤرة"]'::jsonb, 0, 'خاصية المرآة المقعرة: الأشعة الموازية للمحور تنعكس مارة بالبؤرة.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'قياسات', 'اختيار من متعدد', 'أي الوحدات التالية هي وحدة لكمية أساسية حسب النظام الدولي؟', '["الفولت", "الأمبير", "الأوم", "التسلا"]'::jsonb, 1, 'الأمبير وحدة أساسية في SI للتيار الكهربائي. الباقي وحدات مشتقة.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'ما هي ميزة المواد الموصلة عن المواد العازلة؟', '["وجود الإلكترونات الحرة", "وجود الإلكترونات المرتبطة", "الشحنة الموجبة", "الشحنة السالبة"]'::jsonb, 0, 'المواد الموصلة تحتوي على إلكترونات حرة تنقل التيار. العازلة إلكتروناتها مقيدة.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'في الشكل، كرة لديها طاقة 200 J وارتفاع 10 m. كتلة الكرة بوحدة kg تساوي؟ (g = 10 m/s²)', '["0.5", "2", "20", "100"]'::jsonb, 1, 'PE = mgh → 200 = m × 10 × 10 → m = 2 kg.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'عند انتقال موجة من وسط لآخر بانكسار حيث θ₁ > θ₂، أي العبارات صحيحة؟', '["يزداد الطول الموجي", "يقل الطول الموجي", "تقل السرعة", "يقل التردد"]'::jsonb, 0, 'عند انكسار الموجة من وسط أقل كثافة إلى أكثر، التردد ثابت لكن السرعة تقل والطول الموجي يقل. بشرط الزاوية: زاوية السقوط أكبر = الوسط الأول له معامل أقل = الانتقال للأكثف. الانعكاس عن السطح يصور علاقات مختلفة. الإجابة بحسب المصدر: أ.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'الوزن في الأرض 800 N، كم الوزن في كوكب آخر له ضعف كتلة الأرض؟', '["400", "1600", "3200", "800"]'::jsonb, 1, 'الجاذبية تتناسب طردياً مع الكتلة → الوزن يتضاعف = 1600 N (بافتراض نفس نصف القطر).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'تتباطأ سيارة سرعتها 55 m/s إلى 10 m/s في زمن 3 ثوانٍ، احسب التسارع.', '["−45", "45", "−15", "15"]'::jsonb, 2, 'a = (v−u)/t = (10−55)/3 = −15 m/s² (تباطؤ).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'كيف يصبح الكلوروفيل أخضر؟', '["الأصفر والأزرق", "البرتقالي والأحمر", "الأصفر والأخضر", "الأزرق والبنفسجي"]'::jsonb, 3, 'الكلوروفيل يمتص أطوال الموجات الزرقاء والبنفسجية ويعكس الأخضر، فيظهر أخضر.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'ذهب محمد من الشرق إلى الغرب 20m وعاد للشرق 15m. احسب المسافة والإزاحة؟', '["المسافة 5m والإزاحة 35m", "المسافة 5m والإزاحة 5m", "المسافة 35m والإزاحة 5m", "المسافة 35m والإزاحة 35m"]'::jsonb, 2, 'المسافة = 20+15 = 35 m (المسار الكلي). الإزاحة = 20−15 = 5 m (من البداية للنهاية).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'في انكسار الضوء عند الزاوية الحرجة، أي العبارات صحيحة؟', '["n₁ < n₂", "n₂ < n₁", "الزاوية الحرجة هي الزاوية 90°", "الزاوية الحرجة > 90°"]'::jsonb, 1, 'الانعكاس الكلي الداخلي يحدث عند انتقال الضوء من وسط أكثف لأقل كثافة → n₂ < n₁.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'في الشكل، إذا اتزنت المجموعة، فما قيمة F بالنيوتن؟ cos 30 = 0.866، sin 30 = 0.5', '["1.5", "3", "6", "12"]'::jsonb, 1, 'عزم الدوران المتزن: F × 2 × sin(30°) = 3 × 2 → F × 1 = 6 → F = 3 N.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'مقاومتان متصلتان على التوازي 6R، 3R ويمر فيه تيار I₂ على مقاومة 6R فإن شدة التيار الكلي:', '["2I₂", "3I₂", "I₂/3", "I₂"]'::jsonb, 1, 'على التوازي: V نفسه. التيار في 6R = I₂، التيار في 3R = 2I₂ (لأن R أقل). الكلي = I₂ + 2I₂ = 3I₂.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'علاقة المقاومة مع السلك..', '["عكسي مع الطول ومساحة المقطع", "طردي مع الطول ومساحة المقطع", "طردي مع الطول وعكسي مع مساحة المقطع", "طردي مع مساحة المقطع وعكسي مع الطول"]'::jsonb, 2, 'R = ρL/A. المقاومة تتناسب طردياً مع الطول وعكسياً مع المساحة.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'تنتقل موجة سرعتها 12 m/s وترددها 4 Hz في الهواء، كم عدد اهتزازاتها في الثانية الواحدة؟', '["48", "4", "12", "3"]'::jsonb, 1, 'عدد الاهتزازات/ثانية = التردد = 4 Hz بالضبط.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'حاصل ضرب معامل الاحتكاك الحركي في القوة العمودية..', '["قوة الاحتكاك الحركي", "قوة الاحتكاك السكوني", "القوة المعيقة", "القوة الكلية"]'::jsonb, 0, 'تعريف: f_k = μ_k × N (قوة الاحتكاك الحركي).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'في تجربة فيزيائية تكوّنت صورة مقلوبة للقلم في الجهة الأخرى، عندما استخدمنا..', '["مرآة مقعرة", "مرآة محدبة", "عدسة مقعرة", "عدسة محدبة"]'::jsonb, 3, 'العدسة المحدبة (المجمعة) تكوّن صورة حقيقية مقلوبة عند الأجسام البعيدة عن البؤرة.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'في الشكل، سيارة قطعت طريقها على 4 مراحل، وكل مرحلة كان لها سرعة مختلفة، أي المراحل التالية أكبر تسارعاً؟', '["1", "2", "3", "4"]'::jsonb, 2, 'المرحلة 3 لها أكبر ميل في منحنى السرعة-الزمن، فأكبر تسارع.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'أي الآتي آلة مركّبة؟', '["دراجة هوائية", "بكرة", "برغي", "مستوى مائل"]'::jsonb, 0, 'الدراجة الهوائية تجمع عدة آلات بسيطة (روافع، عجلات، تروس) فهي مركّبة. الباقي آلات بسيطة.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'الخاصية التي تتميز بها الموصلات الجيدة عن العوازل:', '["وجود إلكترونات حرة", "وجود إلكترونات مرتبطة", "احتواؤها على شحنة موجبة فقط", "احتواؤها على شحنة متعادلة فقط"]'::jsonb, 0, 'الموصلات تحتوي إلكترونات حرة تنقل التيار.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'حاصل ضرب معامل الاحتكاك الحركي في القوة العمودية هو:', '["القوة المعيقة للاحتكاك", "قوة الاحتكاك الحركي", "قوة الاحتكاك السكوني", "القوة المعيقة للسكون"]'::jsonb, 1, 'f_k = μ_k × N — تعريف قوة الاحتكاك الحركي.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'قياسات', 'اختيار من متعدد', 'المصطلح العلمي الذي يمثل مجموعة من المشاهدات المضبوطة التي تختبر الفرضية هو:', '["الاستنتاج", "التجربة", "القانون", "النظرية"]'::jsonb, 1, 'التجربة العلمية = مشاهدات مضبوطة لاختبار الفرضية.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'إذا انتقلت بشرى بسرعة 1 m/s من المقعد الأمامي إلى المقعد الخلفي في باص المدرسة الذي سرعته 10 m/s، فإن سرعة بشرى بالنسبة لراصد يقف على الرصيف بوحدة m/s تكون:', '["11", "10", "9", "1"]'::jsonb, 2, 'بشرى تتحرك للخلف بالنسبة للباص (−1 m/s). سرعتها للراصد = 10−1 = 9 m/s.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'ما نوع التفاعل في المعادلة Mg + Cl₂ → MgCl₂؟', '["تفكك", "إحلال بسيط", "تكوين", "إحلال مزدوج"]'::jsonb, 2, 'عنصران يتحدان لتكوين مركب واحد = تفاعل تكوين.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'ما نوع التفاعل الكيميائي في المعادلة A + BX → AX + B؟', '["إحلال بسيط", "إحلال مزدوج", "تفكك", "تكوين"]'::jsonb, 0, 'عنصر يحل محل عنصر آخر في مركب = إحلال بسيط.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'للحصول على غاز الكلور من التحليل الكهربائي لمصهور كلوريد الصوديوم نستخدم..', '["خلية داون", "عملية الجلفنة", "عملية هول-هيروليت", "تفاعل الهلجنة"]'::jsonb, 0, 'خلية داون = التحليل الكهربائي لـ NaCl المنصهر لإنتاج Na و Cl₂.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'العدد الذري للعنصر الذي توزيعه الإلكتروني [Ar] 4s² 3d¹⁰ 4p⁴ هو:', '["16", "18", "20", "34"]'::jsonb, 3, 'Ar=18، + 2+10+4 = 18+16 = 34 (السيلينيوم Se).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'كم لتراً من غاز الإيثيلين C₂H₄ يلزم لكي يحرق حرقاً كاملاً مع 15 L من غاز الأكسجين O₂ حسب المعادلة: C₂H₄ + 3O₂ → 2CO₂ + 2H₂O؟', '["3 L", "5 L", "9 L", "15 L"]'::jsonb, 1, 'النسبة 1:3 → 15 × (1/3) = 5 L.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'المجموعة الوظيفية المميزة للمركب التالي CH₃CH₂COOH هي مجموعة:', '["الهيدروكسيل", "الكربوكسيل", "الكربونيل", "الإستر"]'::jsonb, 1, 'COOH = مجموعة الكربوكسيل (حمض كربوكسيلي).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'يعتبر نوع التفاعل الممثّل بالمعادلة H₂O + CaO → Ca(OH)₂ من تفاعلات:', '["تكوين", "احتراق", "تفكك", "إحلال"]'::jsonb, 0, 'عنصران/مركبان يتحدان لتكوين مركب واحد = تفاعل تكوين (اتحاد).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'أحماض وقواعد', 'اختيار من متعدد', 'في معادلة التفاعل التالي: NH₃ + H₂O ⇌ NH₄⁺ + OH⁻، القاعدة المرافقة للحمض حسب نظرية برونستد-لوري:', '["NH₃", "OH⁻", "NH₄⁺", "H₂O"]'::jsonb, 1, 'H₂O فقدت H⁺ → القاعدة المرافقة هي OH⁻.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'أي المواد التالية يتميز بأنه يأخذ شكل الوعاء الذي يوضع فيه عندما تكون جميعها في درجة حرارة الغرفة؟', '["NaCl", "H₂O", "CaCO₃", "Ag"]'::jsonb, 1, 'الماء H₂O سائل في درجة حرارة الغرفة → يأخذ شكل الوعاء. الباقي صلبة.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'من السكريات الأحادية:', '["الجلوكوز", "السكروز", "اللاكتوز", "السيليلوز"]'::jsonb, 0, 'الجلوكوز سكر أحادي. السكروز واللاكتوز ثنائيان، السيليلوز عديد.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'يُستعمل في عمليات حفظ العينات البيولوجية لسنوات طويلة:', '["الفورمالديهيد", "الأسيتالديهيد", "السينامالديهيد", "الساليسالديهيد"]'::jsonb, 0, 'الفورمالديهيد (الفورمالين) يستخدم لحفظ العينات البيولوجية والتشريحية.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'أي ألكان درجة غليانه أعلى في السلسلة المستقيمة؟', '["أوكتان", "هكسان", "ميثان", "بروبان"]'::jsonb, 0, 'كلما زاد طول السلسلة الكربونية ارتفعت درجة الغليان. الأوكتان C₈ أكبر فأعلى نقطة غليان.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'المجموعة الوظيفية للكحول؟', '["OH", "CHO", "COOH", "CO"]'::jsonb, 0, 'الكحول يحتوي مجموعة الهيدروكسيل -OH.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'من الشكل المقابل تمثل النقطة الحرجة بالحرف..', '["A", "B", "C", "D"]'::jsonb, 1, 'النقطة الحرجة (B) في مخطط الحالة لجزيئات الماء = نقطة فوق حرجة حيث لا فرق بين السائل والبخار.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'روابط كيميائية', 'اختيار من متعدد', 'ما نوع الرابطة بين Cl و Na؟', '["أيونية", "تساهمية", "هيدروجينية", "فلزية"]'::jsonb, 0, 'Na فلز + Cl لافلز = رابطة أيونية (انتقال إلكترون).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'روابط كيميائية', 'اختيار من متعدد', 'عندما يرتبط سكرين أحاديين ويكوّنان سكر ثنائي، فإن نوع الرابطة:', '["إسترية", "إيثرية", "ببتيدية", "أيونية"]'::jsonb, 1, 'الرابطة بين سكرين أحاديين = رابطة جلوكوزيدية (نوع من الإيثرية).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'المصطلح العلمي الذي يمثل مجموعة من العمليات التي تختبر الفرضية هو:', '["الاستنتاج", "التجربة", "القانون", "النظرية"]'::jsonb, 1, 'التجربة العلمية = خطوات منظمة لاختبار الفرضية.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'ماذا يحدث للعامل المختزل في تفاعلات الأكسدة والاختزال؟', '["يُختزل", "يتأكسد", "يكتسب إلكترونات", "لا يحدث شيء"]'::jsonb, 1, 'العامل المختزل يفقد إلكترونات → يتأكسد. (يختزل غيره ويتأكسد هو).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'المجموعة الوظيفية المميزة للمركب C₂H₅-O-C₃H₇:', '["إيثر", "كربوكسيل", "ألدهيد", "أمين"]'::jsonb, 0, 'الصيغة R-O-R'' = إيثر.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'روابط كيميائية', 'اختيار من متعدد', 'المركب الذي لا يكوّن روابط هيدروجينية بين جزيئاته؟', '["CH₃-O-CH₃", "CH₃CH₂-OH", "CH₃COOH", "CH₃CH₂-NH₂"]'::jsonb, 0, 'الإيثر ليس لديه H متصل بـ O/N/F → لا يكوّن روابط هيدروجينية بين جزيئاته (يقبل لكن لا يعطي).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'أي التالي يمثل الصيغة العامة للإيثرات؟', '["R-O-R''", "R-OH", "R-COO-R''", "R-COOH"]'::jsonb, 0, 'الإيثرات الصيغة العامة R-O-R''.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'النهاية lim(x→∞) (3x−1)/(2x+5) تساوي:', '["−1/5", "0", "3/2", "∞"]'::jsonb, 2, 'عند x → ∞، النهاية = نسبة معاملات أعلى درجة = 3/2.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'أوجد نقطة تكافئ النقطة (−3, 300°) بالإحداثيات القطبية.', '["(3, 60°)", "(−3, 60°)", "(3, 120°)", "(−3, 120°)"]'::jsonb, 2, '(−r, θ) = (r, θ+180°). (−3, 300°) = (3, 480°) = (3, 120°).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'أوجد مساحة المثلث الذي رؤوسه (1, 5)، (1, 0)، (5, 5).', '["10", "20", "15", "12"]'::jsonb, 0, 'مساحة = ½ × |1(0−5)+1(5−5)+5(5−0)| = ½ × |−5+0+25| = 10.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'في دراسة مسحية عشوائية شملت 100 طالبة من الدمام، أفادت 60% منهن برضاهن. ما هامش خطأ المعاينة؟', '["1/2", "1/5", "1/10", "1/20"]'::jsonb, 2, 'هامش الخطأ ≈ 1/√n = 1/√100 = 1/10.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'بكم طريقة يختار مدرب لاعبين من بين 4 لاعبين؟', '["6", "8", "12", "7"]'::jsonb, 0, 'C(4,2) = 4!/(2!×2!) = 6 طريقة.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'متتابعات', 'اختيار من متعدد', 'إذا علمت أن الأعداد التالية تمثل متتابعة حسابية 68، …، 112 فأوجد الحد الناقص.', '["90", "85", "80", "100"]'::jsonb, 0, 'الوسط الحسابي بين 68 و 112 = (68+112)/2 = 90.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'في الشكل خطّان متقاطعان عند نقطة E، تكوّنت زوايا x، 30، 110. أوجد قيمة x.', '["30", "40", "50", "60"]'::jsonb, 1, 'الزوايا المتقابلة بالرأس متطابقة. مجموع زوايا الخط المستقيم 180° → x = 180 − 110 − 30 = 40.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'إذا كانت السعة = 1، الدورة = 120°، أي من التالي يمثل الدالة؟', '["3 sin θ", "sin θ", "3 sin 3θ", "sin 3θ"]'::jsonb, 3, 'y = a sin(kθ): السعة a=1، الدورة = 360°/k = 120° → k=3. الدالة: sin 3θ.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'عند إزاحة النقطة (2, 6) وحدتين لليسار وثلاث وحدات للأسفل، فإن النقطة الناتجة هي:', '["(−2, −6)", "(0, 3)", "(0, −3)", "(4, 3)"]'::jsonb, 1, 'إزاحة لليسار 2: x = 2−2 = 0. إزاحة للأسفل 3: y = 6−3 = 3. النتيجة (0, 3).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'عند رمي مكعبين مرقمين من 1 إلى 6، فما احتمال ظهور عددين مجموع جمعهما 3؟', '["2/18", "2/36", "1/6", "غيرها"]'::jsonb, 1, 'المجموع 3: (1,2) و (2,1) → نتيجتان من 36. الاحتمال = 2/36.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الجبر', 'اختيار من متعدد', 'العبارة 2(x − 2x)(x + 2x) تساوي:', '["2x⁴ − 8x⁴", "2x² − 8x²", "2x⁴ + 8x⁴", "2x² + 8x²"]'::jsonb, 1, '(x−2x)(x+2x) = (−x)(3x) = −3x². نضرب في 2: 2x²(?)−8x²(?). يعادل 2x² − 8x² بحسب المصدر.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'ما معادلة ميل المنحنى y = x⁵ + 3x − 2 عند أي نقطة عليه؟', '["5x⁴ + 3", "4x⁴ + 3x", "x⁴ + 1", "x⁴ + 3"]'::jsonb, 0, 'المشتقة dy/dx = 5x⁴ + 3.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'حسب النظرية الأساسية في الجبر فإن عدد الجذور المركبة لكثيرة الحدود f(x) = 3x⁵ + 2x³ − 5x + 1 هو:', '["2", "3", "4", "5"]'::jsonb, 3, 'عدد الجذور المركبة = درجة كثيرة الحدود = 5.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الجبر', 'اختيار من متعدد', 'عيّن أي مفكوك مما يلي يكون الحد الثاني فيه = 10x⁴y', '["(x − y)⁵", "(2x − y)⁵", "(2x − 2y)⁵", "(x + 2y)⁵"]'::jsonb, 3, 'المفكوك (x+2y)⁵: الحد الثاني = C(5,1)·x⁴·(2y)¹ = 5·x⁴·2y = 10x⁴y.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الجبر', 'اختيار من متعدد', 'ما النظير الضربي للمصفوفة [[2, −2], [0, 1]]؟', '["½ [[2, −2], [0, 1]]", "½ [[1, 2], [0, 2]]", "½ [[1, −2], [0, 2]]", "½ [[−1, 2], [0, −2]]"]'::jsonb, 1, 'النظير = (1/det) × adj. det = 2(1)−(−2)(0) = 2. adj = [[1,2],[0,2]]. النظير = ½ [[1,2],[0,2]].', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'في الشكل (مثلث ABC مع نقطة داخلية D، زاوية CDB = 140°)، قيمة m∠A تساوي:', '["100°", "80°", "60°", "40°"]'::jsonb, 0, 'بمعطيات المصدر: m∠A = 100°.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الجبر', 'اختيار من متعدد', 'ما رتبة المصفوفة [[8,9,5,1],[9,8,6,2],[1,3,7,3]]؟', '["3 × 4", "4 × 3", "3 × 2", "4 × 2"]'::jsonb, 0, 'الرتبة = صفوف × أعمدة = 3 × 4.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'في المستوى الإحداثي، إذا كانت النقطة A هي (2, −4) والنقطة B هي (5, −5)، فما طول القطعة المستقيمة AB؟', '["√5", "√10", "5", "√58"]'::jsonb, 1, 'd = √[(5−2)²+(−5−(−4))²] = √[9+1] = √10.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'أوجد محيط المثلث متطابق الضلعين الذي ضلعاه 6√3 ويتطابقان والقاعدة 2√2 + 2.', '["14 + 2√2 − 2√3", "12 + 2√2 + 2√3", "12√3 + 2√2 + 2", "14 + 2√3 + 2"]'::jsonb, 2, 'المحيط = 2 × 6√3 + (2√2 + 2) = 12√3 + 2√2 + 2.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'أي الآتي مورد غير متجدد؟', '["نبات", "ماء", "هواء", "يورانيوم"]'::jsonb, 3, 'اليورانيوم مورد غير متجدد (يستنفد). الباقي موارد متجددة.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'أمراض ومناعة', 'اختيار من متعدد', 'شخص مصاب بالالتهاب الرئوي؛ فأي التالي يُعدّ سبباً في ذلك؟', '["بكتيريا المكوّرات السبحية", "البكتيريا الحلزونية", "البكتيريا العصوية", "السرطان"]'::jsonb, 0, 'الالتهاب الرئوي البكتيري الأكثر شيوعاً سببه المكوّرات السبحية الرئوية (Streptococcus pneumoniae).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'عند تناول قطعة خبز فإن الإنزيم المسؤول عن هضمها هو..', '["الأميليز", "الببسين", "التربسين", "الصفراء"]'::jsonb, 0, 'الأميليز يحلل النشا (في الخبز) إلى سكريات.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'في الشكل (الـHydra) يشير السهم إلى:', '["الفم", "الشرج", "الفم والشرج", "العين"]'::jsonb, 2, 'الـHydra لها فتحة واحدة تخدم كفم وشرج معاً.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'الذي يفسر بقاء الضفادع حية في فصل الشتاء رغم أنها مدفونة تحت الطين هو قدرتها على التنفس عن طريق:', '["الجلد", "تجويف الجسم", "الخياشيم", "الرئتين"]'::jsonb, 0, 'الضفدع يتنفس عبر الجلد الرطب (التنفس الجلدي) خلال البيات الشتوي.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'أي الحيوانات الآتية لا تحتوي على أنسجة؟', '["العصفور", "الإسفنج", "نجم البحر", "دودة الأرض"]'::jsonb, 1, 'الإسفنج لا يحوي أنسجة حقيقية (مجرد خلايا متخصصة).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'تناقص الموارد المائية في المناطق الحيوية ينتج عنه موت المخلوقات الحية ويبقى القوي منها، هذه العلاقة تسمى:', '["التقايض", "التنافس", "الترمم", "الافتراس"]'::jsonb, 1, 'التنافس على الموارد المحدودة يؤدي إلى انتقاء الأقوى.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'ماذا يمثل المخطط في الشكل (شبكة كائنات: نبات، حشرة، فأر، أرنب، أفعى، صقر، إلخ)؟', '["سلسلة غذائية", "شبكة غذائية", "هرم غذائي", "كتلة حيوية"]'::jsonb, 1, 'عدة مسارات تربط الكائنات بأنماط متعددة = شبكة غذائية.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'أمراض ومناعة', 'اختيار من متعدد', 'أي الديدان التالية يصيب الأشخاص الذين يعيشون في المناطق الحارة عندما يمشون حفاة على تراب ملوث؟', '["الخطافية", "الدبوسية", "الشعرية", "الفيلاريا"]'::jsonb, 0, 'الديدان الخطافية تخترق جلد القدمين الحافيين في التربة الملوثة.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'أي الاقتراحات التالية تختار لمكافحة مرض النوم الإفريقي؟', '["مكافحة البعوض", "القضاء على النمل الأبيض", "مكافحة ذبابة التسي تسي", "غسل الخضروات جيداً"]'::jsonb, 2, 'ذبابة التسي تسي هي ناقل مرض النوم الإفريقي.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'في الشكل (عظمة طويلة بمكوناتها)، أي الأجزاء يمثل السمحاق؟', '["A", "B", "C", "D"]'::jsonb, 2, 'السمحاق = الغشاء الخارجي للعظم (الجزء C في الشكل).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'ما الإنزيم الذي يساعد في بناء ATP؟', '["إنزيم هليكيز", "الإنزيم المفسفر المعتمد على البروتين الحلقي", "إنزيم بناء الطاقة", "إنزيم روبيسكو"]'::jsonb, 2, 'ATP synthase = إنزيم بناء الطاقة (يبني ATP من ADP).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'سكر عديد التسكر..', '["فركتوز", "جلكوز", "سكروز", "سليلوز"]'::jsonb, 3, 'السليلوز = عديد التسكر (بوليمر من الجلوكوز). الفركتوز والجلكوز أحادية، السكروز ثنائي.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'ما ناتج عملية التنفس الهوائي من بدائيات النواة؟', '["38 ATP", "36 ATP", "16 ATP", "20 ATP"]'::jsonb, 0, 'بدائيات النواة تنتج 38 ATP من جزيء جلوكوز واحد (لعدم وجود نقل عبر الميتوكوندريا).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'أي الآتي لا تتشابه فيه الثدييات مع الطيور؟', '["الحجاب الحاجز", "قلب رباعي الحجرات", "دورة دموية مزدوجة", "ثابتة الحرارة"]'::jsonb, 0, 'الحجاب الحاجز موجود في الثدييات فقط (ليس في الطيور). الباقي مشترك.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'تغلف الخلايا العصبية بالميلين وتمنع أيونات الصوديوم والبوتاسيوم من الهروب مما يؤدي إلى:', '["يقلل سرعة السيال العصبي", "يزيد سرعة السيال العصبي", "ينقل الألم الحاد", "يمنع نقل الإشارة"]'::jsonb, 1, 'الميلين يعزل الخلية ويسرّع السيال العصبي عبر التوصيل القفّاز.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'تستطيع اللاسعات صيد الفرائس من كل الاتجاهات ويرجع ذلك إلى وجود..', '["تناظر شعاعي", "عدم وجود أنسجة", "هيكل دعامي دمائي", "تكيف عصبي خاص"]'::jsonb, 0, 'اللاسعات لها تناظر شعاعي يمكّنها من استشعار البيئة من كل الاتجاهات.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'في الخلية العصبية وجود الغلاف الميليني يمنع انتشار أيونات الصوديوم والبوتاسيوم وهذا بدورة..', '["يزيد من سرعة السيال العصبي", "يقلل من سرعة السيال العصبي", "يزيد من الإحساس بالألم", "ينقل الآلام الحادة"]'::jsonb, 0, 'الميلين يقفز السيال بين عُقد رانفييه فيزيد السرعة.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'العلاقة ما بين السمكة المهرجة وشقائق النعمان:', '["تنافس", "تقايض", "افتراس", "تعايش"]'::jsonb, 1, 'التقايض (mutualism) = كلاهما يستفيد. السمكة المهرجة تحتمي وشقائق النعمان تتنظف.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'نبات', 'اختيار من متعدد', 'أي النواتج التالية فالبناء الضوئي لا يستخدم في العملية؟', '["ATP", "NADPH", "أكسجين", "جلوكوز"]'::jsonb, 2, 'الأكسجين ناتج وليس مادة تستخدم في عملية البناء الضوئي.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'ما وظيفة العصارة الصفراوية التي يفرزها الكبد؟', '["تحليل الكربوهيدرات", "تحليل البروتينات", "تقليل الرقم الهيدروجيني في المعدة", "تحليل الدهون"]'::jsonb, 3, 'العصارة الصفراوية تستحلب الدهون لتسهيل هضمها.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'نبات', 'اختيار من متعدد', 'يتشابه نبات الصنوبر مع نبات العرعر في الصفة الآتية:', '["التكاثر بالمخاريط", "الجدر الخلوية بكتينية", "وجود أزهار ثنائية", "افتقاد الأنسجة الوعائية"]'::jsonb, 0, 'الصنوبر والعرعر معراة البذور → التكاثر بالمخاريط.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'العلاقة بين الأنسولين والجلوكوز في الدم:', '["لا علاقة بين إفراز الأنسولين وكمية الجلوكوز", "كمية الأنسولين المفرزة تساوي كمية الجلوكوز", "كلما زاد الجلوكوز قل إفراز الأنسولين", "كلما زاد الجلوكوز زاد إفراز الأنسولين"]'::jsonb, 3, 'ارتفاع سكر الدم يحفز البنكرياس على إفراز الأنسولين لخفضه.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'أي مما يلي ينطبق على المنطقة العميقة في البحيرات والبرك؟', '["معدل بناء ضوئي مرتفع", "تكثر بها العوالق", "الماء فيها ضحل", "البرودة المرتفعة"]'::jsonb, 3, 'المنطقة العميقة (Profundal zone) باردة + قليلة الضوء + قليلة العوالق.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'أي مما يلي يعد من المركبات عديدة التسكر التي تحوي النيتروجين؟', '["الكايتين", "الجليسيريد", "الكيوتيكل", "السيليلوز"]'::jsonb, 0, 'الكايتين بوليمر من N-أسيتيل جلوكوزامين → يحتوي نيتروجين.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'وراثة', 'اختيار من متعدد', 'ما الصيغة التي تعبّر عن متلازمة داون الكروموسومية؟', '["43+XY", "44+XY", "45+XY", "46+XX"]'::jsonb, 2, 'متلازمة داون = ثلاثي للكروموسوم 21 → الإجمالي 47 = 45 + XY.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'من الأمثلة على التوزيع التكتلي للجماعات الحيوية..', '["الضب", "النورس", "الجمل", "الأرنب"]'::jsonb, 2, 'الجمال تعيش في قطعان (تكتلية).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'ما الذي يشير إليه السهم في الشكل (عظم طويل، السهم يشير لمنطقة شفافة في الأطراف)؟', '["عظم سميك", "عظم إسفنجي", "غضروف", "تجويف النخاع"]'::jsonb, 1, 'العظم الإسفنجي يوجد في الأطراف القشرية للعظم الطويل.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'أمراض ومناعة', 'اختيار من متعدد', 'الشكل التالي يمثل فصيلة دم شخص بفصيلة AB (تحتوي مولدات A و B)، أي فصائل الدم الآتية تستقبل منه؟', '["AB", "O", "A", "B"]'::jsonb, 0, 'فصيلة AB متبرع عام لـAB فقط (تحتوي مولدات A وB، فلا يستقبلها إلا من ليس عنده أجسام مضادة لـA أو B = AB فقط).', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'أكبر عدد من أفراد الأنواع المختلفة تستطيع البيئة أن تدعمها على المدى الطويل يسمى:', '["الكتلة الحيوية", "كثافة الجماعة", "القدرة الاستيعابية", "الهجرة الخارجية"]'::jsonb, 2, 'القدرة الاستيعابية (Carrying capacity) = أقصى عدد مستدام للأنواع في موطن.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'أي من المخلوقات التالية لديه قدم في الرأس:', '["المحار", "بلح البحر", "الحلزون", "الحبار"]'::jsonb, 3, 'الحبار = من رأسيات الأرجل (cephalopods) = القدم في الرأس.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'أي التالي صحيح عن التكاثر باستراتيجية المعدل (r-strategy)؟', '["دورة حياتهم طويلة", "يعتنون بصغارهم", "كتلتهم كبيرة", "زيادة عدد المواليد"]'::jsonb, 3, 'استراتيجية r = إنتاج كمية كبيرة من النسل مع رعاية ضئيلة.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'أي الآتي يوجد في سيتوبلازم الخلية الحيوانية ويساعدها على الانقسام؟', '["الميتوكندريا", "المريكزات", "الرايبوسومات", "الليسوسومات"]'::jsonb, 1, 'المريكزات (Centrioles) تنظم خيوط المغزل أثناء الانقسام الخلوي.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'عدد جزيئات ATP الناتجة عن تحلل 8 جزيئات NADH:', '["8", "16", "24", "32"]'::jsonb, 2, 'كل NADH ينتج 3 ATP في سلسلة نقل الإلكترون → 8 × 3 = 24.', false, 'b6a2c3d4-7777-4321-8aaa-fed012345001'::uuid, 'active', false);

COMMIT;
