-- 88: Day 5 evening (yelo) — batch 4: chemistry + biology (22 questions)
-- Covers PDF pages 25-32. Quality filter: skipped figure-required + ambiguous-answer questions.

BEGIN;

INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'عناصر المجموعة الأولى (الفلزات القلوية) مرتّبة كالتالي: Li, Na, K, Rb, Cs. أيّها له أكبر نصف قطر ذرّي؟', '["Li", "Na", "K", "Cs"]'::jsonb, 3, 'نصف القطر الذرّي يزداد نزولاً في المجموعة لأن عدد مستويات الطاقة يزداد. Cs في أسفل المجموعة → أكبر نصف قطر، وإلكترون التكافؤ الأبعد عن النواة.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'ممّ تتكوّن النيوكليوتيدة (الوحدة البنائية للحمض النووي DNA/RNA)؟', '["خمس ذرّات كربون وحمض وثلاث مجموعات فوسفات", "ست ذرّات كربون وحمض وثلاث مجموعات فوسفات", "سكر خماسي + قاعدة نيتروجينية + مجموعة فوسفات", "ست ذرّات كربون وقاعدة نيتروجينية وثلاث مجموعات فوسفات"]'::jsonb, 2, 'النيوكليوتيدة تتكوّن من ثلاث وحدات: (1) سكر خماسي (Ribose أو Deoxyribose)، (2) قاعدة نيتروجينية (A,T,G,C,U)، (3) مجموعة فوسفات واحدة. تتّصل عدة نيوكليوتيدات لتكوين شريط DNA/RNA.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'أيّ المعادلات التالية موزونة وتمثّل تفاعل نيتروجين + هيدروجين → أمونيا؟', '["N₂ + H₂ → NH₃", "N₂ + 3H₂ → 2NH₃", "N₂ + 2H₂ → H₂O", "O₂ + 2H₂ → H₂O"]'::jsonb, 1, 'معادلة هابر الموزونة: N₂ + 3H₂ → 2NH₃. الذرّات على الطرفين: 2 N (يسار) = 2 N (يمين)، 6 H (يسار) = 6 H (يمين). الخيار د لتفاعل تكوين الماء وليس الأمونيا.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'فصل مخاليط', 'اختيار من متعدد', 'أيّ التالي يمثّل خاصية تشتّت الضوء عند مروره في مخلوط غروي أو معلّق؟', '["المخلوط المتجانس", "تأثير تيندال", "الذوبانية", "الحركة البراونية"]'::jsonb, 1, 'تأثير تيندال (Tyndall effect): تشتّت الضوء عند مروره في وسط يحتوي على دقائق متوسطة الحجم (غروي/معلّق). لا يحدث في المحاليل الحقيقية. مثاله: شعاع الشمس في الغرفة المغبّرة.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'روابط كيميائية', 'اختيار من متعدد', 'قوى تجاذب ضعيفة تنشأ بين الجزيئات غير القطبية تسمّى..', '["رابطة هيدروجينية", "قوى التشتّت (لندن)", "قوى ثنائية القطب", "قوى أيون-ثنائي قطب"]'::jsonb, 1, 'قوى لندن للتشتّت (London Dispersion Forces) هي قوى ضعيفة جداً ناتجة عن ثنائيات قطب مؤقّتة في الجزيئات غير القطبية. هي الأضعف بين القوى بين الجزيئات لكنها الوحيدة الموجودة في الجزيئات غير القطبية.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'أيّ الذرّات التالية لها أقل طاقة تأيّن؟', '["Li", "Na", "Rb", "Cs"]'::jsonb, 3, 'طاقة التأيّن تقلّ نزولاً في المجموعة (إلكترون التكافؤ يبتعد عن النواة فيسهل انتزاعه). Cs في أسفل مجموعة الفلزات القلوية → أقل طاقة تأيّن (~3.89 eV).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'أيّ العناصر التالية أقل نشاطاً كيميائياً؟', '["Na", "O", "Be", "Ar"]'::jsonb, 3, 'Ar من الغازات النبيلة (المجموعة 18). مستوى تكافؤه ممتلئ (8 إلكترونات)، فلا حاجة لتفاعل أو فقد/كسب إلكترونات. الغازات النبيلة الأقل نشاطاً كيميائياً على الإطلاق.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'عنصر عدده الذرّي 25، يقع في أيّ فئة من فئات الجدول الدوري؟', '["s", "p", "d", "f"]'::jsonb, 2, 'العنصر بـ Z=25 هو المنغنيز Mn. توزيعه: [Ar]3d⁵4s². آخر إلكترون دخل المستوى d، إذاً ينتمي لفئة العناصر الانتقالية (d-block).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'ما التوزيع الإلكتروني للعنصر ₅₆Ba علماً بأن آخر غاز نبيل قبله ₅₄Xe؟', '["[Xe] 6s²", "[Xe] 6s⁰ 5d¹", "[Xe] 6s¹ 5d¹", "[Xe] 5s¹ 4d¹"]'::jsonb, 0, 'Ba في المجموعة 2 (فلز قلوي ترابي) والدور 6. يأتي بعد Xe بإلكترونين في المستوى 6s. التوزيع: [Xe] 6s².', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'جهاز معزول حرارياً يستخدم لقياس كمية الحرارة الممتصة أو المنطلقة في العمليات الكيميائية والفيزيائية:', '["الجول", "السعر", "السعر الغذائي", "المسعر"]'::jsonb, 3, 'المسعر (Calorimeter) جهاز معزول حرارياً يقيس q = m·c·ΔT. الجول والسعر وحدات للطاقة، أما المسعر فهو أداة القياس.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'أحماض وقواعد', 'اختيار من متعدد', 'في تفاعل الاتزان: HCOOH(aq) + H₂O(l) ⇌ HCOO⁻(aq) + H₃O⁺(aq)، ما القاعدة المرافقة للحمض HCOOH؟', '["HCOOH", "H₂O", "HCOO⁻", "H₃O⁺"]'::jsonb, 2, 'وفق نظرية برونستد-لوري: القاعدة المرافقة للحمض = الحمض بعد فقد بروتون H⁺. الحمض HCOOH (فورميك) يفقد H⁺ فتنتج قاعدته المرافقة HCOO⁻ (الفورميات).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'الأشعة الضارّة التي تمتصها طبقة الأوزون في الجو..', '["الأشعة السينية", "فوق البنفسجية (UV)", "تحت الحمراء", "الضوء المرئي"]'::jsonb, 1, 'طبقة الأوزون O₃ في الستراتوسفير تمتص الأشعة فوق البنفسجية (UV-B و UV-C) فتحمي الأرض من تأثيراتها الضارّة (سرطان الجلد، تدمير DNA).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'أحماض وقواعد', 'اختيار من متعدد', 'إذا كان pOH في محلول يساوي 9، فما قيمة pH؟', '["9", "3", "14", "5"]'::jsonb, 3, 'العلاقة: pH + pOH = 14 (عند 25°C). إذاً pH = 14 − 9 = 5 → محلول حمضي.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'ما اسم الأيون ClO₃⁻؟', '["هيبوكلوريت ClO⁻", "كلوريت ClO₂⁻", "كلورات ClO₃⁻", "بيركلورات ClO₄⁻"]'::jsonb, 2, 'تسمية الأيونات المتعدّدة الذرّات للكلور: ClO⁻ هيبوكلوريت، ClO₂⁻ كلوريت، ClO₃⁻ كلورات، ClO₄⁻ بيركلورات. (قاعدة: زيادة عدد الأكسجين → اللاحقة -ات والبادئة بير-).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'أحماض وقواعد', 'اختيار من متعدد', 'ما الحمض المرافق للقاعدة NH₃؟', '["NH₄⁺", "NH₃", "NH₄", "NH₂⁻"]'::jsonb, 0, 'الحمض المرافق = القاعدة بعد كسب بروتون H⁺. القاعدة NH₃ تكسب H⁺ فيتكون NH₄⁺ (أيون الأمونيوم)، وهو الحمض المرافق.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'الحدّ الأقصى من الإلكترونات التي يستوعبها مستوى الطاقة الخامس (n=5):', '["8", "18", "2", "50"]'::jsonb, 3, 'العدد الأقصى للإلكترونات في مستوى الطاقة الـn يساوي 2n². عند n=5: 2(5)² = 2 × 25 = 50 إلكترون.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'أيّ التالي لا يؤثّر في سرعة الذوبان؟', '["الحرارة", "مساحة سطح المذاب", "التحريك", "الضغط الأسموزي"]'::jsonb, 3, 'العوامل المؤثّرة في سرعة الذوبان: الحرارة (ترفعها)، مساحة السطح (أكبر = أسرع)، التحريك (يسرّع)، والضغط (مهم للغازات فقط). الضغط الأسموزي ظاهرة منفصلة تتعلّق بالأغشية شبه المنفذة، لا بسرعة الذوبان.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'كُلِّفت مجموعة من الأطباء بإسعاف مصابي حادث سير دون معرفة فصائل دمهم. ما الفصيلة الأنسب لنقل الدم لهم جميعاً؟', '["A", "B", "AB", "O"]'::jsonb, 3, 'فصيلة O (سالبة بدقّة) هي المتبرّع العام (Universal Donor): خلاياها الحمراء لا تحمل مستضدّات A أو B، فلا يرفضها جسم أي مستقبل بغض النظر عن فصيلته.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'تعتبر التغذية في الإسفنج تغذية..', '["ذاتية", "ترشيحية", "ترميمية", "تطفّلية"]'::jsonb, 1, 'الإسفنج يتغذّى بالترشيح (Filter feeding): يضخّ الماء عبر مسامّه (Ostia)، وتلتقط الخلايا الياقية (Choanocytes) الجسيمات الغذائية الدقيقة من الماء، ثم يخرج الماء من الفتحة الكبرى (Osculum).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'شوكيات الجلد (نجم البحر، قنفذ البحر) تصرّف الماء الزائد وتنظّم الجهاز الوعائي المائي عبر:', '["لوامس قدمية", "الصفيحة الغربالية (المدريبورايت)", "حويصلات عضلية", "نظام أرسطو"]'::jsonb, 1, 'الصفيحة الغربالية (Madreporite) فتحة على سطح جسم شوكيات الجلد تسمح بدخول الماء وتنظّم ضغط الجهاز الوعائي المائي المسؤول عن الحركة والتنفّس والتغذية.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'كائن حيّ له هيكل داخلي بأشواك وتماثل شعاعي وجسم رخوي. ينتمي إلى:', '["أسماك عظمية", "أسماك غضروفية", "الإسفنج", "شوكيات الجلد"]'::jsonb, 3, 'الأوصاف الثلاثة (هيكل داخلي بأشواك + تماثل شعاعي + جسم رخوي) تنطبق على شوكيات الجلد (Echinoderms) مثل نجم البحر وقنفذ البحر وخيار البحر.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'أيّ التالي يمثّل تصنيف الضفدع في السلسلة الغذائية؟', '["مُنتج", "مستهلك أوّلي", "مستهلك ثانوي", "مستهلك من المستوى الثالث"]'::jsonb, 2, 'الضفدع يأكل الحشرات (مستهلك أوّلي يأكل النباتات). فالضفدع آكل لحوم يفترس آكلي الأعشاب → مستهلك ثانوي في السلسلة الغذائية.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);

COMMIT;
