-- ═══════════════════════════════════════════════════════════════
-- 101: تسريبات القدرات المحوسب – الأحد ١٦ أغسطس ٢٠٢٦
-- 85 سؤالاً: كمي 31 + لفظي 54 (استيعاب 22 في ٥ قطع)
-- آمن لإعادة التشغيل: guard على وجود أسئلة المجموعة
-- ═══════════════════════════════════════════════════════════════
BEGIN;

INSERT INTO leak_groups (id, title, leak_date, section, question_count, description, is_active, accent_color)
VALUES ('ad160816-2026-4c00-9d00-160820260001', 'تسريبات القدرات – الأحد ١٦ أغسطس ٢٠٢٦', '2026-08-16', 'mixed', 85, 'تسريبات اختبار القدرات المحوسب – الأحد ١٦ أغسطس ٢٠٢٦. القسم الكمي (٣١ سؤالاً) والقسم اللفظي (٥٤ سؤالاً) مع شروح مبسطة لكل سؤال.', true, '#7C3AED')
ON CONFLICT (id) DO NOTHING;

DO $mig$
BEGIN
IF EXISTS (SELECT 1 FROM questions WHERE leak_group_id = 'ad160816-2026-4c00-9d00-160820260001') THEN
  RAISE NOTICE 'أسئلة المجموعة موجودة مسبقاً — تخطي الإدراج';
ELSE
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'التحليل', 'اختيار من متعدد', 'أوجد الحد التالي في المتتابعة: ٣ ، ٥ ، ٩ ، ١٧ ، ٣٣ ، ......', '["٦٠", "٦٢", "٦٣", "٦٥"]'::jsonb, 3, 'الفروق بين الحدود المتتالية: ٢ ، ٤ ، ٨ ، ١٦ — كل فرق ضِعف الذي قبله. الفرق التالي ٣٢، فالحد المطلوب = ٣٣ + ٣٢ = ٦٥.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'مكعب طول حرفه ٢ سم وُضع فيه مكعب طول حرفه ١ سم. ما الحجم المتبقي من المكعب الأول بالسنتيمتر المكعب؟', '["١", "٥", "٦", "٧"]'::jsonb, 3, 'حجم المكعب الكبير = ٢ × ٢ × ٢ = ٨، وحجم الصغير = ١ × ١ × ١ = ١. الحجم المتبقي = ٨ − ١ = ٧.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور، أوجد قيمة س + ص بالدرجات.', '["١٣٠", "٢٣٠", "٢٥٠", "٢٧٠"]'::jsonb, 1, 'زاوية المثلث السفلية اليسرى تساوي ٥٠° (متقابلة بالرأس مع الزاوية المعطاة)، فمجموع زاويتي المثلث الأخريين = ١٨٠ − ٥٠ = ١٣٠°. وبما أن س وص مكملتان لهاتين الزاويتين فإن: س + ص = ١٨٠ + ١٨٠ − ١٣٠ = ٢٣٠°.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug16_q03_angles.png', 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', '(٥⁷ + ٥⁷) ÷ ٥⁷ = ............', '["٢", "٢ × ٥⁷", "١٤", "٥⁷"]'::jsonb, 0, 'البسط = ٥⁷ + ٥⁷ = ٢ × ٥⁷، وعند قسمته على ٥⁷ يُختصر الأس مع مثله ويبقى ٢.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين: القيمة الأولى (٠٫١)²² والقيمة الثانية (٠٫١)³³', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'الأساس ٠٫١ عدد بين الصفر والواحد، وكلما زاد أسّه صغرت قيمته. الأس ٢٢ أصغر من ٣٣، فقيمة (٠٫١)²² أكبر.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'يسير محمد مشياً من البيت إلى المدرسة في ٦٠ دقيقة، وبالسيارة في ٩ دقائق. فإذا مشى لمدة ٢٠ دقيقة ثم أكمل بالسيارة، فما الزمن الكلي بالدقائق الذي استغرقه؟', '["٢٠", "٢٤", "٢٦", "٣٠"]'::jsonb, 2, 'مشيُ ٢٠ دقيقة من أصل ٦٠ يعني أنه قطع ثلث المسافة، وبقي الثلثان. زمن الباقي بالسيارة = ثلثا التسع دقائق = ٦ دقائق. الزمن الكلي = ٢٠ + ٦ = ٢٦ دقيقة.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور أسطوانة مملوءة بالعصير، قطر قاعدتها ١٠ وارتفاعها ١٠. قارن بين: القيمة الأولى (كمية العصير) والقيمة الثانية (٧٥٠)', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'نصف القطر = ١٠ ÷ ٢ = ٥. حجم الأسطوانة = ط × نق² × الارتفاع = ط × ٢٥ × ١٠ = ٢٥٠ط ≈ ٧٨٥، وهو أكبر من ٧٥٠.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug16_q07_cylinder.png', 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'إذا كانت الزاويتان (٦س)° و (٤س − ٢٠)° متتامتين، فما قيمة س؟', '["٩", "١٠", "١١", "١٢"]'::jsonb, 2, 'المتتامتان مجموعهما ٩٠°: ٦س + ٤س − ٢٠ = ٩٠ ← ١٠س = ١١٠ ← س = ١١.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'ما العدد الذي يقع بين ٠٫٠٦ و ٠٫٠٨ ؟', '["٠٫٧٠", "٠٫٠٠٧", "٠٫٦٥", "٠٫٠٧٥"]'::jsonb, 3, 'نكتب الحدين بثلاث منازل عشرية: ٠٫٠٦٠ و ٠٫٠٨٠. العدد الوحيد الواقع بينهما هو ٠٫٠٧٥، أما ٠٫٧٠ و ٠٫٦٥ فأكبر بكثير، و ٠٫٠٠٧ أصغر بكثير.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان ٦ > س > ٤ وكان ص = ٨، فقارن بين: القيمة الأولى (٠٫٧٥) والقيمة الثانية (س ÷ ص)', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'أكبر ما يمكن أن تقترب منه س ÷ ص هو ٦ ÷ ٨ = ٠٫٧٥، لكن س أصغر من ٦ دائماً فلا تصل النسبة إلى ٠٫٧٥ أبداً. إذن القيمة الأولى أكبر.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'إذا كانت مساحة اليمن ٥٦٠٬٠٠٠ كم² والكثافة السكانية فيها ١٤ نسمة لكل كم²، فأوجد عدد السكان.', '["٧٬٨٤٠٬٠٠٠", "٧٨٤٬٠٠٠", "٤٠٬٠٠٠", "٤٬٠٠٠"]'::jsonb, 0, 'الكثافة السكانية = عدد السكان ÷ المساحة، ومنها: عدد السكان = الكثافة × المساحة = ١٤ × ٥٦٠٬٠٠٠ = ٧٬٨٤٠٬٠٠٠ نسمة.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'أب عمره ٧١ عاماً وابنه عمره ٣٥ عاماً. بعد كم عام يصبح عمر الأب مثلَي عمر الابن؟', '["١", "٢", "٣", "٤"]'::jsonb, 0, 'بعد ن سنة: ٧١ + ن = ٢ × (٣٥ + ن) ← ٧١ + ن = ٧٠ + ٢ن ← ن = ١. وللتحقق: بعد سنة يصبح عمر الأب ٧٢ وهو ضِعف ٣٦.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'اشترى شخص ١٠ قطع حلوى سعر الواحدة ريالان، فإذا خُصم له ٥٪ من إجمالي المبلغ، فكم ريالاً يدفع؟', '["٢٠", "١٩", "١٨", "١٧"]'::jsonb, 1, 'الإجمالي = ١٠ × ٢ = ٢٠ ريالاً، والخصم = ٥٪ × ٢٠ = ١ ريال. المدفوع = ٢٠ − ١ = ١٩ ريالاً.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'في الشكل المجاور، إذا كان متوسط قطاعات المدارس والتعليم والجامعات يساوي ١٩٪، فما نسبة قطاع التعليم؟', '["٩٪", "١٠٪", "١١٪", "١٢٪"]'::jsonb, 2, 'متوسط ثلاثة قطاعات ١٩٪ يعني أن مجموعها = ١٩ × ٣ = ٥٧٪. نسبة التعليم = ٥٧ − ١٥ − ٣١ = ١١٪.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug16_q14_pie.png', 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان: سعر فستان + ٥٠٠ ريال = ٥ أمثال سعره − ٩٠٠ ريال، فما سعر الفستان؟', '["٢٥٠", "٣٠٠", "٣٥٠", "٤٠٠"]'::jsonb, 2, 'نفرض السعر س: س + ٥٠٠ = ٥س − ٩٠٠ ← ١٤٠٠ = ٤س ← س = ٣٥٠ ريالاً.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'إذا كان الطباخ يطبخ ٤٠ وجبة في ٤٨ دقيقة، فكم وجبة يطبخ في الساعة؟', '["٥٠", "٥٢", "٦٠", "٦٢"]'::jsonb, 0, 'بالتناسب: الساعة ٦٠ دقيقة، أي ١٫٢٥ ضِعف الـ ٤٨ دقيقة، فعدد الوجبات = ٤٠ × ١٫٢٥ = ٥٠ وجبة.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'احسب مساحة الشكل المجاور بالسنتيمتر المربع.', '["٤٨", "٦٠", "٦٤", "٧٢"]'::jsonb, 1, 'القصّة المثلثية: نصف الضلع الأيسر ٣ والوتر ٥، فعمقها بنظرية فيثاغورس = ٤ (مثلث ٣-٤-٥). مساحة المستطيل = ١٢ × ٦ = ٧٢، ومساحة المثلث المقصوص = نصف × ٦ × ٤ = ١٢. المساحة المطلوبة = ٧٢ − ١٢ = ٦٠.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug16_q17_shape.png', 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'كم عدد الطرق الممكنة لكتابة كلمة (بحروف مختلفة الترتيب) من حروف كلمة «خالد»؟', '["٤", "٦", "١٢", "٢٤"]'::jsonb, 3, 'كلمة «خالد» أربعة حروف مختلفة: للحرف الأول ٤ اختيارات، وللثاني ٣، وللثالث ٢، وللرابع ١. عدد الترتيبات = ٤ × ٣ × ٢ × ١ = ٢٤ طريقة.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور، م مركز المربع. أوجد محيط المربع بالسنتيمترات.', '["١٠", "٢٠", "٣٠", "٤٠"]'::jsonb, 3, 'المسافة من مركز المربع إلى منتصف ضلعه تساوي نصف طول الضلع، فالضلع = ٢ × ٥ = ١٠ سم، والمحيط = ٤ × ١٠ = ٤٠ سم.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug16_q19_square.png', 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'النسبة بين رواتب ثلاثة موظفين على الترتيب ٣ : ٤ : ٥. زاد راتب الأول بنسبة ١٠٠٪ والثاني بنسبة ٥٠٪ والثالث بنسبة ٨٠٪. كم تصبح النسبة بين رواتبهم على الترتيب؟', '["٧ : ٦ : ٦", "٦ : ٧ : ٩", "٢ : ٢ : ٣", "٢ : ٣ : ٣"]'::jsonb, 2, 'الأول تضاعف: ٣ × ٢ = ٦، والثاني زاد النصف: ٤ × ١٫٥ = ٦، والثالث: ٥ × ١٫٨ = ٩. النسبة ٦ : ٦ : ٩ وبالقسمة على ٣ تصبح ٢ : ٢ : ٣.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'احسب قيمة: ٢٥ ÷ ٥ + ٢٠ × (١٠ − ٥)', '["٥", "١٠٥", "١٢٥", "١٧٥"]'::jsonb, 1, 'الأقواس أولاً: ١٠ − ٥ = ٥. ثم القسمة والضرب: ٢٥ ÷ ٥ = ٥ و ٢٠ × ٥ = ١٠٠. وأخيراً الجمع: ٥ + ١٠٠ = ١٠٥.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'الشكل المجاور خماسي مجموع زواياه الداخلية ٥٤٠°. أوجد مجموع الزوايا المرقمة (١ ، ٢ ، ٣ ، ٤ ، ٥).', '["٩٠", "١٨٠", "٢٧٠", "٣٦٠"]'::jsonb, 3, 'كل زاوية مرقمة تكمل الزاوية الداخلية عند رأسها إلى ١٨٠°. المجموع الكلي للأزواج = ٥ × ١٨٠ = ٩٠٠°، فمجموع المرقمة = ٩٠٠ − ٥٤٠ = ٣٦٠°. وهذه قاعدة عامة: مجموع الزوايا الخارجية لأي مضلع = ٣٦٠°.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug16_q22_pentagon.png', 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان ٢^(٤ل) = (٢ ÷ ٢^(٢ن)) × ٤^ل ، فأوجد قيمة ل + ن.', '["١/٤", "١/٢", "٢", "٤"]'::jsonb, 1, 'نوحّد الأساس ٢: الطرف الأيمن = ٢¹ ÷ ٢^(٢ن) × ٢^(٢ل) = ٢ أس (١ − ٢ن + ٢ل). بمساواة الأسس: ٤ل = ١ − ٢ن + ٢ل ← ٢ل + ٢ن = ١ ← ل + ن = ١/٢.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'التحليل', 'اختيار من متعدد', 'اختبار مدته ٩٠ دقيقة مقسم إلى عدد من الأقسام، وبين كل قسمين ٥ دقائق راحة. إذا بدأ الاختبار الساعة ٨:٠٠ وانتهى الساعة ٩:٥٥، فكم عدد أقسام الاختبار؟', '["٧", "٦", "٥", "٤"]'::jsonb, 1, 'الزمن الكلي من ٨:٠٠ إلى ٩:٥٥ = ١١٥ دقيقة، ومنه ٩٠ دقيقة للاختبار، فزمن الراحات = ٢٥ دقيقة أي ٥ راحات. وبما أن الراحة تقع بين كل قسمين، فعدد الأقسام = ٥ + ١ = ٦.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'يوضح الجدول كمية المياه المتوفرة في عدة مناطق: المشرق العربي ٢٦٣ ، المغرب العربي ٢٥٢ ، الشرق الأوسط ٣٢٤ ، الخليج العربي ٢٢٨. ما أكبر منطقة بها مياه متاحة؟', '["المشرق العربي", "المغرب العربي", "الشرق الأوسط", "الخليج العربي"]'::jsonb, 2, 'بمقارنة قيم المياه المتوفرة: ٣٢٤ للشرق الأوسط وهي أعلى من ٢٦٣ و ٢٥٢ و ٢٢٨، فهو صاحب أكبر مياه متاحة.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور دائرة طول قطرها ٤ سم، والمنحنى داخلها مكوّن من نصفي دائرتين متطابقتين (الرسم ليس على القياس). قارن بين: القيمة الأولى (مساحة الجزء المظلل) والقيمة الثانية (٣ط)', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, 'نصف قطر الدائرة = ٢، فمساحتها الكلية = ط × ٢² = ٤ط. المنحنى الأوسط يقسم الدائرة إلى جزأين متطابقين تماماً، فمساحة المظلل = ٢ط، وهي أصغر من ٣ط.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug16_q26_circle.png', 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'شركة عدد موظفيها ١٠٠ موظف عام ١٤٣٣هـ، والشكل المجاور يبين الزيادة والنقص في عددهم خلال ٦ سنوات. ما الفرق بين عدد الموظفين عام ١٤٣٤ وعام ١٤٣٥؟', '["٩٠", "٨٠", "٧٠", "٦٠"]'::jsonb, 2, 'عدد الموظفين عام ١٤٣٤ = ١٠٠ − ٢٠ = ٨٠، وعام ١٤٣٥ = ٨٠ + ٧٠ = ١٥٠. الفرق = ١٥٠ − ٨٠ = ٧٠ موظفاً.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug16_q27_bars.png', 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور، احسب مساحة الدائرة.', '["٨ط", "١٠ط", "١٢ط", "١٦ط"]'::jsonb, 2, 'في المثلث القائم: ظا ٣٠° = المقابل ÷ المجاور، فقاعدة المثلث (وهي ضلع المربع) = ٤ ÷ ظا ٣٠° = ٤√٣. قطر الدائرة يساوي ضلع المربع، فنصف القطر = ٢√٣، والمساحة = ط × (٢√٣)² = ١٢ط.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug16_q28_circsq.png', 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'أب وثلاثة أبناء، مجموع أعمارهم بعد ٨ سنوات يساوي ٩٨. كم مجموع أعمارهم بعد ٥ سنوات؟', '["٧٨", "٨٦", "٩٥", "١٠٣"]'::jsonb, 1, 'عدد الأفراد ٤، وبعد ٨ سنوات يزيد المجموع ٤ × ٨ = ٣٢، فمجموع أعمارهم الآن = ٩٨ − ٣٢ = ٦٦. وبعد ٥ سنوات يزيد ٤ × ٥ = ٢٠، فيصبح ٦٦ + ٢٠ = ٨٦.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', '٤ أعداد فردية متتالية متوسطها (س). إذا كان س + ٢ = ٨، فما العدد الأصغر؟', '["١", "٣", "٥", "٧"]'::jsonb, 1, 'من المعادلة: س = ٦. أربعة أعداد فردية متتالية متوسطها ٦ هي: ٣ ، ٥ ، ٧ ، ٩ (لأن ٦ يتوسط ٥ و ٧). العدد الأصغر = ٣.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور، احسب مساحة الدائرة.', '["ط", "٢ط", "٣ط", "٤ط"]'::jsonb, 0, 'الضلع المقابل للزاوية ٣٠° هو قاعدة المثلث: جا ٣٠° = المقابل ÷ الوتر ← المقابل = ٤ × ٠٫٥ = ٢، وهو ضلع المربع. قطر الدائرة = ٢ فنصف القطر = ١، والمساحة = ط × ١² = ط.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug16_q31_circsq.png', 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'توق : حنين', '["غنى : ثروة", "نقيصة : فضيلة", "نهار : معاش", "مرض : دواء"]'::jsonb, 0, 'التوق والحنين مترادفان بمعنى الشوق، ومثلهما الغنى والثروة. أما نقيصة وفضيلة فمتضادتان، والنهار زمن المعاش، والدواء علاج المرض.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'وجود : عدم', '["سمين : نحيف", "رفيع : رقيق", "طول : امتداد", "قلم : كتابة"]'::jsonb, 0, 'الوجود والعدم متضادان، ومثلهما السمين والنحيف. أما رفيع ورقيق وطول وامتداد فمترادفات، والقلم أداة الكتابة.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'الكعبة : طواف', '["المسجد : الصلاة", "النخلة : التمر", "القلم : الحبر", "الصحراء : الرمال"]'::jsonb, 0, 'الكعبة يُطاف حولها عبادةً، والمسجد تؤدى فيه الصلاة عبادةً — مكان مقدس وعبادة تؤدى فيه. أما النخلة فمصدر التمر، والقلم أداة تعمل بالحبر، والصحراء مكان ومكوناته.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'ربيع : فصول', '["شمال : جهات", "شتاء : برودة", "أسبوع : أيام", "قمر : سماء"]'::jsonb, 0, 'الربيع واحد من الفصول، والشمال واحدة من الجهات — فرد من مجموعته. أما شتاء وبرودة فشيء وصفته، والأسبوع كلٌّ يتكون من الأيام (علاقة معكوسة)، والقمر وموضعه السماء.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'وريد : دم', '["رأس : مخ", "قلب : نبض", "نهر : جسر", "حذاء : قدم"]'::jsonb, 0, 'الوريد وعاء يجري فيه الدم، والرأس وعاء يحوي المخ — احتواء. أما النبض وظيفة القلب، والجسر مجاور للنهر، والحذاء يُلبس في القدم.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'مرسى : سفينة', '["محطة : قطار", "طريق : سيارة", "مطار : مسافر", "شاطئ : بحر"]'::jsonb, 0, 'المرسى مكان وقوف السفينة، والمحطة مكان وقوف القطار. أما الطريق فمكان سير السيارة لا وقوفها، والمسافر شخص لا مركبة، والشاطئ مجاور للبحر.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'جسم : جسد', '["ردم : هدم", "نبأ : خبر", "سهم : سيف", "باب : نافذة"]'::jsonb, 1, 'الجسم والجسد مترادفان، ومثلهما النبأ والخبر. أما الردم والهدم فمتغايران في المعنى رغم تقارب اللفظ، والسهم والسيف والباب والنافذة أزواج من فئة واحدة دون ترادف.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'جميل : قبيح', '["طويل : سمين", "صمت : كلام", "يمين : فوق", "يمشي : يركض"]'::jsonb, 1, 'الجميل والقبيح متضادان، ومثلهما الصمت والكلام. أما طويل وسمين فصفتان لا تضاد بينهما، ويمين وفوق اتجاهان غير متقابلين، ويمشي ويركض تدرج في السرعة لا تضاد.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'شكر النعم يدفع ...... ، وترك الذنوب حياة ......', '["البلاء – النقاء", "النقم – القلوب", "الهموم – الأجساد", "العطايا – النفوس"]'::jsonb, 1, 'شكر النعم يدفع النقم أي يحفظ صاحبه من زوالها، وترك الذنوب يحيي القلوب لأن المعاصي تميتها. «حياة النقاء» و«دفع العطايا» لا يستقيم بهما المعنى.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'الخلق ...... يُحبب صاحبه إلى الناس جميعاً، ويتمكن بذلك من إرضاء الناس على اختلاف ......', '["الحسن – طبقاتهم", "الجميل – أعمالهم", "الغليظ – طبائعهم", "المعتدل – أنواعهم"]'::jsonb, 0, 'الخلق الحسن هو ما يحبب صاحبه إلى الناس، و«على اختلاف طبقاتهم» التعبير الأدق عن تنوع الناس. أما الغليظ فيناقض المعنى، و«اختلاف أعمالهم وأنواعهم» أضعف في هذا السياق.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'إن ضبط النفس هو ...... على توجيه أفكارك ومشاعرك وأفعالك تجاه ...... أهدافك.', '["قدرتك – تحقيق", "عجزك – تحقيق", "قدرتك – تأجيل", "رغبتك – نسيان"]'::jsonb, 0, 'ضبط النفس قدرة، والتوجيه يكون نحو تحقيق الأهداف. أما العجز فنقيض الضبط، والتأجيل والنسيان يناقضان الغاية من توجيه الأفكار والأفعال.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'كما أنك تحب شراء المماليك بمالك، فيجب عليك شراء الأحرار بـ ......', '["مالك", "ملكك", "معروفك", "شرفك"]'::jsonb, 2, 'المماليك تُشترى بالمال، أما الأحرار فتُكسب قلوبهم بالمعروف والإحسان — وهي حكمة مشهورة: الأحرار تُشترى بالمعروف.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'ما أجمل أن يُعطى الإنسان غريزة ...... ، والسكوت ......', '["الود – الدائم", "الحكمة – الجميل", "العقل – الطويل", "الذكاء – العميق"]'::jsonb, 2, '«غريزة العقل» تعبير مأثور يعني رجاحة الفطرة، ويقترن في الأثر بالسكوت الطويل علامةَ الرزانة. ولا يقال «غريزة الود» أو «غريزة الحكمة»، والسكوت لا يوصف بالعمق.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'إذا لم يُحرم الإنسان بعض ...... ، كانت عينه على ......', '["المكروهات – المحظورات", "الواجبات – المحرمات", "المباحات – الواجبات", "المحظورات – المكروهات"]'::jsonb, 0, 'النفس إن لم تُمنع من الأدنى (المكروهات) تطلعت إلى الأشد (المحظورات) — تدرج تصاعدي مستقيم. أما حرمان الواجبات فلا يُتصور، والترتيب المعكوس في الخيار الأخير يفسد المعنى.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'الابتسامة للحياة ...... العقل وتبدد ...... الثقال.', '["تنشط – الهموم", "تقوي – الأمور", "تنمي – الأفكار", "تحرك – المشاعر"]'::jsonb, 0, 'الابتسامة تنشط العقل، والتبدد يناسب الهموم التي توصف بالثقال. أما «تبدد الأمور أو الأفكار أو المشاعر» فلا يستقيم مع وصف «الثقال».', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'لا تلتفت لـ ...... الأمور، حتى لا تلهيك عن ......', '["توافه – حلها", "صغائر – كبارها", "كبار – صغارها", "غوامض – ظواهرها"]'::jsonb, 1, 'المقابلة بين صغائر الأمور وكبارها هي أساس المعنى: الانشغال بالصغير يلهي عن الكبير. وفي الخيار الأول يعود الضمير على التوافه نفسها فيتناقض المعنى، والخيار الثالث معكوس.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«تاج القيصر لا يمكن أن يحميه من الحرارة»', '["تاج", "القيصر", "لا يمكن", "الحرارة"]'::jsonb, 3, 'الجملة مَثَلٌ معناه أن المُلك لا يقي صاحبه الآلام، وصوابها المعروف: التاج لا يحمي من «الصداع». أما «الحرارة» فتكسر المعنى المقصود، وبقية الكلمات متسقة مع السياق.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«الفشل يتحقق بالاستسلام، أما النجاح فيتحقق بالكسل»', '["الفشل", "الاستسلام", "النجاح", "الكسل"]'::jsonb, 3, 'الشطر الأول مستقيم: الفشل نتيجة الاستسلام. أما النجاح فلا يتحقق بالكسل بل بضده، فالصواب نحو: «فيتحقق بالمثابرة». الكلمة المكسورة سياقياً هي الكسل.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«من مهارات القيادة السيطرة على مشكلات العمل وتعقيدها وحسم الخلافات والترجيح بين الآراء»', '["القيادة", "مشكلات", "تعقيدها", "الخلافات"]'::jsonb, 2, 'القائد يسيطر على المشكلات ليحلها ويذللها لا ليزيد تعقيدها، فالصواب «وتذليلها» أو «وحلها». وبقية الكلمات منسجمة مع سياق مهارات القيادة.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«المحسن في الظن يعيش في هم ومشقة»', '["المحسن", "الظن", "هم", "مشقة"]'::jsonb, 0, 'الذي يعيش في همّ ومشقة هو «المسيء» في الظن لأنه يتوقع الشر في كل شيء، أما محسن الظن فمرتاح البال. فالكلمة المخالفة للسياق هي المحسن.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«أصحاب الذاكرة القوية يعانون من متلازمة اللامبالاة وتذكر التفاصيل»', '["الذاكرة", "القوية", "اللامبالاة", "التفاصيل"]'::jsonb, 2, 'من يتذكر أدق التفاصيل يعاني من فرط الانتباه والاستغراق فيها، وهذا ضد اللامبالاة تماماً. فوجودها في الجملة يناقض «تذكر التفاصيل» المذكورة بعدها.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«القلق حالة جسدية نتيجة التوتر والتوقعات السلبية، وقد تكون الاضطرابات النفسية سبباً لذلك»', '["جسدية", "السلبية", "الاضطرابات", "سبباً"]'::jsonb, 0, 'بقية الجملة تدور حول التوتر والتوقعات والاضطرابات النفسية، فالقلق حالة «نفسية» لا جسدية — وهذا هو التصحيح المطلوب.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«القوة أن تحتفظ بهدوئك عند غضبك، وأن تحزن نفسك حتى وأنت لست سعيداً»', '["القوة", "تحتفظ", "غضبك", "تحزن"]'::jsonb, 3, 'السياق يمدح ضبط النفس: تحافظ على هدوئك وقت الغضب، و«تُسعد» نفسك حتى في غير أوقات السعادة. أما «تحزن نفسك» فيناقض المعنى المقصود.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«إذا كنت تريد أن تقهر عدوك فغيّر من غيرك»', '["غيرك", "تقهر", "عدوك", "تريد"]'::jsonb, 0, 'الحكمة الصحيحة: إذا أردت أن تقهر عدوك «فغيّر من نفسك»، لأن تطوير الذات هو ما يغيظ العدو ويقهره. فكلمة «غيرك» هي المخالفة للسياق.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["فريضة", "حج", "صيام", "زكاة"]'::jsonb, 0, 'الحج والصيام والزكاة عبادات محددة من أركان الإسلام، أما «فريضة» فاسم عام يشملها جميعاً وليست عبادة بعينها.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["السعودية", "الكويت", "قطر", "البحرين"]'::jsonb, 3, 'السعودية والكويت وقطر دول متصلة بيابسة شبه الجزيرة العربية، أما البحرين فجزيرة يحيط بها البحر.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["طفولة", "شباب", "كهولة", "مشيب"]'::jsonb, 3, 'الطفولة والشباب والكهولة مراحل عمرية، أما المشيب فوصف لبياض الشعر وليس مرحلة عمرية قائمة بذاتها.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["وجه", "جهة", "اتجاه", "وجهة"]'::jsonb, 0, 'جهة واتجاه ووجهة كلها تدل على المقصد والمسار، أما «الوجه» فعضو في الجسم رغم اشتراك الجذر اللغوي.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["ماء", "نار", "عسل", "زيت"]'::jsonb, 1, 'الماء والعسل والزيت سوائل، أما النار فليست سائلاً.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["قرأ", "نسخ", "كتب", "رسم"]'::jsonb, 0, 'نسخ وكتب ورسم أفعال تنتج أثراً باليد على الورق، أما القراءة فاستقبال للمكتوب لا إنتاج له.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["صهيل", "زئير", "خرير", "عواء"]'::jsonb, 2, 'الصهيل صوت الخيل والزئير صوت الأسد والعواء صوت الذئب — أصوات حيوانات، أما الخرير فصوت الماء.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["شجرة", "نخلة", "تمرة", "بذرة"]'::jsonb, 2, 'الشجرة والنخلة والبذرة مما يُغرس فينبت، أما التمرة فثمرة ناتجة تؤكل.', NULL, 'ad160816-2026-4c00-9d00-160820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يُفهم من النص أن الكهرمان يُعد من:', '["الأحجار الكريمة", "الحيوانات البحرية", "الذهب الخالص", "اللآلئ البحرية"]'::jsonb, 0, 'النص يقول: «وقد تكون من الأحجار الكريمة كالكهرمان» — فالكاف هنا للتمثيل، أي أن الكهرمان مثال على الأحجار الكريمة.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81601-0001-4a01-b001-c0ffee000001', 'يتميز حُلي النساء بأنه مصنوع من مواد محلية ومستوردة، وعناصر ذات قيمة من مواد بحرية وأحجار كريمة كالصدف واللؤلؤ، وقد تكون من الأحجار الكريمة كالكهرمان، بالإضافة إلى الذهب والفضة. وتتميز الحلي بأن لها أشكالاً هندسية كثيرة، ومن أشهرها القلائد والأقراط والأساور.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'سبب تميز حلي النساء كما ورد في النص:', '["اعتمادها على الصناعة المحلية فقط", "صناعتها من مواد بحرية وأحجار كريمة", "جودة تصنيعها", "ارتفاع أسعارها"]'::jsonb, 1, 'التعليل الصريح في النص: «مصنوع من مواد محلية ومستوردة وعناصر ذات قيمة من مواد بحرية وأحجار كريمة». والنص يذكر المحلية والمستوردة معاً، ولم يذكر الجودة ولا الأسعار.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81601-0001-4a01-b001-c0ffee000001', 'يتميز حُلي النساء بأنه مصنوع من مواد محلية ومستوردة، وعناصر ذات قيمة من مواد بحرية وأحجار كريمة كالصدف واللؤلؤ، وقد تكون من الأحجار الكريمة كالكهرمان، بالإضافة إلى الذهب والفضة. وتتميز الحلي بأن لها أشكالاً هندسية كثيرة، ومن أشهرها القلائد والأقراط والأساور.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'نفهم من النص أن الحلي النسائية:', '["مميزة", "مستوردة", "فريدة", "منتشرة"]'::jsonb, 0, 'افتتح النص بقوله «يتميز حُلي النساء» فوصفها بالتميز صراحة. أما المستوردة فبعض موادها فقط، ولم يرد وصفها بالفريدة أو المنتشرة.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81601-0001-4a01-b001-c0ffee000001', 'يتميز حُلي النساء بأنه مصنوع من مواد محلية ومستوردة، وعناصر ذات قيمة من مواد بحرية وأحجار كريمة كالصدف واللؤلؤ، وقد تكون من الأحجار الكريمة كالكهرمان، بالإضافة إلى الذهب والفضة. وتتميز الحلي بأن لها أشكالاً هندسية كثيرة، ومن أشهرها القلائد والأقراط والأساور.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'جاءت كلمة (أشكالاً) بصيغة الجمع في «لها أشكالاً هندسية كثيرة» لتدل على:', '["الكثرة", "القلة", "الأهمية", "التعظيم"]'::jsonb, 0, 'اقترن الجمع بكلمة «كثيرة»، فدلالته هنا كثرة الأشكال وتنوعها.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81601-0001-4a01-b001-c0ffee000001', 'يتميز حُلي النساء بأنه مصنوع من مواد محلية ومستوردة، وعناصر ذات قيمة من مواد بحرية وأحجار كريمة كالصدف واللؤلؤ، وقد تكون من الأحجار الكريمة كالكهرمان، بالإضافة إلى الذهب والفضة. وتتميز الحلي بأن لها أشكالاً هندسية كثيرة، ومن أشهرها القلائد والأقراط والأساور.', 4, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يُفهم من قوله «ومن أشهرها القلائد والأقراط والأساور» أن هذه الحلي:', '["معروفة", "قليلة", "نادرة", "مصنوعة"]'::jsonb, 0, '«أشهرها» تعني أنها الأكثر شهرة وذيوعاً بين الناس، أي معروفة عندهم.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81601-0001-4a01-b001-c0ffee000001', 'يتميز حُلي النساء بأنه مصنوع من مواد محلية ومستوردة، وعناصر ذات قيمة من مواد بحرية وأحجار كريمة كالصدف واللؤلؤ، وقد تكون من الأحجار الكريمة كالكهرمان، بالإضافة إلى الذهب والفضة. وتتميز الحلي بأن لها أشكالاً هندسية كثيرة، ومن أشهرها القلائد والأقراط والأساور.', 5, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'قبل أن تصبح الشركة مملوكة بالكامل للمملكة، كم كانت أعلى نسبة وصلت إليها ملكية الحكومة السعودية؟', '["خمسون بالمئة", "ستون بالمئة", "سبعون بالمئة", "ثمانون بالمئة"]'::jsonb, 1, 'النص: «وفي عام ١٩٧٤ ارتفعت حصة الحكومة السعودية إلى ٦٠٪»، ثم جاء التملك الكامل عام ١٩٨٨.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81602-0002-4a02-b002-c0ffee000002', 'في عام ١٩٤٤ تم تغيير اسم شركة (كاسوك) صاحبة حقوق التنقيب عن النفط في السعودية لتكون الشركة العربية الأمريكية للزيت (أرامكو الأمريكية)، وفي عام ١٩٤٥ بدأ معمل التكرير في رأس تنورة أعماله، وفي عام ١٩٤٨ اشترت شركة (إسو نيوجيرسي للزيت القياسي) حصة ٣٠٪ من أسهم أرامكو الأمريكية من شركتي (سوكال) و(تكساكو)، ثم قامت شركة (سوكوني فاكيوم) والتي اشترتها إكسون موبيل لاحقاً بشراء حصة ١٠٪ من أرامكو الأمريكية من الشركتين نفسيهما، مما ترك لكل من سوكال وتكساكو حصة ٣٠٪ في أرامكو الأمريكية. وفي عام ١٩٥٠ هدد الملك عبدالعزيز آل سعود بتأميم المنشآت النفطية في البلاد، وبذلك استطاع الحصول على حصة من أرباح أرامكو الأمريكية، وكانت عمليات مماثلة قد حدثت مع شركات النفط الأمريكية في فنزويلا في الوقت نفسه، فقامت الحكومة الأمريكية بمنح شركة أرامكو الأمريكية تخفيضات ضريبية تعادل الأرباح التي كانت تُمنح للملك عبدالعزيز، وعُرفت باسم (الحيلة الذهبية)، وفي الترتيب الجديد نُقل مقر الشركة من نيويورك إلى الظهران في عام ١٩٥٠.
وفي عام ١٩٧٣ استحوذت الحكومة السعودية على حصة ٢٥٪ من شركة أرامكو الأمريكية، وفي عام ١٩٧٤ ارتفعت حصة الحكومة السعودية إلى ٦٠٪.
وفي عام ١٩٨٨ تم تعديل اسم الشركة بمرسوم ملكي إلى شركة الزيت العربية السعودية (أرامكو السعودية)، والذي ترتب عليه إدارة العمليات والسيطرة على النفط والغاز السعودي، وأصبحت أرامكو السعودية شركة مملوكة بالكامل للحكومة السعودية.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يتحدث النص عن شركة أرامكو من حيث:', '["تأسيسها", "ملكيتها", "بداياتها", "مراجعها"]'::jsonb, 1, 'معظم فقرات النص تتتبع انتقال الحصص والأسهم: ٣٠٪ ثم ١٠٪ ثم ٢٥٪ ثم ٦٠٪ ثم الملكية الكاملة — فمحور النص هو ملكية الشركة وتحولاتها.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81602-0002-4a02-b002-c0ffee000002', 'في عام ١٩٤٤ تم تغيير اسم شركة (كاسوك) صاحبة حقوق التنقيب عن النفط في السعودية لتكون الشركة العربية الأمريكية للزيت (أرامكو الأمريكية)، وفي عام ١٩٤٥ بدأ معمل التكرير في رأس تنورة أعماله، وفي عام ١٩٤٨ اشترت شركة (إسو نيوجيرسي للزيت القياسي) حصة ٣٠٪ من أسهم أرامكو الأمريكية من شركتي (سوكال) و(تكساكو)، ثم قامت شركة (سوكوني فاكيوم) والتي اشترتها إكسون موبيل لاحقاً بشراء حصة ١٠٪ من أرامكو الأمريكية من الشركتين نفسيهما، مما ترك لكل من سوكال وتكساكو حصة ٣٠٪ في أرامكو الأمريكية. وفي عام ١٩٥٠ هدد الملك عبدالعزيز آل سعود بتأميم المنشآت النفطية في البلاد، وبذلك استطاع الحصول على حصة من أرباح أرامكو الأمريكية، وكانت عمليات مماثلة قد حدثت مع شركات النفط الأمريكية في فنزويلا في الوقت نفسه، فقامت الحكومة الأمريكية بمنح شركة أرامكو الأمريكية تخفيضات ضريبية تعادل الأرباح التي كانت تُمنح للملك عبدالعزيز، وعُرفت باسم (الحيلة الذهبية)، وفي الترتيب الجديد نُقل مقر الشركة من نيويورك إلى الظهران في عام ١٩٥٠.
وفي عام ١٩٧٣ استحوذت الحكومة السعودية على حصة ٢٥٪ من شركة أرامكو الأمريكية، وفي عام ١٩٧٤ ارتفعت حصة الحكومة السعودية إلى ٦٠٪.
وفي عام ١٩٨٨ تم تعديل اسم الشركة بمرسوم ملكي إلى شركة الزيت العربية السعودية (أرامكو السعودية)، والذي ترتب عليه إدارة العمليات والسيطرة على النفط والغاز السعودي، وأصبحت أرامكو السعودية شركة مملوكة بالكامل للحكومة السعودية.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'متى أصبحت أرامكو شركة مملوكة بالكامل للمملكة العربية السعودية؟', '["في الربع الأول من القرن العشرين", "في النصف الثاني من القرن العشرين", "في نهاية القرن التاسع عشر", "في مطلع القرن الحادي والعشرين"]'::jsonb, 1, 'التملك الكامل كان عام ١٩٨٨، وهو يقع في النصف الثاني من القرن العشرين (١٩٥١ – ٢٠٠٠).', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81602-0002-4a02-b002-c0ffee000002', 'في عام ١٩٤٤ تم تغيير اسم شركة (كاسوك) صاحبة حقوق التنقيب عن النفط في السعودية لتكون الشركة العربية الأمريكية للزيت (أرامكو الأمريكية)، وفي عام ١٩٤٥ بدأ معمل التكرير في رأس تنورة أعماله، وفي عام ١٩٤٨ اشترت شركة (إسو نيوجيرسي للزيت القياسي) حصة ٣٠٪ من أسهم أرامكو الأمريكية من شركتي (سوكال) و(تكساكو)، ثم قامت شركة (سوكوني فاكيوم) والتي اشترتها إكسون موبيل لاحقاً بشراء حصة ١٠٪ من أرامكو الأمريكية من الشركتين نفسيهما، مما ترك لكل من سوكال وتكساكو حصة ٣٠٪ في أرامكو الأمريكية. وفي عام ١٩٥٠ هدد الملك عبدالعزيز آل سعود بتأميم المنشآت النفطية في البلاد، وبذلك استطاع الحصول على حصة من أرباح أرامكو الأمريكية، وكانت عمليات مماثلة قد حدثت مع شركات النفط الأمريكية في فنزويلا في الوقت نفسه، فقامت الحكومة الأمريكية بمنح شركة أرامكو الأمريكية تخفيضات ضريبية تعادل الأرباح التي كانت تُمنح للملك عبدالعزيز، وعُرفت باسم (الحيلة الذهبية)، وفي الترتيب الجديد نُقل مقر الشركة من نيويورك إلى الظهران في عام ١٩٥٠.
وفي عام ١٩٧٣ استحوذت الحكومة السعودية على حصة ٢٥٪ من شركة أرامكو الأمريكية، وفي عام ١٩٧٤ ارتفعت حصة الحكومة السعودية إلى ٦٠٪.
وفي عام ١٩٨٨ تم تعديل اسم الشركة بمرسوم ملكي إلى شركة الزيت العربية السعودية (أرامكو السعودية)، والذي ترتب عليه إدارة العمليات والسيطرة على النفط والغاز السعودي، وأصبحت أرامكو السعودية شركة مملوكة بالكامل للحكومة السعودية.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'الضمير في (اشترتها) في قوله «شركة سوكوني فاكيوم والتي اشترتها إكسون موبيل لاحقاً» يعود على:', '["شركة أرامكو الأمريكية", "شركة سوكوني فاكيوم", "شركة سوكال", "شركة تكساكو"]'::jsonb, 1, 'إكسون موبيل اشترت شركة سوكوني فاكيوم نفسها، فالضمير عائد على أقرب مذكور قبله وهو سوكوني فاكيوم.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81602-0002-4a02-b002-c0ffee000002', 'في عام ١٩٤٤ تم تغيير اسم شركة (كاسوك) صاحبة حقوق التنقيب عن النفط في السعودية لتكون الشركة العربية الأمريكية للزيت (أرامكو الأمريكية)، وفي عام ١٩٤٥ بدأ معمل التكرير في رأس تنورة أعماله، وفي عام ١٩٤٨ اشترت شركة (إسو نيوجيرسي للزيت القياسي) حصة ٣٠٪ من أسهم أرامكو الأمريكية من شركتي (سوكال) و(تكساكو)، ثم قامت شركة (سوكوني فاكيوم) والتي اشترتها إكسون موبيل لاحقاً بشراء حصة ١٠٪ من أرامكو الأمريكية من الشركتين نفسيهما، مما ترك لكل من سوكال وتكساكو حصة ٣٠٪ في أرامكو الأمريكية. وفي عام ١٩٥٠ هدد الملك عبدالعزيز آل سعود بتأميم المنشآت النفطية في البلاد، وبذلك استطاع الحصول على حصة من أرباح أرامكو الأمريكية، وكانت عمليات مماثلة قد حدثت مع شركات النفط الأمريكية في فنزويلا في الوقت نفسه، فقامت الحكومة الأمريكية بمنح شركة أرامكو الأمريكية تخفيضات ضريبية تعادل الأرباح التي كانت تُمنح للملك عبدالعزيز، وعُرفت باسم (الحيلة الذهبية)، وفي الترتيب الجديد نُقل مقر الشركة من نيويورك إلى الظهران في عام ١٩٥٠.
وفي عام ١٩٧٣ استحوذت الحكومة السعودية على حصة ٢٥٪ من شركة أرامكو الأمريكية، وفي عام ١٩٧٤ ارتفعت حصة الحكومة السعودية إلى ٦٠٪.
وفي عام ١٩٨٨ تم تعديل اسم الشركة بمرسوم ملكي إلى شركة الزيت العربية السعودية (أرامكو السعودية)، والذي ترتب عليه إدارة العمليات والسيطرة على النفط والغاز السعودي، وأصبحت أرامكو السعودية شركة مملوكة بالكامل للحكومة السعودية.', 4, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'علاقة عبارة «لتكون الشركة العربية الأمريكية للزيت» بما قبلها:', '["تكاملية", "جزئية", "كلية", "سببية"]'::jsonb, 3, 'اللام في «لتكون» لام التعليل، تبين الغاية من تغيير الاسم — فالعلاقة سببية غائية.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81602-0002-4a02-b002-c0ffee000002', 'في عام ١٩٤٤ تم تغيير اسم شركة (كاسوك) صاحبة حقوق التنقيب عن النفط في السعودية لتكون الشركة العربية الأمريكية للزيت (أرامكو الأمريكية)، وفي عام ١٩٤٥ بدأ معمل التكرير في رأس تنورة أعماله، وفي عام ١٩٤٨ اشترت شركة (إسو نيوجيرسي للزيت القياسي) حصة ٣٠٪ من أسهم أرامكو الأمريكية من شركتي (سوكال) و(تكساكو)، ثم قامت شركة (سوكوني فاكيوم) والتي اشترتها إكسون موبيل لاحقاً بشراء حصة ١٠٪ من أرامكو الأمريكية من الشركتين نفسيهما، مما ترك لكل من سوكال وتكساكو حصة ٣٠٪ في أرامكو الأمريكية. وفي عام ١٩٥٠ هدد الملك عبدالعزيز آل سعود بتأميم المنشآت النفطية في البلاد، وبذلك استطاع الحصول على حصة من أرباح أرامكو الأمريكية، وكانت عمليات مماثلة قد حدثت مع شركات النفط الأمريكية في فنزويلا في الوقت نفسه، فقامت الحكومة الأمريكية بمنح شركة أرامكو الأمريكية تخفيضات ضريبية تعادل الأرباح التي كانت تُمنح للملك عبدالعزيز، وعُرفت باسم (الحيلة الذهبية)، وفي الترتيب الجديد نُقل مقر الشركة من نيويورك إلى الظهران في عام ١٩٥٠.
وفي عام ١٩٧٣ استحوذت الحكومة السعودية على حصة ٢٥٪ من شركة أرامكو الأمريكية، وفي عام ١٩٧٤ ارتفعت حصة الحكومة السعودية إلى ٦٠٪.
وفي عام ١٩٨٨ تم تعديل اسم الشركة بمرسوم ملكي إلى شركة الزيت العربية السعودية (أرامكو السعودية)، والذي ترتب عليه إدارة العمليات والسيطرة على النفط والغاز السعودي، وأصبحت أرامكو السعودية شركة مملوكة بالكامل للحكومة السعودية.', 5, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يتحدث النص عن الطاقة من حيث:', '["مصادرها", "استهلاكها", "استخداماتها", "تنوعها"]'::jsonb, 1, 'الجملة الافتتاحية «زاد استهلاك الطاقة بشكل كبير» هي الفكرة المحورية، وما ذُكر بعدها عن المصادر والاستخدامات جاء تفصيلاً وتعليلاً لها.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81603-0003-4a03-b003-c0ffee000003', 'زاد استهلاك الطاقة بشكل كبير حيث يستخدمها الإنسان في مجالات كثيرة كالصناعة والزراعة، ومصادر الطاقة مثل النفط والغاز والمياه والرياح ليست كافية، لذلك اتجه العلماء إلى البحث عن مصادر جديدة للطاقة مثل الطاقة الحرارية والطاقة الشمسية التي يزخر بها الكون.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'معنى (يزخر) في قوله «التي يزخر بها الكون»:', '["يمتلئ", "يكثر", "يعلو", "يتوهج"]'::jsonb, 0, 'زخر البحر: امتلأ وفاض، فالمعنى أن الكون ممتلئ بهذه الطاقات. وهي أدق من «يكثر» لأنها تفيد الامتلاء والفيض معاً.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81603-0003-4a03-b003-c0ffee000003', 'زاد استهلاك الطاقة بشكل كبير حيث يستخدمها الإنسان في مجالات كثيرة كالصناعة والزراعة، ومصادر الطاقة مثل النفط والغاز والمياه والرياح ليست كافية، لذلك اتجه العلماء إلى البحث عن مصادر جديدة للطاقة مثل الطاقة الحرارية والطاقة الشمسية التي يزخر بها الكون.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'الشخص الذي يُقصد بعبارة «يبذل غاية جهده للمساواة مع أقرانه فقط»:', '["المقلد", "المجتهد", "صاحب الهمة الكبيرة", "المتفائل"]'::jsonb, 0, 'من يجعل غايته القصوى مشابهة أقرانه فهو يقلدهم ولا يسعى لتجاوزهم، وهذا وصف صاحب الهمة المتوسطة المتبع للنمطية.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81604-0004-4a04-b004-c0ffee000004', 'تختلف طموحات الناس وهممهم؛ فالأول هو صاحب الهمة الصغيرة، وهو الذي يتكئ على الناس ولا يهمه إلا اللهو، ولا يحب أن يفعل شيئاً أو ينجز شيئاً. والثاني صاحب الهمة المتوسطة، وهو شخص يتبع النمطية ويبذل غاية جهده للمساواة مع أقرانه فقط، فأكبر همه أن يشابه أقرانه. والثالث صاحب الهمة الكبيرة، تجده يلازم الناجحين ويحب أن يكون معهم ويتعلم منهم، وينجز المهام ويهتم بوقته ويحسن استغلاله، ويبتكر أشياء جديدة ويحطم الحواجز ويحقق نجاحه بنفسه.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'الضمير في (تجده) يعود على:', '["صاحب الهمة الكبيرة", "صاحب الهمة الصغيرة", "الناجح", "الفاشل"]'::jsonb, 0, '«والثالث صاحب الهمة الكبيرة تجده يلازم الناجحين» — الضمير عائد على الثالث المذكور قبله مباشرة.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81604-0004-4a04-b004-c0ffee000004', 'تختلف طموحات الناس وهممهم؛ فالأول هو صاحب الهمة الصغيرة، وهو الذي يتكئ على الناس ولا يهمه إلا اللهو، ولا يحب أن يفعل شيئاً أو ينجز شيئاً. والثاني صاحب الهمة المتوسطة، وهو شخص يتبع النمطية ويبذل غاية جهده للمساواة مع أقرانه فقط، فأكبر همه أن يشابه أقرانه. والثالث صاحب الهمة الكبيرة، تجده يلازم الناجحين ويحب أن يكون معهم ويتعلم منهم، وينجز المهام ويهتم بوقته ويحسن استغلاله، ويبتكر أشياء جديدة ويحطم الحواجز ويحقق نجاحه بنفسه.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'أنسب عنوان للنص:', '["أنواع الهمم", "أساليب النجاح", "شحذ الهمم", "صفات الناجحين"]'::jsonb, 0, 'النص قسّم الناس ثلاثة أصناف بحسب هممهم، فالعنوان الجامع لأفكاره كلها هو أنواع الهمم. أما صفات الناجحين فتغطي الصنف الثالث وحده.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81604-0004-4a04-b004-c0ffee000004', 'تختلف طموحات الناس وهممهم؛ فالأول هو صاحب الهمة الصغيرة، وهو الذي يتكئ على الناس ولا يهمه إلا اللهو، ولا يحب أن يفعل شيئاً أو ينجز شيئاً. والثاني صاحب الهمة المتوسطة، وهو شخص يتبع النمطية ويبذل غاية جهده للمساواة مع أقرانه فقط، فأكبر همه أن يشابه أقرانه. والثالث صاحب الهمة الكبيرة، تجده يلازم الناجحين ويحب أن يكون معهم ويتعلم منهم، وينجز المهام ويهتم بوقته ويحسن استغلاله، ويبتكر أشياء جديدة ويحطم الحواجز ويحقق نجاحه بنفسه.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'نفهم من النص أن التعب مرتبط بـ:', '["النجاح", "الفشل", "اللهو", "الراحة"]'::jsonb, 0, 'صاحب الهمة الكبيرة ينجز ويبتكر ويحطم الحواجز ليحقق نجاحه بنفسه — فالنجاح ثمرة الجهد والتعب، بعكس صاحب الهمة الصغيرة الذي يؤثر اللهو والدعة.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81604-0004-4a04-b004-c0ffee000004', 'تختلف طموحات الناس وهممهم؛ فالأول هو صاحب الهمة الصغيرة، وهو الذي يتكئ على الناس ولا يهمه إلا اللهو، ولا يحب أن يفعل شيئاً أو ينجز شيئاً. والثاني صاحب الهمة المتوسطة، وهو شخص يتبع النمطية ويبذل غاية جهده للمساواة مع أقرانه فقط، فأكبر همه أن يشابه أقرانه. والثالث صاحب الهمة الكبيرة، تجده يلازم الناجحين ويحب أن يكون معهم ويتعلم منهم، وينجز المهام ويهتم بوقته ويحسن استغلاله، ويبتكر أشياء جديدة ويحطم الحواجز ويحقق نجاحه بنفسه.', 4, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'أي مما يلي صحيح وفق النص؟', '["الناجح هو الذي يرسم أهدافه ويحققها بنفسه", "صاحب الهمة المتوسطة يبتكر أشياء جديدة", "الناجح يقلد الناجحين في كل شيء", "صاحب الهمة الصغيرة يحسن استغلال وقته"]'::jsonb, 0, 'النص يصف صاحب الهمة الكبيرة بأنه «يحقق نجاحه بنفسه». أما المتوسط فيتبع النمطية ولا يبتكر، والكبير يتعلم من الناجحين ولا يقلدهم، والصغير لا يهمه إلا اللهو.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81604-0004-4a04-b004-c0ffee000004', 'تختلف طموحات الناس وهممهم؛ فالأول هو صاحب الهمة الصغيرة، وهو الذي يتكئ على الناس ولا يهمه إلا اللهو، ولا يحب أن يفعل شيئاً أو ينجز شيئاً. والثاني صاحب الهمة المتوسطة، وهو شخص يتبع النمطية ويبذل غاية جهده للمساواة مع أقرانه فقط، فأكبر همه أن يشابه أقرانه. والثالث صاحب الهمة الكبيرة، تجده يلازم الناجحين ويحب أن يكون معهم ويتعلم منهم، وينجز المهام ويهتم بوقته ويحسن استغلاله، ويبتكر أشياء جديدة ويحطم الحواجز ويحقق نجاحه بنفسه.', 5, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'جملة «ليس بتجاهل المخاطر ولا بنسف الطموحات» جاءت لـ:', '["تصحيح مفهوم", "نفي فكرة", "استقراء حال", "بيان حال"]'::jsonb, 0, 'النص يصحح فهماً خاطئاً للتفاؤل: ينفي عنه ما ليس منه ثم يثبت حقيقته (حسن الظن بالله)، والنفي هنا وسيلة التصحيح لا غاية بذاتها.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81605-0005-4a05-b005-c0ffee000005', 'التفاؤل ليس دعوة لإنكار الواقع بتجاهل المخاطر، ولا بنسف الطموحات والاحتمالات، ولكنه حسن الظن بالله، والوعي والنظر في الاحتمالات الممكنة وتوقع الأفضل منها.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'تدعو القطعة إلى:', '["حسن الظن بالله", "تجاهل المخاطر", "نسف الطموحات", "إنكار الواقع"]'::jsonb, 0, '«ولكنه حسن الظن بالله» هي خلاصة القطعة ودعوتها، أما الخيارات الأخرى فمنفية في النص صراحة.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81605-0005-4a05-b005-c0ffee000005', 'التفاؤل ليس دعوة لإنكار الواقع بتجاهل المخاطر، ولا بنسف الطموحات والاحتمالات، ولكنه حسن الظن بالله، والوعي والنظر في الاحتمالات الممكنة وتوقع الأفضل منها.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'الضمير في كلمة (منها) يعود على:', '["الاحتمالات الممكنة", "الأفضل", "الطموحات", "المخاطر"]'::jsonb, 0, '«النظر في الاحتمالات الممكنة وتوقع الأفضل منها» أي توقع أفضل تلك الاحتمالات — فالضمير عائد عليها.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81605-0005-4a05-b005-c0ffee000005', 'التفاؤل ليس دعوة لإنكار الواقع بتجاهل المخاطر، ولا بنسف الطموحات والاحتمالات، ولكنه حسن الظن بالله، والوعي والنظر في الاحتمالات الممكنة وتوقع الأفضل منها.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'معنى (نسف) في قوله «نسف الطموحات»:', '["هدم", "وقع", "أهمل", "أجّل"]'::jsonb, 0, 'النسف هو الهدم والإزالة من الأساس، ومنه نسف البناء إذا هدمه بالكامل.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81605-0005-4a05-b005-c0ffee000005', 'التفاؤل ليس دعوة لإنكار الواقع بتجاهل المخاطر، ولا بنسف الطموحات والاحتمالات، ولكنه حسن الظن بالله، والوعي والنظر في الاحتمالات الممكنة وتوقع الأفضل منها.', 4, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'الفكرة التي لم ترد في القطعة:', '["التفاؤل هو استبعاد الحلول المستحيلة", "تجاهل الأخطار خطأ", "نسف الاحتمالات أمر مرفوض", "حسن الظن بالله أساس التفاؤل"]'::jsonb, 0, 'القطعة عرّفت التفاؤل بحسن الظن والنظر في الاحتمالات الممكنة، ولم تُعرّفه باستبعاد المستحيلة. أما بقية الأفكار فوردت نصاً أو نفياً صريحاً.', NULL, 'ad160816-2026-4c00-9d00-160820260001', 'e1a81605-0005-4a05-b005-c0ffee000005', 'التفاؤل ليس دعوة لإنكار الواقع بتجاهل المخاطر، ولا بنسف الطموحات والاحتمالات، ولكنه حسن الظن بالله، والوعي والنظر في الاحتمالات الممكنة وتوقع الأفضل منها.', 5, 'active', false);
END IF;
END
$mig$;

-- مزامنة العداد مع الواقع
UPDATE leak_groups
SET question_count = (SELECT COUNT(*) FROM questions WHERE leak_group_id = 'ad160816-2026-4c00-9d00-160820260001')
WHERE id = 'ad160816-2026-4c00-9d00-160820260001';

-- تحقق نهائي
DO $chk$
DECLARE n INT; nq INT; nv INT; np INT;
BEGIN
  SELECT COUNT(*) INTO n FROM questions WHERE leak_group_id = 'ad160816-2026-4c00-9d00-160820260001';
  SELECT COUNT(*) INTO nq FROM questions WHERE leak_group_id = 'ad160816-2026-4c00-9d00-160820260001' AND section = 'quant';
  SELECT COUNT(*) INTO nv FROM questions WHERE leak_group_id = 'ad160816-2026-4c00-9d00-160820260001' AND section = 'verbal';
  SELECT COUNT(*) INTO np FROM questions WHERE leak_group_id = 'ad160816-2026-4c00-9d00-160820260001' AND passage_id IS NOT NULL;
  RAISE NOTICE 'إجمالي: % — كمي: % — لفظي: % — قطع: %', n, nq, nv, np;
  IF n <> 85 THEN RAISE EXCEPTION 'عدد الأسئلة % لا يطابق المتوقع 85', n; END IF;
END
$chk$;

COMMIT;