-- 98: Day 5 morning (hamma) — batch 4: physics (16 questions, pages 73-96)

BEGIN;

INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'مصعد كتلته 70 كجم يصعد مسافة 20 متر خلال 10 ثوانٍ. ما أقل قدرة (بوحدة الواط) يجب أن يولّدها المحرّك؟ (استخدم g = 9.8 m/s²)', '["4.4 × 10³", "3.4 × 10³", "2.4 × 10³", "1.4 × 10³"]'::jsonb, 3, 'الشغل = mgh = 70 × 9.8 × 20 ≈ 13720 J. القدرة = W/t = 13720/10 ≈ 1372 W ≈ 1.4 × 10³ واط.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'الشخص A يرفع جسماً وزنه 5 N إلى ارتفاع 60 متراً، والشخص B يرفع جسماً وزنه 30 N إلى ارتفاع 10 أمتار. قارن بين شغلَيهما.', '["شغل A أكبر من شغل B", "شغل B أكبر من شغل A", "الشغلان متساويان", "لا يمكن المقارنة"]'::jsonb, 2, 'الشغل = القوة × المسافة. شغل A = 5 × 60 = 300 J. شغل B = 30 × 10 = 300 J. الشغلان متساويان.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'الفيزياء', 'اختيار من متعدد', 'من التطبيقات على مبدأ برنولّي:', '["الغوّاصة", "المكبس الهيدروليكي", "جناح الطائرة", "كرسي طبيب الأسنان"]'::jsonb, 2, 'مبدأ برنولّي: زيادة سرعة المائع تقابلها انخفاض ضغطه. جناح الطائرة مصمَّم بحيث الهواء يمرّ بسرعة أكبر فوقه فينخفض الضغط، ويبقى الضغط أعلى تحته، فيتولّد قوة رفع. الغوّاصة والمكبس يستخدمان مبدأ أرخميدس وباسكال.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'الفيزياء', 'اختيار من متعدد', 'بالإمكان إعادة صياغة قانون الديناميكا الحرارية الأول ليصبح ΔU يساوي..', '["Q − W", "Q/W", "Q + W", "Q × W"]'::jsonb, 0, 'قانون الديناميكا الحرارية الأول: التغير في الطاقة الداخلية ΔU = الحرارة المضافة Q − الشغل المبذول من النظام W. صياغة تحفظ الطاقة في الأنظمة الحرارية.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'طفل يقود دراجة، كتلتهما معاً 50 كجم وسرعتهما 3 m/s. أوجد طاقتهما الحركية بوحدة الجول.', '["150 J", "450 J", "75 J", "225 J"]'::jsonb, 3, 'الطاقة الحركية KE = ½ m v² = ½ × 50 × (3)² = ½ × 50 × 9 = 225 J.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'إذا كان أقصى عزم دوران يمكن أن يتحمّله ذراع شخصٍ هو 10 N·m، فما أقصر طول ذراع لازم له لرفع ثقل وزنه 50 N؟', '["0.1 m", "0.2 m", "0.15 m", "0.25 m"]'::jsonb, 1, 'العزم τ = القوة × طول الذراع. r = τ/F = 10/50 = 0.2 m.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'دائرة كهربائية ببطارية 24 V، وفرعان متوازيان: الأول مقاومتاه 4Ω و 4Ω على التوازي، والثاني مقاومتاه 2Ω و 2Ω على التوازي، والفرعان متّصلان على التوالي. ما شدة التيار الكلّي بوحدة الأمبير؟', '["8", "2", "4", "12"]'::jsonb, 0, 'المقاومتان المتوازيتان 4Ω || 4Ω = 2Ω. والمتوازيتان 2Ω || 2Ω = 1Ω. تجمعان على التوالي: R = 2 + 1 = 3Ω. التيار I = V/R = 24/3 = 8 أمبير.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'الصورة تمثّل طيفاً بخطوط ملوّنة منفصلة على خلفية مظلمة، ينتج من ذرّات في حالة مثارة. ما نوع هذا الطيف؟', '["طيف انبعاث", "طيف امتصاص", "خطوط فرنهوفر", "بخار غاز"]'::jsonb, 0, 'طيف الانبعاث (Emission Spectrum) ينتج عن انبعاث الذرات للضوء عند العودة من الحالة المثارة، فيظهر خطوط ضوئية ملوّنة منفصلة على خلفية مظلمة. طيف الامتصاص هو العكس (خطوط داكنة على خلفية ضوئية).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'إذا تحرك جسم وغيّر موقعه بمرور الزمن، فإنه..', '["ساكن ومن المؤكد أنه لا يتسارع", "ساكن ومن الممكن أنه يتسارع", "متحرّك ومن الممكن أنه يتسارع", "متحرّك ومن المؤكد أنه يتسارع"]'::jsonb, 2, 'تغيّر الموقع بمرور الزمن دليل على الحركة (سرعة ≠ 0). أمّا التسارع فيتطلّب تغيّر السرعة، فقد يتحرّك الجسم بسرعة ثابتة (تسارع = 0) أو بسرعة متغيّرة (تسارع ≠ 0).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'تتناسب الطاقة المنبعثة من الموجة الكهرومغناطيسية (إشعاع جسم أسود)..', '["عكسياً مع درجة الحرارة مرفوعة للقوة الرابعة", "طردياً مع الطول الموجي", "طردياً مع درجة الحرارة مرفوعة للقوة الرابعة", "عكسياً مع التردّد"]'::jsonb, 2, 'قانون شتيفان-بولتزمان: شدّة الإشعاع I = σ T⁴، حيث σ ثابت بولتزمان و T درجة الحرارة المطلقة. الطاقة المنبعثة تتناسب طردياً مع T⁴.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'عند اقتراب القطب الجنوبي (S) لمغناطيس من ملف يسري فيه تيار يدخل من اليمين، فإن الطرف المواجه للملف يصبح ذا قطب..', '["جنوبي ويحدث تنافر", "جنوبي ويحدث تجاذب", "شمالي ويحدث تنافر", "شمالي ويحدث تجاذب"]'::jsonb, 2, 'قانون لنز: التيار المستحَث يولّد مجالاً مغناطيسياً يعارض التغيّر المُسبِّب. اقتراب القطب S → الملف يولّد قطباً جنوبياً S للمعارضة → نتيجة: الطرفان متشابهان (S و S) → تنافر. وتفسير آخر: إذا فُسّر الاتجاه عكسياً، الملف يصير قطباً شمالياً N ليتنافر مع N الواصل.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'التفاعل الذي يتمّ داخل نواة الذرّة يُسمّى تفاعل..', '["كيميائي", "فيزيائي", "نووي", "حيوي"]'::jsonb, 2, 'التفاعل النووي يحدث داخل النواة (تشكّل/تحلّل/اندماج النوى) ويُطلق طاقة هائلة. التفاعل الكيميائي يحدث بين الإلكترونات الخارجية للذرّات. التفاعل الحيوي يحدث في الكائنات الحيّة.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'صندوق على أرض أفقية، تؤثّر فيه قوة F رأسياً للأسفل بالإضافة لوزنه mg. ما مقدار القوة العمودية (الرأسية) الإجمالية المؤثّرة عليه نحو الأسفل؟', '["F + mg", "F − mg", "mg − F", "F × mg"]'::jsonb, 0, 'القوّتان كلتاهما تتّجهان للأسفل: القوّة F المسلَّطة، والوزن mg. المحصّلة الرأسية = F + mg (تجمعان لأنهما بنفس الاتجاه).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'كتلة 4 كجم تتحرّك بسرعة 6 m/s. ما طاقتها الحركية بوحدة الجول؟', '["71", "72", "73", "74"]'::jsonb, 1, 'KE = ½ m v² = ½ × 4 × (6)² = ½ × 4 × 36 = 72 جول.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'رافعة تحمل جسماً كتلته 100 كجم باستخدام قوة دخل F = 200 N (g = 10 m/s²). ما مقدار الفائدة الميكانيكية لها؟', '["1", "3", "5", "7"]'::jsonb, 2, 'وزن الجسم (قوة الخرج) = mg = 100 × 10 = 1000 N. الفائدة الميكانيكية = قوة الخرج / قوة الدخل = 1000 / 200 = 5.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'جسم يدور في مسار دائري نصف قطره 40 سم بسرعة 2 m/s. أوجد تسارعه المركزي.', '["10 m/s²", "20 m/s²", "30 m/s²", "40 m/s²"]'::jsonb, 0, 'التسارع المركزي a = v²/r = (2)² / 0.4 = 4 / 0.4 = 10 m/s². (لاحظ تحويل 40 سم = 0.4 م).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);

COMMIT;
