-- 89: Day 5 evening (yelo) — batch 5: biology + biochemistry (23 questions)
-- Covers PDF pages 33-39. Completes the Sunday evening yelo source.

BEGIN;

INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'نبات', 'اختيار من متعدد', 'ما المشترك بين جميع أنواع الطحالب؟', '["بناء ضوئي", "بقعة عينية", "تعيش في مجموعات", "لديها أعضاء حقيقية"]'::jsonb, 0, 'كل الطحالب — وحيدة الخلية أو متعددة — تحوي يخضور (كلوروفيل) وتقوم بالبناء الضوئي. البقعة العينية موجودة في بعضها فقط (يوجلينا)، ولا تملك أعضاء حقيقية.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'بمَ تتميّز الزواحف عن بقية الفقاريات؟', '["وجود صفّين من الأسنان بالفك العلوي", "الجلد الحرشفي", "أحشاء داخلية", "بيض رخوي"]'::jsonb, 1, 'الجلد الحرشفي الجاف الكيراتيني علامة مميّزة للزواحف، يحميها من فقد الماء ويسمح لها بالعيش في البيئات الجافة. الطيور تطورت من الزواحف لكن جلدها مغطّى بريش، والأسماك بحراشف لينة مختلفة.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'أيّ التالي يُعدّ عاملاً لا حيوياً لشجرة في غابة؟', '["قرد يتنقّل بين أغصانها", "ضوء الشمس الذي يخترقها", "نملة تحمل حبّة قمح", "حلزون يزحف حولها"]'::jsonb, 1, 'العوامل اللاحيوية (Abiotic) هي العوامل الفيزيائية/الكيميائية غير الحيّة في النظام البيئي مثل الضوء والحرارة والماء والتربة. القرد والنملة والحلزون كائنات حيّة → عوامل حيوية.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'نبات', 'اختيار من متعدد', 'أيّ التراكيب التالية تستخدمها طحالب عشب البحر (Kelp) لتثبيت نفسها على سطح الماء؟', '["السويقة", "الشوكة", "الجذور", "المثانة الهوائية"]'::jsonb, 3, 'المثانات الهوائية (Air Bladders / Pneumatocysts) أكياس مملوءة بالغاز في طحالب الكلب تجعلها تطفو عمودياً نحو سطح الماء للوصول إلى ضوء الشمس للبناء الضوئي.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'علاقة بين كائنين، يستفيد منها أحدهما بينما يتضرّر الآخر، تسمّى..', '["تطفّل", "تقايض", "تنافس", "تعايش"]'::jsonb, 0, 'التطفّل (Parasitism): يستفيد الكائن المتطفّل ويتضرّر العائل. أمثلة: البعوض، الديدان المعوية. التقايض كلاهما يستفيد، التنافس كلاهما يتضرّر، التعايش أحدهما يستفيد والآخر لا يتأثّر.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'وراثة', 'اختيار من متعدد', 'عند تزاوج حيوان أسود اللون (BB) مع آخر أبيض (bb)، ظهر أفراد الجيل الأول كلهم باللون الرمادي. هذا المثال يمثّل حالة..', '["سيادة تامة", "سيادة مشتركة", "سيادة غير تامة", "تفوّق الجينات"]'::jsonb, 2, 'السيادة غير التامة (Incomplete Dominance): الأليلان معاً ينتجان مظهراً متوسطاً (رمادي = خليط بين الأسود والأبيض). في السيادة المشتركة (Codominance) يظهر اللونان معاً (بقع سوداء وبيضاء). في السيادة التامة يظهر اللون السائد فقط.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'انقسام خلوي', 'اختيار من متعدد', 'كلّما زادت الخلية حجماً مقارنة بمساحة سطحها، فإن ذلك يؤدّي إلى..', '["صعوبة حصولها على الغذاء", "سهولة التخلّص من الفضلات", "نموّها لتصبح كبيرة جداً", "المحافظة عليها بسهولة"]'::jsonb, 0, 'كلّما زاد حجم الخلية، تنخفض نسبة المساحة إلى الحجم (Surface area-to-volume ratio). فيصير السطح غير كافٍ لتبادل الغذاء والفضلات مع البيئة، فتنقسم الخلية أو تموت. هذا أحد أسباب الانقسام الخلوي.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'أيّ مما يلي يُعدّ من خصائص الألياف العضلية بطيئة الانقباض؟', '["داكنة اللون", "تحوي ميتوكوندريا أقل", "تقاوم الإعياء أقل", "فاتحة اللون"]'::jsonb, 0, 'الألياف بطيئة الانقباض (Type I / Slow-twitch) داكنة اللون لاحتوائها على كمية كبيرة من الميوغلوبين والميتوكوندريا، وتعتمد على التنفس الهوائي → تقاوم الإعياء طويلاً. مناسبة لرياضات التحمّل.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'أمراض ومناعة', 'اختيار من متعدد', 'أيّ التالي يساعد على نضج الخلايا التائية (T-cells) في جهاز المناعة؟', '["الطحال", "الغدّة الزعترية", "اللوزتان", "الغدّة الصنوبرية"]'::jsonb, 1, 'الغدّة الزعترية (Thymus) عضو ليمفاوي يقع خلف عظم القص، تتمايز فيها الخلايا التائية وتنضج لتصبح جزءاً من المناعة المكتسبة. الحرف T في T-cells يشير لـ Thymus.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'أيّ التالي يُعتبر كودون البدء (Start Codon) في عملية ترجمة البروتين؟', '["AUG", "UGA", "UAA", "UAG"]'::jsonb, 0, 'AUG هو كودون البدء العالمي، يشفّر الحمض الأميني الميثيونين، ويعطي إشارة بدء الترجمة في الريبوسوم. UGA و UAA و UAG كودونات توقّف لا تشفّر أي حمض أميني.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'المكافحة الحيوية (Biocontrol) تستخدم كائناً حيّاً للقضاء على كائنات أخرى ضارّة. هذه العلاقة يمكن أن تكون..', '["تطفّل أو تقايض", "تطفّل أو افتراس", "افتراس أو تنافس", "تعايش أو تنافس"]'::jsonb, 1, 'المكافحة الحيوية تعتمد على التطفّل (مثل دبور يضع بيوضه داخل اليرقات الضارّة) أو الافتراس (مثل الدعسوقة تأكل المنّ). كلاهما يضرّ الكائن المستهدف ويفيد الكائن المُكافِح.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'ما طبيعة العلاقة بين السمكة المهرّجة وشقائق النعمان البحرية؟', '["افتراس", "تطفّل", "تقايض", "تعايش"]'::jsonb, 2, 'التقايض (Mutualism): علاقة كلاهما يستفيد. السمكة المهرّجة تجد مأوى آمناً بين لوامس شقائق النعمان السامّة (محصّنة بمخاط)، وشقائق النعمان تستفيد من بقايا غذاء السمكة وتنظيفها.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'تشير الأبحاث إلى أن الخلايا الجذعية تعالج العديد من الأمراض والتشوّهات الوراثية، لأنها..', '["خلايا متخصّصة تحل محل أعضاء", "خلايا غير متخصّصة يمكن توجيهها لتصبح أي نوع من الخلايا", "خلايا متخصصة تحلّ محل الخلايا التالفة", "خلايا تنتج مضادات حيوية طبيعية"]'::jsonb, 1, 'الخلايا الجذعية (Stem Cells) غير متخصّصة، يمكن توجيهها لتمايز لأنواع متعدّدة من الخلايا (عصبية، عضلية، دموية...). هذه الخاصية تجعلها أداة قوية في الطب التجديدي وعلاج الأمراض المزمنة.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'عند تشريح حيوان فقاري وُجدت عضلة تفصل التجويف الصدري عن التجويف البطني. إلى أي طائفة ينتمي؟', '["الأسماك", "الطيور", "الثدييات", "الزواحف"]'::jsonb, 2, 'الحجاب الحاجز (Diaphragm) عضلة مميّزة للثدييات فقط، تفصل التجويف الصدري عن البطني وتلعب دوراً أساسياً في عملية التنفّس (تنقبض → دخول الهواء، تنبسط → خروجه).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'الهرمون المسؤول عن انقباض عضلة الرحم الملساء أثناء الولادة..', '["التيروكسين", "الأوكسيتوسين", "الكورتيزول", "الكالسيتونين"]'::jsonb, 1, 'الأوكسيتوسين (Oxytocin) هرمون يفرز من الغدة النخامية الخلفية، يحفّز انقباض عضلات الرحم أثناء الولادة، كما يحفّز إدرار الحليب أثناء الرضاعة.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'بروتين يسرّع نسخ الجين في حقيقيات النوى..', '["المنشّط", "المثبّط", "الحلقي", "المرشّح"]'::jsonb, 0, 'البروتينات المنشّطة (Activators) ترتبط بمناطق المعزّز (Enhancer) على DNA وتساعد على تجميع آلية النسخ، مما يسرّع إنتاج mRNA من الجين المستهدف. المثبّطات (Repressors) تفعل العكس.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'ما الطلائعي الذي يشبه الحيوانات والنباتات في نفس الوقت؟', '["البراميسيوم", "اليوجلينا", "الإسبيروجيرا", "الأميبا"]'::jsonb, 1, 'اليوجلينا (Euglena) طلائعي فريد: تحوي بلاستيدات خضراء فتقوم بالبناء الضوئي مثل النباتات، وتتحرك بسوط طويل وتفترس عند غياب الضوء مثل الحيوانات.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'قد تصاب بيوض الضفادع بعدوى فطرية بسبب تعرّضها لـ..', '["الأشعة فوق البنفسجية", "التيروكسين", "الأشعة السينية", "الأشعة تحت الحمراء"]'::jsonb, 0, 'الأشعة فوق البنفسجية (UV) تضعف جدار بيوض الضفادع الجيلاتيني وتثبّط جهازها المناعي، فتصير أكثر عرضة للإصابة بفطر Saprolegnia. هذا أحد عوامل تراجع أعداد البرمائيات عالمياً.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'أمراض ومناعة', 'اختيار من متعدد', 'أيّ التالي يُعدّ مناعة إيجابية (Active Immunity)؟', '["حقن أجسام مضادّة لسموم العقرب", "حقن أجسام مضادّة لسموم الأفاعي", "انتقال الأجسام المضادّة من الأم إلى الجنين", "حقن الجسم بمضادّات ضد المرض (التطعيم)"]'::jsonb, 3, 'المناعة الإيجابية (Active): الجسم نفسه ينتج الأجسام المضادّة بعد تعرضه لمستضدّ (طبيعياً أو عبر تطعيم بفايروس مضعّف). المناعة السلبية (Passive): استقبال أجسام مضادّة جاهزة (من الأم أو حقنها).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'سلوك', 'اختيار من متعدد', 'من السلوكيات التي تُعدّ مثالاً على استخدام الفيرومونات (Pheromones)؟', '["عواء الذئب", "تجميع أزهار في مكان معيّن", "جمع الغذاء وتخزينه", "وضع الفهد رائحة على الأشجار"]'::jsonb, 3, 'الفيرومونات مواد كيميائية تفرزها الحيوانات للتواصل مع أبناء نوعها (تحديد منطقة، جذب الجنس الآخر، إنذار). علامات الرائحة (Scent Marking) لدى الفهود والكلاب مثال كلاسيكي.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'عند تشريح أحد الزواحف لوحظ أنه لا يمتلك أسناناً. إلى أيّ رتبة ينتمي؟', '["الحرشفيات", "التمساحيات", "السلحفيات", "خطميات الرأس"]'::jsonb, 2, 'السلاحف (Testudines) وحدها من الزواحف لا تمتلك أسناناً — تستخدم منقاراً قرنياً (Beak) صلباً لتقطيع الطعام. الحرشفيات (ثعابين، سحالي) والتمساحيات لها أسنان.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'أيّ التالي خطأ بخصوص الهرمونات؟', '["تحويل الجلايكوجين لجلوكوز عن طريق الجلوكاجون", "زيادة معدل الأيض عن طريق الثيروكسين", "خفض الكالسيوم عن طريق الألدوستيرون", "زيادة معدّل الأيض عن طريق الأدرينالين"]'::jsonb, 2, 'الألدوستيرون يُنظِّم مستوى الصوديوم والبوتاسيوم (وليس الكالسيوم) في الكلى. الكالسيوم يُنظَّم بالكالسيتونين (يخفضه) والباراثرمون (يرفعه). باقي العبارات صحيحة.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'نبات', 'اختيار من متعدد', 'من الفطريات الاقترانية (Zygomycota)..', '["عفن الخبز", "الخميرة", "عيش الغراب", "الفطر النجمي"]'::jsonb, 0, 'عفن الخبز (Rhizopus) من شعبة الفطريات الاقترانية، يتكاثر جنسياً عبر التحام الخيوط لتكوّن أبواغ كيسية (Zygospores). الخميرة كيسية، وعيش الغراب من الفطريات الدعامية.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);

COMMIT;
