-- ═══════════════════════════════════════════════════════════════
-- تسريبات القدرات – الاثنين ٢٤ أغسطس ٢٠٢٦
-- 77 سؤالاً: كمي 26 + لفظي 51 (منها 21 في قطع استيعاب)
-- آمن لإعادة التشغيل: guard على وجود أسئلة المجموعة
-- ═══════════════════════════════════════════════════════════════
BEGIN;

INSERT INTO leak_groups (id, title, leak_date, section, question_count, description, is_active, accent_color)
VALUES ('ad240826-2026-4c00-9d00-240820260001', 'تسريبات القدرات – الاثنين ٢٤ أغسطس ٢٠٢٦', '2026-08-24', 'mixed', 77, 'أسئلة اختبار القدرات المحوسب ليوم الاثنين ٢٤ أغسطس ٢٠٢٦ (١٢ ربيع الأول ١٤٤٨) — القسمان الكمي واللفظي مع الشروح.', true, '#5B21B6')
ON CONFLICT (id) DO NOTHING;

DO $mig$
BEGIN
IF EXISTS (SELECT 1 FROM questions WHERE leak_group_id = 'ad240826-2026-4c00-9d00-240820260001') THEN
  RAISE NOTICE 'أسئلة المجموعة موجودة مسبقاً — تخطي الإدراج';
ELSE
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: مستطيل محيطه = ٢٠ ومساحته = ٢٤، وجميع الدوائر متطابقة. أوجد طول قطر الدائرة.', '["١", "٢", "٣", "٤"]'::jsonb, 1, 'نبحث عن بعدين مجموعهما ١٠ (نصف المحيط) وحاصل ضربهما ٢٤، فهما ٦ و٤. تصطف الدوائر الست في صفين وكل صف ثلاث دوائر، فقطر الدائرة = ٦ ÷ ٣ = ٢، ويؤكده الارتفاع: ٤ ÷ ٢ = ٢.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug24_q01_rect_circles.png', 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'استعار طالب من صديقه ٦ كتب واستعار من مكتبة الحي ٤ كتب، فأصبح في مكتبته ٢٨ كتابًا. كم كان عدد الكتب في مكتبته قبل الاستعارة؟', '["١٢", "١٦", "١٨", "٢٠"]'::jsonb, 2, 'الكتب المستعارة كلها دخيلة على مكتبته: ٦ + ٤ = ١٠ كتب. إذن الأصل = ٢٨ − ١٠ = ١٨ كتابًا.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'أحسب قيمة: ٤² × ٥³ × (١/٥) × (١/٢³)', '["١٠", "١٥", "٢٠", "٥/٢"]'::jsonb, 0, 'نحسب كل عامل: ٤² = ١٦ و٥³ = ١٢٥ و(١/٢³) = ١/٨. الناتج = ١٦ × ١٢٥ ÷ ٥ ÷ ٨ = ٢٠٠٠ ÷ ٢٠٠ = ١٠.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: أ جـ قطر في الدائرة، وكان أ ب = طول نصف قطر الدائرة، و ب جـ = ٥√٣. أوجد طول أ ب.', '["٥√٢", "٥", "١٠", "٥√٣"]'::jsonb, 1, 'المثلث أ ب جـ مرسوم على القطر أ جـ فزاويته عند ب قائمة. نفرض نصف القطر ر، فيكون أ ب = ر والقطر أ جـ = ٢ر. بفيثاغورس: ر² + (٥√٣)² = (٢ر)²، أي ر² + ٧٥ = ٤ر²، فنحصل على ٣ر² = ٧٥ ومنها ر = ٥. إذن أ ب = ٥.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug24_q04_circle_thales.png', 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ٩ − ٠٫٠٠٤٤
القيمة الثانية: ٩ − ٠٫٠٠٠٤٤', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, 'كلما صغر العدد المطروح من ٩ كبر الناتج. المطروح الأول ٠٫٠٠٤٤ أكبر من الثاني ٠٫٠٠٠٤٤، فالناتج الأول أصغر والقيمة الثانية أكبر.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', '(٩٩٩)² − ١ = .....', '["٩٩٩²", "٩٩٨²", "٩٩٨٠٠٠", "٩٩٩٠٠٠"]'::jsonb, 2, 'فرق بين مربعين: ٩٩٩² − ١² = (٩٩٩ − ١)(٩٩٩ + ١) = ٩٩٨ × ١٠٠٠ = ٩٩٨٠٠٠ بلا أي ضرب طويل.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ٨^١٠
القيمة الثانية: (٣⁴)^٥', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, 'نوحد الصورة: ٨^١٠ = (٢³)^١٠ = ٢^٣٠، وهي قرابة المليار. أما (٣⁴)^٥ = ٣^٢٠ = (٣^١٠)² = ٥٩٠٤٩² أي نحو ٣٫٥ مليار. القيمة الثانية أكبر.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'إذا كان طول ضلع المربع = ٢٠ سم، احسب مساحة الجزء المظلل.', '["١٥٧", "٣١٤", "٦٢٨", "٤٠٠"]'::jsonb, 2, 'نصف قطر كل دائرة = نصف ضلع المربع = ١٠. المظلل يجمع: دائرتين كاملتين إلا ربعيهما الداخلين في المربع (٣/٤ + ٣/٤) مع ربعي الدائرتين الأخريين داخل المربع (١/٤ + ١/٤)، والمجموع دائرتان كاملتان = ٢ × ٣٫١٤ × ١٠٠ = ٦٢٨ سم².', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug24_q08_square_4circles.png', 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'ما مجموع أرقام العدد ٩٩٩² ؟', '["٧٢", "١٨", "٢٧", "٥٤"]'::jsonb, 2, '٩٩٩² = ٩٩٩ × ٩٩٩ = ٩٩٨٠٠١، ومجموع أرقامه: ٩ + ٩ + ٨ + ٠ + ٠ + ١ = ٢٧.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: مثلث قائم الزاوية في جـ، وقياس زاويته عند أ = ٦٠°، و ب جـ = ٤√٣ سم. ما طول أ ب؟', '["٤", "٦", "٨", "٨√٣"]'::jsonb, 2, 'الضلع ب جـ يقابل الزاوية ٦٠°، والوتر أ ب يقابل القائمة. جا ٦٠ = ب جـ ÷ أ ب، أي (√٣/٢) = ٤√٣ ÷ أ ب، فيكون أ ب = ٤√٣ × ٢ ÷ √٣ = ٨ سم.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug24_q11_right_60.png', 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'ما عدد المئات في العدد ٧٩٦٣٥؟', '["٧٩٦", "٩٦", "٦٣", "٦"]'::jsonb, 0, 'المطلوب كم مئة كاملة في العدد كله وليس رقم خانة المئات: ٧٩٦٣٥ ÷ ١٠٠ = ٧٩٦٫٣٥، فعدد المئات ٧٩٦. أما الرقم ٦ فهو رقم خانة المئات فقط.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'يبين القطاع الدائري توزيع أنواع النفايات، فإذا تضاعفت النفايات المعدنية على حساب النفايات الورقية، كم تصبح نسبة النفايات الورقية؟', '["١٥٪", "٢٠٪", "٢٥٪", "٣٠٪"]'::jsonb, 1, 'المعدنية ١٥٪ وستتضاعف إلى ٣٠٪، أي إنها ستأخذ ١٥٪ إضافية من الورقية. الورقية ٣٥٪ فتصبح ٣٥ − ١٥ = ٢٠٪.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug24_q13_waste_pie.png', 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'سيارتان تسيران عكس الاتجاه من نفس النقطة، الأولى بسرعة س كم/س والثانية بسرعة ص كم/س. ما العلاقة التي تمثل المسافة بينهما بعد ساعة؟', '["ص × س", "ص ÷ س", "ص − س", "ص + س"]'::jsonb, 3, 'لأنهما تتحركان في اتجاهين متعاكسين تتباعدان بمجموع السرعتين، فبعد ساعة واحدة تكون المسافة = س + ص كيلومترًا.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'كم تساوي ٤ هللات بالريال؟', '["٠٫٤", "٠٫٠٤", "٠٫٠٠٤", "٠٫٠٠٠٤"]'::jsonb, 1, 'الريال = ١٠٠ هللة، فالهللة = ٠٫٠١ ريال، و٤ هللات = ٤ ÷ ١٠٠ = ٠٫٠٤ ريال.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: عدد الدقائق من الساعة ٩:١٢ مساءً إلى الساعة ٩:٠٢ مساء اليوم التالي
القيمة الثانية: ١٤٩٠ دقيقة', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, 'اليوم الكامل من ٩:١٢ إلى ٩:١٢ في اليوم التالي = ١٤٤٠ دقيقة، و٩:٠٢ تسبقها بعشر دقائق، فالمدة = ١٤٣٠ دقيقة، وهي أقل من ١٤٩٠.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'طالب أعار أصدقاءه ٦ كتب، وقام باستعارة ٤ كتب من مكتبة الحي، فأصبح معه ٢٨ كتابًا. كم كان عدد الكتب معه؟', '["٢٤", "٣٠", "٣٢", "٣٦"]'::jsonb, 1, 'نرجع بالعمليات عكسيًا: نعيد الكتب الستة المعارة (+٦) ونرد الأربعة المستعارة (−٤): ٢٨ + ٦ − ٤ = ٣٠ كتابًا.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: أكبر عدد أولي من ٥٠ إلى ٦٤
القيمة الثانية: ٦٣', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, 'نفحص الأعداد من ٦٤ نزولًا: ٦٤ و٦٣ و٦٢ ليست أولية (٦٣ = ٧ × ٩)، و٦١ أولي. فالقيمة الأولى ٦١ وهي أصغر من ٦٣.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'الشكل المجاور مكون من ٧ مربعات متطابقة، ومساحة المربع الواحد = ١٦ م². أوجد محيط الشكل.', '["١٦", "٣٢", "٦٤", "١١٢"]'::jsonb, 2, 'ضلع المربع = √١٦ = ٤ م. بتتبع حدود الشكل الخارجية نعد ١٦ ضلعًا مكشوفًا، فالمحيط = ١٦ × ٤ = ٦٤ م.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug24_q19_seven_squares.png', 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ٣٦٠ ÷ ٠٫٤
القيمة الثانية: (١٦ − ٧)(١٦ − ٦)(٢٦ − ١٦)', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 2, 'الأولى: ٣٦٠ ÷ ٠٫٤ = ٣٦٠٠ ÷ ٤ = ٩٠٠. الثانية: ٩ × ١٠ × ١٠ = ٩٠٠. القيمتان متساويتان.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: ب جـ قطر في الدائرة، أ ب = ٨ و أ جـ = ٦. ما طول نصف قطر الدائرة؟', '["٣", "٤", "٥", "٦"]'::jsonb, 2, 'المثلث المرسوم على القطر قائم عند أ، فالقطر ب جـ هو الوتر: ب جـ = √(٨² + ٦²) = √١٠٠ = ١٠، ونصف القطر = ٥.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug24_q22_circle_68.png', 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'وُزعت ٦٤ طابعة و٤٨ حاسبة على أكبر عدد ممكن من الغرف، بحيث يتساوى نصيب كل غرفة من الطابعات ويتساوى نصيبها من الحاسبات. ما أكبر عدد من الغرف؟', '["٨", "١٢", "١٦", "٢٤"]'::jsonb, 2, 'أكبر عدد غرف يقسم ٦٤ و٤٨ معًا هو القاسم المشترك الأكبر: ٦٤ = ٢⁶ و٤٨ = ٢⁴ × ٣، فالقاسم المشترك الأكبر = ٢⁴ = ١٦ غرفة، ولكل غرفة ٤ طابعات و٣ حاسبات.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'احسب قيمة: (−١)² + (−١)³ + (−١)⁴ + (−١)⁵ + (−١)⁶ + (−١)⁷ + (−١)⁸', '["صفر", "−١", "١", "٢"]'::jsonb, 2, 'قوى العدد −١ تتناوب: الأسس الزوجية (٢، ٤، ٦، ٨) تعطي +١ أربع مرات، والفردية (٣، ٥، ٧) تعطي −١ ثلاث مرات. المجموع = ٤ − ٣ = ١.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: ب أ قطر في الدائرة، وقياس الزاوية عند ب = ٥٠°. أوجد قياس زاوية ب أ جـ.', '["٢٠", "٤٠", "٦٠", "٨٠"]'::jsonb, 1, 'الزاوية عند جـ مرسومة على القطر ب أ فهي قائمة = ٩٠°. في المثلث أ ب جـ: زاوية ب أ جـ = ١٨٠ − ٩٠ − ٥٠ = ٤٠°.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug24_q25_circle_50.png', 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ٣ أيام
القيمة الثانية: ٤٨ ساعة', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, '٣ أيام = ٣ × ٢٤ = ٧٢ ساعة، وهي أكبر من ٤٨ ساعة.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'مثلث قائم الزاوية طولا ضلعي القائمة فيه ٣ سم و٤ سم. احسب طول محيط المثلث.', '["٨", "١٠", "١٢", "١٤"]'::jsonb, 2, 'الوتر = √(٣² + ٤²) = √٢٥ = ٥ سم، فالمحيط = ٣ + ٤ + ٥ = ١٢ سم.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug24_q27_right_34.png', 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: المثلث أ ب جـ قائم الزاوية في أ، و أ جـ = ٤ سم و أ ب = ٥ سم، و هـ منتصف أ جـ، والقطعة هـ د عمودية على أ جـ حيث د على جـ ب. أوجد طول د هـ.', '["١٫٥", "٢", "٢٫٥", "٣"]'::jsonb, 2, 'بما أن أ ب عمودية على أ جـ و هـ د عمودية على أ جـ أيضًا، فإن هـ د توازي أ ب. و هـ منتصف أ جـ، فتكون د منتصف جـ ب و هـ د قطعة متوسطة طولها نصف أ ب = ٥ ÷ ٢ = ٢٫٥ سم.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug24_q28_midsegment.png', 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'عقل : تفكير', '["لسان : ذوق", "أذن : استماع", "عين : إبصار", "قلب : حب"]'::jsonb, 3, 'العقل يقوم بالتفكير وهي وظيفة معنوية غير حسية، ومثله القلب الذي يُنسب إليه الحب. أما بقية الخيارات فأعضاء مع حواس مادية.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'غيث : قطرة', '["عيش : لقمة", "رشفة : ماء", "شرار : نار", "أدب : ثقافة"]'::jsonb, 0, 'الغيث يتكون من قطرات، والعيش (الخبز) يؤكل لقمة لقمة؛ فالعلاقة كلٌّ وجزؤه الصغير، والاتجاه محفوظ. أما رشفة : ماء فمعكوسة الترتيب.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'شجرة : غصن', '["جد : حفيد", "بحر : سفينة", "كتاب : قلم", "جبل : سهل"]'::jsonb, 0, 'الغصن يتفرع من الشجرة كما يتفرع الحفيد من الجد؛ علاقة أصل وفرع منه.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'بازلاء : فول', '["سيف : رمح", "عدس : كمون", "باذنجان : كرز", "موز : فاكهة"]'::jsonb, 0, 'البازلاء والفول صنفان من فصيلة واحدة (البقوليات)، والسيف والرمح كلاهما سلاح. أما عدس : كمون فبقل مع تابل، وموز : فاكهة نوع مع جنسه.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'طَود : جبل', '["سحب : غيم", "النجوم : السماء", "عالٍ : منخفض", "عميق : واسع"]'::jsonb, 0, 'الطود هو الجبل العظيم فالعلاقة ترادف، ومثلها السحب والغيم.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'رائحة : شم', '["خشونة : لمس", "طعم : لسان", "سمع : أذن", "قرب : بعد"]'::jsonb, 0, 'الرائحة صفة تُدرك بحاسة الشم، والخشونة صفة تُدرك بحاسة اللمس. أما طعم : لسان وسمع : أذن فمع العضو لا الحاسة.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'قمة : سفح', '["سافر : مقنع", "سفر : سائح", "حارس : خفير", "ممر : نافذ"]'::jsonb, 0, 'القمة أعلى الجبل والسفح أسفله فالعلاقة تضاد، ومثلها السافر (مكشوف الوجه) والمقنع (مغطاه). أما حارس : خفير وممر : نافذ فمترادفان.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'من يجد أن القدوة لا ....... فإنه لن يجد من ....... به.', '["يخطئ – يقتدي", "يصيب – يهتدي", "ينجح – يتأثر", "يتقن – يلتزم"]'::jsonb, 0, 'من يشترط في القدوة ألا يخطئ أبدًا يطلب كمالًا لا يوجد في البشر، فلن يجد أحدًا يقتدي به. المعنى يستقيم بالفعلين: يخطئ – يقتدي.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'ما أجمل أن يحتوي حديثك على رقة ....... ودقة .......', '["الأسلوب – المحتوى", "الحديث – الغضب", "الصوت – الملل", "الكلام – التسرع"]'::jsonb, 0, 'الرقة تناسب الأسلوب والدقة تناسب المحتوى، فيكتمل المدح لجانبي الحديث: شكله ومضمونه.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'الثروة ....... كالسلحفاة و....... كالغزال.', '["تقوى – تضعف", "تأتي – تفر", "تنمو – تثبت", "تظل – تهرم"]'::jsonb, 1, 'التشبيهان مبنيان على السرعة: تأتي الثروة ببطء كمشية السلحفاة، وتفر بسرعة كعدْو الغزال.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'الحكيم قد ....... بالمصائب ....... منها الفوائد.', '["يفرح – ليقطف", "يحزن – ليترك", "يغضب – ليأخذ", "ييأس – ليجمع"]'::jsonb, 0, 'المفارقة مقصودة: الحكيم قد يفرح بالمصيبة لأنه يحسن قراءتها فيقطف منها الدروس والفوائد. بقية الأزواج ينقض أحد طرفيها الآخر.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'حلاوة ....... تكسب محبة الناس وتقلل عدد .......', '["الأخلاق – النفاق", "الأسلوب – النقاش", "الكلام – الصعاب", "المنطق – الأعداء"]'::jsonb, 3, 'حلاوة المنطق أي عذوبة الحديث تجلب المحبة، وما دام الناس يحبونك قلّ أعداؤك؛ فالزوج المتسق: المنطق – الأعداء.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'لا تخشَ آراء الآخرين، فهي ....... وليست .......', '["أفكارهم – واقعك", "أفعالهم – أفعالك", "خطأهم – خطأك", "آراؤهم – أفكارك"]'::jsonb, 0, 'آراء الناس تبقى أفكارًا في رؤوسهم، ولا تتحول إلى واقعك الذي تعيشه؛ لذلك لا تستحق الخشية.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'لا تكن ....... فيُستغنى عنك، ولا تكن ....... فيُستهان بك.', '["ثقيلًا – خفيفًا", "فقيرًا – غنيًا", "عزيزًا – جادًّا", "نبيلًا – عظيمًا"]'::jsonb, 0, 'الحكمة توصي بالاعتدال: الثقيل على الناس يستغنون عنه، والخفيف الذي لا وزن له يستهينون به.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'الحدس الصائب يكون ....... على التجربة وليس من ....... الذهن.', '["قائمًا – أوهام", "بعيدًا – وحي", "شاردًا – خيال", "متصلًا – أوهام"]'::jsonb, 0, 'الحدس الموفق يستند إلى خبرة وتجربة سابقة، ولا يصدر عن أوهام يصنعها الذهن؛ فالزوج المستقيم: قائمًا – أوهام.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«المروءة مانعة من الكذب باعثة على التملق؛ لأنها تمنع من فعل ما كان مستكرهًا، فأولى أن تمنع من فعل ما كان مستقبحًا»', '["المروءة", "مانعة", "الكذب", "التملق"]'::jsonb, 3, 'المروءة تمنع الرذائل وتبعث على الفضائل، فلا يستقيم أن تبعث على التملق وهو خلق مذموم؛ والصواب أنها باعثة على الصدق.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«الرياح الملبدة بالغيوم توحي بهطول الأمطار»', '["الرياح", "الغيوم", "توحي", "هطول"]'::jsonb, 0, 'التلبد بالغيوم وصف للسماء لا للرياح؛ فالصواب: السماء الملبدة بالغيوم توحي بهطول الأمطار.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«عندما ينظر المرء إلى الغير بطريقة إيجابية يساعد الإنسان في مواجهة تحديات الحياة النفسية»', '["الغير", "النفسية", "إيجابية", "تحديات"]'::jsonb, 0, 'النظرة الإيجابية التي تعين على مواجهة التحديات هي النظرة إلى الحياة نفسها لا إلى الغير؛ فالكلمة الأنسب مكان «الغير» هي «الحياة».', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«استبسل الجنود في المعركة فانتصر الأعداء بيسر وسهولة»', '["استبسل", "المعركة", "بيسر", "سهولة"]'::jsonb, 0, 'الاستبسال يعني القتال بشجاعة منقطعة النظير، وهو لا يؤدي إلى انتصار الأعداء بسهولة؛ فالمناسب للسياق: تخاذل الجنود.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«من عيوب المحادثة أن يتضمر المرء الجواب قبل أن ينتهي السائل من كلامه»', '["عيوب", "يتضمر", "ينتهي", "السائل"]'::jsonb, 1, 'العيب المقصود هو انشغال المستمع بتجهيز رده قبل اكتمال كلام محدثه، والفعل السليم لهذا المعنى «يُعِدّ»؛ أما «يتضمر» فصيغة لا تستقيم في السياق.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«غناك في نفسك وقيمتك في ذاتك، فلا تبحث عنهما في فؤادك»', '["غناك", "نفسك", "قيمتك", "فؤادك"]'::jsonb, 3, 'صدر الجملة يقرر أن الغنى والقيمة في داخلك، فالنهي لا بد أن ينصبّ على طلبهما عند الآخرين؛ والصواب: فلا تبحث عنهما عند غيرك.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«استمع لنصيحة الشباب، فإن فقدوا حدة الذكاء فقد خاضوا التجارب وعاركتهم الحياة»', '["الشباب", "الذكاء", "عاركتهم", "التجارب"]'::jsonb, 0, 'من خاض التجارب وعاركته الحياة وقلّت حدة ذكائه مع العمر هم الشيوخ لا الشباب؛ فالكلمة الصحيحة: نصيحة الشيوخ.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["مطرقة", "مقص", "منشار", "مسمار"]'::jsonb, 1, 'المطرقة والمنشار والمسمار من عدة النجار وأعمال الخشب، أما المقص فأداة قص القماش والورق.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["ابتسامة", "عبوس", "بشاشة", "صراخ"]'::jsonb, 3, 'الابتسامة والعبوس والبشاشة تعبيرات تظهر على الوجه، أما الصراخ فصوت.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["يخت", "قارب", "غواصة", "سفينة"]'::jsonb, 2, 'اليخت والقارب والسفينة تسير على سطح الماء، أما الغواصة فتسير في أعماقه.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["هرم", "غار", "كوخ", "خيمة"]'::jsonb, 0, 'الغار والكوخ والخيمة مساكن يأوي إليها الإنسان، أما الهرم فبناء جنائزي ضخم وليس مسكنًا.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["نهض", "وقع", "جلس", "سجد"]'::jsonb, 1, 'النهوض والجلوس والسجود حركات يفعلها الإنسان بإرادته، أما الوقوع فيحدث دون قصد.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["حصن", "سياج", "سور", "جدار"]'::jsonb, 0, 'السياج والسور والجدار حواجز تحيط بالمكان، أما الحصن فبناء متكامل يُتحصن به.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["صُم", "قُم", "نَم", "تَم"]'::jsonb, 3, 'صم وقم ونم أفعال أمر، أما تم فهو فعل ماضٍ بمعنى اكتمل.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["ذات", "نفس", "كيان", "الاقتداء"]'::jsonb, 3, 'الذات والنفس والكيان ألفاظ مترادفة تدل على حقيقة الشيء، أما الاقتداء فمعناه اتباع الغير.', NULL, 'ad240826-2026-4c00-9d00-240820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'ما أهم الصفات التي يجب أن يتصف بها المسعف؟', '["السرعة البديهية في اتخاذ القرار", "القوة البدنية العالية", "معرفة أسماء الأدوية كاملة", "تهدئة المصاب فقط"]'::jsonb, 0, 'النص ينص على أن أهم صفات المسعف سرعته في التعامل الجيد مع الحالة واتخاذ القرار المناسب في وقته.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82401-2026-4c00-9d00-000000000001', 'يتوقف على طريقة تعامل المسعف مع المصاب الكثير من العوامل، ومن أهم الصفات التي يجب أن يتصف بها المسعف سرعته في التعامل الجيد مع الحالة واتخاذ القرار المناسب في التوقيت المناسب.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'ما معنى كلمة (عصب) الواردة في الفقرة الثانية؟', '["محور", "أغلبية", "عصابة", "منشأ"]'::jsonb, 0, 'عصب الاقتصاد أي محوره الذي يقوم عليه؛ فالزراعة هي قوام الاقتصاد الكيني.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82402-2026-4c00-9d00-000000000002', '١- تقع جمهورية كينيا في القسم الشرقي من القارة الأفريقية، وحدودها مرتبطة مع كثير من الدول الأفريقية؛ فالمحيط الهندي يحدها من الجهة الشرقية، وأوغندا من الجهة الغربية، وتنزانيا من الجهة الجنوبية، وأثيوبيا والسودان من الجهة الشمالية، أما من الجهة الشمالية الشرقية فتحدها الصومال.
٢- وتنقسم أراضيها إلى قسمين: ساحلية ومرتفعة، ويعيش سكانها ضمن ٨٪ من مساحتها فقط، والباقي واحات ومساحات شاسعة تعيش فيها حيوانات نادرة. فالمنطقة الساحلية شريط ضيق لكن تربته خصبة في معظم أجزائها خاصة في الجنوب، ويعيش نحو ٧٥٪ من سكان كينيا في الأراضي المرتفعة وتقع فيها نيروبي أكبر مدينة في كينيا، ويعمل أغلب سكانها في الزراعة التي تعد عصب الاقتصاد الكيني، ويتكلم أكثر السكان اللغة الساحلية إلا أن المتعلمين منهم يتحدثون الإنجليزية وهي اللغة المعتمدة في البلاد.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', '(إلا أن) الواردة في الفقرة الثانية يمكن استبدالها بـ:', '["غير أن", "حيث أن", "مع أن", "رغم أن"]'::jsonb, 0, '«إلا أن» أداة استدراك، وأقرب البدائل أداء لهذا المعنى في الموضع نفسه هي «غير أن».', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82402-2026-4c00-9d00-000000000002', '١- تقع جمهورية كينيا في القسم الشرقي من القارة الأفريقية، وحدودها مرتبطة مع كثير من الدول الأفريقية؛ فالمحيط الهندي يحدها من الجهة الشرقية، وأوغندا من الجهة الغربية، وتنزانيا من الجهة الجنوبية، وأثيوبيا والسودان من الجهة الشمالية، أما من الجهة الشمالية الشرقية فتحدها الصومال.
٢- وتنقسم أراضيها إلى قسمين: ساحلية ومرتفعة، ويعيش سكانها ضمن ٨٪ من مساحتها فقط، والباقي واحات ومساحات شاسعة تعيش فيها حيوانات نادرة. فالمنطقة الساحلية شريط ضيق لكن تربته خصبة في معظم أجزائها خاصة في الجنوب، ويعيش نحو ٧٥٪ من سكان كينيا في الأراضي المرتفعة وتقع فيها نيروبي أكبر مدينة في كينيا، ويعمل أغلب سكانها في الزراعة التي تعد عصب الاقتصاد الكيني، ويتكلم أكثر السكان اللغة الساحلية إلا أن المتعلمين منهم يتحدثون الإنجليزية وهي اللغة المعتمدة في البلاد.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'أي الآتي صحيح حسب الفقرة الثانية؟', '["أغلب النشاط الزراعي في الأراضي المرتفعة", "٧٥٪ من سكان كينيا يعملون في الزراعة", "التربة الخصبة لا تتوفر إلا في المناطق المرتفعة", "ربع مساحة كينيا صالح للزراعة"]'::jsonb, 0, 'النص يذكر أن أغلب سكان المرتفعات يعملون بالزراعة وأنها عصب الاقتصاد، فأغلب النشاط الزراعي هناك. أما نسبة ٧٥٪ فهي نسبة من يسكنون المرتفعات، وأغلبهم لا كلهم يعملون بالزراعة.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82402-2026-4c00-9d00-000000000002', '١- تقع جمهورية كينيا في القسم الشرقي من القارة الأفريقية، وحدودها مرتبطة مع كثير من الدول الأفريقية؛ فالمحيط الهندي يحدها من الجهة الشرقية، وأوغندا من الجهة الغربية، وتنزانيا من الجهة الجنوبية، وأثيوبيا والسودان من الجهة الشمالية، أما من الجهة الشمالية الشرقية فتحدها الصومال.
٢- وتنقسم أراضيها إلى قسمين: ساحلية ومرتفعة، ويعيش سكانها ضمن ٨٪ من مساحتها فقط، والباقي واحات ومساحات شاسعة تعيش فيها حيوانات نادرة. فالمنطقة الساحلية شريط ضيق لكن تربته خصبة في معظم أجزائها خاصة في الجنوب، ويعيش نحو ٧٥٪ من سكان كينيا في الأراضي المرتفعة وتقع فيها نيروبي أكبر مدينة في كينيا، ويعمل أغلب سكانها في الزراعة التي تعد عصب الاقتصاد الكيني، ويتكلم أكثر السكان اللغة الساحلية إلا أن المتعلمين منهم يتحدثون الإنجليزية وهي اللغة المعتمدة في البلاد.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يستفاد من الفقرة الثانية أن:', '["المناطق الساحلية لا تحتوي على تربة خصبة", "كل الكينيين يتحدثون اللغة الساحلية", "المتعلمين يتحدثون اللغة الإنجليزية", "الكينيين يزرعون الشاي"]'::jsonb, 2, 'النص صريح: أكثر السكان يتكلمون الساحلية إلا أن المتعلمين يتحدثون الإنجليزية وهي اللغة المعتمدة.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82402-2026-4c00-9d00-000000000002', '١- تقع جمهورية كينيا في القسم الشرقي من القارة الأفريقية، وحدودها مرتبطة مع كثير من الدول الأفريقية؛ فالمحيط الهندي يحدها من الجهة الشرقية، وأوغندا من الجهة الغربية، وتنزانيا من الجهة الجنوبية، وأثيوبيا والسودان من الجهة الشمالية، أما من الجهة الشمالية الشرقية فتحدها الصومال.
٢- وتنقسم أراضيها إلى قسمين: ساحلية ومرتفعة، ويعيش سكانها ضمن ٨٪ من مساحتها فقط، والباقي واحات ومساحات شاسعة تعيش فيها حيوانات نادرة. فالمنطقة الساحلية شريط ضيق لكن تربته خصبة في معظم أجزائها خاصة في الجنوب، ويعيش نحو ٧٥٪ من سكان كينيا في الأراضي المرتفعة وتقع فيها نيروبي أكبر مدينة في كينيا، ويعمل أغلب سكانها في الزراعة التي تعد عصب الاقتصاد الكيني، ويتكلم أكثر السكان اللغة الساحلية إلا أن المتعلمين منهم يتحدثون الإنجليزية وهي اللغة المعتمدة في البلاد.', 4, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'تقع كينيا في:', '["شمال أفريقيا غرب المحيط الهندي", "شمال أفريقيا شرق المحيط الهندي", "جنوب أفريقيا", "شرق أفريقيا غرب المحيط الهندي"]'::jsonb, 3, 'كينيا في القسم الشرقي من أفريقيا، والمحيط الهندي يحدها من الشرق أي أنها تقع غربه.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82402-2026-4c00-9d00-000000000002', '١- تقع جمهورية كينيا في القسم الشرقي من القارة الأفريقية، وحدودها مرتبطة مع كثير من الدول الأفريقية؛ فالمحيط الهندي يحدها من الجهة الشرقية، وأوغندا من الجهة الغربية، وتنزانيا من الجهة الجنوبية، وأثيوبيا والسودان من الجهة الشمالية، أما من الجهة الشمالية الشرقية فتحدها الصومال.
٢- وتنقسم أراضيها إلى قسمين: ساحلية ومرتفعة، ويعيش سكانها ضمن ٨٪ من مساحتها فقط، والباقي واحات ومساحات شاسعة تعيش فيها حيوانات نادرة. فالمنطقة الساحلية شريط ضيق لكن تربته خصبة في معظم أجزائها خاصة في الجنوب، ويعيش نحو ٧٥٪ من سكان كينيا في الأراضي المرتفعة وتقع فيها نيروبي أكبر مدينة في كينيا، ويعمل أغلب سكانها في الزراعة التي تعد عصب الاقتصاد الكيني، ويتكلم أكثر السكان اللغة الساحلية إلا أن المتعلمين منهم يتحدثون الإنجليزية وهي اللغة المعتمدة في البلاد.', 5, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يمكن استبدال حرف (من) في النص بـ:', '["عن", "حتى", "إلى", "على"]'::jsonb, 0, 'المعنى: تمحي الحياء عن وجهه؛ فحرف الجر «عن» يؤدي المعنى نفسه في هذا الموضع.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82403-2026-4c00-9d00-000000000003', 'كثرة سؤال الرجل للناس تمحي الحياء من وجهه.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'المقصود بـ(السؤال) في سياق النص:', '["العلم", "المال", "العطاء", "الكرم"]'::jsonb, 1, 'سؤال الناس هنا هو طلب المال والحاجات منهم، وهو الذي يذهب ماء الوجه مع كثرته.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82403-2026-4c00-9d00-000000000003', 'كثرة سؤال الرجل للناس تمحي الحياء من وجهه.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'النص يحث على:', '["الحياء", "التعفف", "الكرم", "الصبر"]'::jsonb, 1, 'إذا كانت كثرة السؤال تمحي الحياء فالنص يدعو إلى تركها، أي إلى التعفف عما في أيدي الناس.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82403-2026-4c00-9d00-000000000003', 'كثرة سؤال الرجل للناس تمحي الحياء من وجهه.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'النوع الأول من داء السكري — كما يُفهم من القطعة — هو الذي يعتمد على:', '["الأنسولين", "الدهون", "السكر", "الرياضة"]'::jsonb, 0, 'وصف النص النوع الثاني بأنه غير المعتمد على الأنسولين، فيلزم أن النوع الأول هو المعتمد عليه.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82404-2026-4c00-9d00-000000000004', 'أوضح الباحثون أن النوع الثاني من داء السكري — وهو غير المعتمد على الأنسولين — يحدث بين الأطفال، وقد بلغ عشرة أضعاف ما كان عليه منذ عقد من الزمن، وينصح الأطباء بتقليل الدهون أو التخلص من الدهون المشبعة والدهون المهدرجة. النشاط البدني يقلل من احتمالية الإصابة بمرض السكري؛ فكلما زاد خمول الإنسان زادت نسبة احتمالية إصابته بالسكري. أصبح المجتمع في عصرنا الحالي يعتمد على الرفاهية والخمول مما أدى إلى ظهور مرض السكري، وهو مرض وبائي في المجتمع.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يُفهم من النص أن إصابات السكري عند الأطفال في:', '["تنامٍ", "تراجع", "ثبات", "اختفاء"]'::jsonb, 0, 'النص يذكر أن النوع الثاني بين الأطفال بلغ عشرة أضعاف ما كان عليه قبل عقد، وهذا تنامٍ واضح.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82404-2026-4c00-9d00-000000000004', 'أوضح الباحثون أن النوع الثاني من داء السكري — وهو غير المعتمد على الأنسولين — يحدث بين الأطفال، وقد بلغ عشرة أضعاف ما كان عليه منذ عقد من الزمن، وينصح الأطباء بتقليل الدهون أو التخلص من الدهون المشبعة والدهون المهدرجة. النشاط البدني يقلل من احتمالية الإصابة بمرض السكري؛ فكلما زاد خمول الإنسان زادت نسبة احتمالية إصابته بالسكري. أصبح المجتمع في عصرنا الحالي يعتمد على الرفاهية والخمول مما أدى إلى ظهور مرض السكري، وهو مرض وبائي في المجتمع.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'معنى كلمة (وبائي) في سياق النص:', '["معدٍ", "خطر", "قاتل", "منتشر"]'::jsonb, 3, 'وصف المرض بالوبائي هنا إشارة إلى سعة انتشاره في المجتمع، لا إلى العدوى بمعناها الطبي.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82404-2026-4c00-9d00-000000000004', 'أوضح الباحثون أن النوع الثاني من داء السكري — وهو غير المعتمد على الأنسولين — يحدث بين الأطفال، وقد بلغ عشرة أضعاف ما كان عليه منذ عقد من الزمن، وينصح الأطباء بتقليل الدهون أو التخلص من الدهون المشبعة والدهون المهدرجة. النشاط البدني يقلل من احتمالية الإصابة بمرض السكري؛ فكلما زاد خمول الإنسان زادت نسبة احتمالية إصابته بالسكري. أصبح المجتمع في عصرنا الحالي يعتمد على الرفاهية والخمول مما أدى إلى ظهور مرض السكري، وهو مرض وبائي في المجتمع.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'علاقة (داء السكري) بـ(زيادة الوزن عند الأطفال):', '["طردية", "عكسية", "تزامنية", "تماثلية"]'::jsonb, 0, 'النص يربط السكري بالدهون والخمول؛ فكلما زاد الوزن زاد احتمال الإصابة، وهذه علاقة طردية.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82404-2026-4c00-9d00-000000000004', 'أوضح الباحثون أن النوع الثاني من داء السكري — وهو غير المعتمد على الأنسولين — يحدث بين الأطفال، وقد بلغ عشرة أضعاف ما كان عليه منذ عقد من الزمن، وينصح الأطباء بتقليل الدهون أو التخلص من الدهون المشبعة والدهون المهدرجة. النشاط البدني يقلل من احتمالية الإصابة بمرض السكري؛ فكلما زاد خمول الإنسان زادت نسبة احتمالية إصابته بالسكري. أصبح المجتمع في عصرنا الحالي يعتمد على الرفاهية والخمول مما أدى إلى ظهور مرض السكري، وهو مرض وبائي في المجتمع.', 4, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'الفقرة الأخيرة تدل على:', '["النصح", "التعجب", "الاستفهام", "المدح"]'::jsonb, 0, 'الفقرة تحذر من الاعتماد على الرفاهية والخمول وما يقود إليه من مرض، وهذا أسلوب نصح وتحذير.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82404-2026-4c00-9d00-000000000004', 'أوضح الباحثون أن النوع الثاني من داء السكري — وهو غير المعتمد على الأنسولين — يحدث بين الأطفال، وقد بلغ عشرة أضعاف ما كان عليه منذ عقد من الزمن، وينصح الأطباء بتقليل الدهون أو التخلص من الدهون المشبعة والدهون المهدرجة. النشاط البدني يقلل من احتمالية الإصابة بمرض السكري؛ فكلما زاد خمول الإنسان زادت نسبة احتمالية إصابته بالسكري. أصبح المجتمع في عصرنا الحالي يعتمد على الرفاهية والخمول مما أدى إلى ظهور مرض السكري، وهو مرض وبائي في المجتمع.', 5, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'ما الذي ينصح به الأطباء في النص لتجنب الإصابة بالسكري؟', '["ترك السكر", "تقليل الدهون", "ممارسة الرياضة", "حماية الجسم"]'::jsonb, 1, 'النصيحة المنسوبة للأطباء نصًّا هي تقليل الدهون والتخلص من المشبعة والمهدرجة. أما النشاط البدني فورد كحقيقة عامة لا كنصيحة الأطباء.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82404-2026-4c00-9d00-000000000004', 'أوضح الباحثون أن النوع الثاني من داء السكري — وهو غير المعتمد على الأنسولين — يحدث بين الأطفال، وقد بلغ عشرة أضعاف ما كان عليه منذ عقد من الزمن، وينصح الأطباء بتقليل الدهون أو التخلص من الدهون المشبعة والدهون المهدرجة. النشاط البدني يقلل من احتمالية الإصابة بمرض السكري؛ فكلما زاد خمول الإنسان زادت نسبة احتمالية إصابته بالسكري. أصبح المجتمع في عصرنا الحالي يعتمد على الرفاهية والخمول مما أدى إلى ظهور مرض السكري، وهو مرض وبائي في المجتمع.', 6, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'علاقة (النشاط البدني) بـ(احتمال الإصابة بمرض السكري):', '["طردية", "عكسية", "نتيجة", "تزامنية"]'::jsonb, 1, 'النص يقرر أن النشاط البدني يقلل احتمالية الإصابة؛ فكلما زاد أحدهما نقص الآخر، وهذه علاقة عكسية.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82404-2026-4c00-9d00-000000000004', 'أوضح الباحثون أن النوع الثاني من داء السكري — وهو غير المعتمد على الأنسولين — يحدث بين الأطفال، وقد بلغ عشرة أضعاف ما كان عليه منذ عقد من الزمن، وينصح الأطباء بتقليل الدهون أو التخلص من الدهون المشبعة والدهون المهدرجة. النشاط البدني يقلل من احتمالية الإصابة بمرض السكري؛ فكلما زاد خمول الإنسان زادت نسبة احتمالية إصابته بالسكري. أصبح المجتمع في عصرنا الحالي يعتمد على الرفاهية والخمول مما أدى إلى ظهور مرض السكري، وهو مرض وبائي في المجتمع.', 7, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'جملة (مما أدى إلى ظهور مرض السكري) تفيد:', '["سببًا", "نتيجة", "مقارنة", "استدراكًا"]'::jsonb, 1, '«مما أدى إلى» تعبير يسوق ما بعده نتيجةً لما قبله: الاعتماد على الرفاهية والخمول نتيجته ظهور المرض.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82404-2026-4c00-9d00-000000000004', 'أوضح الباحثون أن النوع الثاني من داء السكري — وهو غير المعتمد على الأنسولين — يحدث بين الأطفال، وقد بلغ عشرة أضعاف ما كان عليه منذ عقد من الزمن، وينصح الأطباء بتقليل الدهون أو التخلص من الدهون المشبعة والدهون المهدرجة. النشاط البدني يقلل من احتمالية الإصابة بمرض السكري؛ فكلما زاد خمول الإنسان زادت نسبة احتمالية إصابته بالسكري. أصبح المجتمع في عصرنا الحالي يعتمد على الرفاهية والخمول مما أدى إلى ظهور مرض السكري، وهو مرض وبائي في المجتمع.', 8, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'أي الآتي صحيح من خلال النص؟', '["اعتمد المجتمع بإفراط على الرفاهية", "ترك المجتمع التعامل مع الرفاهية", "انخفضت إصابات الأطفال بالسكري", "النوع الثاني يعتمد على الأنسولين"]'::jsonb, 0, 'النص يقول إن المجتمع أصبح يعتمد على الرفاهية والخمول حتى ظهر المرض، وهذا هو الإفراط المقصود.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82404-2026-4c00-9d00-000000000004', 'أوضح الباحثون أن النوع الثاني من داء السكري — وهو غير المعتمد على الأنسولين — يحدث بين الأطفال، وقد بلغ عشرة أضعاف ما كان عليه منذ عقد من الزمن، وينصح الأطباء بتقليل الدهون أو التخلص من الدهون المشبعة والدهون المهدرجة. النشاط البدني يقلل من احتمالية الإصابة بمرض السكري؛ فكلما زاد خمول الإنسان زادت نسبة احتمالية إصابته بالسكري. أصبح المجتمع في عصرنا الحالي يعتمد على الرفاهية والخمول مما أدى إلى ظهور مرض السكري، وهو مرض وبائي في المجتمع.', 9, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'علاقة (النشاطات البدنية) بـ(الصحة):', '["طردية", "عكسية", "متذبذبة", "لا علاقة بينهما"]'::jsonb, 0, 'النشاط البدني يقلل احتمال المرض أي يرفع مستوى الصحة؛ فالعلاقة بينه وبين الصحة طردية، بعكس علاقته باحتمال الإصابة.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82404-2026-4c00-9d00-000000000004', 'أوضح الباحثون أن النوع الثاني من داء السكري — وهو غير المعتمد على الأنسولين — يحدث بين الأطفال، وقد بلغ عشرة أضعاف ما كان عليه منذ عقد من الزمن، وينصح الأطباء بتقليل الدهون أو التخلص من الدهون المشبعة والدهون المهدرجة. النشاط البدني يقلل من احتمالية الإصابة بمرض السكري؛ فكلما زاد خمول الإنسان زادت نسبة احتمالية إصابته بالسكري. أصبح المجتمع في عصرنا الحالي يعتمد على الرفاهية والخمول مما أدى إلى ظهور مرض السكري، وهو مرض وبائي في المجتمع.', 10, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'من خلال القطعة نفهم أنه لا بد من:', '["المبالغة في استخدام التقنية", "الحرص على استخدام التقنية", "التقليل من استخدام التقنية", "منع التقنية نهائيًا"]'::jsonb, 2, 'الرفاهية والخمول اللذان حذر منهما النص من أبرز أسبابهما الإفراط في وسائل التقنية، فالمطلوب التقليل منها لا منعها.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82404-2026-4c00-9d00-000000000004', 'أوضح الباحثون أن النوع الثاني من داء السكري — وهو غير المعتمد على الأنسولين — يحدث بين الأطفال، وقد بلغ عشرة أضعاف ما كان عليه منذ عقد من الزمن، وينصح الأطباء بتقليل الدهون أو التخلص من الدهون المشبعة والدهون المهدرجة. النشاط البدني يقلل من احتمالية الإصابة بمرض السكري؛ فكلما زاد خمول الإنسان زادت نسبة احتمالية إصابته بالسكري. أصبح المجتمع في عصرنا الحالي يعتمد على الرفاهية والخمول مما أدى إلى ظهور مرض السكري، وهو مرض وبائي في المجتمع.', 11, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'أنسب عنوان للنص:', '["كتم الأسرار", "فضيلة الطيبة", "عدم الثقة بالآخرين", "ترجمة السلوك إلى أفعال"]'::jsonb, 1, 'النص كله يدور حول الطيبة: كن طيبًا، وأخفِ طيبتك، والتمسها في الناس؛ فأنسب عنوان: فضيلة الطيبة.', NULL, 'ad240826-2026-4c00-9d00-240820260001', 'e1a82405-2026-4c00-9d00-000000000005', 'كن طيبًا، واحرص على ألا يعرف أحد أنك طيب لئلا يعتريك العجب، وابحث عن الجانب الطيب في كل من تعامله من الناس، وإياك أن تفتش عن الجانب السيئ فيهم، وقل الحق دائمًا ولا سيما على نفسك.', 1, 'active', false);
END IF;
END
$mig$;

-- مزامنة العداد مع الواقع
UPDATE leak_groups
SET question_count = (SELECT COUNT(*) FROM questions WHERE leak_group_id = 'ad240826-2026-4c00-9d00-240820260001')
WHERE id = 'ad240826-2026-4c00-9d00-240820260001';

-- تحقق نهائي
DO $chk$
DECLARE n INT; nq INT; nv INT; np INT;
BEGIN
  SELECT COUNT(*) INTO n FROM questions WHERE leak_group_id = 'ad240826-2026-4c00-9d00-240820260001';
  SELECT COUNT(*) INTO nq FROM questions WHERE leak_group_id = 'ad240826-2026-4c00-9d00-240820260001' AND section = 'quant';
  SELECT COUNT(*) INTO nv FROM questions WHERE leak_group_id = 'ad240826-2026-4c00-9d00-240820260001' AND section = 'verbal';
  SELECT COUNT(*) INTO np FROM questions WHERE leak_group_id = 'ad240826-2026-4c00-9d00-240820260001' AND passage_id IS NOT NULL;
  RAISE NOTICE 'إجمالي: % — كمي: % — لفظي: % — قطع: %', n, nq, nv, np;
  IF n <> 77 THEN RAISE EXCEPTION 'عدد الأسئلة % لا يطابق المتوقع 77', n; END IF;
  IF nq <> 26 OR nv <> 51 THEN RAISE EXCEPTION 'توزيع كمي/لفظي غير مطابق'; END IF;
END
$chk$;

COMMIT;