-- 87: Day 5 evening (yelo) — batch 3: physics + chemistry (25 questions)
-- Covers PDF pages 17-24. Strict quality filter applied: skipped figure-required questions + ambiguous ones.

BEGIN;

INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'أي الأجهزة التالية يُخزَّن فيها الشحنة الكهربائية؟', '["المولّد الكهربائي", "المكثف الكهربائي", "الفولتميتر", "البطارية الجافة"]'::jsonb, 1, 'المكثف الكهربائي (capacitor) جهاز مصمّم خصيصاً لتخزين الشحنة الكهربائية بين لوحين موصلين بينهما مادة عازلة. المولّد يحوّل الطاقة، والفولتميتر يقيس الجهد.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'ما الطاقة الحركية العظمى KE التي يكتسبها الإلكترون إذا كان جهد الإيقاف له V=3 (علماً أن شحنة الإلكترون e=1.6×10⁻¹⁹ كولوم)؟', '["1.6×10⁻¹⁹ J", "3.2×10⁻¹⁹ J", "2.4×10⁻¹⁴ J", "4.8×10⁻¹⁹ J"]'::jsonb, 3, 'الطاقة الحركية العظمى KE_max = e·V_stop = (1.6×10⁻¹⁹)(3) = 4.8×10⁻¹⁹ J. هذه علاقة أينشتاين للأثر الكهروضوئي.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'تؤثر القوّتان المتعاكستان 7 N و 12 N في جسم يسير في مسار مستقيم مسافة 7 m. ما الشغل الناتج بوحدة الجول؟', '["5", "19", "35", "84"]'::jsonb, 2, 'محصلة القوّتين = 12 − 7 = 5 N (في اتجاه القوة الأكبر). الشغل = القوة المحصّلة × المسافة = 5 × 7 = 35 جول.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'إذا كانت الطاقة الحركية الناتجة عن شغل سالب مبذول على جسم، فإن الطاقة الحركية للجسم..', '["تتزايد", "تتناقص", "تصبح صفراً", "تبقى ثابتة"]'::jsonb, 1, 'نظرية الشغل-الطاقة: الشغل المحصّل = التغير في الطاقة الحركية (W = ΔKE). إذا كان الشغل سالباً (القوة عكس الحركة)، فالطاقة الحركية تتناقص.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'الفيزياء', 'اختيار من متعدد', 'انتقال الطاقة الحرارية نتيجة التصادم المباشر بين جزيئات المادة يسمّى..', '["التوصيل الحراري", "الحمل الحراري", "الإشعاع الحراري", "الاتزان الحراري"]'::jsonb, 0, 'التوصيل الحراري (conduction) ينتقل عبر التصادم المباشر بين الجزيئات المتجاورة في المادة، خاصة الصلبة. الحمل عبر حركة المائع، والإشعاع عبر موجات كهرومغناطيسية بدون وسط.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'إذا كان مقدار المتجه الأول 6 ومقدار المتجه الثاني 8 وهما متعامدان، فاحسب مقدار محصّلتهما.', '["5", "10", "15", "20"]'::jsonb, 1, 'للمتجهين المتعامدين تُحسب المحصلة بنظرية فيثاغورس: |R| = √(|A|² + |B|²) = √(36 + 64) = √100 = 10.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'يصف نموذج بور مستويات الطاقة والأطياف الضوئية بصورة ممتازة في ذرة:', '["الهيدروجين فقط", "الهيدروجين والهيليوم", "عناصر المجموعة الأولى", "الهيليوم فقط"]'::jsonb, 0, 'نموذج بور دقيق فقط لذرة الهيدروجين (إلكترون واحد). للذرات متعددة الإلكترونات، التداخل بين الإلكترونات يكسر التوقعات البسيطة للنموذج.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'المساحة تحت منحنى (القوة-الزمن) تساوي..', '["الزخم", "السرعة", "التسارع", "الدفع"]'::jsonb, 3, 'الدفع (Impulse) J = ∫F·dt = المساحة تحت منحنى القوة-الزمن. ووفق نظرية الدفع-الزخم: الدفع = التغير في الزخم.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'في محوّل كهربائي: عدد لفّات الملف الابتدائي Nₚ=40 وجهده Vₚ=200 V، وعدد لفّات الملف الثانوي Nₛ=80. احسب جهد الملف الثانوي Vₛ.', '["100 V", "200 V", "400 V", "800 V"]'::jsonb, 2, 'معادلة المحوّل: Vₛ/Vₚ = Nₛ/Nₚ، فإن Vₛ = Vₚ × (Nₛ/Nₚ) = 200 × (80/40) = 200 × 2 = 400 V. هذا محوّل رافع (Nₛ > Nₚ).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'معدل تغيّر السرعة بالنسبة للزمن هو..', '["المسافة", "السرعة المتوسطة", "التسارع", "السرعة اللحظية"]'::jsonb, 2, 'التسارع (acceleration) بالتعريف = dv/dt = معدل تغيّر السرعة بالنسبة للزمن. وحدته m/s².', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'قياسات', 'اختيار من متعدد', 'كم تعادل درجة الحرارة 37°C بوحدة الكلفن؟', '["100 K", "273 K", "310 K", "410 K"]'::jsonb, 2, 'للتحويل من سيليزي إلى كلفن: K = °C + 273. إذاً 37 + 273 = 310 K. (درجة حرارة جسم الإنسان الطبيعية).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'وصل ضوء جرم سماوي إلى الأرض بعد 8×10⁶ ثانية. ما المسافة التي قطعها الضوء، علماً بأن سرعته c = 3×10⁸ m/s؟', '["37.5 m", "24×10¹⁴ m", "26.6×10⁻² m", "2.4×10¹⁴ m"]'::jsonb, 1, 'المسافة = السرعة × الزمن = (3×10⁸ m/s)(8×10⁶ s) = 24×10¹⁴ m. هذه ~76,000 سنة ضوئية تقريباً (في المجال المجرّي).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'دائرة كهربائية بسيطة فيها مقاومتان متصلتان على التوالي R و 2R، يدخل التيار 3 أمبير من المصدر. احسب شدة التيار المار في المقاومة R.', '["6 A", "3 A", "2 A", "1 A"]'::jsonb, 1, 'في التوصيل على التوالي، التيار ثابت في جميع عناصر الدائرة. لذا التيار في R يساوي تيار المصدر = 3 A.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'كلما زاد الحجم الذري للعنصر يزداد عدد..', '["البروتونات", "النيوترونات", "الإلكترونات", "الفوتونات"]'::jsonb, 2, 'الحجم الذري يحدّده عدد المستويات الإلكترونية (مدارات تحوي الإلكترونات). كلما زاد عدد الإلكترونات، زاد عدد المستويات وزاد نصف القطر الذري.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'أحماض وقواعد', 'اختيار من متعدد', 'أي الأحماض التالية أكثر موصلية للتيار الكهربائي؟', '["NH₃", "H₃PO₄", "HF", "HCl"]'::jsonb, 3, 'الموصلية تعتمد على درجة التأيّن. HCl حمض قوي يتأيّن كلياً في الماء، فينتج عدداً كبيراً من الأيونات الحرة (H⁺ و Cl⁻). الباقي حموض ضعيفة (والأمونيا قاعدة).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'اتزان كيميائي', 'اختيار من متعدد', 'في أي الحالات التالية يتكوّن راسب في محلول؟', '["Qsp > Ksp", "Qsp = Ksp", "Qsp < Ksp", "Qsp ≥ 0"]'::jsonb, 0, 'عند مقارنة حاصل الذوبان Qsp بثابت حاصل الذوبان Ksp: إذا Qsp > Ksp → المحلول فوق المشبع → يتكوّن راسب. إذا Qsp = Ksp → مشبع متّزن. إذا Qsp < Ksp → لا راسب.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'أحماض وقواعد', 'اختيار من متعدد', 'محلول مائي pH=5، ما قيمة pOH له؟', '["5", "6", "11", "9"]'::jsonb, 3, 'العلاقة الأساسية: pH + pOH = 14 (عند 25°C). إذاً pOH = 14 − 5 = 9.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'جميع التالي عناصر ما عدا..', '["Al", "K", "Ca", "CO₂"]'::jsonb, 3, 'العناصر مواد نقية مكوّنة من نوع واحد من الذرات. Al و K و Ca عناصر فلزية، بينما CO₂ مركّب كيميائي مكوّن من ذرتي أكسجين وذرة كربون.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'أحماض وقواعد', 'اختيار من متعدد', 'الرقم الهيدروجيني pH للماء المقطر النقي عند 25°C يساوي..', '["7", "5", "11", "14"]'::jsonb, 0, 'الماء المقطر النقي متعادل: [H⁺] = [OH⁻] = 10⁻⁷ M، إذاً pH = −log(10⁻⁷) = 7. هذا التعريف القياسي للوسط المتعادل.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'روابط كيميائية', 'اختيار من متعدد', 'عدد إلكترونات التكافؤ في عنصر الفلور ₉F هو..', '["5", "2", "7", "9"]'::jsonb, 2, 'التوزيع الإلكتروني للفلور: 1s² 2s² 2p⁵. إلكترونات التكافؤ هي إلكترونات المستوى الأخير: 2s² + 2p⁵ = 7 إلكترونات.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'أي العناصر التالية له عدد تأكسد +2؟', '["₂₀Ca", "₁₁Na", "₁₃Al", "₃₆Kr"]'::jsonb, 0, 'عناصر المجموعة 2 (الفلزات القلوية الترابية) لها عدد تأكسد ثابت +2 لأنها تفقد إلكترونَي التكافؤ. Ca في المجموعة 2 → عدد تأكسده +2.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'أي مما يلي يُعدّ تغيّراً فيزيائياً؟', '["انصهار", "انفجار", "تأكسد", "تحلل"]'::jsonb, 0, 'التغيّر الفيزيائي يغيّر شكل المادة أو حالتها دون تكوين مواد جديدة. الانصهار تحوّل حالة فقط (صلب → سائل). الباقي تغيّرات كيميائية ينتج عنها مواد جديدة.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'روابط كيميائية', 'اختيار من متعدد', 'أقوى أنواع القوى بين الجزيئات (intermolecular forces) هي..', '["أيونية", "هيدروجينية", "ثنائية القطب", "تساهمية"]'::jsonb, 1, 'بين الجزيئات: الرابطة الهيدروجينية هي الأقوى (~5-30 kJ/mol)، تظهر بين H المرتبط بـ F أو O أو N وذرة سالبة في جزيء آخر. الأيونية والتساهمية روابط داخل الجزيء لا بين الجزيئات.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'أي العناصر التالية له أعلى طاقة تأيّن (جهد تأيّن)؟', '["Li", "Be", "Mg", "K"]'::jsonb, 1, 'طاقة التأيّن تزيد عبر الدور (يميناً) وتقلّ نزولاً في المجموعة. Be (دور 2، مجموعة 2) أصغر حجماً وأعلى Z مؤثّر من Li في نفس الدور، ومن Mg/K في نفس المجموعة. القيم: Be ≈ 9.3 eV > Li ≈ 5.4 eV > Mg ≈ 7.6 eV > K ≈ 4.3 eV.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'اتزان كيميائي', 'اختيار من متعدد', 'في حالة الاتزان الكيميائي:', '["تركيز المتفاعلات والنواتج متساوي", "تركيز المتفاعلات والنواتج ثابت", "تركيز المتفاعلات والنواتج مختلف", "يتوقّف التفاعل تماماً"]'::jsonb, 1, 'عند الاتزان: معدل التفاعل الأمامي = معدل التفاعل العكسي، فيبقى التركيز ثابتاً (وليس بالضرورة متساوي) ولا يتوقف التفاعل (اتزان ديناميكي).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);

COMMIT;
