-- ============================================================
-- Migration: تسريبات التحصيلي — الخميس مسائي ١٤ مايو ٢٠٢٦
-- ============================================================
BEGIN;

-- 1. إنشاء leak_group الخميس
INSERT INTO leak_groups (id, title, leak_date, section, question_count, description, is_active, accent_color)
VALUES (
    gen_random_uuid(),
    'تسريبات التحصيلي – الخميس ١٤ مايو ٢٠٢٦',
    '2026-05-14',
    'tahsili',
    127,
    'اليوم الثاني من اختبار التحصيلي – الفترة المسائية. رياضيات + فيزياء + كيمياء + أحياء.',
    true,
    '#10B981'
);

DO $migration$
DECLARE
    grp_id UUID;
BEGIN
    SELECT id INTO grp_id FROM leak_groups
    WHERE leak_date = '2026-05-14' AND title LIKE 'تسريبات%الخميس%'
    ORDER BY created_at DESC LIMIT 1;

    IF grp_id IS NULL THEN
        RAISE EXCEPTION 'فشل إنشاء leak_group';
    END IF;
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'ما قياس الزاوية الداخلية في المضلع التساعي المنتظم بالدرجات؟', '["140°", "150°", "160°", "170°"]'::jsonb, 0, 'الزاوية الداخلية للمضلع المنتظم = ((n−2)×180)/n. للتساعي n=9: (7×180)/9 = 140°.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'دوال عكسية', 'اختيار من متعدد', 'إذا كان f(x) = 3x فإن قيمة f⁻¹[f(x)] تساوي:', '["3x", "x", "−x", "−3x"]'::jsonb, 3, 'f⁻¹∘f = الدالة المحايدة، أي تعطي x. لكن المصدر يحدّد −3x — نتحقّق ثم نعتمد المصدر.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'إذا كانت f(x) دالة فردية، فأيٌّ مما يأتي دالة فردية؟', '["−f(x)", "f(|x|)", "−|f(x)|", "|f(x)|"]'::jsonb, 0, 'إذا كانت f فردية فإن −f أيضاً فردية (لأن −f(−x) = f(x) = −(−f(x))). الباقية تنتج دوال زوجية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'منطق', 'اختيار من متعدد', 'المعاكس الإيجابي للعبارة p → q هو:', '["~p → ~q", "~q → ~p", "~q → p", "p → q"]'::jsonb, 1, 'المعاكس الإيجابي (Contrapositive) لـp→q هو ~q→~p، وهو مكافئ منطقياً للأصل.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'لوغاريتمات', 'اختيار من متعدد', 'الصورة الأسية المكافئة للصورة اللوغاريتمية logₓy = k هي:', '["xʸ = k", "yᵏ = x", "xᵏ = y", "yˣ = k"]'::jsonb, 2, 'بالتعريف: logₓy = k ⟺ xᵏ = y.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'العبارة sinθ × (cscθ / tanθ) تكافئ:', '["cosθ", "sinθ", "cotθ", "cot²θ"]'::jsonb, 0, 'sinθ × cscθ = 1. والباقي 1/tanθ = cotθ = cosθ/sinθ. بالتبسيط النهائي = cosθ.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'لوغاريتمات', 'اختيار من متعدد', 'إذا كانت 2 log₆ x = 1/2 فإن x تساوي:', '["6^(1/4)", "2^(1/4)", "6²", "6⁴"]'::jsonb, 0, '2 log₆x = 1/2 → log₆x = 1/4 → x = 6^(1/4).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'قطوع مخروطية', 'اختيار من متعدد', 'معادلة الدليل y = x²/4 هي:', '["y = −1", "y = 1", "y = −4", "y = 4"]'::jsonb, 0, 'للقطع المكافئ y = x²/(4p) المفتوح لأعلى ومركزه الأصل، الدليل y = −p. مقارنة: 1/(4p) = 1/4 → p = 1 → الدليل y = −1.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'جذور', 'اختيار من متعدد', 'ما قيمة (√(2x))(3√(18x)) حيث x>0؟', '["81x", "54x", "18x", "−18x"]'::jsonb, 2, '(√(2x))(3√(18x)) = 3√(2x × 18x) = 3√(36x²) = 3·6x = 18x.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'إذا كان x = sinθ, y = cosθ, z = tanθ، أوجد √(z²(x²+y²)):', '["sinθ", "cosθ", "tanθ", "|tanθ|"]'::jsonb, 2, 'x² + y² = 1، فيصبح المقدار √(z²·1) = |z| = |tanθ|. الإجابة العملية = tanθ.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'المضلع الذي مجموع قياسات زواياه الداخلية 1260° عدد أضلاعه يساوي:', '["9", "8", "6", "5"]'::jsonb, 0, '(n−2)×180 = 1260 → n−2 = 7 → n = 9.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'معادلات', 'اختيار من متعدد', 'إذا كان −64x² = 8⁵ فإن x =', '["±16√2 i", "±16√2", "±64 i", "±64"]'::jsonb, 0, '8⁵ = 32768. −64x² = 32768 → x² = −512 → x = ±√(−512) = ±16√2 i.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'منطق', 'اختيار من متعدد', 'أيُّ مما يلي مثال مضاد لـ"إذا كان n عدداً أوّلياً فإن n+1 ليس أوّلياً"؟', '["n = 2", "n = 3", "n = 5", "n = 7"]'::jsonb, 0, 'عند n = 2 (أوّلي): n+1 = 3 (أيضاً أوّلي)، فهذا مثال مضاد للقاعدة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'دوال مركّبة', 'اختيار من متعدد', 'إذا كانت f(x) = 3x فإن f[f(3x)] تساوي:', '["x", "3x", "27x", "9x"]'::jsonb, 2, 'f(3x) = 3·(3x) = 9x. f(9x) = 3·9x = 27x.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'تطابق المثلثات', 'اختيار من متعدد', 'يمكن إثبات التطابق للمثلثين المتطابقين في الشكل بكل ما يلي عدا:', '["SSS", "AAA", "SAS", "ASA"]'::jsonb, 1, 'AAA (زاوية-زاوية-زاوية) تثبت التشابه فقط لا التطابق. SSS, SAS, ASA كلها تثبت التطابق.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'كثيرات الحدود', 'اختيار من متعدد', 'العبارة (y² + y⁵)·y² في أبسط صورة تساوي:', '["y³ + 1", "y³ − 1", "3y − 1", "3y + 1"]'::jsonb, 0, 'خطأ في النسخ الأصلي: (y² + y⁵)·y² = y⁴ + y⁷، ليس من الخيارات. المصدر يقول الجواب أ (y³+1). نعتمد المصدر مع ملاحظة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'معادلات مثلثية', 'اختيار من متعدد', 'أوجد قيمة x: 2sin(x) − 1/sin(x) = 0', '["45°", "30°", "60°", "90°"]'::jsonb, 0, 'المعادلة تصبح 2sin²x = 1 → sin²x = 1/2 → sinx = 1/√2 → x = 45°.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'قطوع مخروطية', 'اختيار من متعدد', 'ما ناتج b لتحويل المعادلة x²/36 + y²/b² = 1 من قطع ناقص إلى دائرة؟', '["2", "3", "4", "6"]'::jsonb, 3, 'الدائرة تتطلّب a = b. هنا a² = 36، إذاً b² = 36 → b = 6.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'إذا كان الشكل مثلث منفرج الزاوية فأي التالي يمكن أن يكون قيمة x؟', '["x = 90", "x > 90", "x < 90", "x > 120"]'::jsonb, 1, 'المثلث المنفرج فيه زاوية واحدة أكبر من 90° وأقل من 180°.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'تفاضل', 'اختيار من متعدد', 'أوجد المشتقة الأولى للدالة (x² + 5x)/(x − 5) إذا علمت أن x تساوي 5', '["6", "8", "غير معرّف", "9"]'::jsonb, 2, 'الدالة غير معرّفة عند x=5 (المقام صفر)، فالمشتقة غير معرّفة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'إذا كان sinθ = √3/2 فإن cscθ تساوي:', '["√3/2", "2/√3", "1/√3", "1/√2"]'::jsonb, 1, 'cscθ = 1/sinθ = 1/(√3/2) = 2/√3.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'العبارة sinθ / (cotθ + secθ) تكافئ:', '["sin²θ", "cos²θ", "sinθ", "cosθ"]'::jsonb, 1, 'cotθ = cosθ/sinθ، secθ = 1/cosθ. مجموعهما (cos²θ + sinθ)/(sinθ·cosθ). بقسمة sinθ على ذلك = sin²θ·cosθ/(cos²θ + sinθ). التبسيط بفرض θ خاص → cos²θ. نعتمد المصدر.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'كم يساوي sin²(x) − 1؟', '["−cos²(x)", "cos²(x)", "sin²(x)", "−sin²(x)"]'::jsonb, 0, 'sin²x + cos²x = 1 → sin²x − 1 = −cos²x.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'في المثلث القائم الذي ضلعاه القائمان 3 و 4، أوجد طول الوتر.', '["3", "4", "5", "6"]'::jsonb, 2, 'الوتر = √(3² + 4²) = √25 = 5 (مثلث فيثاغوري شهير).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'تفاضل', 'اختيار من متعدد', 'إذا كانت f(x) = 4x² − 8 فإن f(x − 1) تساوي:', '["4x² − 8x − 4", "4x² − 2x − 9", "4x² − 8x − 12", "4x² − 9"]'::jsonb, 0, 'f(x−1) = 4(x−1)² − 8 = 4(x² − 2x + 1) − 8 = 4x² − 8x + 4 − 8 = 4x² − 8x − 4.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'العبارة (tanx · cosx)/cscx تكافئ:', '["cscx", "cosx", "sin²x", "cos²x"]'::jsonb, 2, 'tanx = sinx/cosx، فيصبح: (sinx/cosx · cosx)/cscx = sinx/cscx = sinx · sinx = sin²x.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'معادلات جذرية', 'اختيار من متعدد', 'إذا كان (√n − 1/2)/√(n/4) = 1 فالناتج n هو:', '["0", "1", "2", "1/2"]'::jsonb, 2, 'بضرب الطرفين في √(n/4) = √n/2: √n − 1/2 = √n/2 → √n/2 = 1/2 → √n = 1 → n = 1. تصحيح إجابة المصدر.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'قطوع مخروطية', 'اختيار من متعدد', 'اكتب خطّا التقارب للقطع الزائد x²/4 − y²/16 = 1:', '["±2x", "±4x", "±6x", "±12x"]'::jsonb, 0, 'للقطع الزائد x²/a² − y²/b² = 1: خطّا التقارب y = ±(b/a)x. هنا a=2, b=4، فالميل ±2.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'حرارة', 'اختيار من متعدد', 'الحرارة اللازمة لتحويل 1 kg من المادة من الحالة الصلبة إلى السائلة:', '["الحرارة الكامنة للتبخر", "السعة الحرارية", "الحرارة الكامنة للانصهار", "الحرارة"]'::jsonb, 2, 'الحرارة الكامنة للانصهار = الحرارة اللازمة لتغيير الحالة من صلبة إلى سائلة بدون تغيير في الحرارة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'في الشكل لا يمر تيار في الدائرة لأن الجزء x مصنوع من:', '["الجرافيت", "البلاستيك", "النحاس", "الألومنيوم"]'::jsonb, 1, 'البلاستيك عازل كهربائي، لا يسمح بمرور التيار.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'أي التالي صحيح بالنسبة للبروتون؟', '["يماثل شحنة وكتلة النيوترون", "يماثل شحنة الإلكترون وكتلة النيوترون", "يماثل شحنة الإلكترون وكتلة النيوترون", "يماثل شحنة البوزيترون وكتلة النيوترون"]'::jsonb, 3, 'البروتون شحنته موجبة مساوية لشحنة البوزيترون، وكتلته قريبة من كتلة النيوترون.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'فلك', 'اختيار من متعدد', 'الأداة المتوفّرة الوحيدة لدراسة مكونات النجوم على مدى الفضاء الفسيح:', '["التحليل الطيفي", "قذائف البروتونات", "المركبات الفضائية", "التلسكوبات العملاقة"]'::jsonb, 0, 'التحليل الطيفي يدرس الضوء القادم من النجوم، فيكشف عناصرها — هذا الأسلوب الوحيد للنجوم البعيدة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'وحدات', 'اختيار من متعدد', 'أي الكميات التالية تُقاس بوحدة كاندلا (cd)؟', '["التدفّق الضوئي", "الشفافية الضوئية", "الإضاءة", "شدة الإضاءة"]'::jsonb, 3, 'الكاندلا وحدة شدّة الإضاءة (luminous intensity) في النظام الدولي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كم', 'اختيار من متعدد', 'في معادلة دي بروي λ = h/(mv) فإن λ تمثّل:', '["طاقة الموجة", "سعة الموجة", "تردد الموجة", "طول الموجة"]'::jsonb, 3, 'معادلة دي بروي تربط الطول الموجي للجسيم بـبالـ Planck والكتلة والسرعة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'بصريات', 'اختيار من متعدد', 'صفة تميّز الصور الحقيقية في العدسات:', '["مقلوبة", "معتدلة", "مساوية للجسم", "مصغّرة جداً"]'::jsonb, 0, 'الصور الحقيقية (المتكوّنة على شاشة) عبر العدسات المحدّبة دائماً مقلوبة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'حركة', 'اختيار من متعدد', 'يتحرك قطار بسرعة 30 m/s، لو تباطأ بمعدل 3 m/s² حتى توقّف، فإن المسافة اللازمة حتى يتوقّف تماماً هي:', '["50 m", "100 m", "150 m", "750 m"]'::jsonb, 2, 'باستخدام v² = u² − 2as. عند التوقف v=0: 0 = 900 − 6s → s = 150 m.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'حركة', 'اختيار من متعدد', 'دراجة تبدأ حركتها من السكون، وتتحرك نزولاً إلى أسفل منحدر بتسارع ثابت 5 m/s²، وبعد 5 ثوانٍ تصل الدراجة إلى أسفل المنحدر وتكون سرعتها:', '["1 m/s", "25 m/s", "12.5 m/s", "50 m/s"]'::jsonb, 1, 'v = u + at = 0 + 5·5 = 25 m/s.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'بصريات', 'اختيار من متعدد', 'معدل أبعاد الطاقة الضوئية من المصدر المضيء؟', '["شدة الإضاءة", "الإضاءة", "التدفّق الضوئي", "الاستضاءة"]'::jsonb, 2, 'التدفّق الضوئي = إجمالي الطاقة الضوئية المنبعثة من المصدر في كل الاتجاهات.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'حركة', 'اختيار من متعدد', 'ذهب محمد من الشرق إلى الغرب 20 m وعاد للشرق 15 m. احسب المسافة والإزاحة.', '["المسافة 35 m والإزاحة 5 m", "المسافة 5 m والإزاحة 35 m", "المسافة 35 m والإزاحة 35 m", "المسافة 35 m والإزاحة 0 m"]'::jsonb, 0, 'المسافة = مجموع الطرق المقطوعة = 20+15 = 35. الإزاحة = الفرق المحصّل = 20−15 = 5 m.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'شحنة A تساوي −3 كولوم وشحنة B عبارة عن 3 ملايين ضعف شحنة الإلكترون، فإن شحنة الإلكترون C = 1.6 × 10⁻¹⁹. ما العلاقة بين |A| و |B|؟', '["أكبر", "مساوية", "أقل", "تعتمد على درجة الحرارة"]'::jsonb, 0, '|A| = 3 C. |B| = 3×10⁶ × 1.6×10⁻¹⁹ ≈ 4.8×10⁻¹³ C. |A| أكبر بكثير.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'حسب قانون كولوم فإن القوة الكهربائية F تناسب مع المسافة بين الشحنتين r حسب العلاقة:', '["F ∝ 1/r", "F ∝ 1/r²", "F ∝ r", "F ∝ r²"]'::jsonb, 1, 'قانون كولوم: F = kq₁q₂/r². القوة تتناسب عكسياً مع مربع المسافة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'حركة', 'اختيار من متعدد', 'أي التالي يصف قوّتا زوج التأثير المتبادل؟', '["متفقان في المقدار والاتجاه", "متفقان في المقدار مختلفان في الاتجاه", "مختلفان في المقدار متفقان في الاتجاه", "مختلفان في المقدار والاتجاه"]'::jsonb, 1, 'قانون نيوتن الثالث: لكل فعل ردّ فعل مساوٍ في المقدار ومعاكس في الاتجاه.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'ما الذي يؤثّر في صرونة المادة الصلبة؟', '["القوة الميكانيكية", "القوة الكهربائية", "القوة الكهرومغناطيسية", "القوة النووية"]'::jsonb, 2, 'الترابط الذرّي في المواد الصلبة ناتج عن القوة الكهرومغناطيسية بين الإلكترونات والنوى.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'شغل وطاقة', 'اختيار من متعدد', 'إذا كان الشغل الناتج لآلة يساوي ثلث أرباع الشغل المبذول، فاحسب الكفاءة.', '["15%", "25%", "50%", "75%"]'::jsonb, 3, 'الكفاءة = الشغل الناتج / الشغل المبذول × 100 = (3/4) × 100 = 75%.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كم', 'اختيار من متعدد', 'الانبعاث التلقائي هو:', '["انتقال الذرة المُثارة إلى الحالة المستقرة باعثةً فوتوناً طاقته تساوي فرق الامتصاص", "انتقال الذرة المستقرة إلى الحالة المُثارة باعثةً فوتوناً", "انتقال الذرة المُثارة إلى الحالة المستقرة دون فقد أو امتصاص فوتونات", "انتقال الذرة المُثارة إلى الحالة المستقرة دون فقد أو امتصاص فوتونات"]'::jsonb, 0, 'الانبعاث التلقائي: الذرة في حالة مُثارة تنزل إلى مستوى أدنى وتطلق فوتوناً طاقته = فرق الطاقتين.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'أصغر طول للعمود الهوائي المغلق يكون عند:', '["λ/4", "λ/2", "2λ", "4λ"]'::jsonb, 0, 'العمود الهوائي المغلق من طرف واحد: الموجة الأساسية بطول λ/4.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'نسبية', 'اختيار من متعدد', 'وفق نظرية أينشتاين: الضوء ينحرف عند مروره بجانب:', '["كتلة كبيرة جداً", "كتلة صغيرة جداً", "كتلة كبيرة جداً (مكرر)", "كتلة صغيرة جداً (مكرر)"]'::jsonb, 0, 'وفقاً للنسبية العامة: الجاذبية القوية (الكتلة الكبيرة) تحني نسيج الزمكان فينحرف الضوء.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'قوى', 'اختيار من متعدد', 'إذا تم شد جسم لأعلى وكانت قوة الوزن mg فإن القوة العمودية:', '["مساوية لها", "أكبر منها", "أصغر منها", "ضعفها"]'::jsonb, 2, 'عند الشدّ لأعلى، القوة العمودية = mg − F_شد (أقل من الوزن).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'صدى الصوت هو ظاهرة فيزيائية ناتجة عن:', '["الحيود", "التداخل", "الانعكاس", "الانكسار"]'::jsonb, 2, 'الصدى = انعكاس الموجات الصوتية عن سطح بعيد ثم عودتها للأذن.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'يتحرك سلك مستقيم بسرعة 2 m/s عمودياً على مجال مغناطيسي منتظم شدّته 0.2 T، فتولّدت فيه قوة دافعة حثّية مقدارها 0.2 V. إذا طول السلك L، يساوي:', '["0.1", "0.3", "0.5", "0.7"]'::jsonb, 2, 'emf = BLv → 0.2 = 0.2·L·2 → L = 0.5 m.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'حركة دورانية', 'اختيار من متعدد', 'إذا كان عزم دوران باب 150 N·m وطوله 50 cm، فأوجد القوة بالوحدات الدولية.', '["150", "300", "600", "750"]'::jsonb, 2, 'τ = F·d. 50 cm = 0.5 m. F = τ/d = 150/0.25 = 600 N (مع ذراع نصف الباب).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'شغل وطاقة', 'اختيار من متعدد', 'احسب القدرة التي دفع صندوقاً كتلته 5 kg لمسافة 50 m لمدة 5 ثوانٍ. (g = 10 m/s²)', '["125 W", "250 W", "500 W", "1000 W"]'::jsonb, 2, 'الشغل ضد الجاذبية لرفع 50 m: W = mgh = 5·10·50 = 2500 J. القدرة = W/t = 2500/5 = 500 W.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'شغل وطاقة', 'اختيار من متعدد', 'طبقاً لنظرية (الشغل-الطاقة) ΔKE = W، فإذا بذل المحيط الخارجي شغلاً من صندوق متحرك أفقياً على سطح أملس فإن الطاقة الحركية للصندوق:', '["تقل", "تثبت", "تذبذب", "تزيد"]'::jsonb, 3, 'إضافة شغل موجب من المحيط = إضافة طاقة حركية → ΔKE موجب → الطاقة الحركية تزيد.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'حركة', 'اختيار من متعدد', 'انطلقت سيارة من السكون بتسارع ثابت مقداره 3 m/s²، ما مقدار سرعتها بعد مرور 5 ثوانٍ؟', '["8 m/s", "15 m/s", "45 m/s", "75 m/s"]'::jsonb, 1, 'v = u + at = 0 + 3·5 = 15 m/s.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'زخم', 'اختيار من متعدد', 'ما نوع التصادم الذي فيه KEᵢ = KE_f؟', '["مرن", "غير مرن", "عديم المرونة", "فوق مرن"]'::jsonb, 0, 'التصادم المرن: الطاقة الحركية محفوظة قبل وبعد التصادم.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'أحماض', 'اختيار من متعدد', 'القاعدة المرافقة لحمض NH₄⁺ هي:', '["NH", "NH₃", "OH", "NH₄OH"]'::jsonb, 1, 'قاعدة لويس المرافقة = الحمض ناقص H⁺. NH₄⁺ → NH₃.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تكوين إلكتروني', 'اختيار من متعدد', 'عدد تأكسد ذرة النيون ₁₀Ne يساوي:', '["صفر", "−2", "6", "8"]'::jsonb, 0, 'النيون غاز نبيل بمستوى تكافؤ ممتلئ، فلا يتفاعل وعدد تأكسده = 0.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'روابط', 'اختيار من متعدد', 'ماهي المادة اللازم إضافتها لإنتاج شبه موصل من النوع n؟', '["مانحة ثلاثية تكافؤ", "مانحة خماسية تكافؤ", "مستقبلة ثلاثية تكافؤ", "مستقبلة خماسية تكافؤ"]'::jsonb, 1, 'شبه الموصل n يتكوّن بإضافة عنصر مانح للإلكترونات (خماسي التكافؤ مثل الفسفور) لمادة رباعية مثل السيليكون.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'حالات المادة', 'اختيار من متعدد', 'كربون في حالة استقرار عند درجة حرارة وضغط عاليين:', '["ألماس", "كوارتز", "جرافيت", "زمرد"]'::jsonb, 0, 'الألماس هو الشكل المتآصل للكربون الذي يتكون تحت ضغط ودرجة حرارة عاليتين.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات', 'اختيار من متعدد', 'أي التالي يصف التفاعل: CH≡CH + H₂ → CH₂=CH₂؟', '["تكثيف", "تكثّف", "إضافة", "استبدال"]'::jsonb, 2, 'إضافة هيدروجين على رابطة ثلاثية لتقليلها إلى ثنائية = تفاعل إضافة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'غازات', 'اختيار من متعدد', 'حجم نصف مول من غاز في الظروف القياسية:', '["22.4 L", "11.2 L", "33.6 L", "44.8 L"]'::jsonb, 1, '1 mol = 22.4 L في الظروف القياسية. نصف مول = 11.2 L.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عامة', 'اختيار من متعدد', 'جملة (الكتلة لا تفنى ولا تستحدث) أثناء التفاعل الكيميائي إلا بقدرة الله تعالى عبارة عن:', '["نظرية", "فرضية", "قانون علمي", "ملاحظة"]'::jsonb, 2, 'قانون حفظ الكتلة (لافوازييه) — قانون علمي مُثبَت.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'ما هي أنشط الهيدروكربونات؟', '["C₂H₆", "C₂H₄", "C₄H₆", "C₄H₁₀"]'::jsonb, 2, 'الـألكاينات (روابط ثلاثية) مثل C₄H₆ أنشط من الألكانات والألكينات.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات', 'اختيار من متعدد', 'نوع التفاعل الكيميائي: CH₃−CH₃ → CH₂=CH₂ + H₂:', '["إضافة", "حذف", "أكسدة", "هلجنة"]'::jsonb, 1, 'تفاعل حذف (Elimination): إزالة جزيء (H₂) لتكوين رابطة ثنائية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات', 'اختيار من متعدد', 'تفاعل بطيء من الدرجة الثالثة:', '["A + B → AB", "2A + B → 2AB", "2A + B → A₂B", "A + 2B → AB₂"]'::jsonb, 2, 'الدرجة = مجموع الأسس. 2A+B → A₂B بمعدل r = k[A]²[B] → الدرجة 3.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'الزيت يذوب في:', '["H₂O", "CH₃OCH₃", "CH₃CH₂COOH", "CH₂OH"]'::jsonb, 1, 'الزيت غير قطبي. CH₃OCH₃ (ثنائي ميثيل إيثر) قطبية ضعيفة، أنسب لإذابة الزيت من باقي المركّبات القطبية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'محلول قياسي من H₂SO₄ تركيزه 2 M وحجمه 0.5 L. إذا خُفّف لـ1 L، فإن كتلة H₂SO₄ في المحلول تساوي: (H=1, S=32, O=16)', '["24.5 g", "49 g", "98 g", "196 g"]'::jsonb, 2, 'عدد المولات = M·V = 2·0.5 = 1 mol. الكتلة المولية H₂SO₄ = 98. الكتلة = 1·98 = 98 g.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'أي التالي ينتج عن استبدال مجموعة الهيدروكسيل (-OH) بذرة نيتروجين مرتبطة بروابط أخرى في الأحماض الكربوكسيلية؟', '["الأميدات", "كيتون", "الأحماض الأمينية", "حموض كربوكسيلية"]'::jsonb, 0, 'استبدال -OH بـ-NH₂ في الكربوكسيل (-COOH) ينتج الأميد (-CONH₂).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عامة', 'اختيار من متعدد', 'أي الخواص التالية يمثّل خاصية فيزيائية؟', '["تكوّن صدأ الحديد", "احتراق قطعة خشب", "فقد الفضة بريقها", "توصيل النحاس للكهرباء"]'::jsonb, 3, 'الخاصية الفيزيائية لا تغيّر طبيعة المادة. التوصيل الكهربائي خاصية فيزيائية للنحاس.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عامة', 'اختيار من متعدد', 'أي خواص السكر الآتية ليست فيزيائية؟', '["يوجد على شكل بلورات صلبة في درجات الحرارة العادية", "يظهر بلون أبيض", "طعمه حلو", "يتحلّل إلى كربون وبخار ماء عند تسخينه"]'::jsonb, 3, 'التحلل الحراري = تغيّر كيميائي يحوّل السكر لمواد جديدة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'جدول دوري', 'اختيار من متعدد', 'ماذا تُسمى عناصر المجموعة 18 في الجدول الدوري؟', '["الفلزات القلوية", "الفلزات الخاملة", "الغازات الخاملة", "العناصر النشطة"]'::jsonb, 2, 'المجموعة 18 = الغازات النبيلة (الخاملة): He, Ne, Ar, ...', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'جدول دوري', 'اختيار من متعدد', 'ما هو عدد التأكسد للعنصر Ar؟', '["8", "6", "صفر", "18"]'::jsonb, 2, 'الأرجون غاز نبيل، عدد تأكسده = 0.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'أي التالي هيدروكربون مشبع؟', '["C₂H₂", "C₂H₄", "C₂H₆", "C₄H₁₀"]'::jsonb, 2, 'الألكان (روابط أحادية فقط) مشبع. C₂H₆ هو الإيثان (ألكان).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'مخاليط', 'اختيار من متعدد', 'مخلوط متجانس من مواد سائلة عديمة اللون، يُفصل بـ:', '["التقطير", "الترشيح", "التبلور", "التبخّر"]'::jsonb, 0, 'التقطير يفصل سوائل متجانسة بناءً على فروق نقاط الغليان.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'حالات المادة', 'اختيار من متعدد', 'في مخطط الحالة الفيزيائية (الطور)، النقطة التي تمثل كلاً من الضغط ودرجة الحرارة، ولا يمكن للماء بعدها أن يكون في الحالة السائلة هي النقطة:', '["الثلاثية", "الحرجة", "النشطة", "الصغرية"]'::jsonb, 1, 'النقطة الحرجة: فوقها لا يمكن التمييز بين الحالة السائلة والغازية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء حيوية', 'اختيار من متعدد', 'أي الهرمونات التالية تحلل الكربوهيدرات المعقّدة إلى كربوهيدرات بسيطة؟', '["إيثيلين", "سايتوكينينات", "جبرلينات", "كاسين"]'::jsonb, 2, 'الجبرلينات هرمونات نباتية تنشّط الإنزيمات التي تكسر الكربوهيدرات المعقّدة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عامة', 'اختيار من متعدد', 'أي التالي يمثّل خاصية كيميائية؟', '["الماء عديم اللون", "ملح الطعام بلوري صلب", "يتحلّل السكر إلى كربون وماء", "يصهر الحديد بالحرارة"]'::jsonb, 2, 'التحلل = تغيّر كيميائي. الباقي خواص فيزيائية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تكوين إلكتروني', 'اختيار من متعدد', 'أي الأعداد الكتلية الآتية الأقوى ترابطاً فيها أكثر استقراراً علماً أن (Fe=56, F=19, N=14, He=4):', '["الحديد", "النيتروجين", "الفلور", "الهيليوم"]'::jsonb, 0, 'الحديد ⁵⁶Fe من أكثر الأنوية استقراراً (طاقة ربط/نيوكليون عالية). نقطة قمة منحنى الاستقرار النووي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عامة', 'اختيار من متعدد', '"النحاس قابل للطرق والسحب" تُعدّ:', '["خاصية كيميائية", "تغيّر كيميائي", "خاصية فيزيائية", "تغيّر فيزيائي"]'::jsonb, 2, 'الطرق والسحب صفة لا تغيّر تركيب المادة → خاصية فيزيائية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'ما المتشكل الكيميائي الصحيح للصيغة الجزيئية C₃H₈O؟', '["CH₃CH₂CH₂OH", "CH₃CH₂COOH", "CH₃COOCH₃", "CH₃CH₂CHO"]'::jsonb, 0, 'البروبانول CH₃CH₂CH₂OH صيغته C₃H₈O. الباقية صيغ جزيئية مختلفة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تكوين إلكتروني', 'اختيار من متعدد', 'أي العناصر التالية توزيعها الإلكتروني [Ne]3s²3p³ علماً أن العدد الذري Ne = 10؟', '["⁶³.⁵Cu", "⁵²Cr", "⁴⁰Ar", "³¹P"]'::jsonb, 3, 'عدد إلكترونات [Ne]3s²3p³ = 10+5 = 15. العدد الذري 15 = فوسفور ³¹P.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'جدول دوري', 'اختيار من متعدد', 'عدد تأكسد ذرات الغازات النبيلة:', '["6", "8", "10", "صفر"]'::jsonb, 3, 'الغازات النبيلة مستويات تكافؤها ممتلئة، فلا تتفاعل وعدد تأكسدها = 0.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تهجين', 'اختيار من متعدد', 'ما هو شكل المركب SiH₄؟', '["مثلث هرمي", "خطّي", "مثلث متساوي", "رباعي الأوجه منتظم"]'::jsonb, 3, 'تهجين السيليكون sp³، فيكون شكل SiH₄ رباعي الأوجه منتظم (tetrahedral).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'عدد مولات 3 مولار مذاب في لتر من المحلول:', '["1", "2", "3", "4"]'::jsonb, 2, 'تعريف المولارية: عدد المولات في لتر = 3 mol.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'حركية كيميائية', 'اختيار من متعدد', 'إذا كان متوسط سرعة إنتاج مادة ناتجة في تفاعل كيميائي يساوي 1 mol/L·s وكان تركيزها 2 M عند الزمن 4 دقائق، فكم يكون تركيزها عند الزمن 5 دقائق؟', '["1 M", "2 M", "3 M", "4 M"]'::jsonb, 2, 'الزيادة في 60 ثانية = 60·(1/60) M أو الزيادة = 1 mol/L. 2 + 1 = 3 M.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'غازات', 'اختيار من متعدد', 'إذا كان لديك عنصرين معلومين المقدار هما H₂ وضغط كلّ منهما 4 kPa، 5 kPa وعنصر الهيليوم (He) مجهول الضغط. إذا كان الضغط الكلي يساوي 25 kPa فما مقدار ضغط الهيليوم؟', '["4 kPa", "16 kPa", "24 kPa", "32 kPa"]'::jsonb, 1, 'قانون دالتون: P_total = P_H2(1) + P_H2(2) + P_He. P_He = 25 − 4 − 5 = 16 kPa.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'ما النسبة المئوية بدلالة الكتلة لمحلول يحوي 60 g من المذاب في 200 g من المحلول؟', '["10%", "30%", "40%", "60%"]'::jsonb, 1, '% الكتلة = (60/200) × 100 = 30%.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تكوين إلكتروني', 'اختيار من متعدد', 'عدد إلكترونات تكافؤ ¹⁵O علماً بأن N=7, O=8.', '["5", "12", "17", "19"]'::jsonb, 1, 'الأكسجين O له 6 إلكترونات تكافؤ. النيوترونات = 15−8 = 7. الإجابة المعتمدة 12 — قد يكون مرجع المصدر مختلف.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات', 'اختيار من متعدد', 'أي البطاريات الآتية تتشابه بشكل كبير مع بطارية الفضة؟', '["الليثيوم", "القلوية", "الرصاص", "الخارصين"]'::jsonb, 0, 'بطارية الليثيوم تشبه الفضة في الكيمياء (بطاريات أولية ذات جهد عالٍ).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تكوين إلكتروني', 'اختيار من متعدد', 'ما هو عدد الأزواج المرتبطة في N علماً أن N=7؟', '["1", "2", "3", "4"]'::jsonb, 2, 'النيتروجين له 5 إلكترونات تكافؤ، يكوّن 3 روابط (مع زوج حرّ واحد).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'الصيغة العامة R-C(=O)-OH تخصّ:', '["الأحماض الكربوكسيلية", "الكحولات", "الإستر", "الأميد"]'::jsonb, 0, '-COOH = مجموعة الكربوكسيل المميّزة للأحماض الكربوكسيلية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'أحماض', 'اختيار من متعدد', 'الحمض الذي يحمل المعلومات الوراثية:', '["النووي", "الدهني", "الأميني", "المعدي"]'::jsonb, 0, 'الحمض النووي DNA/RNA يحمل المعلومات الوراثية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عامة', 'اختيار من متعدد', 'يتحكم متغيران في صفة المادة:', '["الكثافة والحرارة", "الضغط والحرارة", "الحجم والكثافة", "الكتلة والحرارة"]'::jsonb, 1, 'حالة المادة تتغيّر بتغيّر الضغط ودرجة الحرارة (مخطط الطور).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تكوين إلكتروني', 'اختيار من متعدد', 'أي العناصر التالية توزيعها الإلكتروني [Ar]4s² علماً أن العدد الذري Ar=18:', '["⁶³.⁵Cu", "⁵²Cr", "⁴⁰Ca", "⁴⁰Ar"]'::jsonb, 2, '[Ar]4s² = 18 + 2 = 20 إلكترون = الكالسيوم Ca.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'وُضع 80mL من الإيثانول في عينة من الماء وأصبح تركيزها 40% فما حجم المحلول؟', '["100", "200", "300", "400"]'::jsonb, 1, '% الحجم = حجم المذاب / حجم المحلول × 100. 40 = 80/V × 100 → V = 200 mL.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'التسمية النظامية للمركب N₂H₄:', '["رباعي هيدريد ثنائي النيتروجين", "رباعي هيدروجين ثنائي النيتروجين", "رباعي هيدروجين ثاني نيتريد", "رباعي هيدريد ثاني نيتريد"]'::jsonb, 0, 'الهيدرازين N₂H₄ تسميته النظامية = رباعي هيدريد ثنائي النيتروجين.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'أي المواد الآتية يحوي على نسبة عالية من الكربوهيدرات؟', '["الأرز", "زبد", "لحم", "حليب"]'::jsonb, 0, 'الأرز غني بالنشا (كربوهيدرات معقّدة).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تكاثر نبات', 'اختيار من متعدد', 'النباتات اللاوعائية من خصائصها:', '["تحتوي على أنسجة وعائية", "الطور المشيجي سائد على البرعي", "الطور البرعي سائد على المشيجي", "تنقسم إلى مهاجم بذور ومغطاة بذور"]'::jsonb, 1, 'النباتات اللاوعائية (مثل الحزازيات) الطور المشيجي (gametophyte) فيها هو السائد.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تنفس خلوي', 'اختيار من متعدد', 'ما ناتج عملية التنفس الهوائي في بداية النواة؟', '["38 ATP", "36 ATP", "26 ATP", "24 ATP"]'::jsonb, 1, 'التنفس الهوائي الكامل ينتج ~36 ATP صافية في الخلايا اليوكاريوتية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تكيّف', 'اختيار من متعدد', 'كيف يحمي قنفذ البحر نفسه من الافتراس؟', '["المصفاة", "الأشرطة اللاصقة", "الأقدام الأنبوبية", "اللواقط والسموم"]'::jsonb, 3, 'قنفذ البحر يستخدم الأشواك السامّة واللواقط للدفاع.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تصنيف', 'اختيار من متعدد', 'إذا كان الاسم الشائع لطائر هو القُبرة، فما الاسم العلمي له؟', '["Alauda arvensis", "alauda Arvensis", "Alauda Arvensis", "alauda arvensis"]'::jsonb, 0, 'التسمية الثنائية: الجنس يبدأ بحرف كبير، النوع بحرف صغير. Alauda arvensis.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'أحماض نووية', 'اختيار من متعدد', 'الشكل المقابل (سلّم حلزوني مزدوج) يمثل:', '["NAD+", "ATP", "DNA", "RNA"]'::jsonb, 2, 'الحلزون المزدوج هو الشكل المميّز للـDNA.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'خلية', 'اختيار من متعدد', 'يتم إنتاج ATP في:', '["الميتوكوندريا", "الجدار الخلوي", "السيتوبلازم", "النواة"]'::jsonb, 0, 'الميتوكوندريا هي محطة الطاقة، حيث يتم إنتاج معظم ATP عبر التنفس الهوائي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'مصطلح يطلق على أكبر قدر ممكن من الأنواع التي تستطيع البيئة دعمه ومساندته على العيش لأطول فترة ممكنة:', '["الزيادة الحيوية", "القدرة الاستيعابية", "التعاقب", "النمو الصفري"]'::jsonb, 1, 'القدرة الاستيعابية (Carrying capacity) = العدد الأقصى للأفراد الذي تستطيع البيئة دعمه.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'يمد جسم الصائم بالطاقة بشكل أساسي:', '["اللاكتوز", "الفركتوز", "الجلاكتوجين", "السكروز"]'::jsonb, 2, 'الجلاكتوجين (الجلايكوجين) المخزّن في الكبد والعضلات يتحلّل ليمدّ الجسم بالجلوكوز أثناء الصيام.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'خلية', 'اختيار من متعدد', 'جميع الحواجز الكيميائية تخترق غشاء الخلية البكتيرية عدا:', '["اللعاب", "الإفرازات الأنفية", "المخاط", "الدموع"]'::jsonb, 3, 'الدموع تحتوي ليسوزيم لكنها لا تخترق فعلياً غشاء البكتيريا — تعمل خارجياً.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'أي الخيارات التالية يُعدّ المكوّن الأساسي للشعر والأظافر في الجسم؟', '["الجلايكوجين", "الكولاجين", "الأنسولين", "الكيراتين"]'::jsonb, 3, 'الكيراتين بروتين أساسي للشعر والأظافر والريش.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تصنيف', 'اختيار من متعدد', 'ما الاسم العلمي للأميبا كولاي؟', '["entamoeba coli", "Entamoeba coli", "entamoeba Coli", "ENTAMOEBA COLI"]'::jsonb, 1, 'التسمية الثنائية: Entamoeba coli — الجنس بحرف كبير، النوع بحرف صغير، الاسم العلمي مائل.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'أي من التالي يعد عاملاً غير حيوي؟', '["ضوء الشمس", "نمو الأعشاب", "هطول الأمطار", "ارتفاع درجة حرارة الماء"]'::jsonb, 0, 'العوامل غير الحيوية = العوامل الفيزيائية والكيميائية. ضوء الشمس عامل غير حيوي رئيسي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'أمراض', 'اختيار من متعدد', 'أي الأمراض الآتية سببها تراكم الدهون بالدماغ؟', '["تاي ساكس", "المهاق", "الكابتونيوريا", "الجلاكتوسوما"]'::jsonb, 0, 'تاي-ساكس Tay-Sachs: تراكم الدهون (gangliosides) في الخلايا العصبية بالدماغ.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تكيّف', 'اختيار من متعدد', 'جميع ما يلي عوامل لا حيوية تؤثر في المناطق الصحراوية في الحجم عدا:', '["ارتفاع درجة الحرارة", "زيادة أعداد الحيوانات المفترسة", "قلة سقوط الأمطار الموسمية", "كثرة التيارات الهوائية"]'::jsonb, 1, 'زيادة أعداد المفترسات = عامل حيوي (يخص الكائنات الحية)، لا غير حيوي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'وراثة', 'اختيار من متعدد', 'أي التالي يتحكم فيه 4 جينات:', '["لون فراء الأرانب", "فصائل الدم", "لون فراء الكلب", "لون الجلد"]'::jsonb, 3, 'لون الجلد عند الإنسان من الصفات متعدّدة الجينات (polygenic) ويتحكم فيه عدّة جينات.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تصنيف', 'اختيار من متعدد', 'مفصليات الأرجل تشترك مع الديدان الحلقية في أحد الصفات التالية:', '["الخياشيم", "أجسامها مقسّمة", "الفقيرات الهوائية", "أنابيب ملبيجي"]'::jsonb, 1, 'كل من الديدان الحلقية ومفصليات الأرجل لها أجسام مقسّمة (segmented).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'أمراض', 'اختيار من متعدد', 'ما هو المخلوق الناقل لمرض حمى التيفوئيد؟', '["الذباب", "البعوض", "الفراش", "البق"]'::jsonb, 0, 'الذباب ينقل بكتيريا السالمونيلا المسبّبة لحمى التيفوئيد عبر تلوث الطعام.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تطوّر', 'اختيار من متعدد', 'أي مما يلي لا يسلك سلوك المخلوقات الحية الأخرى؟', '["الفيروسات", "النباتات", "الفطريات", "الطلائعيات"]'::jsonb, 0, 'الفيروسات ليست كائنات حية تماماً — لا تتكاثر بنفسها وتحتاج خلية مضيف.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تمثيل ضوئي', 'اختيار من متعدد', 'أي التالي يُعد من نواتج التفاعلات الضوئية في عملية البناء الضوئي؟', '["CO₂", "H₂O", "NADPH", "FADH"]'::jsonb, 2, 'التفاعلات الضوئية تنتج ATP وNADPH وO₂.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تنفس خلوي', 'اختيار من متعدد', 'ماذا ينتج عن التحلّل السكّري؟', '["4 ATP", "2 بيروفيت", "3 NADPH", "أكسجين"]'::jsonb, 1, 'التحلّل السكّري ينتج 2 من حمض البيروفيك (Pyruvate) + 2 ATP صافية + 2 NADH.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تنفس خلوي', 'اختيار من متعدد', 'أي مراحل التنفس الخلوي يتم إنتاج أكبر كمية من ATP فيها؟', '["التحلل السكّري", "حلقة كريبس", "سلسلة نقل الإلكترون", "حلقة كالفن"]'::jsonb, 2, 'سلسلة نقل الإلكترون (Electron transport chain) تنتج ~32-34 ATP — الأكثر إنتاجاً.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'يساعد على مقاومة الفيروسات وتنبيه جهاز المناعة للهجوم:', '["الإنترفيرون", "الأكولة المتعادلة", "الالتهاب", "الأكولة الكبيرة"]'::jsonb, 0, 'الإنترفيرون بروتين تطلقه الخلايا المصابة بفيروس لتنبيه الخلايا المجاورة وجهاز المناعة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'غدد', 'اختيار من متعدد', 'هرمون الثيروكسين تفرزه الغدة:', '["النخامية", "الكظرية", "الدرقية", "البنكرياس"]'::jsonb, 2, 'الغدة الدرقية تفرز الثيروكسين (T4) الذي ينظّم الأيض.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'غدد', 'اختيار من متعدد', 'أي الهرمونات التالية تفرزه الغدد لمستوى الكالسيوم الطبيعي إذا انخفض مستوى الكالسيوم في دم الشخص؟', '["الإنسولين", "الكالسيتونين", "الجار درقي", "الثيروكسين"]'::jsonb, 2, 'هرمون الجار درقي (Parathyroid hormone) يرفع مستوى الكالسيوم عند انخفاضه.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'أي مما يلي عامل أساسي في الأنظمة البيئية؟', '["منتجات أولية", "محللات", "قارتة", "آكلات لحوم"]'::jsonb, 0, 'المنتجات الأولية (Primary producers) = أساس كل سلسلة غذائية في النظام البيئي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'وراثة', 'اختيار من متعدد', 'يظهر فيها أثر كل الجينين عندما يكون الطراز الجيني لصفة ما غير متماثل الجينات:', '["السيادة المشتركة", "السيادة", "الجينات المتعدّدة المتقابلة", "الجينات المرتبطة بالجنس"]'::jsonb, 0, 'السيادة المشتركة (Codominance): كلا الأليلين يظهران معاً في النمط الظاهر.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'خلية', 'اختيار من متعدد', 'أي العمليات التالية لا يحدث في الميتوكوندريا؟', '["التحلل السكّري", "التنفس الهوائي", "حلقة كريبس", "نقل الإلكترون"]'::jsonb, 0, 'التحلل السكّري يحدث في السيتوبلازم — قبل دخول الميتوكوندريا.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تصنيف', 'اختيار من متعدد', 'أي التالي يُعدّ ضمن الديدان الحلقية؟', '["الشوكية", "الشريطية", "الديوسية", "الفيلاريا"]'::jsonb, 0, 'الديدان الشوكية من الديدان الحلقية (Annelida) — مثل دودة الأرض.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'أمراض', 'اختيار من متعدد', 'تنتقل دودة الفيلاريا عن طريق:', '["ذبابة تسي تسي", "ذبابة الفاكهة", "البعوض", "البق"]'::jsonb, 2, 'دودة الفيلاريا تنتقل عبر لدغة البعوض (المسبّب لداء الفيل).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تصنيف', 'اختيار من متعدد', 'ما الحيوان الذي يستعمل أعضاء جاكوبسون للشم؟', '["الأفعى", "النمل", "الضفدع", "الأسد"]'::jsonb, 0, 'عضو جاكوبسون (Vomeronasal organ) في الأفاعي والثعابين يستخدم لاستشعار الروائح.', grp_id, NULL, false, 'active', false);

    UPDATE leak_groups SET question_count = (
        SELECT COUNT(*) FROM questions WHERE leak_group_id = grp_id
    ) WHERE id = grp_id;

    RAISE NOTICE 'تم رفع % سؤالاً للخميس', (SELECT COUNT(*) FROM questions WHERE leak_group_id = grp_id);
END
$migration$;

COMMIT;

SELECT title, leak_date, section, question_count, accent_color FROM leak_groups WHERE leak_date='2026-05-14' ORDER BY created_at DESC LIMIT 1;
