-- ═══════════════════════════════════════════════════════════════
-- تسريبات القدرات – الخميس ١٠ سبتمبر ٢٠٢٦
-- 64 سؤالاً: كمي 40 + لفظي 24 (منها 8 في قطع استيعاب)
-- آمن لإعادة التشغيل: guard على وجود أسئلة المجموعة
-- ═══════════════════════════════════════════════════════════════
BEGIN;

INSERT INTO leak_groups (id, title, leak_date, section, question_count, description, is_active, accent_color)
VALUES ('ad100926-2026-4c00-9d00-100920260001', 'تسريبات القدرات – الخميس ١٠ سبتمبر ٢٠٢٦', '2026-09-10', 'mixed', 64, 'أسئلة اختبار القدرات المحوسب ليوم الخميس ١٠ سبتمبر ٢٠٢٦ (٢٨ ربيع الأول ١٤٤٨) — القسمان الكمي واللفظي مع الشروح.', true, '#8B5CF6')
ON CONFLICT (id) DO NOTHING;

DO $mig$
BEGIN
IF EXISTS (SELECT 1 FROM questions WHERE leak_group_id = 'ad100926-2026-4c00-9d00-100920260001') THEN
  RAISE NOTICE 'أسئلة المجموعة موجودة مسبقاً — تخطي الإدراج';
ELSE
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'طابعة تطبع كتابًا يبدأ ترقيمه من الصفحة ١، وقد طبعت ٢٥٨ رقمًا في ترقيم صفحات الكتاب. كم عدد صفحات الكتاب؟', '["١٢١", "١٢٢", "١٢٣", "١٢٤"]'::jsonb, 1, 'الصفحات ١–٩ تستهلك ٩ أرقام، و١٠–٩٩ تستهلك ٩٠ × ٢ = ١٨٠ رقمًا (المجموع ١٨٩). يبقى ٢٥٨ − ١٨٩ = ٦٩ رقمًا للصفحات ذات الثلاثة أرقام: ٦٩ ÷ ٣ = ٢٣ صفحة، فآخر صفحة = ٩٩ + ٢٣ = ١٢٢.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'مربع طول ضلعه ٦، رُسم عند كل رأس من رؤوسه الأربعة ربع دائرة نصف قطرها ٣ داخل المربع، وظُلّل الجزء المتبقي في الوسط. أوجد مساحة المظلل.', '["٣٠ − ٣π", "٢٤ − ٩π", "٣٦ − ٩π", "١٨ − ٣π"]'::jsonb, 2, 'أرباع الدوائر الأربعة تكوّن معًا دائرة كاملة نصف قطرها ٣ مساحتها ٩π. المظلل = مساحة المربع − ٩π = ٣٦ − ٩π.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep10_q002_star.png', 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'في جدول عن دولة: المساحة ٥٦٠٠٠٠ كم²، والكثافة السكانية ١٤ نسمة لكل كم². أوجد عدد السكان.', '["٧٨٤٠٠٠٠", "٧٨٤٠٠٠", "٤٠٠٠٠", "٤٠٠٠"]'::jsonb, 0, 'عدد السكان = الكثافة × المساحة = ١٤ × ٥٦٠٠٠٠ = ٧٨٤٠٠٠٠ نسمة.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'إذا كان ن عددًا طبيعيًا، فأوجد متوسط الأعداد: ن، ن + ٢، ن + ١٠.', '["٣ن + ٤", "٣ن + ١٢", "ن + ٥", "ن + ٤"]'::jsonb, 3, 'المجموع = ٣ن + ١٢، والمتوسط = (٣ن + ١٢) ÷ ٣ = ن + ٤.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'قطعة أرض مستطيلة بداخلها حديقة على شكل نصف دائرة طول نصف قطرها ١ سم. ما محيط الحديقة؟', '["π", "π + ٢", "π + ٦", "π + ١٢"]'::jsonb, 1, 'محيط نصف الدائرة = نصف محيط الدائرة الكاملة + القطر = (٢π × ١) ÷ ٢ + ٢ = π + ٢.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: مستقيمان يتقاطعان فتتكوّن زاوية ٥٠° أسفل نقطة التقاطع، ويقطعهما مستقيم ثالث من الأعلى فيتكوّن مثلث رأسه نقطة التقاطع. س وص هما الزاويتان الخارجيتان للمثلث عند رأسيه العلويين. أوجد س + ص.', '["٣٠", "٢٣٠", "٢١٠", "٣١٠"]'::jsonb, 1, 'زاوية المثلث عند نقطة التقاطع = ٥٠° (متقابلة بالرأس مع الزاوية السفلية)، فمجموع زاويتي القاعدة = ١٣٠°. الزاوية الخارجية عند كل رأس = ١٨٠ − الداخلية، فمجموع الخارجيتين = ٣٦٠ − ١٣٠ = ٢٣٠°.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep10_q006_x.png', 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'مثلث متساوي الأضلاع محيطه ٢٤ سم، رُسم على أحد أضلاعه (خارج المثلث) نصف دائرة قطرها ذلك الضلع. أوجد مساحة الشكل كله.', '["٢٤ + ١٦π", "١٦√٣ + ١٦π", "١٦√٣ + ٨π", "٨√٣ + ١٦π"]'::jsonb, 2, 'ضلع المثلث = ٢٤ ÷ ٣ = ٨ سم، ومساحته = (√٣/٤) × ٨² = ١٦√٣. نصف الدائرة نصف قطرها ٤ ومساحتها = ½ × π × ٤² = ٨π. المجموع = ١٦√٣ + ٨π.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'في رسم دائري لموظفي شركة: الإداريون ٢٥٪، والمهندسون ٣٥٪، والفنيون ٤٠٪. إذا كان عدد الإداريين ٦٠ موظفًا، فأوجد عدد الفنيين.', '["٦٠", "٧٤", "٨٠", "٩٦"]'::jsonb, 3, '٢٥٪ من الموظفين = ٦٠، فالكل = ٢٤٠ موظفًا، والفنيون = ٤٠٪ × ٢٤٠ = ٩٦.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'طريق فيه ١١ عمود إنارة، والمسافة بين كل عمودين متجاورين ٤٠ م. ما المسافة بين أول عمود وآخر عمود؟', '["٤٥٠", "٤٠٠", "٢٥٠", "٢٠٠"]'::jsonb, 1, 'بين ١١ عمودًا توجد ١٠ فجوات فقط، فالمسافة = ١٠ × ٤٠ = ٤٠٠ م.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'قيم أربع فترات في عام ١٤٢٧: ٩٠، ٨٠، ٤٠، ٤٠. أوجد متوسط عام ١٤٢٧.', '["٦٠", "٦١٫٢", "٦٢٫٥", "٦٥٫٥"]'::jsonb, 2, 'المجموع = ٩٠ + ٨٠ + ٤٠ + ٤٠ = ٢٥٠، والمتوسط = ٢٥٠ ÷ ٤ = ٦٢٫٥.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان الجذر التكعيبي لمجموع (√١٩ + √١٩ + ... + √١٩) يساوي √١٩، فكم مرة تكرر √١٩ داخل الجذر التكعيبي؟', '["٨", "١٨", "١٩", "٣٦١"]'::jsonb, 2, 'المجموع تحت الجذر = (√١٩)³ = ١٩√١٩، أي أن √١٩ تكرر ١٩ مرة.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'أحمد أطول من ماجد بـ٢٠ سم، وماجد أقصر من أخته بـ٥ سم، وطول ماجد ١٢٠ سم. ما مجموع أطوالهم الثلاثة؟', '["٣٣٥", "٣٧٥", "٣٨٥", "٣٩٥"]'::jsonb, 2, 'أحمد = ١٤٠ سم، ماجد = ١٢٠ سم، أخته = ١٢٥ سم، والمجموع = ٣٨٥ سم.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: (٣)⁰
القيمة الثانية: (−٢)³ + (−١)²', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, '(٣)⁰ = ١. و(−٢)³ = −٨ و(−١)² = ١ فمجموعهما −٧. القيمة الأولى أكبر.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل: زاويتان متتامتان إحداهما ٥٠° والأخرى ص. قارن بين:
القيمة الأولى: ٢ص
القيمة الثانية: ١٠٠', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, 'ص = ٩٠ − ٥٠ = ٤٠°، فـ٢ص = ٨٠ وهي أقل من ١٠٠.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ١٠٫١
القيمة الثانية: ٠٫٠٣/٠٫٣ + ٠٫٣/٠٫٠٣', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 2, '٠٫٠٣ ÷ ٠٫٣ = ٠٫١، و٠٫٣ ÷ ٠٫٠٣ = ١٠، ومجموعهما ١٠٫١؛ القيمتان متساويتان.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'ثعبان : زحف', '["سكين : قطع", "عصفور : نقر", "طائرة : طيران", "لاعب : جري"]'::jsonb, 2, 'الزحف طريقة حركة الثعبان، والطيران طريقة حركة الطائرة: شيء وطريقة انتقاله.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'حماس : تهور', '["سخاء : تبذير", "لطف : عطف", "جود : كرم", "شجاعة : خوف"]'::jsonb, 0, 'التهور هو الحماس إذا تجاوز حده، والتبذير هو السخاء إذا تجاوز حده: صفة محمودة والإفراط فيها.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'بقرة : عجل', '["كلب : جرو", "عنكبوت : عقرب", "حصان : فرس", "ضبع : ثعلب"]'::jsonb, 0, 'العجل صغير البقرة، والجرو صغير الكلب: حيوان وصغيره.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'قطر : الجزائر', '["الإمارات : البرازيل", "الكويت : تونس", "عُمان : الأردن", "لبنان : مصر"]'::jsonb, 1, 'قطر دولة خليجية والجزائر دولة مغاربية، والكويت خليجية وتونس مغاربية: الزوج الوحيد الذي يجمع خليجية بمغاربية.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'ربيع : سنة', '["شتاء : صيف", "شمال : جهات", "يوم : ساعة", "شهر : أسبوع"]'::jsonb, 1, 'الربيع أحد فصول السنة الأربعة، والشمال إحدى الجهات الأربع: جزء من مجموعة محددة.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'أسنان : فك', '["أقدام : حوافر", "إطارات : سيارة", "يد : أصابع", "أعمى : أعشى"]'::jsonb, 1, 'الأسنان مثبتة في الفك، والإطارات مثبتة في السيارة: أجزاء متعددة وما تثبت فيه بالترتيب نفسه. أما «يد : أصابع» فالترتيب معكوس.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'لا تكن خلف قناعات ....... حتى تثبت التجارب .......', '["غيرك – سلامتها", "أصدقائك – سلامتها", "الآخرين – صحتها", "نفسك – موثوقيتها"]'::jsonb, 2, 'لا تتبع قناعات الآخرين قبل أن تثبت التجارب صحتها؛ فالزوج المناسب: الآخرين – صحتها.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'أتقن الأداء؛ على أن تأثر المشاهدين بمباراته كان .......', '["محدودًا", "ملحوظًا", "واسعًا", "كبيرًا"]'::jsonb, 0, '«على أن» تفيد الاستدراك، فما بعدها يخالف ما قبلها: أتقن الأداء لكن التأثر كان محدودًا.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'محاولة تخطئة الطرف الآخر في كل ما يقول والبرهنة على ....... الموقف بالكامل ....... للتواصل.', '["سلامة – دعم", "زيغ – غلق", "جنوح – فرع", "صحة – بتر"]'::jsonb, 1, 'تخطئة الآخر في كل شيء تبرهن على زيغ موقفه كله، وهذا يغلق باب التواصل؛ فالزوج المناسب: زيغ – غلق.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'من يتجاهل الإساءة ليس عاجزًا عن ردها، ولكنه عرف المحسن فتجاهله.', '["يتجاهل", "ردها", "المحسن", "عاجزًا"]'::jsonb, 2, 'الذي يُتجاهل هو المسيء لا المحسن؛ فالخطأ في «المحسن» وصوابها «المسيء».', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'يجب ألا تدخل في نيات الناس وأن تكتفي بالظواهر فقط، وذلك يدل على سوء الظن.', '["الظواهر", "سوء", "نيات", "تكتفي"]'::jsonb, 1, 'الاكتفاء بالظواهر وعدم التدخل في النيات يدل على حسن الظن لا سوئه؛ فالخطأ في «سوء».', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'من الأفضل لمدير الشركة أن يسمي شخصًا موثوقًا يفوضه ليقوم بشؤون الشركة بالإنابة عنه عند إيابه.', '["يسمي", "يفوضه", "إيابه", "بالإنابة"]'::jsonb, 2, 'الإنابة تكون عند غياب المدير لا عند إيابه (رجوعه)؛ فالخطأ في «إيابه» وصوابها «غيابه».', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'من كان في خواطره ومجالات فكره دنيئًا حسيًّا لم يكن في سائر أمره إلا كذلك.', '["خواطره", "فكره", "حسيًّا", "سائر"]'::jsonb, 2, 'الوصف الملائم لدناءة الخواطر هو «خسيسًا»؛ فـ«حسيًّا» في غير موضعها.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["مال", "حاد", "حكم", "زاغ"]'::jsonb, 2, 'مال وحاد وزاغ كلها بمعنى انحرف عن الطريق، أما «حكم» فمعناها قضى وفصل.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["مساومة", "ملاكمة", "مصارعة", "مبارزة"]'::jsonb, 0, 'الملاكمة والمصارعة والمبارزة رياضات قتالية، أما المساومة فمفاوضة على السعر.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["حليب", "بيض", "سكر", "عسل"]'::jsonb, 2, 'الحليب والبيض والعسل منتجات حيوانية طبيعية، أما السكر فمنتج نباتي مصنّع.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يُفهم من النص أن التخطيط مفيد لـ:', '["المؤسسة", "القوة", "التشخيص", "الشراكة"]'::jsonb, 2, 'النص صريح: التخطيط للتشخيص يساعد في تحقيق أهداف المنظومة، فالتخطيط يخدم التشخيص.', NULL, 'ad100926-2026-4c00-9d00-100920260001', 'e1a91001-2026-4c00-9d00-000000000001', 'التشخيص عملية مهمة للفرد، يمكنه فيها أن يحدد نقاط القوة ومواضعها ونقاط الضعف ومكامنها. ويندرج تحت التشخيص التخطيط، والتخطيط أمر مهم فيه؛ فالتخطيط للتشخيص يساعد في تحقيق أهداف المنظومة، ويجب أن يكون التخطيط من خلال: معرفة نقاط القوة والضعف، وترتيب الأمور حسب الأولوية.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'ما المقصود بـ«التنزه في عقول الناس»؟', '["مرافقة البسطاء", "التحدث مع الناس", "قراءة ما يكتبه الآخرون", "معرفة ما يفكرون به"]'::jsonb, 2, 'التنزه في عقول الناس كناية عن القراءة: فالكتب هي عقول أصحابها المكتوبة، ومن يقرؤها يتجول فيها.', NULL, 'ad100926-2026-4c00-9d00-100920260001', 'e1a91002-2026-4c00-9d00-000000000002', 'قيل للمأمون: ما ألذ الأشياء؟ قال: «التنزه في عقول الناس».', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يقصد المأمون في الجملة:', '["الأسفار", "الرحلات", "الصيد", "القراءة"]'::jsonb, 3, 'المتعة التي وصفها المأمون بالتنزه في عقول الناس هي القراءة والاطلاع على ما كتبوه.', NULL, 'ad100926-2026-4c00-9d00-100920260001', 'e1a91002-2026-4c00-9d00-000000000002', 'قيل للمأمون: ما ألذ الأشياء؟ قال: «التنزه في عقول الناس».', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'كيف تأهبت الشركات الطبية للاستفادة من اكتشافات الأحياء البحرية؟', '["إنسانية طبية", "صناعية تجارية", "إنسانية تجارية", "بحرية صناعية"]'::jsonb, 1, 'النص يذكر أن الشركات استنفرت للإفادة من الاكتشافات وتوزيعها على مستوى تجاري، أي تأهب صناعي تجاري.', NULL, 'ad100926-2026-4c00-9d00-100920260001', 'e1a91003-2026-4c00-9d00-000000000003', 'كانت استخدامات الأحياء البحرية في البداية للملبس والمأكل والعيش، ثم اكتشف العلماء أن في بعض النباتات البحرية موادّ تعالج الأمراض المستعصية. فاستنفرت الشركات الطبية للإفادة من اكتشافات الأحياء البحرية وتوزيعها على مستوى تجاري.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'نستنتج من النص أن أقصى مقدار للرصد الذي وصل إليه البشر هو تقريبًا:', '["١٥٫٥ بليون سنة ضوئية", "١٦٫٥ بليون سنة ضوئية", "١٧٫٥ بليون سنة ضوئية", "١٨٫٥ بليون سنة ضوئية"]'::jsonb, 2, 'الانفجار يبعد ٩ بلايين سنة ضوئية وهي تقريبًا نصف أقصى مسافة رُصدت، فأقصى مدى الرصد يقارب ١٧٫٥ بليون سنة ضوئية.', NULL, 'ad100926-2026-4c00-9d00-100920260001', 'e1a91004-2026-4c00-9d00-000000000004', 'رصد العلماء من خلال تلسكوبات في نيو مكسيكو ضوءًا خافتًا جدًا من بعيد، تبيّن أنه انفجار يبعد عنا نحو ٩ بلايين سنة ضوئية، وهي تقريبًا نصف المسافة التي استطاع البشر أن يصلوا إليها بالرصد، فهذه المسافة تزيد عن نصف الحافة المرئية للكون. وهو من أسطع الانفجارات التي حصلت، ومثل هذه الانفجارات لا يمكن قياسها بالمنظار ثنائي العينين.
ولو حصل هذا الانفجار على نصف هذه المسافة لكان في المنطقة التي يمكننا فيها رصد الإشعاع، ولأثّر على الأرض والبشرية كما تؤثر أشعة الشمس.
وأشعة جاما نوعان: طويلة المدى وقصيرة المدى، وهي ظاهرة كونية نادرة وعنيفة تصدر فيها انبعاثات قوية، ومصدرها جسم مشع بعيد جدًا في الكون، وقد التقطت التلسكوبات هذه الانبعاثات بدقة عالية مما سمح للعلماء بدراسة خصائصها الفريدة.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'ما أنسب عنوان للقطعة؟', '["دفقات جاما", "أسطع الانفجارات", "كويكبة الكرير", "المراصد الفلكية"]'::jsonb, 1, 'محور النص انفجار وُصف بأنه من أسطع الانفجارات وأبعدها، فالعنوان الجامع: أسطع الانفجارات.', NULL, 'ad100926-2026-4c00-9d00-100920260001', 'e1a91004-2026-4c00-9d00-000000000004', 'رصد العلماء من خلال تلسكوبات في نيو مكسيكو ضوءًا خافتًا جدًا من بعيد، تبيّن أنه انفجار يبعد عنا نحو ٩ بلايين سنة ضوئية، وهي تقريبًا نصف المسافة التي استطاع البشر أن يصلوا إليها بالرصد، فهذه المسافة تزيد عن نصف الحافة المرئية للكون. وهو من أسطع الانفجارات التي حصلت، ومثل هذه الانفجارات لا يمكن قياسها بالمنظار ثنائي العينين.
ولو حصل هذا الانفجار على نصف هذه المسافة لكان في المنطقة التي يمكننا فيها رصد الإشعاع، ولأثّر على الأرض والبشرية كما تؤثر أشعة الشمس.
وأشعة جاما نوعان: طويلة المدى وقصيرة المدى، وهي ظاهرة كونية نادرة وعنيفة تصدر فيها انبعاثات قوية، ومصدرها جسم مشع بعيد جدًا في الكون، وقد التقطت التلسكوبات هذه الانبعاثات بدقة عالية مما سمح للعلماء بدراسة خصائصها الفريدة.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'علاقة الفقرة الثانية بالفقرة الأولى:', '["تعليل لظواهرها", "تحديد أهدافها", "تفسير لمضمونها", "تلخيص لها"]'::jsonb, 2, 'الفقرة الثانية توضح ما يعنيه بُعد الانفجار وأثره الافتراضي لو كان أقرب، فهي تفسير لمضمون الأولى.', NULL, 'ad100926-2026-4c00-9d00-100920260001', 'e1a91004-2026-4c00-9d00-000000000004', 'رصد العلماء من خلال تلسكوبات في نيو مكسيكو ضوءًا خافتًا جدًا من بعيد، تبيّن أنه انفجار يبعد عنا نحو ٩ بلايين سنة ضوئية، وهي تقريبًا نصف المسافة التي استطاع البشر أن يصلوا إليها بالرصد، فهذه المسافة تزيد عن نصف الحافة المرئية للكون. وهو من أسطع الانفجارات التي حصلت، ومثل هذه الانفجارات لا يمكن قياسها بالمنظار ثنائي العينين.
ولو حصل هذا الانفجار على نصف هذه المسافة لكان في المنطقة التي يمكننا فيها رصد الإشعاع، ولأثّر على الأرض والبشرية كما تؤثر أشعة الشمس.
وأشعة جاما نوعان: طويلة المدى وقصيرة المدى، وهي ظاهرة كونية نادرة وعنيفة تصدر فيها انبعاثات قوية، ومصدرها جسم مشع بعيد جدًا في الكون، وقد التقطت التلسكوبات هذه الانبعاثات بدقة عالية مما سمح للعلماء بدراسة خصائصها الفريدة.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'أي الجمل الآتية لا تتوافق مع معنى عبارة «يصدر ضوءًا باهتًا»؟', '["رأيت الماسة زرقاء اللون", "يصدر المصباح ضوءًا متموجًا", "أصبح لون النباتات أخضر نضيرًا", "تراكم زبد البحر على الشاطئ"]'::jsonb, 3, 'الجمل الثلاث الأولى تصف لونًا أو ضوءًا كما تصف العبارة ضوءًا باهتًا، أما تراكم الزبد فلا صلة له بالضوء أو اللون.', NULL, 'ad100926-2026-4c00-9d00-100920260001', 'e1a91004-2026-4c00-9d00-000000000004', 'رصد العلماء من خلال تلسكوبات في نيو مكسيكو ضوءًا خافتًا جدًا من بعيد، تبيّن أنه انفجار يبعد عنا نحو ٩ بلايين سنة ضوئية، وهي تقريبًا نصف المسافة التي استطاع البشر أن يصلوا إليها بالرصد، فهذه المسافة تزيد عن نصف الحافة المرئية للكون. وهو من أسطع الانفجارات التي حصلت، ومثل هذه الانفجارات لا يمكن قياسها بالمنظار ثنائي العينين.
ولو حصل هذا الانفجار على نصف هذه المسافة لكان في المنطقة التي يمكننا فيها رصد الإشعاع، ولأثّر على الأرض والبشرية كما تؤثر أشعة الشمس.
وأشعة جاما نوعان: طويلة المدى وقصيرة المدى، وهي ظاهرة كونية نادرة وعنيفة تصدر فيها انبعاثات قوية، ومصدرها جسم مشع بعيد جدًا في الكون، وقد التقطت التلسكوبات هذه الانبعاثات بدقة عالية مما سمح للعلماء بدراسة خصائصها الفريدة.', 4, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'أوجد قيمة: (−٦) × ٢ + ١', '["−١٢", "−١١", "١٠", "٥"]'::jsonb, 1, 'الضرب أولًا: (−٦) × ٢ = −١٢، ثم نضيف ١ فيصبح الناتج −١١.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان ٢٠^ل = ١٦، و١٠^م = ٢٠، و٤^ن = ١٠، فأوجد قيمة ل × م × ن.', '["٨", "٢٠", "٢", "١٠"]'::jsonb, 2, 'نعوض بالتسلسل: ١٦ = ٢٠^ل = (١٠^م)^ل = (٤^ن)^(م ل) = ٤^(ل م ن). وبما أن ١٦ = ٤²، فإن ل × م × ن = ٢.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'يبين الشكل المجاور عدد الطلاب في أربعة أعوام. أوجد نسبة الزيادة من عام ١٤٣٠ إلى عام ١٤٣٣.', '["٢٠٪", "٢٥٪", "١٠٪", "١٥٪"]'::jsonb, 0, 'عام ١٤٣٠ = ١٢٥ وعام ١٤٣٣ = ١٥٠، فالزيادة ٢٥ ونسبتها إلى الأصل = ٢٥ ÷ ١٢٥ = ٢٠٪.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep10_q042_bars.png', 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان ١٠ × ١٠ × س = ٥ × ٥ × ٥ × ٥ × ص، قارن بين:
القيمة الأولى: س
القيمة الثانية: ص', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 3, '١٠٠س = ٦٢٥ص أي س = ٦٫٢٥ص. إن كانت ص موجبة فـس أكبر، وإن كانت سالبة فـس أصغر، وإن كانت صفرًا تساويا؛ فالمعطيات غير كافية.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'يبين الجدول لأربع سيارات: المسافة المقطوعة (كم) وأجرة السائق والتكلفة الكلية (ريال): الأولى ١٠٠٠ / ٦٠٠ / ١١٠٠، الثانية ١٨٠٠ / ٤٠٠ / ١١٥٠، الثالثة ١٥٠٠ / ٥٠٠ / ١٢٥٠، الرابعة ١٢٠٠ / ٥٠٠ / ١٥٠٠. إذا كان سعر لتر الوقود ٥ ريالات، فما أكثر سيارة موفرة للوقود؟', '["الأولى", "الثانية", "الثالثة", "الرابعة"]'::jsonb, 1, 'تكلفة الوقود = التكلفة − أجرة السائق، وعدد اللترات = تكلفة الوقود ÷ ٥. الأولى: ٥٠٠ ريال = ١٠٠ لتر لـ١٠٠٠ كم (١٠ كم/لتر)؛ الثانية: ٧٥٠ = ١٥٠ لترًا لـ١٨٠٠ كم (١٢ كم/لتر)؛ الثالثة: ١٥٠ لترًا لـ١٥٠٠ كم (١٠)؛ الرابعة: ٢٠٠ لتر لـ١٢٠٠ كم (٦). الثانية تقطع أكبر مسافة باللتر.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'يبين الجدول عدد المتقدمين والمقبولين في جامعة: ٢٠١٠: ٣٠٠٠ متقدم و١٥٠ مقبول، ٢٠١١: ٤٥٠٠ و٣٥٠٠، ٢٠١٢: ٥٠٠٠ و١٦٠، ٢٠١٣: ٨٥٠٠ و١٧٠، ٢٠١٤: ٦٠٠٠ و٥٠٠. في أي عام كان عدد المقبولين أقل من ٣٪ من عدد المتقدمين؟', '["٢٠١٠", "٢٠١١", "٢٠١٢", "٢٠١٣"]'::jsonb, 3, 'نحسب ٣٪ من المتقدمين ونقارن بالمقبولين: ٢٠١٠: ٩٠ والمقبولون ١٥٠ (أكثر)؛ ٢٠١٢: ١٥٠ والمقبولون ١٦٠ (أكثر)؛ ٢٠١٣: ٢٥٥ والمقبولون ١٧٠ فقط (أقل من ٣٪).', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كانت العبارة ٢س² + ١١س + ١٥ تعبر عن مساحة مستطيل عرضه (س + ٣)، فما طوله؟', '["٢س + ٣", "س + ٣", "٢س + ٥", "س + ٥"]'::jsonb, 2, 'الطول = المساحة ÷ العرض. نحلل: ٢س² + ١١س + ١٥ = (س + ٣)(٢س + ٥) لأن ٣ × ٥ = ١٥ و٣ × ٢س + ٥ × س = ١١س؛ فالطول ٢س + ٥.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'قال أب: «عمري قبل ١٠ سنوات يساوي أربعة أمثال عمر ابني الآن، وعمر ابني بعد سنتين ١٢ سنة». فما عمر الأب الآن؟', '["٣٠", "٤٠", "٥٠", "٦٠"]'::jsonb, 2, 'عمر الابن الآن = ١٢ − ٢ = ١٠ سنوات، فعمر الأب قبل ١٠ سنوات = ٤ × ١٠ = ٤٠، وعمره الآن ٥٠.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'يبين الشكل المجاور عدد الزوار (بالآلاف) لأربع مدن خلال الأعوام ١٤٣٠ إلى ١٤٣٤. أي المدن في زيادة مطردة؟', '["مكة", "المدينة", "الطائف", "عسير"]'::jsonb, 2, 'الزيادة المطردة تعني أن العدد يرتفع كل عام عن الذي قبله دون أي نزول، وهذا يتحقق للطائف وحدها (١٥ ثم ١٧ ثم ٢٠ ثم ٢٢ ثم ٢٤)، بينما بقية المدن تذبذبت.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep10_q048_cities.png', 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'كم عددًا يمكن تكوينه من الأرقام (١، ٢، ٣، ٥) بدون تكرار؟', '["٢٤", "٣٢", "٥٤", "٦٤"]'::jsonb, 3, 'نجمع الأعداد بكل الأطوال: من رقم واحد ٤ أعداد، ومن رقمين ٤ × ٣ = ١٢، ومن ثلاثة أرقام ٤ × ٣ × ٢ = ٢٤، ومن أربعة أرقام ٢٤ أيضًا؛ المجموع ٦٤.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'يبين الشكل المجاور مبيعات محل (بالآلاف) من أربعة أصناف خلال أربعة أشهر. إذا كان سعر ٤ حبات خبز ٦ ريالات، فأوجد قيمة مبيعات الخبز في شهر شوال.', '["٨٠٠٠٠", "٩٠٠٠٠", "١٠٠٠٠٠", "١٢٠٠٠٠"]'::jsonb, 3, 'من الشكل: مبيعات الخبز في شوال ٨٠ ألف حبة. سعر الحبة = ٦ ÷ ٤ = ١٫٥ ريال، فالقيمة = ٨٠٠٠٠ × ١٫٥ = ١٢٠٠٠٠ ريال.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep10_q050_sales.png', 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'في مستودع ١٢٠ جهازًا: ٣٥ منها تالفة جزئيًا و٤٥ تالفة كليًا. ما نسبة الأجهزة غير التالفة؟', '["٣٠٪", "٣٣٪", "٤٠٪", "٦٧٪"]'::jsonb, 1, 'غير التالفة = ١٢٠ − ٣٥ − ٤٥ = ٤٠ جهازًا، ونسبتها = ٤٠ ÷ ١٢٠ = الثلث ≈ ٣٣٪.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', '(√٣٦ ÷ (٢ × ٣)) × (س/٢ + س/٣ + س/٦) = .....', '["س/٦", "س/٢", "س/٣", "س"]'::jsonb, 3, '√٣٦ = ٦ و٢ × ٣ = ٦ فالعامل الأول = ١. أما س/٢ + س/٣ + س/٦ فبمقام موحد ٦: (٣س + ٢س + س)/٦ = س. الناتج س.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: مثلث رأس زاويته القائمة هو مركز الدائرة. إذا علمت أن مساحة الدائرة ٤٠π ومساحة المثلث ٣٠، فأوجد مساحة الجزء المظلل.', '["٣٠ − ٤٠π", "٣٠ − ١٠π", "٤٠π + ٣٠", "١٠π + ٣٠"]'::jsonb, 1, 'الزاوية القائمة عند المركز تحصر داخل المثلث ربع الدائرة بالضبط، ومساحته ٤٠π ÷ ٤ = ١٠π. المظلل هو ما بقي من المثلث خارج الدائرة = ٣٠ − ١٠π.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep10_q053_circle_tri.png', 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ٤١
القيمة الثانية: (٤ + ٣)² − (٤ − ٢)^(−٣)', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, '(٤ + ٣)² = ٤٩، و(٤ − ٢)^(−٣) = ٢^(−٣) = ١/٨. فالقيمة الثانية = ٤٩ − ١/٨ = ٤٨٫٨٧٥ وهي أكبر من ٤١.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'إذا كان ١٠ ريالات = دينار واحد، وشخص لديه ٧٧٧٧ ريالًا يريد تحويلها إلى دنانير من فئة ٢٠ دينارًا، فكم ورقة يحصل عليها من التحويل؟', '["٣٩", "٣٤", "٣٦", "٣٨"]'::jsonb, 3, '٧٧٧٧ ريالًا = ٧٧٧٫٧ دينار. عدد أوراق فئة ٢٠ = ٧٧٧٫٧ ÷ ٢٠ = ٣٨٫٨ أي ٣٨ ورقة كاملة (٣٩ ورقة تحتاج ٧٨٠ دينارًا).', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'يخطط أحمد لإحاطة حديقة مستطيلة الشكل بسياج طوله ٤٥ و٣/٤ مترًا. إذا كان عرض الحديقة ١٠ و١/٢ متر، فما طولها؟', '["١٢ و٣/١٨", "١٢ و١/٤", "١٢ و١/٢", "١٢ و٣/٨"]'::jsonb, 3, 'المحيط = ٢ × (الطول + العرض)، فالطول + العرض = ٤٥٫٧٥ ÷ ٢ = ٢٢٫٨٧٥، والطول = ٢٢٫٨٧٥ − ١٠٫٥ = ١٢٫٣٧٥ أي ١٢ و٣/٨ مترًا.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'زجاجتان بلاستيكيتان، حجم الأولى أكبر من حجم الثانية. قارن بين:
القيمة الأولى: المساحة السطحية للزجاجة الأولى
القيمة الثانية: المساحة السطحية للزجاجة الثانية', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 3, 'الحجم الأكبر لا يعني بالضرورة مساحة سطحية أكبر؛ فشكل الزجاجة (طويلة رفيعة أو قصيرة عريضة) يغير المساحة السطحية دون معرفة الأبعاد. المعطيات غير كافية.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'يمثل الشكل المجاور استهلاك الكهرباء (بالكيلوواط) في الفترتين الصباحية والمسائية لكل يوم من أيام الأسبوع، بنقطتين لكل يوم. ما إجمالي الاستهلاك يوم الثلاثاء؟', '["١٠", "٢٥", "١٥", "٣٠"]'::jsonb, 1, 'عند يوم الثلاثاء نقطتان: الأولى عند ٢٠ والثانية عند ٥، ومجموعهما ٢٥ كيلوواط.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep10_q058_dots.png', 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كانت ٢^(س + ١) = ٦، فإن ١٦^س = .....', '["٢", "٣", "١٢", "٨١"]'::jsonb, 3, '٢^(س + ١) = ٢ × ٢^س = ٦ فـ٢^س = ٣. و١٦^س = (٢⁴)^س = (٢^س)⁴ = ٣⁴ = ٨١.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ١٠٠٠٠
القيمة الثانية: (٩٩٩٩)² ÷ ١٠٠٠٠', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, '٩٩٩٩ أصغر من ١٠٠٠٠، فـ٩٩٩٩ × ٩٩٩٩ أصغر من ٩٩٩٩ × ١٠٠٠٠، وعند القسمة على ١٠٠٠٠ يبقى الناتج أصغر من ٩٩٩٩، أي أصغر من ١٠٠٠٠. القيمة الأولى أكبر.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: أربعة مستطيلات متجاورة، مساحات ثلاثة منها ٢٠ و١٢ و١٨ كما هو مبين، وداخل الرابع مثلث قاعدته ضلعه السفلي ورأسه على ضلعه العلوي. أوجد مساحة الجزء المظلل.', '["١٨", "١٥", "١٢", "٢٠"]'::jsonb, 1, 'المستطيلان العلويان يشتركان في الارتفاع والسفليان كذلك، والمستطيلان الأيمنان يشتركان في العرض. لذا: مساحة الرابع = ٢٠ × ١٨ ÷ ١٢ = ٣٠. المثلث الأبيض قاعدته وارتفاعه هما بعدا المستطيل فمساحته نصفه = ١٥، والمظلل = ٣٠ − ١٥ = ١٥.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep10_q061_grid.png', 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'دائرة محيطها ١٠٠ سم، وقطاع منها زاويته المركزية ٣٦°. أوجد طول قوس هذا القطاع.', '["١٢", "٨", "٤", "١٠"]'::jsonb, 3, 'طول القوس = (الزاوية المركزية ÷ ٣٦٠) × المحيط = (٣٦ ÷ ٣٦٠) × ١٠٠ = ١٠ سم.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كانت (ل + ٢) ÷ (ل − ٤) = صفر، فإن ل − ١ = .....', '["٢", "٣", "−٢", "−٣"]'::jsonb, 3, 'الكسر يساوي صفرًا عندما يكون البسط صفرًا والمقام غير صفري: ل + ٢ = ٠ فـل = −٢، والمقام عندها −٦ لا يساوي صفرًا. إذًا ل − ١ = −٣.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان المتوسط الحسابي للعددين س و٤/س يساوي ٢، فإن س تساوي:', '["صفر", "٣", "٢", "١"]'::jsonb, 2, 'المتوسط = (س + ٤/س) ÷ ٢ = ٢، فـس + ٤/س = ٤. بالضرب في س: س² − ٤س + ٤ = ٠ أي (س − ٢)² = ٠، فـس = ٢.', NULL, 'ad100926-2026-4c00-9d00-100920260001', NULL, NULL, NULL, 'active', false);
END IF;
END
$mig$;

-- مزامنة العداد مع الواقع
UPDATE leak_groups
SET question_count = (SELECT COUNT(*) FROM questions WHERE leak_group_id = 'ad100926-2026-4c00-9d00-100920260001')
WHERE id = 'ad100926-2026-4c00-9d00-100920260001';

-- تحقق نهائي
DO $chk$
DECLARE n INT; nq INT; nv INT; np INT;
BEGIN
  SELECT COUNT(*) INTO n FROM questions WHERE leak_group_id = 'ad100926-2026-4c00-9d00-100920260001';
  SELECT COUNT(*) INTO nq FROM questions WHERE leak_group_id = 'ad100926-2026-4c00-9d00-100920260001' AND section = 'quant';
  SELECT COUNT(*) INTO nv FROM questions WHERE leak_group_id = 'ad100926-2026-4c00-9d00-100920260001' AND section = 'verbal';
  SELECT COUNT(*) INTO np FROM questions WHERE leak_group_id = 'ad100926-2026-4c00-9d00-100920260001' AND passage_id IS NOT NULL;
  RAISE NOTICE 'إجمالي: % — كمي: % — لفظي: % — قطع: %', n, nq, nv, np;
  IF n <> 64 THEN RAISE EXCEPTION 'عدد الأسئلة % لا يطابق المتوقع 64', n; END IF;
  IF nq <> 40 OR nv <> 24 THEN RAISE EXCEPTION 'توزيع كمي/لفظي غير مطابق'; END IF;
END
$chk$;

COMMIT;