-- ═══════════════════════════════════════════════════════════════
-- تسريبات القدرات – الأربعاء ٢٦ أغسطس ٢٠٢٦
-- 102 سؤالاً: كمي 52 + لفظي 50 (منها 19 في قطع استيعاب)
-- آمن لإعادة التشغيل: guard على وجود أسئلة المجموعة
-- ═══════════════════════════════════════════════════════════════
BEGIN;

INSERT INTO leak_groups (id, title, leak_date, section, question_count, description, is_active, accent_color)
VALUES ('ad260826-2026-4c00-9d00-260820260001', 'تسريبات القدرات – الأربعاء ٢٦ أغسطس ٢٠٢٦', '2026-08-26', 'mixed', 102, 'أسئلة اختبار القدرات المحوسب ليوم الأربعاء ٢٦ أغسطس ٢٠٢٦ (١٤ ربيع الأول ١٤٤٨) — القسمان الكمي واللفظي مع الشروح.', true, '#6D28D9')
ON CONFLICT (id) DO NOTHING;

DO $mig$
BEGIN
IF EXISTS (SELECT 1 FROM questions WHERE leak_group_id = 'ad260826-2026-4c00-9d00-260820260001') THEN
  RAISE NOTICE 'أسئلة المجموعة موجودة مسبقاً — تخطي الإدراج';
ELSE
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'أوجد ناتج: (١٤٣٧² − ٢٠١٥²) ÷ (١٤٣٧ + ٢٠١٥) − (١٤٣٧ − ٢٠١٥)', '["−١", "٠", "١", "−١١٥٦"]'::jsonb, 1, 'بفرق المربعين: (١٤٣٧² − ٢٠١٥²) = (١٤٣٧ − ٢٠١٥)(١٤٣٧ + ٢٠١٥)، فالكسر يختصر إلى (١٤٣٧ − ٢٠١٥). يبقى: (١٤٣٧ − ٢٠١٥) − (١٤٣٧ − ٢٠١٥) = ٠ دون حساب أي مربع.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'صندوق به ٤ كرات حمراء و٣ صفراء و٥ بيضاء، فما احتمال سحب كرة غير بيضاء عشوائيًا؟', '["٥/١٢", "٧/١٢", "٣/١٢", "٤/١٢"]'::jsonb, 1, 'مجموع الكرات ١٢، وغير البيضاء = ٤ + ٣ = ٧ كرات، فالاحتمال = ٧/١٢.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: مثلث متطابق الضلعين، وامتداد ساقه اليمنى يصنع مع امتداد القاعدة زاوية قياسها ٧٠°. أوجد قيمة هـ.', '["٧٠", "١١٠", "٤٠", "٦٠"]'::jsonb, 2, 'الزاوية ٧٠° تقابل بالرأس زاوية القاعدة الداخلية فهي ٧٠° أيضًا، ولتطابق الضلعين تكون زاويتا القاعدة ٧٠° و٧٠°. إذن هـ = ١٨٠ − ١٤٠ = ٤٠°.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug26_q03_isosceles_70.png', 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'إذا كان ٠٫٧٪ من عدد يساوي ٢١، ما هذا العدد؟', '["٣٠٠", "٣٠٠٠", "٣٠٠٠٠", "٣"]'::jsonb, 1, 'العدد = ٢١ ÷ ٠٫٠٠٧ = ٢١٠٠٠ ÷ ٧ = ٣٠٠٠.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'إذا كان ٢^١٥ يقبل القسمة على س، فأي القيم الآتية يمكن أن يكون قيمة س؟', '["٣٢", "٣٠", "٢٠", "١٢"]'::jsonb, 0, 'قواسم ٢^١٥ كلها قوى للعدد ٢. الخيار ٣٢ = ٢⁵ فيقبل القسمة عليه، أما ٣٠ و٢٠ و١٢ ففيها عوامل (٣ أو ٥) لا توجد في ٢^١٥.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان س² − ص² = ل، و س + ص = م، أوجد قيمة س − ص.', '["ل م", "ل + م", "ل ÷ م", "م ÷ ل"]'::jsonb, 2, 'س² − ص² = (س − ص)(س + ص)، أي ل = (س − ص) × م، ومنها س − ص = ل ÷ م.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان هناك ١٥ ورقة نقدية من فئتي الريال و٥ ريالات، وكان عدد الأوراق من فئة ٥ ريالات يساوي مثلي عدد الأوراق من فئة الريال، فكم المبلغ الكلي؟', '["٨٠", "٦٠", "٧٠", "٥٥"]'::jsonb, 3, 'نفرض أوراق الريال ن فأوراق الخمسة ٢ن، والمجموع ٣ن = ١٥ فيكون ن = ٥. المبلغ = ٥ × ١ + ١٠ × ٥ = ٥ + ٥٠ = ٥٥ ريالًا.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'مطعم به طاولات بقائمة واحدة وكراسٍ بثلاث قوائم، وكل طاولة حولها ٤ كراسٍ. إذا كان مجموع القوائم ٦٥، فما عدد الكراسي؟', '["٢٠", "٢٤", "١٥", "١٠"]'::jsonb, 0, 'كل طاولة مع كراسيها الأربعة: ١ + ٤ × ٣ = ١٣ قائمة. عدد الطاولات = ٦٥ ÷ ١٣ = ٥، فعدد الكراسي = ٥ × ٤ = ٢٠.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'اشترى رجل ثلاثة عطور: الأول بكامل السعر، والثاني بنصف السعر، والثالث بربع السعر، وكان المجموع ١٤٠٠ ريال. كم سعر العطر الأول؟', '["٨٠٠", "٦٠٠", "٧٠٠", "٤٠٠"]'::jsonb, 0, 'لو سعر الأول س فالمجموع = س + س/٢ + س/٤ = (٧/٤)س = ١٤٠٠، ومنها س = ١٤٠٠ × ٤ ÷ ٧ = ٨٠٠ ريال.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'في المدرسة، إذا كان كل ١٥ طالبًا يشرف عليهم معلمان، فكم عدد المعلمين إذا كان عدد الطلاب ٤٥٠؟', '["٦٥", "٦٠", "١٢٠", "٣٠"]'::jsonb, 1, 'عدد المجموعات = ٤٥٠ ÷ ١٥ = ٣٠ مجموعة، ولكل مجموعة معلمان: ٣٠ × ٢ = ٦٠ معلمًا.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور مثلثان متشابهان، فما قيمة س؟', '["٩", "٨", "٧", "٦"]'::jsonb, 0, 'بتقابل الرأسين تتناظر الأضلاع: ٨ مع ١٢، و(س + ١) مع (٢س − ٣). من التناسب: ٨/١٢ = (س + ١)/(٢س − ٣)، فنحصل على ٨(٢س − ٣) = ١٢(س + ١)، أي ١٦س − ٢٤ = ١٢س + ١٢، ومنها ٤س = ٣٦ فتكون س = ٩.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug26_q16_bowtie_similar.png', 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'ينام شخص ٨ ساعات يوميًا، ما الكسر الذي يمثل عدد ساعات نومه في الأسبوع؟', '["١/٣", "١/٢", "١/٦", "٢/٣"]'::jsonb, 0, 'نسبة النوم ثابتة يوميًا: ٨/٢٤ = ١/٣، وبالأسبوع كذلك: ٥٦ ساعة نوم من ١٦٨ ساعة = ١/٣.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: حجم مكعب طول حرفه ٢ سم
القيمة الثانية: ثلث حجم متوازي مستطيلات أبعاده ١٢ سم و٨ سم و٦ سم', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, 'حجم المكعب = ٢³ = ٨ سم³. حجم متوازي المستطيلات = ١٢ × ٨ × ٦ = ٥٧٦ سم³ وثلثه ١٩٢ سم³، فالقيمة الثانية أكبر بكثير.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug26_q19_box_cube.png', 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: طول قطر الدائرة = ١٠ سم، وارتفاع عمودي طوله س يصل القطر بالدائرة عند نقطة تبعد ١ سم عن طرف القطر. أوجد قيمة س.', '["٣", "٤", "٥", "٦"]'::jsonb, 0, 'نصف القطر ٥، والنقطة تبعد عن المركز ٥ − ١ = ٤. بفيثاغورس في المثلث الواصل من المركز: س = √(٥² − ٤²) = √٩ = ٣ سم.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug26_q20_circle_chord.png', 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'دائرتان متحدتا المركز، والزاوية المركزية المرسومة قياسها ٦٠°. قارن بين:
القيمة الأولى: طول القوس (أ جـ) على الدائرة الكبرى
القيمة الثانية: طول القوس (ب د) على الدائرة الصغرى', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'القوسان مقابلان لنفس الزاوية المركزية، وطول القوس يتناسب مع نصف القطر؛ ونصف قطر الكبرى أطول فقوسها أطول.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug26_q21_concentric.png', 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'فتح شخص كتاب الرياضيات فكان مجموع رقمي الصفحتين المتقابلتين ٦١، فأي الخيارات الآتية رقم ممكن لإحدى الصفحتين؟', '["٣١", "٣٢", "٣٣", "٣٤"]'::jsonb, 0, 'الصفحتان المتقابلتان متتاليتان: ن + (ن + ١) = ٦١ فيكون ن = ٣٠ والصفحتان ٣٠ و٣١؛ الممكن من الخيارات ٣١.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'يبين الشكل المجاور أعداد سنتي ١٤٢٧ و١٤٢٨ في أربع مجموعات. أوجد متوسط عام ١٤٢٧.', '["٦٠", "٦١٫٢", "٦٢٫٥", "٦٥٫٥"]'::jsonb, 2, 'قيم ١٤٢٧ هي: ٩٠ و٨٠ و٤٠ و٤٠، ومجموعها ٢٥٠. المتوسط = ٢٥٠ ÷ ٤ = ٦٢٫٥.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug26_q23_double_bars.png', 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: المسافة التي يقطعها عداء بسرعة ١٠٠ م/د في ٣ ساعات
القيمة الثانية: المسافة التي يقطعها عداء بسرعة ٨٠ م/د في ٤ ساعات', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, 'الأولى: ١٠٠ × ١٨٠ دقيقة = ١٨٠٠٠ م. الثانية: ٨٠ × ٢٤٠ دقيقة = ١٩٢٠٠ م. الثانية أكبر.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: مستطيل طوله ضعف عرضه، وطول قطره √٥. احسب محيط المستطيل.', '["٣", "٤", "٦", "١٠"]'::jsonb, 2, 'لو العرض س فالطول ٢س، وبفيثاغورس: س² + ٤س² = ٥، أي ٥س² = ٥ فتكون س = ١. الأبعاد ١ و٢ والمحيط = ٢(١ + ٢) = ٦.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug26_q25_rect_diag.png', 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'تسمح حديقة بدخول ٩٠ شخصًا من الرجال والنساء والأطفال، فإذا كان سعر تذكرة الطفل ٢٠٠ ريال وإجمالي مبيعات تذاكر الأطفال ٦٠٠٠ ريال، وكان عدد الرجال نصف عدد النساء، فأوجد عدد الرجال.', '["١٠", "٢٠", "٣٠", "٤٠"]'::jsonb, 1, 'عدد الأطفال = ٦٠٠٠ ÷ ٢٠٠ = ٣٠، فيبقى للرجال والنساء ٦٠. الرجال نصف النساء: ن + ن/٢ = ٦٠ فالنساء ٤٠ والرجال ٢٠.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'محل عصائر لديه نوعان من العصير (مانجو – برتقال)، بكم طريقة يمكن لهند أن تشتري ٤ أكواب عصير؟', '["٢", "٥", "٨", "١٠"]'::jsonb, 1, 'يكفي تحديد عدد أكواب المانجو من الأربعة: ٠ أو ١ أو ٢ أو ٣ أو ٤، والباقي برتقال؛ فهذه ٥ طرق.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور مثلثان متقابلان بالرأس وقاعدتاهما متوازيتان، فأوجد قيمة س.', '["٤", "٥", "٦", "٩"]'::jsonb, 3, 'التوازي مع التقابل بالرأس يجعل المثلثين متشابهين، والضلعان الواقعان على مستقيم واحد متناظران: س يقابل ٣، و٦ يقابل ٢. من التناسب: س/٣ = ٦/٢ فتكون س = ٩ سم.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug26_q29_bowtie_vertical.png', 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: دائرة ظُلل جميعها عدا قطاع قياس زاويته ٣٦°، وكانت مساحة الجزء المظلل = ٩٠ط. قارن بين:
القيمة الأولى: مساحة الجزء غير المظلل
القيمة الثانية: ٩ط', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'المظلل يمثل ٣٦٠ − ٣٦ = ٣٢٤ درجة. مساحة الدائرة كلها = ٩٠ط × ٣٦٠ ÷ ٣٢٤ = ١٠٠ط، فغير المظلل = ١٠ط وهو أكبر من ٩ط.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug26_q31_circle_36.png', 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'إذا كانت مساحة المربع أ ب جـ د = ١٠٠، والنقاط المعلمة على الأضلاع منتصفاتها، أوجد مساحة الجزء المظلل.', '["٢٠", "٢٥", "٣٠", "٤٠"]'::jsonb, 1, 'توصيل المنتصفات المتقابلة يقسم المربع أربعة مربعات متطابقة، والمظلل واحد منها = ١٠٠ ÷ ٤ = ٢٥.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug26_q33_square_quarter.png', 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: المتوسط الحسابي للأعداد ٣^٤٠ و ٩^٢٠ و ٨١^١٠
القيمة الثانية: ٣^٤٠', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 2, 'نوحد الأسس: ٩^٢٠ = (٣²)^٢٠ = ٣^٤٠، و٨١^١٠ = (٣⁴)^١٠ = ٣^٤٠. فالأعداد الثلاثة متساوية ومتوسطها يساوي كلًّا منها = ٣^٤٠.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كانت س³ = ٣٤٣، أوجد قيمة س.', '["٣", "٥", "٦", "٧"]'::jsonb, 3, '٧ × ٧ = ٤٩، و٤٩ × ٧ = ٣٤٣؛ إذن س = ٧.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'خمسة أعداد أصغرها ٢، والمتوسط عدد صحيح، والمنوال ٧، والوسيط ٦. أوجد المتوسط.', '["٥", "٦", "٧", "٨"]'::jsonb, 0, 'بالترتيب: [٢، س، ٦، ٧، ٧] حتى يكون الوسيط ٦ والمنوال ٧. المجموع = ٢٢ + س ويجب أن يقبل القسمة على ٥، والوحيد الممكن بين ٢ و٦ هو س = ٣. المجموع ٢٥ والمتوسط ٥.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ١٢٥٪ من ٣٥
القيمة الثانية: ٣٥٪ من ١٢٥', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 2, 'النسبة المئوية ضرب: أ٪ من ب = أ × ب ÷ ١٠٠، والضرب إبدالي؛ فالقيمتان متساويتان (كلتاهما ٤٣٫٧٥).', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كانت −(س/٢)^(−٣) = ٨، فأوجد قيمة س.', '["−١", "١", "٢", "١/٢"]'::jsonb, 0, 'من المعادلة: (س/٢)^(−٣) = −٨، أي (٢/س)³ = −٨، فيكون ٢/س = −٢ ومنها س = −١. وبالتحقق: (−١/٢)^(−٣) = (−٢)³ = −٨ وسالبها ٨.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ٠٫٩
القيمة الثانية: ١/١٠', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, '١/١٠ = ٠٫١، و٠٫٩ أكبر منها بوضوح.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان أ − ب = ٥، و ب − جـ = ٣، و جـ + د = ١، فما قيمة أ + د؟', '["٥", "٩", "٣", "٧"]'::jsonb, 1, 'بجمع المعادلات الثلاث تحذف ب وجـ: (أ − ب) + (ب − جـ) + (جـ + د) = أ + د = ٥ + ٣ + ١ = ٩.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان مع محمد ١٩٥ ريالًا من فئات ٥ و١٠ و٥٠ ريالًا، وعدد الأوراق من كل فئة متساوٍ، فكم عدد الأوراق من كل فئة؟', '["١", "٢", "٣", "٤"]'::jsonb, 2, 'كل ثلاثية أوراق (واحدة من كل فئة) قيمتها ٥ + ١٠ + ٥٠ = ٦٥ ريالًا، وعدد الثلاثيات = ١٩٥ ÷ ٦٥ = ٣.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ١١/١١١
القيمة الثانية: ٠٫١', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, '٠٫١ = ١١٫١/١١١، وبسط القيمة الأولى ١١ أصغر من ١١٫١ على المقام نفسه؛ فالقيمة الثانية أكبر.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'في الشكل المجاور شبكة من ١٠ مربعات ظُلل منها ٣. ما عدد المربعات التي يجب تظليلها إضافة حتى تصبح نسبة المظلل إلى مجموع المربعات ٤ : ٥؟', '["٢", "٣", "٤", "٥"]'::jsonb, 3, 'النسبة ٤ : ٥ من عشرة مربعات تعني ٨ مربعات مظللة. المظلل حاليًّا ٣، فنحتاج ٨ − ٣ = ٥ مربعات إضافية.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug26_q42_grid_shade.png', 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: مثلث أ ب جـ فيه قياس زاوية ب = ٨٠°، والزاوية الخارجية عند جـ = ١٣٠°. قارن بين:
القيمة الأولى: طول أ ب
القيمة الثانية: طول ب جـ', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 2, 'الداخلية عند جـ = ١٨٠ − ١٣٠ = ٥٠°، فزاوية أ = ١٨٠ − ٨٠ − ٥٠ = ٥٠°. تساوت زاويتا أ وجـ فيتساوى الضلعان المقابلان لهما: ب جـ = أ ب.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug26_q43_tri_80_130.png', 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان س⁵/٣٦ = ٤ ÷ (١/٢ × ٩)، فأوجد قيمة س.', '["٢", "٤", "٦", "٨"]'::jsonb, 0, 'الطرف الأيمن: ٤ ÷ ٤٫٥ = ٨/٩. إذن س⁵ = ٣٦ × ٨ ÷ ٩ = ٣٢ = ٢⁵، فتكون س = ٢.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'أي الأعداد التالية يمكن كتابته على صورة ٣ن، حيث ن عدد صحيح؟', '["٣٢", "٤٣", "٥٧", "٦٢"]'::jsonb, 2, 'نبحث عن مضاعف للعدد ٣: مجموع رقمي ٥٧ هو ١٢ ويقبل القسمة على ٣ (٥٧ = ٣ × ١٩)، وبقية الخيارات لا تقبل.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'إذا أجاب طالب على ٣٠ سؤالًا في الاختبار وهي تمثل ٦٠٪ من الأسئلة، كم عدد الأسئلة التي لم يجب عنها؟', '["١٠", "١٥", "٢٠", "٣٠"]'::jsonb, 2, 'عدد الأسئلة الكلي = ٣٠ ÷ ٠٫٦ = ٥٠ سؤالًا، فلم يجب عن ٥٠ − ٣٠ = ٢٠ سؤالًا.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'التحليل', 'اختيار من متعدد', 'يبين الجدول معدل التضخم في عدة دول بين ٢٠٠٣ و٢٠٠٧. في أي عام كان معدل التضخم في دول اليورو أكبر منه في دول مجلس التعاون؟', '["٢٠٠٣", "٢٠٠٥", "٢٠٠٦", "٢٠٠٧"]'::jsonb, 0, 'نقارن الصفين الأخيرين عامًا بعام: في ٢٠٠٣ اليورو ٢٫٢ مقابل ١٫٦ للمجلس فقط، وفي بقية الأعوام معدل المجلس أعلى.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug26_q46_inflation_table.png', 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'التحليل', 'اختيار من متعدد', 'نقاط في المستوى الإحداثي م، ن، ج، ل، ف تمثل قرى: إذا كانت ل تقع شرق م وغرب ن، و ج تقع جنوب شرق ن، و م تقع جنوب شرق ف، فأي حرف يقع في أقصى الغرب؟', '["ف", "ج", "ن", "ل"]'::jsonb, 0, 'ل شرق م يعني م أغرب من ل ومن ن وج التي تقع شرقًا أبعد. وم جنوب شرق ف يعني ف شمال غرب م أي أغرب منها؛ فأقصى الغرب ف.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'احسب قيمة: ١^١ + ١^٢ + ١^٣ + ١^٤ + ..... + ١^١٤٣٣', '["صفر", "٢", "١", "١٤٣٣"]'::jsonb, 3, 'الواحد مرفوعًا لأي أس يساوي ١، والمجموع ١٤٣٣ حدًّا قيمة كل منها ١، فالناتج ١٤٣٣.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'رسوم مدرسة كانت ١٠٠٠٠ ريال فزادت ١٥٪، ويوجد تخفيض ٥٪ للإخوة. كم الرسوم لأخوين؟', '["١١٨٠٠", "٢١٨٥٠", "٢٢٨٠٠", "٢٤٠٠٠"]'::jsonb, 1, 'بعد الزيادة: ١٠٠٠٠ × ١٫١٥ = ١١٥٠٠ للطالب. لأخوين ٢٣٠٠٠، وبعد خصم ٥٪: ٢٣٠٠٠ × ٠٫٩٥ = ٢١٨٥٠ ريالًا.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'سيارتان تحركتا في نفس الوقت من المدينة (أ) إلى المدينة (ب): الأولى عبر طريق نصف دائري نصف قطره ١٠٠ كم ووصلت بعد ساعتين ونصف، والثانية عبر الطريق المستقيم (القطر) ووصلت بعد ساعتين. قارن بين:
القيمة الأولى: سرعة السيارة ٢
القيمة الثانية: سرعة السيارة ١', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, 'مسافة السيارة ١ = نصف المحيط = ١٠٠ط ≈ ٣١٤ كم، وسرعتها ≈ ٣١٤ ÷ ٢٫٥ ≈ ١٢٥٫٦ كم/س. مسافة السيارة ٢ = القطر = ٢٠٠ كم وسرعتها ١٠٠ كم/س. سرعة السيارة ١ أكبر.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug26_q50_semicircle_paths.png', 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ٩ − ٠٫٠٠٤
القيمة الثانية: ٩ − ٠٫٠٤٤', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'المطروح في الأولى ٠٫٠٠٤ أصغر من ٠٫٠٤٤، فالباقي في الأولى أكبر.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان س + (١/س) = ٢ + (١/٢)، فأوجد قيمة س من الخيارات.', '["٣", "٤", "١/٢", "١/٣"]'::jsonb, 2, 'الصورة س + ١/س تتحقق بالعدد ومقلوبه: فالحلان س = ٢ أو س = ١/٢ لأن ١/٢ + ٢ = ٢٫٥ أيضًا. المتاح في الخيارات ١/٢.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كانت س > ٢، قارن بين:
القيمة الأولى: س
القيمة الثانية: (س + س) ÷ س', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'القيمة الثانية = ٢س ÷ س = ٢ دائمًا، وس أكبر من ٢ بالفرض؛ فالأولى أكبر.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'نسبة عدد الأطفال إلى الرجال إلى النساء في قرية ١ : ٣ : ٥ على التوالي، وبعد إضافة ٢٠ طفلًا جديدًا أصبحت نسبة الأطفال إلى الرجال ١ : ٢. فكم عددهم الكلي بعد الإضافة؟', '["٣٨٠", "٣٦٠", "٢٨٠", "٣٤٠"]'::jsonb, 0, 'نفرض الوحدة ك: الأطفال ك والرجال ٣ك والنساء ٥ك. بعد الإضافة: (ك + ٢٠)/(٣ك) = ١/٢، فيكون ٢ك + ٤٠ = ٣ك ومنها ك = ٤٠. الكلي = ٩ك + ٢٠ = ٣٨٠.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'ضُبطت ساعة حائط على الساعة ٨ صباحًا، وكانت تتأخر ٢٠ دقيقة كل ساعة. إذا كان الوقت الفعلي ٨ مساءً، فكم يكون الوقت في تلك الساعة؟', '["٥ مساءً", "٦ مساءً", "٨ مساءً", "٤ مساءً"]'::jsonb, 3, 'مرت ١٢ ساعة فعلية، والتأخير = ١٢ × ٢٠ = ٢٤٠ دقيقة أي ٤ ساعات؛ فتعرض الساعة ٨ − ٤ = ٤ مساءً.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'إذا كانت السنة ٣٦٦ يومًا وبدأت يوم الخميس، فمتى تنتهي؟', '["الاثنين", "الثلاثاء", "الجمعة", "السبت"]'::jsonb, 2, '٣٦٦ = ٥٢ أسبوعًا كاملًا + يومان. اليوم ٣٦٥ يوافق خميسًا (تمام ٥٢ أسبوعًا + يوم أول)، فاليوم ٣٦٦ هو الجمعة. ومن يحسبها يومين بعد الخميس يقع في خطأ اليوم الواحد الشائع.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور شكل رباعي فيه زاويتان قائمتان عند أ و جـ، وقياس الزاوية عند د = ٢س. إذا كان س = ٣٠، فما قياس زاوية ب؟', '["٦٠", "١٢٠", "٣٠", "١٥٠"]'::jsonb, 1, 'مجموع زوايا الرباعي ٣٦٠°: ٩٠ + ٩٠ + ٢(٣٠) + ب = ٣٦٠، فيكون ب = ٣٦٠ − ٢٤٠ = ١٢٠°.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_aug26_q56_kite.png', 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'إذا كان ثمن العلبة الصغيرة سعة ١٫١٤ لتر هو ٤ ريالات، وثمن العلبة الكبيرة سعة ٢٫٢ لتر هو ٧ ريالات، قارن بين:
القيمة الأولى: سعر اللتر في العلبة الصغيرة
القيمة الثانية: سعر اللتر في العلبة الكبيرة', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'الصغيرة: ٤ ÷ ١٫١٤ ≈ ٣٫٥١ ريال/لتر. الكبيرة: ٧ ÷ ٢٫٢ ≈ ٣٫١٨ ريال/لتر. سعر اللتر في الصغيرة أعلى.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان ٢٥٪ من س أكبر من ٥٠، فكل القيم الآتية يمكن أن تساويها س ما عدا:', '["١٨٠", "٢٨٠", "٣٨٠", "٤٨٠"]'::jsonb, 0, 'الشرط: ربع س أكبر من ٥٠ أي س أكبر من ٢٠٠. كل الخيارات تحقق ذلك عدا ١٨٠.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'عسل : نحل', '["ديوان : كتب", "ماء : ثلج", "زبدة : لبن", "كتاب : مكتبة"]'::jsonb, 2, 'العسل يُستخرج من النحل كما تُستخرج الزبدة من اللبن؛ منتج من مصدره. أما الماء من الثلج فتحول لنفس المادة.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'إشراك : إسلام', '["إخراج : قدوم", "إكرام : إسراف", "إدناء : إقصاء", "إقبال : إسراع"]'::jsonb, 2, 'الإشراك ضد الإسلام، والإدناء (التقريب) ضد الإقصاء (الإبعاد)؛ علاقة تضاد.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'سحاب : مطر', '["رياح : ضباب", "أشجار : ظل", "ماء : ترسب", "احتياج : أمان"]'::jsonb, 1, 'السحاب مصدر ينتج عنه المطر، والأشجار مصدر ينتج عنه الظل.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'شجرة : نبات', '["كهرباء : طاقة", "شيب : بياض", "سقوط : تأرجح", "أشجار : أوراق"]'::jsonb, 0, 'الشجرة نوع من جنس النبات، والكهرباء نوع من جنس الطاقة.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'علم : مبنى', '["تاج : رأس", "غصن : ثمرة", "دولة : عاصمة", "سلاح : جندي"]'::jsonb, 0, 'العلم يُرفع فوق المبنى في أعلاه، كما يوضع التاج فوق الرأس.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'ابن : عائلة', '["غرفة : منزل", "سيارة : إطار", "فأس : خشب", "زوج : أبناء"]'::jsonb, 0, 'الابن فرد من العائلة والغرفة جزء من المنزل؛ جزء من كل بالاتجاه نفسه. أما سيارة : إطار فمعكوسة.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'نعمة : نقمة', '["يقظة : رقاد", "أباد : أزال", "خوف : فزع", "رسالة : خطاب"]'::jsonb, 0, 'النعمة ضد النقمة واليقظة ضد الرقاد؛ أما بقية الأزواج فمترادفات.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'كتابة : صقل', '["مداواة : علة", "نصرة : استغاثة", "تقويم : اعوجاج", "خلل : معالجة"]'::jsonb, 3, 'الكتابة تحتاج إلى صقل يحسنها، والخلل يحتاج إلى معالجة تصلحه؛ الاتجاه محفوظ (الشيء ثم ما يُصلحه). بقية الأزواج معكوسة: الفعل قبل المشكلة.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'يجب أن ....... المسيء من ذوي القربى، لأن ....... حثك على العفو.', '["تسامح – الدين", "تعاقب – العقل", "تجادل – الخلق", "تقاطع – الكرم"]'::jsonb, 0, 'سياق العفو المطلوب مع الأقارب يستدعي المسامحة، والحاث عليها هو الدين.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'تُعرف قيمة الأشياء بأضدادها؛ فلولا المرض لما عرفت قيمة الصحة، ولولا ....... لما استمتعت .......', '["التعب – بالراحة", "الأماني – بالتفاؤل", "النوم – بالعمل", "الحب – بالعاطفة"]'::jsonb, 0, 'القاعدة المطروحة هي الضد يُظهر ضده: فكما عرّف المرضُ الصحةَ، يعرّف التعبُ لذةَ الراحة.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'تميز بما شئت ولكن لا ....... أبدًا.', '["تكذب", "تتخاذل", "تتكبر", "تسخر"]'::jsonb, 2, 'آفة التميز التي يحذر منها السياق هي الترفع على الناس؛ فالنهي الأنسب: لا تتكبر.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'لا تقود السيارة بـ....... سرعة حتى لا ....... أرواح الأبرياء.', '["أقصى – تُزهَق", "أكثر – تزيد", "أدنى – تُنقَذ", "أعلى – تُحمَى"]'::jsonb, 0, 'التحذير من القيادة بأقصى سرعة، والنتيجة المخوف منها إزهاق الأرواح؛ فالزوج المستقيم: أقصى – تُزهَق.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'خطب يزيد يومًا فاستغلق عليه الكلام، فنزل عن المنبر وقال: أنتم إلى أمير ....... أحوج منكم إلى أمير .......', '["فعّال – قوّال", "عادل – مائل", "رحيم – غافل", "فاضل – متسامح"]'::jsonb, 0, 'المقابلة بين العمل والكلام: حاجة الناس إلى أمير يفعل أشد من حاجتهم إلى أمير يجيد القول؛ فالزوج: فعّال – قوّال.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'عند الشدائد تعرف .......', '["أعداءك", "أصحابك", "الحسنات", "السيئات"]'::jsonb, 1, 'الشدة محك يكشف الصديق الحقيقي ممن سواه؛ فعندها تعرف أصحابك.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'إذا كان الشغل ....... فالفراغ .......', '["مصلحة – منقبة", "مشقة – مفسدة", "ربحًا – خسارة", "جهدًا – راحة"]'::jsonb, 1, 'الحكمة تقابل بين تعب مأمون العاقبة وفراغ مذموم: إن كان الشغل مشقة فإن الفراغ مفسدة.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', '....... تزداد عظمتها أو قيمتها كلما مر عليك .......', '["الصحة – المرض", "الفضة – الوقت", "الألماس – الضيق", "الصدقة – الزمن"]'::jsonb, 0, 'كل مرور بالمرض يذكرك بقدر الصحة فيرفع قيمتها عندك؛ فالزوج المتسق: الصحة – المرض.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«إن لم تركب السفن لن تنال الرغائب»', '["تركب", "السفن", "تنال", "الرغائب"]'::jsonb, 1, 'المثل الأصل: من لم يركب الأهوال لم ينل الرغائب؛ فالمقصود ركوب الأخطار لا السفن.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«إذا أردت السعادة عليك الابتعاد عن الذي ينفع النفس والناس»', '["السعادة", "الابتعاد", "ينفع", "الناس"]'::jsonb, 2, 'لا يستقيم أن يكون طريق السعادة هجر النافع؛ فالمراد الابتعاد عن الذي يضر النفس والناس.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«لنعلم أن السلوكيات المنتشرة في المجتمع تحتاج تصحيحًا»', '["لنعلم", "المنتشرة", "المجتمع", "تحتاج"]'::jsonb, 1, 'ليس كل منتشر خطأً يحتاج تصحيحًا؛ إنما التي تحتاج التصحيح هي السلوكيات الخاطئة.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«من الكلام كلام لا ترجو خطأه وتخشى عاقبته فهو الداء العضال»', '["كلام", "خطأه", "عاقبته", "العضال"]'::jsonb, 1, 'المقابلة تكون بين رجاء الخير وخشية العاقبة؛ فالصواب: لا ترجو خيره وتخشى عاقبته.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«إن الطمع يجعل الغني فقيرًا، لأنه مثل الذي يشرب من ماء النهر كلما كثر شربه زاد عطشه»', '["الطمع", "فقيرًا", "يشرب", "النهر"]'::jsonb, 3, 'ماء النهر عذب يروي شاربه، أما الذي يزيد العطش كلما شرب منه فهو ماء البحر المالح.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«النجاح بقية اجتهاد مستمر»', '["النجاح", "بقية", "اجتهاد", "مستمر"]'::jsonb, 1, 'النجاح ثمرة الاجتهاد لا بقيته؛ فالكلمة الصحيحة: نتيجة اجتهاد مستمر.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«يظل النحل يختار رحيق الأزهار ليصنع أطيب وأشهى شراب، كذلك الإنسان يختار مناوئه ليصنع أخلاقه»', '["النحل", "الأزهار", "أشهى", "مناوئه"]'::jsonb, 3, 'كما ينتقي النحل أطيب الرحيق ينتقي الإنسان أصفياءه الذين تُصنع بصحبتهم أخلاقه؛ لا مناوئيه أي خصومه.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حدد الكلمة التي لا يتفق معناها مع سياق الجملة:
«معلومات الشبكة العنكبوتية كثيرة ومنافعها نزيرة إذا أُحسن استخدامها»', '["نزيرة", "معلومات", "منافعها", "استخدامها"]'::jsonb, 0, 'حسن الاستخدام يجعل المنافع وفيرة لا قليلة؛ فالصواب: منافعها غزيرة، والنزر هو القليل.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["أحمر", "أصفر", "أزرق", "أسود"]'::jsonb, 3, 'الأحمر والأصفر والأزرق ألوان أساسية تُمزج منها بقية الألوان، وليس الأسود منها.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["حقل", "سكة", "درب", "جادة"]'::jsonb, 0, 'السكة والدرب والجادة أسماء للطريق، أما الحقل فأرض تُزرع.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["فالح", "ظافر", "خالد", "بسام"]'::jsonb, 3, 'فالح وظافر وخالد على وزن فاعل، أما بسام فصيغة مبالغة على وزن فعّال.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["كمين", "فخ", "خديعة", "هزيمة"]'::jsonb, 3, 'الكمين والفخ والخديعة وسائل يوقع بها بالخصم، أما الهزيمة فنتيجة تلحق به.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["قميص", "ثوب", "سروال", "عمامة"]'::jsonb, 3, 'القميص والثوب والسروال تُلبس على الجسد، أما العمامة فتوضع على الرأس.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["غزال", "دولفين", "حوت", "سمك"]'::jsonb, 0, 'الدولفين والحوت والسمك حيوانات مائية، أما الغزال فبري.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة مما يلي:', '["محافظة", "قرية", "عاصمة", "إقليم"]'::jsonb, 2, 'المحافظة والقرية والإقليم تقسيمات إدارية للمكان، أما العاصمة فصفة وظيفية تُطلق على مدينة الحكم.', NULL, 'ad260826-2026-4c00-9d00-260820260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'النص يدل على:', '["نظرية", "خاطرة", "حقيقة علمية", "فرضية فيزيائية"]'::jsonb, 3, 'النص يفسر حركة الكرة بقوى مفترضة تفسيرًا فيزيائيًا قابلًا للاختبار؛ فهو فرضية فيزيائية.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82601-2026-4c00-9d00-000000000001', 'عندما نركل الكرة فإننا نعطيها قوة باتجاهين: إلى الأعلى وإلى الأمام، ثم تبتعد الكرة عنا فلا تتلقى منا مزيدًا من القوة، لكن تستمر قوتان في التأثير عليها: قوة الاحتكاك التي تبطئ سرعتها إلى الأمام، وقوة الجاذبية التي تؤثر عليها من الأعلى إلى الأسفل.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'من الذي ينصحك النص بتركه؟', '["كثير القناعة", "قليل الهمة", "قليل العزيمة", "قليل المعرفة"]'::jsonb, 0, 'الذي أُمرنا بالتكبير عليه أربعًا هو المقاوم للتغيير الراضي بالقليل، أي القانع بوضعه الذي لا يطلب المزيد.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82602-2026-4c00-9d00-000000000002', 'من كان جاهلًا فعلّمه، ومن تنقصه الإرادة فحفّزه، ومن ضل الطريق فوجّهه بتجاربك، لكن المقاوم للتغيير الراضي بالقليل فكبّر عليه أربعًا، فلا تذهب نفسك عليهم حسرات.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'من الذي يحتاج إلى تحفيز؟', '["قليل العزيمة", "قليل المعرفة", "فاقد المعنويات", "صاحب العزيمة"]'::jsonb, 0, 'النص خصص التحفيز لمن تنقصه الإرادة، أي قليل العزيمة. أما قليل المعرفة فعلاجه التعليم.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82602-2026-4c00-9d00-000000000002', 'من كان جاهلًا فعلّمه، ومن تنقصه الإرادة فحفّزه، ومن ضل الطريق فوجّهه بتجاربك، لكن المقاوم للتغيير الراضي بالقليل فكبّر عليه أربعًا، فلا تذهب نفسك عليهم حسرات.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'ما الصفة التي يذمها النص؟', '["الجمود", "الأنانية", "البخل", "الفوقية"]'::jsonb, 0, 'الوحيد الذي يئس منه النص هو مقاوم التغيير، ومقاومة التغيير هي الجمود.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82602-2026-4c00-9d00-000000000002', 'من كان جاهلًا فعلّمه، ومن تنقصه الإرادة فحفّزه، ومن ضل الطريق فوجّهه بتجاربك، لكن المقاوم للتغيير الراضي بالقليل فكبّر عليه أربعًا، فلا تذهب نفسك عليهم حسرات.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'ما الذي يحث عليه الكاتب؟', '["نشر التجارب والعلم", "الثبات على الرأي", "معاملة الناس حسب احتياجاتهم", "تحمل المسؤولية"]'::jsonb, 2, 'النص يصف لكل صنف علاجه: الجاهل بالتعليم، وناقص الإرادة بالتحفيز، والضال بالتوجيه؛ فهو يحث على معاملة كل إنسان بما يحتاجه.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82602-2026-4c00-9d00-000000000002', 'من كان جاهلًا فعلّمه، ومن تنقصه الإرادة فحفّزه، ومن ضل الطريق فوجّهه بتجاربك، لكن المقاوم للتغيير الراضي بالقليل فكبّر عليه أربعًا، فلا تذهب نفسك عليهم حسرات.', 4, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يوجه النص إلى:', '["نقل المعارف والتجارب", "تحمل الخطأ", "الثبات على الرأي", "تحمل المسؤولية"]'::jsonb, 0, 'قوله «علّمه» و«وجّهه بتجاربك» دعوة صريحة إلى نقل ما عندك من معرفة وتجربة للآخرين.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82602-2026-4c00-9d00-000000000002', 'من كان جاهلًا فعلّمه، ومن تنقصه الإرادة فحفّزه، ومن ضل الطريق فوجّهه بتجاربك، لكن المقاوم للتغيير الراضي بالقليل فكبّر عليه أربعًا، فلا تذهب نفسك عليهم حسرات.', 5, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'أنسب عنوان للنص:', '["الاستفادة من الخبرات السابقة", "تحمل المسؤولية", "البحث عن الأخطاء", "التمسك بالرأي"]'::jsonb, 0, 'مدار النص على توظيف تجاربك وخبراتك في تعليم الناس وتوجيههم؛ فأنسب عنوان: الاستفادة من الخبرات السابقة.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82602-2026-4c00-9d00-000000000002', 'من كان جاهلًا فعلّمه، ومن تنقصه الإرادة فحفّزه، ومن ضل الطريق فوجّهه بتجاربك، لكن المقاوم للتغيير الراضي بالقليل فكبّر عليه أربعًا، فلا تذهب نفسك عليهم حسرات.', 6, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'الضمير في (بها) يعود على:', '["الصبّار", "التفاح", "الأشياء", "المستقبل"]'::jsonb, 2, 'التقدير: كي لا يصدمك المستقبل بالأشياء التي جهلت أصلها؛ فالضمير يعود على الأشياء.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82603-2026-4c00-9d00-000000000003', 'لا تتوقع من نبتة الصبّار أن تثمر لك التفاح، حاول أن تعرف أصل الأشياء وماضيها كي لا يصدمك المستقبل بها.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'مضمون القطعة يدل على:', '["الصبر", "الفطنة", "القوة", "الحكمة"]'::jsonb, 1, 'معرفة أصول الأشياء وتوقع ما تثمره قبل وقوعه هو الفطنة التي يدعو إليها النص.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82603-2026-4c00-9d00-000000000003', 'لا تتوقع من نبتة الصبّار أن تثمر لك التفاح، حاول أن تعرف أصل الأشياء وماضيها كي لا يصدمك المستقبل بها.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'مقابل (تلوث):', '["لهو", "نقاء", "رخاء", "ارتكاب"]'::jsonb, 1, 'ضد تلوث النفوس صفاؤها ونقاؤها؛ فالمقابل: نقاء.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82604-2026-4c00-9d00-000000000004', 'لا مكان للمنعزلين في هذا العالم؛ تحاول الدول المتقدمة التقدم بالعلم. الحكومة الواعية تحاول الوصول للهدف المنشود لرخاء شعبها، والحذر الشديد من ارتكاب النقائص وتلوث النفوس وعدم صفوها.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'أي مما يلي يمكن استبداله بكلمة (تلوث) دون أن يتغير المعنى؟', '["فساد", "خمول", "صفاء", "ضعف"]'::jsonb, 0, 'تلوث النفوس معناه فسادها، فالبديل الذي يحفظ المعنى هو الفساد. أما الخمول فمعناه الكسل ولا يؤدي المعنى.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82604-2026-4c00-9d00-000000000004', 'لا مكان للمنعزلين في هذا العالم؛ تحاول الدول المتقدمة التقدم بالعلم. الحكومة الواعية تحاول الوصول للهدف المنشود لرخاء شعبها، والحذر الشديد من ارتكاب النقائص وتلوث النفوس وعدم صفوها.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', '(لرخاء شعبها) تفيد:', '["التعليل", "التشبيه", "التوكيد", "التعريف"]'::jsonb, 0, 'اللام هنا لام التعليل: تسعى الحكومة للهدف المنشود من أجل رخاء شعبها.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82604-2026-4c00-9d00-000000000004', 'لا مكان للمنعزلين في هذا العالم؛ تحاول الدول المتقدمة التقدم بالعلم. الحكومة الواعية تحاول الوصول للهدف المنشود لرخاء شعبها، والحذر الشديد من ارتكاب النقائص وتلوث النفوس وعدم صفوها.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'ما النتائج المترتبة على ارتكاب الذنوب وعدم صفو النفوس؟', '["الرفاهية", "ارتفاع المستوى المعيشي", "انخفاض المستوى المعيشي", "القناعة"]'::jsonb, 2, 'النص جعل الحذر من النقائص وتلوث النفوس شرطًا لبلوغ الرخاء؛ فارتكابها يفضي إلى ضده: انخفاض المستوى المعيشي.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82604-2026-4c00-9d00-000000000004', 'لا مكان للمنعزلين في هذا العالم؛ تحاول الدول المتقدمة التقدم بالعلم. الحكومة الواعية تحاول الوصول للهدف المنشود لرخاء شعبها، والحذر الشديد من ارتكاب النقائص وتلوث النفوس وعدم صفوها.', 4, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'الإنسان في القرارات الكبيرة يكون:', '["مترددًا", "حاسمًا", "متسرعًا", "لا مباليًا"]'::jsonb, 0, 'النص يفتتح بأن الإنسان في حيرة من أمره في القرارات الكبيرة، والحيرة هي التردد.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82605-2026-4c00-9d00-000000000005', 'الإنسان يكون في حيرة من أمره في القرارات الكبيرة؛ يعتمد العقل تارة وأحيانًا تحكمه العاطفة. في الحياة يجب أن يكون العقل هو القبطان الذي يبحر بالسفينة ويصل بها إلى بر الأمان، والعاطفة هي الوقود الذي يحرك السفينة.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'معنى (يعتمد العقل) في النص:', '["يقدّم العقل", "يفكر بالعاطفة فقط", "يهمل العقل", "يؤجل القرار"]'::jsonb, 0, 'اعتماد العقل هو تقديمه وجعله مرجع القرار.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82605-2026-4c00-9d00-000000000005', 'الإنسان يكون في حيرة من أمره في القرارات الكبيرة؛ يعتمد العقل تارة وأحيانًا تحكمه العاطفة. في الحياة يجب أن يكون العقل هو القبطان الذي يبحر بالسفينة ويصل بها إلى بر الأمان، والعاطفة هي الوقود الذي يحرك السفينة.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يستفاد من النص:', '["العمل بالعاطفة فقط", "العمل بالعقل فقط", "الموازنة بين العقل والعاطفة", "إهمال القرارات الكبيرة"]'::jsonb, 2, 'تشبيه العقل بالقبطان والعاطفة بالوقود يجعل لكل منهما دورًا لا تسير السفينة إلا بهما معًا: قيادة عاقلة بدافع عاطفي.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82605-2026-4c00-9d00-000000000005', 'الإنسان يكون في حيرة من أمره في القرارات الكبيرة؛ يعتمد العقل تارة وأحيانًا تحكمه العاطفة. في الحياة يجب أن يكون العقل هو القبطان الذي يبحر بالسفينة ويصل بها إلى بر الأمان، والعاطفة هي الوقود الذي يحرك السفينة.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'الإنسان في حياته — كما يصف النص —:', '["يعتمد العقل تارة وتحكمه العاطفة تارة", "يسمع للعقل فقط", "لا يفكر إلا بالعاطفة", "يمشي وراء آراء الآخرين"]'::jsonb, 0, 'هذا نص العبارة الافتتاحية: يعتمد العقل تارة وأحيانًا تحكمه العاطفة.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82605-2026-4c00-9d00-000000000005', 'الإنسان يكون في حيرة من أمره في القرارات الكبيرة؛ يعتمد العقل تارة وأحيانًا تحكمه العاطفة. في الحياة يجب أن يكون العقل هو القبطان الذي يبحر بالسفينة ويصل بها إلى بر الأمان، والعاطفة هي الوقود الذي يحرك السفينة.', 4, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'القائد في حياة الإنسان:', '["التجارب", "العقل", "العاطفة", "الحظ"]'::jsonb, 1, 'جعل النص العقل هو القبطان الذي يبحر بالسفينة، والقبطان هو القائد.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82605-2026-4c00-9d00-000000000005', 'الإنسان يكون في حيرة من أمره في القرارات الكبيرة؛ يعتمد العقل تارة وأحيانًا تحكمه العاطفة. في الحياة يجب أن يكون العقل هو القبطان الذي يبحر بالسفينة ويصل بها إلى بر الأمان، والعاطفة هي الوقود الذي يحرك السفينة.', 5, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'الضمير في (بها) يعود على:', '["العاطفة", "السفينة", "الحياة", "القرارات"]'::jsonb, 1, 'التقدير: يبحر بالسفينة ويصل بها إلى بر الأمان؛ فالضمير يعود على السفينة.', NULL, 'ad260826-2026-4c00-9d00-260820260001', 'e1a82605-2026-4c00-9d00-000000000005', 'الإنسان يكون في حيرة من أمره في القرارات الكبيرة؛ يعتمد العقل تارة وأحيانًا تحكمه العاطفة. في الحياة يجب أن يكون العقل هو القبطان الذي يبحر بالسفينة ويصل بها إلى بر الأمان، والعاطفة هي الوقود الذي يحرك السفينة.', 6, 'active', false);
END IF;
END
$mig$;

-- مزامنة العداد مع الواقع
UPDATE leak_groups
SET question_count = (SELECT COUNT(*) FROM questions WHERE leak_group_id = 'ad260826-2026-4c00-9d00-260820260001')
WHERE id = 'ad260826-2026-4c00-9d00-260820260001';

-- تحقق نهائي
DO $chk$
DECLARE n INT; nq INT; nv INT; np INT;
BEGIN
  SELECT COUNT(*) INTO n FROM questions WHERE leak_group_id = 'ad260826-2026-4c00-9d00-260820260001';
  SELECT COUNT(*) INTO nq FROM questions WHERE leak_group_id = 'ad260826-2026-4c00-9d00-260820260001' AND section = 'quant';
  SELECT COUNT(*) INTO nv FROM questions WHERE leak_group_id = 'ad260826-2026-4c00-9d00-260820260001' AND section = 'verbal';
  SELECT COUNT(*) INTO np FROM questions WHERE leak_group_id = 'ad260826-2026-4c00-9d00-260820260001' AND passage_id IS NOT NULL;
  RAISE NOTICE 'إجمالي: % — كمي: % — لفظي: % — قطع: %', n, nq, nv, np;
  IF n <> 102 THEN RAISE EXCEPTION 'عدد الأسئلة % لا يطابق المتوقع 102', n; END IF;
  IF nq <> 52 OR nv <> 50 THEN RAISE EXCEPTION 'توزيع كمي/لفظي غير مطابق'; END IF;
END
$chk$;

COMMIT;