-- ═══════════════════════════════════════════════════════════════
-- تسريبات القدرات – الأحد ٦ سبتمبر ٢٠٢٦
-- 118 سؤالاً: كمي 53 + لفظي 65 (منها 9 في قطع استيعاب)
-- آمن لإعادة التشغيل: guard على وجود أسئلة المجموعة
-- ═══════════════════════════════════════════════════════════════
BEGIN;

INSERT INTO leak_groups (id, title, leak_date, section, question_count, description, is_active, accent_color)
VALUES ('ad060926-2026-4c00-9d00-060920260001', 'تسريبات القدرات – الأحد ٦ سبتمبر ٢٠٢٦', '2026-09-06', 'mixed', 118, 'أسئلة اختبار القدرات المحوسب ليوم الأحد ٦ سبتمبر ٢٠٢٦ (٢٤ ربيع الأول ١٤٤٨) — القسمان الكمي واللفظي مع الشروح.', true, '#4C1D95')
ON CONFLICT (id) DO NOTHING;

DO $mig$
BEGIN
IF EXISTS (SELECT 1 FROM questions WHERE leak_group_id = 'ad060926-2026-4c00-9d00-060920260001') THEN
  RAISE NOTICE 'أسئلة المجموعة موجودة مسبقاً — تخطي الإدراج';
ELSE
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'عمر هدى بعد ٩ سنوات سيصبح مثلي عمرها بعد ٣ سنوات، ما عمر هدى الآن؟', '["١٢", "٣", "٩", "٢٤"]'::jsonb, 1, 'لو عمرها الآن س: بعد ٩ سنوات يصبح س + ٩، وبعد ٣ سنوات يصبح س + ٣. المعطى: س + ٩ = ٢(س + ٣) = ٢س + ٦، ومنها س = ٣.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'الجذر الرابع للمقدار (٨١ × ٨١ × ٨١ × ٨١) = .....', '["٣", "√٣", "٩", "٨١"]'::jsonb, 3, 'المقدار تحت الجذر هو ٨١ مضروبًا في نفسه أربع مرات أي ٨١⁴، والجذر الرابع لـ٨١⁴ يعيد الأساس نفسه: ٨١.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'كم عدد المربعات في الشكل المجاور؟', '["٣٢", "٩", "١١", "١٣"]'::jsonb, 2, 'الشكل مكوّن من ٨ مربعات صغيرة (صف علوي فيه مربعان، وتحته صفان في كل منهما ٣ مربعات). نضيف المربعات المكوّنة من أربعة مربعات صغيرة (٢×٢) وعددها ٣. المجموع ٨ + ٣ = ١١.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep06_q003_squares.png', 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', '٤⁴ + ٤³ = ......', '["٣ × ٤⁴", "٣ × ٤³", "٥ × ٤⁴", "٥ × ٤³"]'::jsonb, 3, 'نأخذ ٤³ عاملًا مشتركًا: ٤⁴ + ٤³ = ٤³ × (٤ + ١) = ٥ × ٤³.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'اشترى شخص ١٠٠ سهم بمبلغ ٦٠٠٠٠ ريال، فنقصت قيمة السهم الواحد ٢٠٠ ريال. كم نسبة خسارته؟', '["١/٦", "١/٣", "١/٢", "١/٤"]'::jsonb, 1, 'سعر السهم الواحد = ٦٠٠٠٠ ÷ ١٠٠ = ٦٠٠ ريال. نقص ٢٠٠ من ٦٠٠ يعني أن نسبة الخسارة = ٢٠٠ ÷ ٦٠٠ = ١/٣.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'إذا كان محيط المربع = محيط المستطيل، قارن بين:
القيمة الأولى: مساحة المربع
القيمة الثانية: مساحة المستطيل', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'عند تساوي المحيط يكون المربع صاحب أكبر مساحة بين كل المستطيلات. جرّب محيطًا ١٦: مربع ضلعه ٤ مساحته ١٦، ومستطيل ٥ × ٣ مساحته ١٥ فقط.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ٩ − ٠٫٠٤٤
القيمة الثانية: ٩ − ٠٫٠٠٤٤', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, 'كلما كان المطروح أصغر كان الناتج أكبر. ٠٫٠٠٤٤ أصغر من ٠٫٠٤٤، فالقيمة الثانية ٩ − ٠٫٠٠٤٤ هي الأكبر.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'عدد مكوّن من رقمين، آحاده يقل عن عشراته بمقدار ٢، وخمسة أمثال مجموع رقميه مقسومًا على ١٠ يساوي ٧. ما هذا العدد؟', '["٥٣", "٧٥", "٨٦", "٩٧"]'::jsonb, 2, 'من الشرط الثاني: ٥ × المجموع ÷ ١٠ = ٧، فمجموع الرقمين = ١٤. رقمان مجموعهما ١٤ والآحاد أقل من العشرات بـ٢: العشرات ٨ والآحاد ٦، فالعدد ٨٦.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'غرفة طولها ١٠ م وعرضها ٦ م، وتحتاج ٣ أطنان تبريد. إذا كان كل ١ م³ يحتاج ٣٠٠ وحدة حرارية، وطن التبريد الواحد = ١٢٠٠٠ وحدة حرارية، فما ارتفاع الغرفة بالمتر؟', '["١٫٥", "٢٫٥", "٢", "٣٫٥"]'::jsonb, 2, '٣ أطنان = ٣ × ١٢٠٠٠ = ٣٦٠٠٠ وحدة حرارية، تكفي لحجم ٣٦٠٠٠ ÷ ٣٠٠ = ١٢٠ م³. مساحة الأرضية = ١٠ × ٦ = ٦٠ م²، فالارتفاع = ١٢٠ ÷ ٦٠ = ٢ م.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', '(٦٦٦/٣٣٣) ÷ [(٤٤٤/٥٥٥) ÷ (٤٤٤/٥٥٥)] = .....', '["٢", "١١١", "٢٢٢", "٤٤٤"]'::jsonb, 0, 'القوس يحوي قسمة كسر على نفسه فناتجه ١. و٦٦٦ ÷ ٣٣٣ = ٢، ثم ٢ ÷ ١ = ٢.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: مثلث مرسوم داخل دائرة أحد أضلاعه قطر الدائرة، وضلعاه الآخران متساويان. ما قيمة س؟', '["٣٠", "٤٥", "٦٠", "٩٠"]'::jsonb, 1, 'الزاوية المقابلة لقطر الدائرة في أي مثلث مرسوم داخلها قائمة (٩٠°). والمثلث متساوي الساقين، فزاويتا القاعدة متساويتان: س = (١٨٠ − ٩٠) ÷ ٢ = ٤٥°.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep06_q011_circle_tri.png', 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: أشعة تخرج من نقطة على مستقيم فتكوّن الزوايا س، ٢س، ٣س، ٤س، ٥س. ما قيمة س؟', '["٦", "٩", "١٢", "١٥"]'::jsonb, 2, 'الزوايا الخمس تكوّن معًا زاوية مستقيمة مجموعها ١٨٠°: س + ٢س + ٣س + ٤س + ٥س = ١٥س = ١٨٠، فتكون س = ١٢.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep06_q012_rays.png', 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: مربع طول ضلعه ٥ سم، ومستطيل طول قطره ٥ سم. قارن بين:
القيمة الأولى: مساحة المربع
القيمة الثانية: مساحة المستطيل', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'مساحة المربع = ٥ × ٥ = ٢٥ سم². أما المستطيل فقطره ٥ سم فقط، وأي مستطيل قطره ٥ تكون مساحته أقل من ١٢٫٥ سم² (أقصاها عندما يصبح مربعًا). فالقيمة الأولى أكبر.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep06_q013_sq_rect.png', 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'التحليل', 'اختيار من متعدد', 'إذا كان ٨ أشخاص يجلسون على ٣ طاولات متلاصقة كما في الشكل المجاور، فكم شخصًا يمكنهم الجلوس على ١٣ طاولة بالطريقة نفسها؟', '["٣٩", "٢٨", "٢٥", "٣٠"]'::jsonb, 1, 'في صف الطاولات المتلاصقة تتيح كل طاولة مقعدين (مقعد من كل جانب)، ويُضاف مقعدان في طرفي الصف. لـ١٣ طاولة: ٢ × ١٣ + ٢ = ٢٨ شخصًا.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep06_q014_tables.png', 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'إذا كانت نسبة الكرات الحمراء إلى الكرات غير الحمراء = ١ : ٤، فما نسبة الكرات الحمراء من مجموع الكرات؟', '["٢٠٪", "٢٥٪", "٥٠٪", "٧٥٪"]'::jsonb, 0, 'الكرات الحمراء جزء واحد من أصل ١ + ٤ = ٥ أجزاء، أي ١/٥ = ٢٠٪ من الكرات كلها.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', '٣ عمال يستغرقون ساعتين لدهان جدار طوله ١٢٠ قدمًا. كم ساعة يحتاج ٤ عمال لدهان جدار طوله ١٦٠ قدمًا بالمعدل نفسه؟', '["١", "١٫٥", "٢", "٢٫٥"]'::jsonb, 2, 'معدل العامل الواحد = ١٢٠ ÷ (٣ × ٢) = ٢٠ قدمًا في الساعة. أربعة عمال ينجزون ٨٠ قدمًا في الساعة، فيحتاجون ١٦٠ ÷ ٨٠ = ساعتين.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'إذا كان عرض مستطيل = س، ومساحته = ٢س²، فأوجد مساحة مربع طول ضلعه يساوي طول قطر المستطيل.', '["٢س²", "٣س²", "٤س²", "٥س²"]'::jsonb, 3, 'طول المستطيل = المساحة ÷ العرض = ٢س² ÷ س = ٢س. مربع القطر = س² + (٢س)² = ٥س²، ومساحة المربع الذي ضلعه القطر تساوي مربع القطر = ٥س².', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'قطعت عجلتان المسافة نفسها. نصف قطر الأولى س وقد دارت ٣٠ دورة، ونصف قطر الثانية ص وقد دارت ١٥ دورة. أي الآتي صحيح؟', '["ص = س", "ص = ٢س", "ص = ٣س", "ص = ٤س"]'::jsonb, 1, 'المسافة = عدد الدورات × المحيط. ٣٠ × ٢πس = ١٥ × ٢πص، وبالاختصار ٣٠س = ١٥ص، فتكون ص = ٢س.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'عبوة مملوءة إلى ثُمنها، وإذا أضفنا إليها ٦٣ مل أصبحت ممتلئة بالكامل. ما سعة العبوة؟', '["٧٠", "٧٢", "٧٥", "٨٠"]'::jsonb, 1, 'الفراغ = ٧/٨ من السعة = ٦٣ مل، فالثُمن الواحد = ٦٣ ÷ ٧ = ٩ مل، والسعة الكاملة = ٩ × ٨ = ٧٢ مل.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'إذا كان حجم الهرم = (مساحة القاعدة × الارتفاع) ÷ ٣، قارن بين:
القيمة الأولى: حجم مكعب طول حرفه ٥ سم
القيمة الثانية: حجم هرم مساحة قاعدته ٢٥ سم² وارتفاعه ١٠ سم', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'حجم المكعب = ٥³ = ١٢٥ سم³، وحجم الهرم = ٢٥ × ١٠ ÷ ٣ ≈ ٨٣٫٣ سم³. فالقيمة الأولى أكبر.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'اشترى شخص بنصف ما معه، ثم اشترى بثلث المتبقي. ما نسبة ما تبقى معه إلى ما كان معه أصلًا؟', '["١/٦", "١/٥", "١/٤", "١/٣"]'::jsonb, 3, 'بعد الشراء الأول يبقى النصف. ينفق ثلث هذا النصف فيبقى ثلثاه: (٢/٣) × (١/٢) = ١/٣ مما كان معه.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'التحليل', 'اختيار من متعدد', 'في رسم بياني لتحويل الوحدات، الخط المستقيم الذي يمثل تحويل البوصة إلى السنتيمتر يمر بنقطة الأصل وبالنقطة (٤٠ بوصة، ١٠٠ سم). كم سنتيمترًا تساوي ٨٠ بوصة تقريبًا؟', '["٥٠", "١٠٠", "١٢٠", "٢٠٠"]'::jsonb, 3, 'الخط مستقيم يمر بنقطة الأصل، فالتحويل نسبة ثابتة: ٤٠ بوصة تقابل ١٠٠ سم، إذًا ٨٠ بوصة (الضعف) تقابل ٢٠٠ سم.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'مساحة قاعدة هرم ثلاثي = ارتفاع هرم رباعي = ٤٠، ومساحة قاعدة الهرم الرباعي = ارتفاع الهرم الثلاثي = ٣٦. قارن بين:
القيمة الأولى: حجم الهرم الثلاثي
القيمة الثانية: حجم الهرم الرباعي', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 2, 'حجم أي هرم = (مساحة القاعدة × الارتفاع) ÷ ٣ بغضّ النظر عن شكل قاعدته. الثلاثي: ٤٠ × ٣٦ ÷ ٣، والرباعي: ٣٦ × ٤٠ ÷ ٣، والناتج واحد (٤٨٠)؛ فالقيمتان متساويتان.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'يبيّن الرسم البياني المجاور أعداد المراجعين في أربعة أشهر حسب الفئة. أوجد متوسط عدد المراجعات البالغات في الأشهر الأربعة.', '["٦٥", "٦٠", "٥٠", "٥٥"]'::jsonb, 3, 'نقرأ أعمدة «إناث بالغات» فقط: رجب ٥٠، شعبان ٥٠، رمضان ٧٠، شوال ٥٠. المجموع ٢٢٠، والمتوسط = ٢٢٠ ÷ ٤ = ٥٥.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep06_q024_barchart.png', 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'انخفض سهم شركة يوم الثلاثاء بنسبة ٣٪، وهذا الانخفاض يعادل ٠٫٣ ريال. قارن بين:
القيمة الأولى: ٣٠ ريالًا
القيمة الثانية: قيمة السهم يوم الثلاثاء بعد الانخفاض', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, '٣٪ من السعر = ٠٫٣ ريال، فالسعر قبل الانخفاض = ٠٫٣ ÷ ٠٫٠٣ = ١٠ ريالات، وبعده ٩٫٧ ريال، وهي أقل من ٣٠ ريالًا.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور مستقيمان متوازيان، والزاويتان المبينتان ٢٥° و٣٧°. أوجد قيمة س.', '["٦٢", "١١٨", "٢٤٢", "٢٩٨"]'::jsonb, 3, 'بين المستقيمين المتوازيين تكون الزاوية الداخلية عند رأس الانكسار مساوية لمجموع الزاويتين المتبادلتين: ٢٥ + ٣٧ = ٦٢°. المطلوب س هي الزاوية المنعكسة في الجهة الأخرى = ٣٦٠ − ٦٢ = ٢٩٨°.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep06_q026_parallel.png', 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان س/٣٦ = ٠٫٥/٩، فأوجد قيمة س.', '["٢", "٤", "٦", "٩"]'::jsonb, 0, 'بالضرب التبادلي: ٩س = ٣٦ × ٠٫٥ = ١٨، ومنها س = ٢.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'التحليل', 'اختيار من متعدد', 'ما الحد التالي في النمط: ١٣، ١٤، ١٢، ١٣، ١١، ١٢، ......؟', '["١٠", "١٢", "١٣", "١٤"]'::jsonb, 0, 'النمط يتكرر: زيادة ١ ثم نقصان ٢. بعد ١٢ (الناتجة عن زيادة ١) يأتي نقصان ٢: ١٢ − ٢ = ١٠.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'سبات : ليل', '["عمل : نهار", "ضحى : نهار", "سحور : فجر", "طواف : إحرام"]'::jsonb, 0, 'العلاقة: نشاط والزمن الذي يستغرقه كاملًا. السبات (النوم) يستغرق الليل، والعمل يستغرق النهار. أما السحور فلحظة قصيرة قبل الفجر لا تستغرقه.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'حصان : صهيل', '["طير : شقشقة", "أسد : الشجاعة", "مرض : شيخوخة", "صرير : قلم"]'::jsonb, 0, 'العلاقة: كائن وصوته. الصهيل صوت الحصان، والشقشقة صوت الطير. أما «صرير : قلم» فترتيبها معكوس (الصوت قبل صاحبه).', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'حاسر : رأس', '["عريان : ثوب", "أشعث : شعر", "حافي : قدم", "أعسب : رأس"]'::jsonb, 2, 'الحاسر من كُشف رأسه بلا غطاء، والحافي من كُشفت قدمه بلا نعل: صفة الشيء المكشوف وموضعه. العريان يوصف بجسده لا بثوبه، والأشعث صفة للشعر نفسه.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'النية : الصلاة', '["العمل : الجزاء", "ولد : ابن", "الشيب : الشباب", "الجمرات : الطواف"]'::jsonb, 0, 'النية تسبق الصلاة وتتوقف عليها، والعمل يسبق الجزاء ويترتب عليه: علاقة سابق ولاحق مترتب عليه.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'الكعبة : المطاف', '["السور : البيت", "البطن : الحزام", "الحديقة : الورد", "المقام : الحجر الأسود"]'::jsonb, 1, 'المطاف يحيط بالكعبة، والحزام يحيط بالبطن: علاقة شيء وما يحيط به بالترتيب نفسه. أما «السور : البيت» فالمحيط جاء أولًا فالترتيب معكوس.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'أرض : جاذبية', '["ثرية : صحراء", "فضاء : كواكب", "تاريخ : أحداث", "تلفزيون : مذياع"]'::jsonb, 1, 'العلاقة: مكان وما يوجد فيه ويميزه. الجاذبية توجد في الأرض، والكواكب توجد في الفضاء.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'خسوف : القمر', '["مرض : حيوان", "كوكب : شمس", "سطوع : نجم", "اجتهاد : لعب"]'::jsonb, 0, 'الخسوف عارض يصيب القمر فيحجب ضوءه، والمرض عارض يصيب الحيوان: علاقة عارض وما يصيبه. أما السطوع فصفة أصلية في النجم لا عارض.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'خور : بسالة', '["غريم : خصم", "زهو : تواضع", "كبح : تردد", "تعويم : تفويض"]'::jsonb, 1, 'الخَوَر هو الضعف والجبن وهو ضد البسالة (الشجاعة)، والزهو (التكبر) ضد التواضع: علاقة تضاد.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'عليكم ....... الأخبار فإنها من صفات الملوك، ....... تصلون إلى منزلتهم وعظمتهم.', '["بأجود – عندها", "بأخبار – بها", "بطرائف – بها", "بعجائب – منهم"]'::jsonb, 2, '«طرائف الأخبار» هي ما يليق بمجالس الملوك، والضمير في «بها» يعود على الطرائف: بها تصلون إلى منزلتهم.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'مثل ....... كمثل الواقف على الجبل، يرى الناس ....... ويرونه صغيرًا.', '["المتكبر – صغارًا", "الكريم – كبارًا", "المتكبر – حقيرًا", "اللئيم – ذليلًا"]'::jsonb, 0, 'التشبيه يصف المتكبر: يرى الناس صغارًا من علوّه المزعوم، وهم بدورهم يرونه صغيرًا؛ فالتقابل «صغارًا / صغيرًا» هو المقصود.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'تستطيع تجريد جيش من ....... ولكن لا تستطيع تجريد الناس من .......', '["سلاحهم – هيمنتهم", "قائدهم – إرادتهم", "سمائه – أرضهم", "هزيمته – عزيمتهم"]'::jsonb, 1, 'الجيش يمكن تجريده من قائده لأنه أمر خارجي، لكن الإرادة شيء داخلي في الناس لا يُنتزع منهم: قائدهم – إرادتهم.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'ينبغي للعاقل أن يكون لنفسه .......؛ كي يدعوها للتواضع والعمل.', '["مهتمًا", "متوهًا", "متّهِمًا", "متوهمًا"]'::jsonb, 2, 'من يتّهم نفسه (يحاسبها ولا يبرئها) يدفعها إلى التواضع والعمل، فالمناسب «متّهِمًا».', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'تنوء الأمة ....... أخطاء أبنائها الذين انحرفوا عن سبيل الحق ووقعوا في ....... الشيطان.', '["بعمل – مصايد", "بسوء – جوانب", "ببوادر – حبائل", "بثقل – براثن"]'::jsonb, 3, '«تنوء» أي تثقل وتميل بالحمل، فيناسبها «بثقل»، ومن انحرف يقع في براثن الشيطان (مخالبه)؛ فالتعبيران المستقيمان: بثقل – براثن.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'العلم يعمل على صقل ....... الخشنة، وتهذيب ....... الجافية.', '["الفنون – الناس", "العادات – الأخلاق", "السجايا – المزايا", "الطباع – النفوس"]'::jsonb, 3, 'الصقل يكون للطباع الخشنة، والتهذيب للنفوس الجافية (القاسية)؛ فالزوج المناسب: الطباع – النفوس.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'يقطع ....... ليلًا أو نهارًا بـ....... فتزداد حكمة وعقلًا ومروءة.', '["السفر – سحب", "الحطب – اللهب", "الفراغ – الكتاب", "اللحم – الطعام"]'::jsonb, 2, 'قطع وقت الفراغ بالكتاب هو ما يزيد صاحبه حكمة وعقلًا؛ فالمعنى الوحيد المستقيم: الفراغ – الكتاب.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'الصديق المزيف كالظل، يمشي ورائي عندما أكون في ....... ويختفي عندما أكون في .......', '["اليسر – العسر", "الشمس – الظلام", "المرض – الصحة", "الغنى – الفاقة"]'::jsonb, 1, 'الجملة تشبيه بالظل، والظل يظهر في الشمس ويختفي في الظلام؛ فالإكمال الملائم لصورة التشبيه: الشمس – الظلام.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'يتناسب المستوى الحضاري للإنسان ولمجتمعه مع قيمة وحجم ما يحتاج من عمل وجهد.', '["الحضاري", "قيمة", "يحتاج", "جهد"]'::jsonb, 2, 'المستوى الحضاري يتناسب مع ما يُبذل من عمل وجهد لا مع ما «يُحتاج»؛ الكلمة الصحيحة: يبذل.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'يعرف المعلم الطالب الحريص من حسن إنصاته وجوابه عما يجهله.', '["المعلم", "الحريص", "إنصاته", "جوابه"]'::jsonb, 3, 'الطالب الحريص يُعرف بحسن إنصاته وسؤاله عما يجهله؛ فـ«جوابه» في غير موضعها والصواب «سؤاله».', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'الذنوب تخرس الكتب الفصيحة وتعمي الأفئدة الصحيحة.', '["الذنوب", "الكتب", "الأفئدة", "الصحيحة"]'::jsonb, 1, 'الخرس صفة اللسان لا الكتاب: الذنوب تُخرس الألسن الفصيحة وتُعمي الأفئدة؛ فالخطأ في «الكتب» وصوابها «الألسن».', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'عظمة الرجل تقاس بمدى استعداده للانتقام ممن أساء إليه.', '["عظمة", "تقاس", "للانتقام", "أساء"]'::jsonb, 2, 'عظمة الرجل تُقاس باستعداده للعفو عمن أساء إليه لا بالانتقام؛ فالخطأ في «للانتقام».', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'حقيقة الخيانة أن تتصرف في الأمانة بمثل ما أريد منك دون علم صاحبها.', '["الخيانة", "الأمانة", "بمثل", "صاحبها"]'::jsonb, 2, 'الخيانة أن تتصرف في الأمانة بخلاف ما أُريد منك؛ فـ«بمثل» تناقض المعنى والصواب «بغير».', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'تؤثر المنحدرات الجبلية في التوزيع السكاني لأنها تمتاز بوجود خوانق تساعد النشاط البشري.', '["التوزيع", "تمتاز", "خوانق", "تساعد"]'::jsonb, 3, 'الخوانق (المضايق الجبلية) تعيق النشاط البشري لا تساعده؛ فالخطأ في «تساعد» وصوابها «تعيق».', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'يوم العدل على الظالم أشد من يوم الجور على الظالم.', '["العدل", "الظالم (الأولى)", "الجور", "الظالم (الثانية)"]'::jsonb, 3, 'المعنى المقصود: يوم العدل على الظالم أشد من يوم الجور على المظلوم؛ فالكلمة الثانية «الظالم» خطأ وصوابها «المظلوم».', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'كلما تواضعت للناس تستشري محبتك في قلوبهم.', '["تواضعت", "تستشري", "الناس", "محبتك"]'::jsonb, 1, '«تستشري» تُقال لانتشار الشر والمرض، فلا تناسب المحبة؛ والصواب «تزداد» أو «تنتشر».', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["جاهل", "غبي", "أحمق", "شقي"]'::jsonb, 3, 'جاهل وغبي وأحمق كلها تصف نقصًا في العقل أو العلم، أما «شقي» فتصف سوء الحال والتعاسة.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["رياضة", "سرعة", "رشاقة", "لياقة"]'::jsonb, 0, 'السرعة والرشاقة واللياقة صفات بدنية تنتج عن الرياضة، أما «رياضة» فهي النشاط نفسه لا صفة.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["أب", "أم", "عمة", "جد"]'::jsonb, 2, 'الأب والأم والجد من أصول الإنسان المباشرة، أما «العمة» فمن الحواشي (الأقارب من جهة الأب) لا من الأصول.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["اختلاس", "رشوة", "نزاهة", "تزوير"]'::jsonb, 2, 'الاختلاس والرشوة والتزوير جرائم فساد، أما «النزاهة» فضدها جميعًا.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["طحين", "طين", "تراب", "فخار"]'::jsonb, 0, 'الطين والتراب والفخار مواد من أصل واحد هو التربة، أما «الطحين» فمن الحبوب.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["مجداف", "زعنفة", "جناح", "منقار"]'::jsonb, 3, 'المجداف والزعنفة والجناح أدوات للحركة والدفع في الماء أو الهواء، أما «المنقار» فعضو للأكل والالتقاط.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["لبؤة", "زرافة", "أتان", "فرس"]'::jsonb, 0, 'الزرافة والأتان والفرس حيوانات آكلة عشب غير مفترسة، أما «اللبؤة» فأنثى الأسد وهي مفترسة.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["علاج", "شفاء", "عقار", "دواء"]'::jsonb, 1, 'العلاج والعقار والدواء وسائل للمعالجة، أما «الشفاء» فهو نتيجتها.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يتم التعديل عند توفر:', '["معرفة الأسباب", "تفنيد الأسباب", "فرص التعديل", "ترتيب المشكلة"]'::jsonb, 2, 'النص يجعل التعديل (الحل) مرحلة أخيرة لا تتم إلا بعد أن تتهيأ فرصته بتفكيك المشكلة وتفنيد أخطائها ثم إعادة ترتيبها.', NULL, 'ad060926-2026-4c00-9d00-060920260001', 'e1a90601-2026-4c00-9d00-000000000001', 'نقوم بتفكيك المشكلة وتجزئتها من أجل تفنيد الأخطاء والقضاء على أي هشاشة أو رقّة فيها، ثم نعيد ترتيبها لنتمكن من حلّها.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يعتدل الأمر إذا تهيأت له:', '["طرق التعديل", "أسباب التعديل", "تفنيد التعديل", "نتائج التعديل"]'::jsonb, 0, 'النص يصف طريقة التعديل (تفكيك، تفنيد، إعادة ترتيب)؛ فالأمر يعتدل إذا تهيأت له طرق التعديل هذه.', NULL, 'ad060926-2026-4c00-9d00-060920260001', 'e1a90601-2026-4c00-9d00-000000000001', 'نقوم بتفكيك المشكلة وتجزئتها من أجل تفنيد الأخطاء والقضاء على أي هشاشة أو رقّة فيها، ثم نعيد ترتيبها لنتمكن من حلّها.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يُفهم من النص أن القرار الفردي:', '["أسرع من القرار الجماعي", "مرهون بعقلية صاحبه", "يحتاج تجارب حياتية ليكون صائبًا", "يكون جيدًا إذا درسه الشخص جيدًا"]'::jsonb, 1, 'النص يقابل القرار الفردي بالقرار الجماعي الذي يعبّر عن عقلية المؤسسة بعد نقاشات وحوارات؛ فالفردي بالمقابل مرهون بعقلية صاحبه وحده.', NULL, 'ad060926-2026-4c00-9d00-060920260001', 'e1a90602-2026-4c00-9d00-000000000002', 'في الدول المتقدمة لا يُعتمد على الرأي الفردي، بل على القرارات الجماعية التي تُتخذ بعد عدة نقاشات وحوارات، وتخرج للمجتمع بصورة مناسبة تعبّر عن عقلية المؤسسة وتفكيرها.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'النص يحذّر من جميع ما يلي ما عدا:', '["القيادة بسرعة عالية", "التفحيط", "استخدام الهاتف أثناء القيادة", "القيادة بالسرعة القانونية"]'::jsonb, 3, 'القيادة بالسرعة القانونية هي ما يدعو إليه النص لا ما يحذّر منه؛ أما السرعة العالية والتفحيط والهاتف فكلها مما حذّر منه.', NULL, 'ad060926-2026-4c00-9d00-060920260001', 'e1a90603-2026-4c00-9d00-000000000003', 'القيادة بسرعة عالية والتفحيط واستخدام الهواتف أثناء قيادة السيارة تؤدي إلى كثرة الحوادث، وبالتالي ازدحام الطرق وكثرة الوفيات؛ لذا يجب علينا أن نقود بالسرعة القانونية وأن نلتزم بقوانين السلامة.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'من الفنانون الذين سيُصمَّم لهم نظام البصمة؟', '["جميع الفنانين", "المميزون منهم", "التشكيليون", "الحداثيون"]'::jsonb, 0, 'النص صريح: النظام يحفظ «لكل الفنانين» بصمتهم المميزة، فلم يخصص فئة دون أخرى.', NULL, 'ad060926-2026-4c00-9d00-060920260001', 'e1a90604-2026-4c00-9d00-000000000004', 'يعمل الباحثون على تصميم نظام إلكتروني يحفظ لكل الفنانين بصمتهم المميزة، ويقترحون أن تُسمّى «بصمة الفرشاة».', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', '٢ ÷ (√٣ − ١) = .....', '["√٣ + ١", "√٣ − ١", "√٣ + ٢", "√٣ − ٢"]'::jsonb, 0, 'نضرب البسط والمقام في مرافق المقام (√٣ + ١): المقام يصبح (√٣)² − ١² = ٢، والبسط ٢(√٣ + ١)، فالناتج √٣ + ١.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'مستطيل طوله ٤٠⅓ وعرضه ١٠½. احسب طول محيطه.', '["١١١½", "١٠١⅔", "١٠٠", "١١١"]'::jsonb, 1, 'المحيط = ٢ × (الطول + العرض) = ٢ × (٤٠⅓ + ١٠½) = ٢ × ٥٠⅚ = ١٠١⅔.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'مستطيل طوله ٥⅓ وعرضه ٢¼. احسب مساحته.', '["١٢", "١٢٫٥", "١١", "١١٫٥"]'::jsonb, 0, 'نحوّل إلى كسور: ٥⅓ = ١٦/٣ و٢¼ = ٩/٤، والمساحة = (١٦/٣) × (٩/٤) = ١٤٤/١٢ = ١٢.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'مثلث قائم الزاوية طولا ضلعي قائمته ٢ و٣، ومستطيل أبعاده ٤ × ٦. كم مثلثًا من هذا المثلث يمكن وضعه داخل المستطيل؟', '["٤", "٨", "٦", "١٠"]'::jsonb, 1, 'مساحة المثلث = ٢ × ٣ ÷ ٢ = ٣، ومساحة المستطيل = ٤ × ٦ = ٢٤، فعدد المثلثات = ٢٤ ÷ ٣ = ٨ (كل مثلثين يكوّنان مستطيلًا ٢ × ٣ يملأ المستطيل الكبير بلا فراغ).', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'اشترى رجل ١٨٠ برتقالة بـ١٥٠ ريالًا، ففسدت ٢٠ منها، وباع كل ٨ برتقالات بـ٨٫٥ ريال. ما مقدار ربحه؟', '["٢٥", "٢٠", "٣٠", "٣"]'::jsonb, 1, 'الصالح للبيع ١٦٠ برتقالة = ٢٠ مجموعة من ٨، ثمنها ٢٠ × ٨٫٥ = ١٧٠ ريالًا. الربح = ١٧٠ − ١٥٠ = ٢٠ ريالًا.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: الضلع الأيسر طوله ٧، والجزء العلوي ينزل من القمة إلى مستوى الدرجة بمقدار ٥، وارتفاع الجزء الأيمن ٣. أوجد طول أ ب.', '["٤", "٣", "٢", "١"]'::jsonb, 3, 'مستوى الدرجة يبعد عن القاعدة ٧ − ٥ = ٢. والجزء الأيمن ارتفاعه ٣ عن القاعدة نفسها، فالفرق بين المستويين هو أ ب = ٣ − ٢ = ١.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep06_q071_step.png', 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور مستقيمان يتقاطعان في نقطة، والزاوية بينهما من الأعلى ١١٨°، وشعاع يخرج من نقطة التقاطع يقسم الزاوية المقابلة لها بالرأس إلى ٤١° وس. أوجد قيمة س.', '["٦٢", "٨٢", "٤٨", "٧٧"]'::jsonb, 3, 'الزاويتان المتقابلتان بالرأس متساويتان، فالزاوية السفلية = ١١٨° وهي مقسومة إلى ٤١ + س، ومنها س = ١١٨ − ٤١ = ٧٧.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep06_q072_lines.png', 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في مثلث، إحدى زواياه ٦١° وزاوية أخرى فيه ص. قارن بين:
القيمة الأولى: ص
القيمة الثانية: ٥٩', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 3, 'مجموع الزاويتين الأخريين = ١٨٠ − ٦١ = ١١٩، ويمكن توزيعه بينهما بطرق كثيرة، فقد تكون ص أقل من ٥٩ أو أكبر؛ المعطيات غير كافية.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'في رسم دائري لمبيعات متجر: الكمبيوترات ٥٠°، الإكسسوارات ٨٠°، الجوالات ٦٠°، الكتب ٣٠°، والقطاع المتبقي للألعاب. ما أكبر قطاع مبيعًا؟', '["الألعاب", "الكمبيوترات", "الكتب", "الجوالات"]'::jsonb, 0, 'مجموع القطاعات المذكورة = ٥٠ + ٨٠ + ٦٠ + ٣٠ = ٢٢٠°، فقطاع الألعاب = ٣٦٠ − ٢٢٠ = ١٤٠° وهو الأكبر.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور شكل على هيئة حرف L: عرض الجزء العلوي ٦، والامتداد السفلي إلى اليسار ٥، والارتفاع الكلي ٧. أوجد محيط الشكل.', '["١٨", "٢٠", "٣٠", "٣٦"]'::jsonb, 3, 'محيط أي شكل مستقيم الأضلاع بزوايا قائمة يساوي محيط المستطيل المحيط به: العرض الكلي = ٦ + ٥ = ١١ والارتفاع ٧، فالمحيط = ٢ × (١١ + ٧) = ٣٦.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep06_q075_lshape.png', 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان ٣ < س < ٥ و ص > س، قارن بين:
القيمة الأولى: ٠٫٧٥
القيمة الثانية: س/ص', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 3, 'بما أن ص > س فإن س/ص أقل من ١، لكنه قد يكون أكبر من ٠٫٧٥ (مثل ٤/٥ = ٠٫٨) أو أقل (مثل ٤/١٠ = ٠٫٤)؛ فالمعطيات غير كافية.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان س³ = ١٢٥، قارن بين:
القيمة الأولى: س
القيمة الثانية: ٣', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'س³ = ١٢٥ = ٥³، فالحل الحقيقي الوحيد س = ٥، وهو أكبر من ٣.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'في عام ١٤٣٧ كان عمر محمد سنة واحدة وعمر خالد ٤ سنوات. في أي عام يصبح عمر محمد ثلاثة أرباع عمر خالد؟', '["١٤٤٤", "١٤٤٥", "١٤٤٦", "١٤٤٧"]'::jsonb, 1, 'بعد س سنة: ١ + س = (٣/٤)(٤ + س)، أي ٤ + ٤س = ١٢ + ٣س فتكون س = ٨، والعام المطلوب = ١٤٣٧ + ٨ = ١٤٤٥.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'سحب شخص من البنك ٢٠٪ من راتبه، ثم صرف من هذا المبلغ ١٠٠٠ للأكل و٣٥٠٠ للملبس و٥٠٠ للأجهزة وتبقى لديه ٢٠٠. فكم راتب الشخص؟', '["٥٢٠٠", "٢٦٠٠٠", "٢٥٠٠٠٠", "٢٠٨٠٠"]'::jsonb, 1, 'المسحوب = ١٠٠٠ + ٣٥٠٠ + ٥٠٠ + ٢٠٠ = ٥٢٠٠ ريال، وهو ٢٠٪ من الراتب، فالراتب = ٥٢٠٠ ÷ ٠٫٢ = ٢٦٠٠٠ ريال.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان س ع + س ص = ١٠٠، فما قيمة (س/٥)(٣ع + ٣ص) + ١٠؟', '["٩٠", "٥٠", "٦٠", "٧٠"]'::jsonb, 3, '(س/٥)(٣ع + ٣ص) = (٣/٥)(س ع + س ص) = (٣/٥) × ١٠٠ = ٦٠، ثم نضيف ١٠ فيكون الناتج ٧٠.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'في مكتبة يستوعب الرف الواحد ٣٠ كتابًا. كم رفًّا نحتاج لوضع ١٢٥ كتابًا؟', '["٤", "٥", "٦", "٧"]'::jsonb, 1, '١٢٥ ÷ ٣٠ = ٤ وباقٍ ٥ كتب، فنحتاج ٤ رفوف ممتلئة ورفًّا خامسًا للكتب الخمسة الباقية: ٥ رفوف.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'يستخدم أحمد العد القفزي بمقدار ٥ أعداد، ويستخدم ناصر العد القفزي بمقدار ٣ أعداد. إذا كانت بدايتهما من الصفر ونهايتهما قبل العدد ١٠٠، فكم عدد الأعداد المشتركة بينهما؟', '["صفر", "٢", "٤", "٧"]'::jsonb, 3, 'الأعداد المشتركة هي مضاعفات ١٥ (المضاعف المشترك الأصغر لـ٣ و٥) بدءًا من الصفر: ٠، ١٥، ٣٠، ٤٥، ٦٠، ٧٥، ٩٠ — سبعة أعداد.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: مربع طول ضلعه ٤ سم أحد رؤوسه ب، وب ج قطر المربع. رُسمت من ب قطعة ب أ طولها ٧ سم عمودية على ب ج. أوجد مساحة المثلث أ ب ج.', '["٤√٢", "١٨√٢", "١٤√٢", "٩"]'::jsonb, 2, 'قطر المربع ب ج = ٤√٢ سم. المثلث قائم الزاوية في ب، فمساحته = ½ × ب ج × ب أ = ½ × ٤√٢ × ٧ = ١٤√٢ سم².', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep06_q083_tri.png', 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'وضع بائع خصمًا مقداره الخُمس على أحد المنتجات. إذا أراد إرجاع المنتج إلى سعره الأصلي، فكم نسبة الزيادة المطلوبة على السعر المخفض؟', '["١/٤", "١/٥", "١/٦", "١/٧"]'::jsonb, 0, 'لو السعر الأصلي ١٠٠: بعد خصم الخُمس يصبح ٨٠. للعودة إلى ١٠٠ نزيد ٢٠ على ٨٠، أي نسبة ٢٠/٨٠ = ١/٤.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'أوجد قيمة ثلث العدد ١٦.', '["٣/١٦", "١/٦", "٣/٩", "١٦/٣"]'::jsonb, 3, 'ثلث العدد = العدد ÷ ٣ = ١٦/٣ (أي ٥⅓).', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'اشتراك جوال: أول عشر دقائق بـ٤ ريالات، وبعد العشر دقائق تُحسب الدقيقة بـ٠٫٢ ريال. فكم ريالًا تكلفة ساعة كاملة؟', '["١٠", "١٢", "١٤", "٢٠"]'::jsonb, 2, 'الساعة ٦٠ دقيقة: أول ١٠ دقائق بـ٤ ريالات، والباقي ٥٠ دقيقة × ٠٫٢ = ١٠ ريالات، فالمجموع ١٤ ريالًا.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان س < صفر، قارن بين:
القيمة الأولى: س²
القيمة الثانية: −س³', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 3, 'لما س سالبة فإن س² موجبة و−س³ موجبة أيضًا. جرّب س = −٢: س² = ٤ و−س³ = ٨ (الثانية أكبر)، وجرّب س = −٠٫٥: س² = ٠٫٢٥ و−س³ = ٠٫١٢٥ (الأولى أكبر)؛ فالمعطيات غير كافية.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'أوجد قيمة: √(٢٥ × ∛(٢٥ × √٢٥)) ÷ √٥', '["٢٥", "٥", "√٥", "١٢٥"]'::jsonb, 1, 'نبدأ من الداخل: √٢٥ = ٥، ثم ٢٥ × ٥ = ١٢٥ وجذره التكعيبي ٥، ثم ٢٥ × ٥ = ١٢٥ وجذره التربيعي ٥√٥. أخيرًا ٥√٥ ÷ √٥ = ٥.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور مثلث متساوي الأضلاع، وبداخله مثلث آخر أضلاعه الثلاثة متساوية، وقد رُمز لإحدى زوايا المثلث الداخلي بـد. أوجد قيمة د.', '["٤٥", "١٢٠", "٥٤", "٦٠"]'::jsonb, 3, 'المثلث الداخلي متساوي الأضلاع لأن أضلاعه الثلاثة متساوية، وكل زاوية في المثلث متساوي الأضلاع = ١٨٠ ÷ ٣ = ٦٠°.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep06_q089_tri.png', 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'يبيّن الرسم الدائري المجاور توزيع تقديرات الطلاب. ما التقدير الذي حصل عليه ٢٥٪ من الطلاب؟', '["مقبول", "جيد", "جيد جدًا", "ممتاز"]'::jsonb, 2, '٢٥٪ من الدائرة = ربعها، أي قطاع زاويته ٩٠°، وهو في الرسم قطاع «جيد جدًا» ذو الزاوية القائمة.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep06_q090_pie.png', 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'عنكبوت : خيوط', '["نحلة : عسل", "شرنقة : فراشة", "حشرة : جرادة", "طائر : صقر"]'::jsonb, 0, 'العنكبوت ينتج الخيوط، والنحلة تنتج العسل: علاقة كائن وما ينتجه.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'صدق : أمانة', '["فرح : ابتهاج", "عمل : إتقان", "كذب : خيانة", "كذب : كذوب"]'::jsonb, 2, 'الصدق خلق حميد يلازمه خلق حميد آخر هو الأمانة، والكذب خلق ذميم يلازمه الخيانة: صفتان متلازمتان من الجنس نفسه.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'غزال : حيوان', '["ظبي : مها", "صقر : طائر", "سمك : بحر", "إبل : ناقة"]'::jsonb, 1, 'الغزال نوع من الحيوانات، والصقر نوع من الطيور: علاقة نوع وجنسه.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'ملعقة : قِدر', '["دلو : بئر", "شوكة : طعام", "فراولة : مشمش", "قمح : أرز"]'::jsonb, 0, 'الملعقة أداة يُغترف بها من القِدر، والدلو أداة يُغترف بها من البئر: أداة والوعاء الذي تأخذ منه.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'تضاد : تناقض', '["تشابه : تعاكس", "هجاء : ذم", "تطابق : اختلاف", "جود : بخل"]'::jsonb, 1, 'التضاد والتناقض كلمتان مترادفتان، وكذلك الهجاء والذم؛ أما بقية الخيارات فأضداد لا مترادفات.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'موظف : مدير', '["حاجة : عمل", "طفل : مراهق", "نيسان : شباط", "بركان : نار"]'::jsonb, 1, 'الموظف يترقى فيصبح مديرًا، والطفل يكبر فيصبح مراهقًا: مرحلة والمرحلة التالية لها.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'حسنة : سيئة', '["سخط : رضا", "عقوق : آثام", "هداية : عذاب", "مدافعة : مرافعة"]'::jsonb, 0, 'الحسنة ضد السيئة، والسخط ضد الرضا: علاقة تضاد.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'عدوى : مرض', '["برودة : سخونة", "دواء : شفاء", "خوف : خشية", "حزن : بكاء"]'::jsonb, 1, 'العدوى سبب يؤدي إلى المرض، والدواء سبب يؤدي إلى الشفاء: علاقة سبب ونتيجة.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'الحياة أقصر من أن تضيعها في اكتساب .......', '["الندماء", "التباريح", "الغرماء", "السؤدد"]'::jsonb, 2, 'المعنى أن الحياة لا تستحق أن تُهدر في صنع الخصومات، فالمناسب «الغرماء» أي الخصوم والأعداء.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'إذا أتتك الدنيا تأتك ولو على ....... وإذا لم تأتك لم تدفعها بـ.......', '["ضعفك – قوتك", "مرضك – صحتك", "نفوذك – جاهك", "ثروتك – بفقرك"]'::jsonb, 0, 'التقابل المقصود: الدنيا تأتيك رغم ضعفك، ولا تستطيع جلبها بقوتك؛ فالزوج المتضاد المناسب: ضعفك – قوتك.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'الأنانية تسلب روح ....... وتنمي حب .......', '["المحبة – الآخرين", "التعاون – الذات", "العطاء – الخير", "المنافسة – الإيثار"]'::jsonb, 1, 'الأنانية تقتل روح التعاون مع الناس وتضخّم حب الذات؛ فالزوج المتناسب: التعاون – الذات.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'اتبع ....... العدو فهي ترشدك إليه.', '["سهام", "أخبار", "أفكار", "خطط"]'::jsonb, 0, 'السهام تأتي من جهة الرامي، فمن تتبّع مسارها عرف موضع عدوه؛ لذلك «سهام» هي الكلمة التي يستقيم بها المعنى.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'يفهم الإنسان ....... الشيء الذي يطمح الوصول إليه عندما يحوّل الوسيلة إلى .......', '["قيمة – غاية", "حالة – أداة", "أهمية – وسائل", "غاية – قيمة"]'::jsonb, 0, 'الإنسان يدرك قيمة ما يطمح إليه حين يجعل الوسيلة غاية في ذاتها؛ فالمناسب: قيمة – غاية.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'الغبي إذا فشل يسارع في ....... والذكي إذا فشل يسارع في .......', '["الشكوى – العمل", "العمل – الشكوى", "الأعداء – الأصدقاء", "الأصدقاء – الأعداء"]'::jsonb, 0, 'الجملة تقابل بين سلوك الغبي عند الفشل (الشكوى) وسلوك الذكي (العمل).', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', '....... يرتكز على قدمين قويتين: العلم والأخلاق؛ فبدون العلم لا يستطيعون مواكبة العصر، وبدون الأخلاق يصبحون ....... متفجرة.', '["الشباب – طاقة", "الشيخوخة – خبرة", "الرجال – قوة", "النساء – قوة"]'::jsonb, 0, 'الضمير «يستطيعون» يدل على جماعة، والوصف «متفجرة» يناسب «طاقة»: الشباب بلا أخلاق طاقة متفجرة.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'من الغباء أن تتوقع أن أول النجاح لك سيكون تكملة لجميع نجاحاتك.', '["الغباء", "تتوقع", "تكملة", "نجاحاتك"]'::jsonb, 2, 'أول النجاح يكون بداية للنجاحات لا تكملة لها؛ فالخطأ في «تكملة» وصوابها «بداية».', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'كي تبني عاليًا يجب أن تحفر قليلًا.', '["تبني", "عاليًا", "تحفر", "قليلًا"]'::jsonb, 3, 'البناء العالي يحتاج أساسًا عميقًا؛ فالخطأ في «قليلًا» وصوابها «عميقًا».', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'احذر الساكت فهو سم فاتك.', '["احذر", "الساكت", "سم", "فاتك"]'::jsonb, 3, '«فاتك» تُقال لمن يبطش بالناس ويقتل منهم، أما السم فيوصف بأنه «قاتل» أو «ناقع»؛ فالخطأ في «فاتك».', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'تشرق شمسنا وتغيب لكن أملنا بأنفسنا ليس له حدود.', '["تشرق", "لكن", "بأنفسنا", "حدود"]'::jsonb, 2, 'الأمل الذي لا حدود له يكون بالله لا بالأنفس؛ فالخطأ في «بأنفسنا» وصوابها «بالله».', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'أغبى الناس من ضل الطريق في أول سفره وقد قارب المنزل.', '["أغبى", "ضل", "أول", "قارب"]'::jsonb, 2, 'من قارب المنزل يكون في آخر سفره لا في أوله؛ فالخطأ في «أول» وصوابها «آخر».', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["عمود", "سقف", "جدار", "حائط"]'::jsonb, 0, 'السقف والجدار والحائط أسطح تحيط بالمكان وتغلقه، أما العمود فدعامة تحمل ولا تحيط.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["نجوم", "شمس", "سراج", "شموع"]'::jsonb, 0, 'الشمس والسراج والشموع مصادر تضيء ما حولها ويُنتفع بضوئها، أما النجوم فلا تضيء الأرض وإن كانت مضيئة في ذاتها.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["منشار", "زجاج", "مقص", "فأس"]'::jsonb, 1, 'المنشار والمقص والفأس أدوات قطع، أما الزجاج فمادة تُقطع.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["شجرة", "نخلة", "ثمرة", "بذرة"]'::jsonb, 2, 'الشجرة والنخلة والبذرة كائنات نباتية تنبت وتنمو، أما الثمرة فهي ناتج الشجرة لا نبات ينمو.', NULL, 'ad060926-2026-4c00-9d00-060920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'ما سبب الأنَفة من المسألة؟', '["حقارة المسألة", "الحياء", "العلم الغزير", "التكبر"]'::jsonb, 1, 'قال «فلما كبرتُ أنفتُ من ذكرها»: كِبَر سنّه جعله يستحيي أن يسأل عمّا كان ينبغي أن يتعلمه صغيرًا؛ فالسبب هو الحياء.', NULL, 'ad060926-2026-4c00-9d00-060920260001', 'e1a90605-2026-4c00-9d00-000000000005', 'قال بعض أهل النظر والروية: توانيتُ في أوان التعلم عن المسألة عن أشياء كانت الحاجة تحفز إليها والكسل يصد عنها، فلما كبرتُ أنفتُ من ذكرها وعرضها على من علمها عنده، فبقيت الجهالة في نفسي، وركدت الوحشة بين قلبي وفكري.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'القطعة تعبّر عن .......', '["حديث نفس", "تجارب حياة", "أحلام نائم", "الكبر والتواضع"]'::jsonb, 0, 'المتكلم يحاسب نفسه ويصف ما جرى في داخله من توانٍ وأنفة وندم، وهذا هو حديث النفس.', NULL, 'ad060926-2026-4c00-9d00-060920260001', 'e1a90605-2026-4c00-9d00-000000000005', 'قال بعض أهل النظر والروية: توانيتُ في أوان التعلم عن المسألة عن أشياء كانت الحاجة تحفز إليها والكسل يصد عنها، فلما كبرتُ أنفتُ من ذكرها وعرضها على من علمها عنده، فبقيت الجهالة في نفسي، وركدت الوحشة بين قلبي وفكري.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'معنى (توانيتُ) في النص:', '["تواجدت", "ترددت", "تقاعست", "تأنيت"]'::jsonb, 2, 'توانى في الأمر أي قصّر فيه وتقاعس عنه، وهو ما يناسب سياق «الكسل يصد عنها»؛ فالأقرب «تقاعست».', NULL, 'ad060926-2026-4c00-9d00-060920260001', 'e1a90605-2026-4c00-9d00-000000000005', 'قال بعض أهل النظر والروية: توانيتُ في أوان التعلم عن المسألة عن أشياء كانت الحاجة تحفز إليها والكسل يصد عنها، فلما كبرتُ أنفتُ من ذكرها وعرضها على من علمها عنده، فبقيت الجهالة في نفسي، وركدت الوحشة بين قلبي وفكري.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'معنى (يصد) في النص:', '["يتوجب", "يتحرر", "يجبر", "يرد"]'::jsonb, 3, '«الكسل يصد عنها» أي يردّ عنها ويمنع منها؛ فمعنى يصد: يرد.', NULL, 'ad060926-2026-4c00-9d00-060920260001', 'e1a90605-2026-4c00-9d00-000000000005', 'قال بعض أهل النظر والروية: توانيتُ في أوان التعلم عن المسألة عن أشياء كانت الحاجة تحفز إليها والكسل يصد عنها، فلما كبرتُ أنفتُ من ذكرها وعرضها على من علمها عنده، فبقيت الجهالة في نفسي، وركدت الوحشة بين قلبي وفكري.', 4, 'active', false);
END IF;
END
$mig$;

-- مزامنة العداد مع الواقع
UPDATE leak_groups
SET question_count = (SELECT COUNT(*) FROM questions WHERE leak_group_id = 'ad060926-2026-4c00-9d00-060920260001')
WHERE id = 'ad060926-2026-4c00-9d00-060920260001';

-- تحقق نهائي
DO $chk$
DECLARE n INT; nq INT; nv INT; np INT;
BEGIN
  SELECT COUNT(*) INTO n FROM questions WHERE leak_group_id = 'ad060926-2026-4c00-9d00-060920260001';
  SELECT COUNT(*) INTO nq FROM questions WHERE leak_group_id = 'ad060926-2026-4c00-9d00-060920260001' AND section = 'quant';
  SELECT COUNT(*) INTO nv FROM questions WHERE leak_group_id = 'ad060926-2026-4c00-9d00-060920260001' AND section = 'verbal';
  SELECT COUNT(*) INTO np FROM questions WHERE leak_group_id = 'ad060926-2026-4c00-9d00-060920260001' AND passage_id IS NOT NULL;
  RAISE NOTICE 'إجمالي: % — كمي: % — لفظي: % — قطع: %', n, nq, nv, np;
  IF n <> 118 THEN RAISE EXCEPTION 'عدد الأسئلة % لا يطابق المتوقع 118', n; END IF;
  IF nq <> 53 OR nv <> 65 THEN RAISE EXCEPTION 'توزيع كمي/لفظي غير مطابق'; END IF;
END
$chk$;

COMMIT;