-- ═══════════════════════════════════════════════════════════════
-- تسريبات القدرات – الاثنين ٧ سبتمبر ٢٠٢٦
-- 68 سؤالاً: كمي 32 + لفظي 36 (منها 13 في قطع استيعاب)
-- آمن لإعادة التشغيل: guard على وجود أسئلة المجموعة
-- ═══════════════════════════════════════════════════════════════
BEGIN;

INSERT INTO leak_groups (id, title, leak_date, section, question_count, description, is_active, accent_color)
VALUES ('ad070926-2026-4c00-9d00-070920260001', 'تسريبات القدرات – الاثنين ٧ سبتمبر ٢٠٢٦', '2026-09-07', 'mixed', 68, 'أسئلة اختبار القدرات المحوسب ليوم الاثنين ٧ سبتمبر ٢٠٢٦ (٢٥ ربيع الأول ١٤٤٨) — القسمان الكمي واللفظي مع الشروح.', true, '#5B21B6')
ON CONFLICT (id) DO NOTHING;

DO $mig$
BEGIN
IF EXISTS (SELECT 1 FROM questions WHERE leak_group_id = 'ad070926-2026-4c00-9d00-070920260001') THEN
  RAISE NOTICE 'أسئلة المجموعة موجودة مسبقاً — تخطي الإدراج';
ELSE
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'ما الرقم في خانة العشرات في ناتج ضرب العددين ٥٤٣٢١ و١٢٣٤٥؟', '["٥", "٤", "٣", "٢"]'::jsonb, 1, 'خانتا الآحاد والعشرات في ناتج الضرب تتحددان من آخر رقمين في كل عدد فقط: ٢١ × ٤٥ = ٩٤٥، فرقم العشرات ٤.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'موقف سيارات يسع ٤٣٢ سيارة مقسّم إلى ستة أجزاء، كل جزء مكوّن من ٧٢ موقفًا، ومرتبة حسب اللون بالترتيب: أحمر – أبيض – أخضر – أصفر – أسود – أزرق. ما لون الموقف رقم ٣٦٠؟', '["أبيض", "أسود", "أزرق", "أصفر"]'::jsonb, 1, '٣٦٠ ÷ ٧٢ = ٥ بالضبط، فالموقف ٣٦٠ هو آخر موقف في الجزء الخامس، ولون الجزء الخامس بالترتيب هو الأسود.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'خمسة أعداد متتالية مجموع أول عددين منها ٢٧. ما العدد الرابع؟', '["١٤", "١٥", "١٦", "١٧"]'::jsonb, 2, 'عددان متتاليان مجموعهما ٢٧ هما ١٣ و١٤، فالأعداد الخمسة: ١٣، ١٤، ١٥، ١٦، ١٧، والرابع ١٦.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'إذا كانت النقطة (٨، ٥) هي منتصف القطعة الواصلة بين النقطتين (س، ٦) و(٨، ص)، قارن بين:
القيمة الأولى: س
القيمة الثانية: ص', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'الإحداثي السيني للمنتصف = (س + ٨) ÷ ٢ = ٨ فتكون س = ٨، والإحداثي الصادي = (٦ + ص) ÷ ٢ = ٥ فتكون ص = ٤. إذًا س أكبر من ص.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في مثلث قائم الزاوية، زاويتاه الحادتان س وص. قارن بين:
القيمة الأولى: ٣س + ٢ص
القيمة الثانية: ١٨٠', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'في المثلث القائم س + ص = ٩٠. إذًا ٣س + ٢ص = ٢(س + ص) + س = ١٨٠ + س، وهي أكبر من ١٨٠ لأن س موجبة.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'بكم طريقة يمكن تكوين عدد أكبر من ١٠٠٠ أرقامه مختلفة من الأرقام {١، ٢، ٣، ٥}؟', '["٢٤", "٣٠", "٣٢", "٣٦"]'::jsonb, 0, 'العدد الأكبر من ١٠٠٠ يجب أن يكون من أربعة أرقام، أي نستخدم الأرقام الأربعة كلها دون تكرار: ٤ × ٣ × ٢ × ١ = ٢٤ ترتيبًا.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ١/٢٩٣ + ١/٣٩٦
القيمة الثانية: ١/٢٩٩ + ١/٣٩٧', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'الكسر ذو المقام الأصغر أكبر: ١/٢٩٣ > ١/٢٩٩ و١/٣٩٦ > ١/٣٩٧، فمجموع القيمة الأولى أكبر.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'في رسم دائري لمحاصيل مزرعة: القمح ٢٠٪، المانجو ٢٠٪، البرتقال ٣٠٪، الفراولة ٢٠٪، والعنب ١٠٪. ما أقل محصول؟', '["قمح", "مانجو", "عنب", "فراولة"]'::jsonb, 2, 'نقارن النسب: أصغرها ١٠٪ وهي نسبة العنب.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: ٦٠²
القيمة الثانية: ٦٠ × ٣٦ + ٦٠ × ٢٤', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 2, 'نأخذ ٦٠ عاملًا مشتركًا في القيمة الثانية: ٦٠ × (٣٦ + ٢٤) = ٦٠ × ٦٠ = ٦٠²؛ فالقيمتان متساويتان.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'الشكل المجاور أسطوانة. ما شكل قاعدتها؟', '["دائرة", "مثلث", "مستطيل", "مربع"]'::jsonb, 0, 'الأسطوانة مجسّم قاعدتاه دائرتان متطابقتان متوازيتان يصل بينهما سطح منحنٍ.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'مثلث قائم الزاوية ضلعا قائمته ٣ و٤ مرسوم داخل دائرة بحيث يكون وتره قطرًا لها. قارن بين:
القيمة الأولى: ٣
القيمة الثانية: طول نصف قطر الدائرة', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'الوتر = √(٣² + ٤²) = ٥ وهو القطر، فنصف القطر = ٢٫٥ وهو أقل من ٣.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور: مربع كبير طول ضلعه يساوي طول قطر مربع صغير طول ضلعه ٤ سم. المربع الصغير مائل بحيث ينطبق أحد قطريه على الضلع السفلي للمربع الكبير، فنصفه داخل الكبير ونصفه خارجه. احسب مساحة الجزء المظلل (ما داخل المربع الكبير وخارج الصغير).', '["٢٤", "٣٦", "٤٨", "٦٤"]'::jsonb, 0, 'قطر المربع الصغير = ٤√٢ = ضلع الكبير، فمساحة الكبير = (٤√٢)² = ٣٢ سم². نصف المربع الصغير فقط داخل الكبير ومساحته ١٦ ÷ ٢ = ٨، فالمظلل = ٣٢ − ٨ = ٢٤ سم².', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep07_q012_squares.png', 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'معدل انسياب السيارات في الساعة: يوم الاثنين ٤٠٠ سيارة، ويوم الخميس ٣٠٠ سيارة. كم ساعة يلزم يوم الاثنين ليمر عدد من السيارات يساوي ما يمر يوم الخميس في ٤ ساعات؟', '["٢", "٢٫٥", "٢٫٧", "٣"]'::jsonb, 3, 'الخميس في ٤ ساعات: ٤ × ٣٠٠ = ١٢٠٠ سيارة. بمعدل الاثنين ٤٠٠ في الساعة نحتاج ١٢٠٠ ÷ ٤٠٠ = ٣ ساعات.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'يبيّن الجدول القروض بالمليارات لأربع دول: السعودية: استهلاكية ٢٧٦ وعقارية ٨٦؛ قطر: ٢٥٠ و١٨٥؛ الإمارات: ٢٧٢ و٢٥٦؛ البحرين: ٢٤٢ و١٧٥. ما الدولة التي بها أعلى قروض عقارية؟', '["السعودية", "قطر", "الإمارات", "البحرين"]'::jsonb, 2, 'نقارن عمود القروض العقارية فقط: ٨٦، ١٨٥، ٢٥٦، ١٧٥، وأعلاها ٢٥٦ للإمارات.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'بكم طريقة يمكن تكوين عدد من الأرقام ١، ٣، ٤ (باستخدامها كلها دون تكرار) بحيث يقبل القسمة على ٤؟', '["صفر", "١", "٢", "٣"]'::jsonb, 0, 'العدد يقبل القسمة على ٤ إذا قبل آخر رقمين فيه القسمة على ٤. الأزواج الممكنة في النهاية: ١٣، ١٤، ٣١، ٣٤، ٤١، ٤٣، ولا واحد منها يقبل القسمة على ٤، فلا توجد طريقة.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'الإنتاج السنوي للسيارات في ألمانيا ٢¼ مليون سيارة. إذا كان الإنتاج ثابتًا شهريًا، فكم سيارة تنتج ألمانيا شهريًا؟', '["١٨٧٥٠٠", "١٨٥٧٠٠", "١٨٥٠٠", "١٨٠٠٠٠"]'::jsonb, 0, '٢¼ مليون = ٢٢٥٠٠٠٠ سيارة سنويًا، وبالقسمة على ١٢ شهرًا: ٢٢٥٠٠٠٠ ÷ ١٢ = ١٨٧٥٠٠ سيارة شهريًا.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان ٩^(ص/٢) = ٨١، قارن بين:
القيمة الأولى: ص²
القيمة الثانية: ٦', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, '٨١ = ٩²، فيكون ص/٢ = ٢ ومنها ص = ٤، وص² = ١٦ وهي أكبر من ٦.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'يقرأ محمود كتابًا خلال ٦ أيام، وكل يوم يقرأ مثلي ما قرأه في اليوم السابق. إذا قرأ في اليوم الأول ٥ صفحات، فكم عدد صفحات الكتاب؟', '["٣٠٠", "٣٠٥", "٣١٥", "٣٢٠"]'::jsonb, 2, 'الصفحات اليومية تتضاعف: ٥، ١٠، ٢٠، ٤٠، ٨٠، ١٦٠، ومجموعها ٣١٥ صفحة.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'الإيرادات والمصروفات بالملايين لأربع شركات: الأولى ٢ و٤، الثانية ٢ و٣٫١، الثالثة ٤٫١ و٣٫٨، الرابعة ٤٫٣ و٣٫١. أي الشركات أكثر تحقيقًا للربح؟', '["الأولى", "الثانية", "الثالثة", "الرابعة"]'::jsonb, 3, 'الربح = الإيرادات − المصروفات: الأولى −٢ (خسارة)، الثانية −١٫١، الثالثة ٠٫٣، الرابعة ١٫٢؛ فالرابعة الأكثر ربحًا.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان س > ١ و ٢٠٪ من (س²/٥٠) = ٢، قارن بين:
القيمة الأولى: س
القيمة الثانية: ١٤', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, '٢٠٪ من (س²/٥٠) = ٢ يعني س²/٥٠ = ١٠، فـس² = ٥٠٠ وس ≈ ٢٢٫٤ (موجبة لأن س > ١)، وهي أكبر من ١٤.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'في مخطط الساق والأوراق لدرجات صف (١/٣): الساق ٠ أوراقه ١، ٢، ٣، ٤، ٥، ٦؛ والساق ١ أوراقه ١، ٢، ٣، ٥، ٥، ٦؛ والساق ٢ أوراقه ١، ٣، ٤، ٥، ٦؛ والساق ٣ أوراقه ٠، ٠، ٠، ٠. أوجد عدد طلاب الصف.', '["٢٤", "٢٢", "٢١", "٢٠"]'::jsonb, 2, 'كل ورقة تمثل طالبًا واحدًا، فنعدّ الأوراق: ٦ + ٦ + ٥ + ٤ = ٢١ طالبًا.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'فول : بقوليات', '["طماطم : فاكهة", "بيض : بروتين", "مدارس : جامعات", "حافلة : مركبات"]'::jsonb, 3, 'الفول فرد من فئة البقوليات، والحافلة فرد من فئة المركبات: علاقة فرد بفئته.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'سيارة : كفر', '["قشر : برتقال", "مكتبة : رفوف", "فصل : ساحة", "غرفة : باب"]'::jsonb, 3, 'الكفر جزء من السيارة، والباب جزء من الغرفة: كلٌّ وجزؤه بالترتيب نفسه. أما «قشر : برتقال» فالجزء جاء أولًا.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'نشيج : بكاء', '["شمس : نهار", "فل : ياسمين", "كآبة : مرأة", "رجل : كهل"]'::jsonb, 1, 'النشيج بكاء له صوت متقطع، فهو نوع من البكاء؛ والفل نوع من الياسمين: علاقة نوع وجنسه.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'أسد : غزال', '["كلب : نباح", "خيل : فرس", "نمر : سرعة", "نحل : رحيق"]'::jsonb, 3, 'الغزال غذاء الأسد الذي يصطاده، والرحيق غذاء النحل الذي يجمعه: علاقة كائن وغذائه.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'مراجع : بحث', '["صيت : شهرة", "عبرة : تأمل", "كتابة : مراجعة", "تدرب : خبرة"]'::jsonb, 3, 'المراجع هي ما يُبنى عليه البحث، والتدرب ما تُبنى عليه الخبرة: علاقة أساس وما ينتج عنه.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'العراق : بغداد', '["السعودية : الدرعية", "القاهرة : الإسكندرية", "سوريا : دمشق", "الرباط : المغرب"]'::jsonb, 2, 'بغداد عاصمة العراق، ودمشق عاصمة سوريا: علاقة دولة وعاصمتها بالترتيب نفسه. أما «الرباط : المغرب» فالترتيب معكوس.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'ما زالت ....... التسرب من التعليم مثيرة للقلق، وما زالت طرائق التدريس عامة تجري بأساليب تربوية ....... الزمن.', '["معدلات – تفاداها", "أفواج – تجاوزها", "أنواع – تحاشاها", "شرائح – تناساها"]'::jsonb, 1, '«تجاوزها الزمن» هو التعبير المستقر لوصف الأساليب القديمة، و«أفواج التسرب» تصف الأعداد الكبيرة من المتسربين؛ فالزوج المناسب: أفواج – تجاوزها.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'الشعراء ....... تغنوا بالشجرة حتى شبهوا المرأة بأغصانها .......', '["الجاهلون – الطويلة", "الفحول – الواقفة", "الأقوياء – المورقة", "العرب – المتمايلة"]'::jsonb, 3, 'الشعراء العرب هم من اشتهروا بالتغني بالشجرة، والأغصان المتمايلة هي وجه الشبه بقوام المرأة؛ فالزوج المناسب: العرب – المتمايلة.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'اللغة ....... أكثر اللغات السامية استخدامًا، ومن ....... اللغات انتشارًا.', '["الإنجليزية – أقل", "العربية – أكثر", "اللاتينية – أولى", "العبرية – آخر"]'::jsonb, 1, 'العربية من اللغات السامية وهي أكثرها استخدامًا، وهي أيضًا من أكثر اللغات انتشارًا في العالم.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'المتحدث الذي ....... من حقه أن يكون .......', '["لا يخطئ – مغرورًا", "لا يحفظ – ناسيًا", "لا يهتم – شجاعًا", "لا يحضّر – خائفًا"]'::jsonb, 3, 'من لا يحضّر لحديثه يحق له أن يخاف من الوقوف أمام الناس؛ فالمعنى المستقيم: لا يحضّر – خائفًا.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'الكبر على الباطل ....... والكبر على الحق .......', '["حلال – محال", "محال – حلال", "باطل – واجب", "واجب – باطل"]'::jsonb, 3, 'التعالي على الباطل ورفضه واجب، أما التكبر على الحق فباطل مرفوض؛ فالزوج المناسب: واجب – باطل.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'لما كان القصد من الوفاء والنية المحمولة عليه ....... لا يعلمها سوى صاحبها وخالقه، فإن الجزاء يكون على ....... الوفاء وليس على وقوعه.', '["مضمرة – قصدية", "غائبة – رغبة", "ظاهرة – عفوية", "بينة – حيلة"]'::jsonb, 0, 'النية خفية (مضمرة) لا يعلمها إلا صاحبها والله، ولذلك يكون الجزاء على قصد الوفاء (قصديته) لا على وقوعه.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'للحياة حدان، أحدهما الأمل والثاني الأجل، فبالأول فراقها وبالثاني فناؤها.', '["الأمل", "الأجل", "فراقها", "فناؤها"]'::jsonb, 2, 'بالأمل تُعمر الحياة وتبقى، وبالأجل تفنى؛ فـ«فراقها» في غير موضعها والصواب «بقاؤها».', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'كل شيء إذا قلّ رخص إلا العلم فإنه إذا كثر غلا.', '["قلّ", "العلم", "كثر", "غلا"]'::jsonb, 0, 'الحكمة المعروفة: كل شيء إذا كثر رخص إلا العلم فإنه إذا كثر غلا؛ فالمقابلة تقتضي «كثر» في الموضعين، والخطأ في «قلّ».', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'لا يتم أمر الإنسان إلا بالوزراء والأعوان، ولا ينفع الوزراء والأعوان إلا بالمودة والنصيحة، ولا تنفع المودة والنصيحة إلا بالرأي والعفة.', '["الإنسان", "الوزراء", "ينفع", "المودة"]'::jsonb, 0, 'الوزراء والأعوان يكونون للملك أو السلطان لا لعامة الناس؛ فالخطأ في «الإنسان» وصوابها «السلطان».', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'تعودت على الضوضاء حتى إن الإزعاج بدأ يثير أعصابي.', '["تعودت", "الإزعاج", "بدأ", "أعصابي"]'::jsonb, 1, 'من تعوّد الضوضاء يصبح الهدوء هو ما يثير أعصابه؛ فالخطأ في «الإزعاج» وصوابها «الهدوء».', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'إن للتعلم مرارة لن يذوقها إلا من ذاق مرارته.', '["مرارة", "يذوقها", "ذاق", "مرارته"]'::jsonb, 0, 'المعنى المقصود المقابلة بين حلاوة التعلم ومرارته: إن للتعلم حلاوة لن يذوقها إلا من ذاق مرارته؛ فالخطأ في «مرارة» الأولى.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["إصابة", "تعب", "مرض", "إعاقة"]'::jsonb, 3, 'الإصابة والتعب والمرض حالات عارضة تزول بالعلاج أو الراحة، أما الإعاقة فحالة دائمة.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["حنو", "رأفة", "رحمة", "غلو"]'::jsonb, 3, 'الحنو والرأفة والرحمة معانٍ متقاربة للعطف واللين، أما الغلو فهو المبالغة وتجاوز الحد.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["تمر", "عسل", "جبن", "بيض"]'::jsonb, 0, 'العسل والجبن والبيض منتجات حيوانية المصدر، أما التمر فنباتي.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["بحر", "بحيرة", "نهر", "بئر"]'::jsonb, 3, 'البحر والبحيرة والنهر مسطحات مائية طبيعية ظاهرة على سطح الأرض، أما البئر فحفرة يصنعها الإنسان للوصول إلى الماء الجوفي.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["مال", "قرض", "دين", "سلف"]'::jsonb, 0, 'القرض والدين والسلف كلها صور لمال مستحق الرد، أما «مال» فكلمة عامة لا تحمل معنى الاستحقاق.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["المسك", "الريحان", "الفل", "الياسمين"]'::jsonb, 0, 'الريحان والفل والياسمين نباتات عطرية، أما المسك فطيب حيواني المصدر.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يُفهم من النص أن:', '["القراءة الصامتة أكثر فاعلية في تحقيق الأهداف من القراءة بصوت عالٍ", "القراءة الصامتة تساعد على الاستقلالية", "القراءة الشفهية أسرع في التعلم", "القراءة الصامتة تناسب الكبار فقط"]'::jsonb, 0, 'النص صريح: القراءة الصامتة أفضل من الشفهية لأنها تساعد في تحقيق الأهداف أكثر منها.', NULL, 'ad070926-2026-4c00-9d00-070920260001', 'e1a90701-2026-4c00-9d00-000000000001', 'القراءة الصامتة عملية تتطلب تركيزًا، وهي أفضل من القراءة الشفهية لأنها تساعد في تحقيق الأهداف أكثر منها. والطفل لا بد أن يبدأ في تعلمها منذ وقت مبكر؛ لأنها ستفيده عندما يكبر ويعتمد على نفسه في دراسة المقررات الدراسية، حتى تكون لديه استقلالية في القراءة منذ الصغر.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يُستفاد من النص أن:', '["القراءة الصامتة تساعد في تحقيق الأهداف", "القراءة الصامتة تمكّن الطفل من الاستقلالية في القراءة منذ الصغر", "القراءة الشفهية لا فائدة منها", "الطفل لا يحتاج تعلم القراءة الصامتة مبكرًا"]'::jsonb, 0, 'الفائدة الأساسية التي بنى عليها النص تفضيل القراءة الصامتة هي أنها تساعد في تحقيق الأهداف.', NULL, 'ad070926-2026-4c00-9d00-070920260001', 'e1a90701-2026-4c00-9d00-000000000001', 'القراءة الصامتة عملية تتطلب تركيزًا، وهي أفضل من القراءة الشفهية لأنها تساعد في تحقيق الأهداف أكثر منها. والطفل لا بد أن يبدأ في تعلمها منذ وقت مبكر؛ لأنها ستفيده عندما يكبر ويعتمد على نفسه في دراسة المقررات الدراسية، حتى تكون لديه استقلالية في القراءة منذ الصغر.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'من مميزات القراءة الصامتة:', '["استيعاب واستخلاص المفردات المطبوعة", "تساعد على استقلالية الأطفال في القراءة", "أكثر فاعلية من القراءة الشفهية في تلبية الأغراض", "تميّز وتفسّر الكلمات المطبوعة"]'::jsonb, 2, 'الميزة التي ذكرها النص صراحة أنها تحقق الأهداف (الأغراض) أكثر من القراءة الشفهية.', NULL, 'ad070926-2026-4c00-9d00-070920260001', 'e1a90701-2026-4c00-9d00-000000000001', 'القراءة الصامتة عملية تتطلب تركيزًا، وهي أفضل من القراءة الشفهية لأنها تساعد في تحقيق الأهداف أكثر منها. والطفل لا بد أن يبدأ في تعلمها منذ وقت مبكر؛ لأنها ستفيده عندما يكبر ويعتمد على نفسه في دراسة المقررات الدراسية، حتى تكون لديه استقلالية في القراءة منذ الصغر.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'المترجم الفطين هو الذي:', '["يحافظ على روح النص", "يترجم حرفيًا ما ينقله إلى اللغة الأخرى", "يستبدل المعاني بأخرى مؤثرة", "يقدّر الأفكار والأقوال وفق ميوله"]'::jsonb, 0, 'النص يصف المترجم بأنه يقدّر المعنى المقصود وكيفية نقله للغة المترجم إليها، أي يحافظ على روح النص لا حرفيته.', NULL, 'ad070926-2026-4c00-9d00-070920260001', 'e1a90702-2026-4c00-9d00-000000000002', 'تلعب الترجمة دورًا أساسيًا في حياة الأفراد والأمم، فهي نقل الأفكار والأقوال من لغة إلى أخرى، وتساهم في نشر وتبادل الثقافات والعلوم بين شعوب العالم. والترجمة من الفنون القديمة، ومن أوائل التراجم ذات الدلالة الحضارية تلك التي تمت في الأندلس، حيث تُرجم الكثير من الأعمال الأدبية وعلوم الرياضيات والطب من العربية إلى اللاتينية، وقد ساهمت هذه العلوم والآداب في قيام عصر النهضة في أوروبا.
والمترجم هو المحور الأساس في عملية الترجمة، حيث يقوم بتقدير المعنى المقصود من تلك الأفكار والنصوص المراد ترجمتها تقديرًا صحيحًا، وكيفية نقلها للغة المترجم إليها.
وهناك ثلاثة أنواع من التراجم:
١. الترجمة التحريرية: وهي الأكثر شيوعًا، وتمتاز بدقة المعنى وسلامة الأسلوب بسبب الفرصة الممنوحة للمترجم من أعمال المراجعة والتدقيق للنص المترجم قبل نشره.
٢. الترجمة الفورية: وتُستخدم عادة في لغة الكلام، حيث يتم خلالها ترجمة ما يصدر من قول في اللغة الأصل إلى اللغة التي يفهمها السامع.
٣. الترجمة الميكانيكية: وهي التي يقوم بها جهاز حاسوبي لأغراض الترجمة، وبها تجري ترجمة حرفية للكلمات فينتج عنها جمل غالبًا ما تكون ناقصة وغير سليمة من حيث القواعد اللغوية.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'تتطلب الترجمة الفورية — كما يُفهم من النص — مهارة الترجمة والإتقان للغة:', '["الأم", "المترجم منها", "المترجم إليها", "المترجم منها وإليها"]'::jsonb, 3, 'الترجمة الفورية تنقل القول من اللغة الأصل إلى لغة السامع في اللحظة نفسها، فلا تتم إلا بإتقان اللغتين معًا.', NULL, 'ad070926-2026-4c00-9d00-070920260001', 'e1a90702-2026-4c00-9d00-000000000002', 'تلعب الترجمة دورًا أساسيًا في حياة الأفراد والأمم، فهي نقل الأفكار والأقوال من لغة إلى أخرى، وتساهم في نشر وتبادل الثقافات والعلوم بين شعوب العالم. والترجمة من الفنون القديمة، ومن أوائل التراجم ذات الدلالة الحضارية تلك التي تمت في الأندلس، حيث تُرجم الكثير من الأعمال الأدبية وعلوم الرياضيات والطب من العربية إلى اللاتينية، وقد ساهمت هذه العلوم والآداب في قيام عصر النهضة في أوروبا.
والمترجم هو المحور الأساس في عملية الترجمة، حيث يقوم بتقدير المعنى المقصود من تلك الأفكار والنصوص المراد ترجمتها تقديرًا صحيحًا، وكيفية نقلها للغة المترجم إليها.
وهناك ثلاثة أنواع من التراجم:
١. الترجمة التحريرية: وهي الأكثر شيوعًا، وتمتاز بدقة المعنى وسلامة الأسلوب بسبب الفرصة الممنوحة للمترجم من أعمال المراجعة والتدقيق للنص المترجم قبل نشره.
٢. الترجمة الفورية: وتُستخدم عادة في لغة الكلام، حيث يتم خلالها ترجمة ما يصدر من قول في اللغة الأصل إلى اللغة التي يفهمها السامع.
٣. الترجمة الميكانيكية: وهي التي يقوم بها جهاز حاسوبي لأغراض الترجمة، وبها تجري ترجمة حرفية للكلمات فينتج عنها جمل غالبًا ما تكون ناقصة وغير سليمة من حيث القواعد اللغوية.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'تمتاز الترجمة التحريرية بدقة المعنى لأنها:', '["تعطي متسعًا من الوقت للترجمة", "كثيرة التدقيق والتأكد", "تعتمد على أساليب المترجم ودقته", "استخدامها شائع"]'::jsonb, 0, 'النص يعلل الدقة بـ«الفرصة الممنوحة للمترجم» للمراجعة والتدقيق قبل النشر، أي بالوقت المتسع.', NULL, 'ad070926-2026-4c00-9d00-070920260001', 'e1a90702-2026-4c00-9d00-000000000002', 'تلعب الترجمة دورًا أساسيًا في حياة الأفراد والأمم، فهي نقل الأفكار والأقوال من لغة إلى أخرى، وتساهم في نشر وتبادل الثقافات والعلوم بين شعوب العالم. والترجمة من الفنون القديمة، ومن أوائل التراجم ذات الدلالة الحضارية تلك التي تمت في الأندلس، حيث تُرجم الكثير من الأعمال الأدبية وعلوم الرياضيات والطب من العربية إلى اللاتينية، وقد ساهمت هذه العلوم والآداب في قيام عصر النهضة في أوروبا.
والمترجم هو المحور الأساس في عملية الترجمة، حيث يقوم بتقدير المعنى المقصود من تلك الأفكار والنصوص المراد ترجمتها تقديرًا صحيحًا، وكيفية نقلها للغة المترجم إليها.
وهناك ثلاثة أنواع من التراجم:
١. الترجمة التحريرية: وهي الأكثر شيوعًا، وتمتاز بدقة المعنى وسلامة الأسلوب بسبب الفرصة الممنوحة للمترجم من أعمال المراجعة والتدقيق للنص المترجم قبل نشره.
٢. الترجمة الفورية: وتُستخدم عادة في لغة الكلام، حيث يتم خلالها ترجمة ما يصدر من قول في اللغة الأصل إلى اللغة التي يفهمها السامع.
٣. الترجمة الميكانيكية: وهي التي يقوم بها جهاز حاسوبي لأغراض الترجمة، وبها تجري ترجمة حرفية للكلمات فينتج عنها جمل غالبًا ما تكون ناقصة وغير سليمة من حيث القواعد اللغوية.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'أي الآتي صحيح وفق النص؟', '["المشكلات والعقبات ملح الحياة", "المشكلات والعقبات من ضروريات الحياة", "المشكلات والعقبات من منغصات الحياة", "العقبات والصعوبات غير ضرورية"]'::jsonb, 0, 'النص يرى أن الحياة بلا عقبات مملة ولا قيمة لها، فالعقبات هي ما يعطيها طعمها؛ أي إنها ملح الحياة.', NULL, 'ad070926-2026-4c00-9d00-070920260001', 'e1a90703-2026-4c00-9d00-000000000003', 'لو خلت الحياة من العقبات والعوائق لأصبحت مملة؛ فمحاولة تخطي العقبات والعوائق هي التي تولّد الشعور بالإثارة والفوز. فالحياة بلا مشقة ولا متاعب تصبح حياة لا قيمة لها، ويجب أن يكون هناك متاعب، ثم مثابرة لتخطيها، ثم الفوز بالحياة.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'علاقة عبارة (لأصبحت مملة) بما قبلها:', '["نتيجة", "سبب", "تعليل", "تضاد"]'::jsonb, 0, '«لو خلت الحياة من العقبات» شرط، و«لأصبحت مملة» جوابه، أي النتيجة المترتبة على الشرط.', NULL, 'ad070926-2026-4c00-9d00-070920260001', 'e1a90703-2026-4c00-9d00-000000000003', 'لو خلت الحياة من العقبات والعوائق لأصبحت مملة؛ فمحاولة تخطي العقبات والعوائق هي التي تولّد الشعور بالإثارة والفوز. فالحياة بلا مشقة ولا متاعب تصبح حياة لا قيمة لها، ويجب أن يكون هناك متاعب، ثم مثابرة لتخطيها، ثم الفوز بالحياة.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'نستنتج من ترتيب النص أن الحياة عبارة عن:', '["مشقة ومتاعب – مثابرة – الفوز بالحياة", "الفوز بالحياة – مشقة ومتاعب – مثابرة", "مثابرة – الفوز بالحياة – مشقة ومتاعب", "الفوز بالحياة – مثابرة – مشقة ومتاعب"]'::jsonb, 0, 'النص يرتبها صراحة: متاعب، ثم مثابرة لتخطيها، ثم الفوز بالحياة.', NULL, 'ad070926-2026-4c00-9d00-070920260001', 'e1a90703-2026-4c00-9d00-000000000003', 'لو خلت الحياة من العقبات والعوائق لأصبحت مملة؛ فمحاولة تخطي العقبات والعوائق هي التي تولّد الشعور بالإثارة والفوز. فالحياة بلا مشقة ولا متاعب تصبح حياة لا قيمة لها، ويجب أن يكون هناك متاعب، ثم مثابرة لتخطيها، ثم الفوز بالحياة.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'العلاقة بين (المشقة) و(المتاعب):', '["ترادف", "تتابع", "تضاد", "تمثيل"]'::jsonb, 0, 'المشقة والمتاعب لفظان بمعنى واحد تقريبًا، فالعلاقة ترادف.', NULL, 'ad070926-2026-4c00-9d00-070920260001', 'e1a90703-2026-4c00-9d00-000000000003', 'لو خلت الحياة من العقبات والعوائق لأصبحت مملة؛ فمحاولة تخطي العقبات والعوائق هي التي تولّد الشعور بالإثارة والفوز. فالحياة بلا مشقة ولا متاعب تصبح حياة لا قيمة لها، ويجب أن يكون هناك متاعب، ثم مثابرة لتخطيها، ثم الفوز بالحياة.', 4, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'العنوان الأنسب للنص:', '["وجود العوائق والعقبات ضروري من أجل الحياة", "وجود العقبات وتخطيها ضروري من أجل الحياة", "الحياة بلا عقبات", "الفوز بالحياة سهل"]'::jsonb, 1, 'النص لا يكتفي بوجود العقبات بل يجعل تخطيها هو ما يولّد الإثارة والفوز؛ فالعنوان الجامع: وجود العقبات وتخطيها.', NULL, 'ad070926-2026-4c00-9d00-070920260001', 'e1a90703-2026-4c00-9d00-000000000003', 'لو خلت الحياة من العقبات والعوائق لأصبحت مملة؛ فمحاولة تخطي العقبات والعوائق هي التي تولّد الشعور بالإثارة والفوز. فالحياة بلا مشقة ولا متاعب تصبح حياة لا قيمة لها، ويجب أن يكون هناك متاعب، ثم مثابرة لتخطيها، ثم الفوز بالحياة.', 5, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'الترتيب الزمني لتخطي العقبات هو:', '["تخطي العقبات – الإثارة – الشعور بالفوز", "الإثارة – تخطي العقبات – الشعور بالفوز", "الشعور بالفوز – الإثارة – تخطي العقبات", "الإثارة – الشعور بالفوز – تخطي العقبات"]'::jsonb, 0, 'النص يقول إن محاولة تخطي العقبات هي التي تولّد الإثارة ثم الشعور بالفوز، فالتخطي أولًا ثم الإثارة ثم الفوز.', NULL, 'ad070926-2026-4c00-9d00-070920260001', 'e1a90703-2026-4c00-9d00-000000000003', 'لو خلت الحياة من العقبات والعوائق لأصبحت مملة؛ فمحاولة تخطي العقبات والعوائق هي التي تولّد الشعور بالإثارة والفوز. فالحياة بلا مشقة ولا متاعب تصبح حياة لا قيمة لها، ويجب أن يكون هناك متاعب، ثم مثابرة لتخطيها، ثم الفوز بالحياة.', 6, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'علاقة (العوائق) بـ(العقبات):', '["تضاد", "ترادف", "ترتيب", "تخالف"]'::jsonb, 1, 'العوائق والعقبات كلمتان بمعنى واحد في النص، فالعلاقة ترادف.', NULL, 'ad070926-2026-4c00-9d00-070920260001', 'e1a90703-2026-4c00-9d00-000000000003', 'لو خلت الحياة من العقبات والعوائق لأصبحت مملة؛ فمحاولة تخطي العقبات والعوائق هي التي تولّد الشعور بالإثارة والفوز. فالحياة بلا مشقة ولا متاعب تصبح حياة لا قيمة لها، ويجب أن يكون هناك متاعب، ثم مثابرة لتخطيها، ثم الفوز بالحياة.', 7, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'ما أكبر عدد يمكن تكوينه من الأرقام ١، ٢، ٣، ٥ بحيث يكون أكبر من ١٠٠٠ ودون تكرار أي رقم؟', '["٥٢٣١", "٣٥٢١", "٥٣١٢", "٥٣٢١"]'::jsonb, 3, 'للحصول على أكبر عدد نرتب الأرقام تنازليًا من اليسار: ٥ ثم ٣ ثم ٢ ثم ١، فالعدد ٥٣٢١.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'مكعب ٣ من أوجهه باللون الأزرق، ووجهان باللون الأحمر، ووجه واحد باللون الأصفر. أوجد نسبة الأوجه الحمراء.', '["١/٦", "٣/٥", "١/٣", "٢/٣"]'::jsonb, 2, 'للمكعب ٦ أوجه، والحمراء منها ٢، فالنسبة = ٢/٦ = ١/٣.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'أوجد قيمة: (٤ + ٣) × ٢ − ٤ = .....', '["١٢", "٤", "٥", "١٠"]'::jsonb, 3, 'القوس أولًا: ٤ + ٣ = ٧، ثم الضرب: ٧ × ٢ = ١٤، ثم الطرح: ١٤ − ٤ = ١٠.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: (٢٦ − ١٦) × (١٦ − ٦) × (١٦ − ٧)
القيمة الثانية: ٣٦ ÷ ٠٫٠٤', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 2, 'الأولى: ١٠ × ١٠ × ٩ = ٩٠٠. الثانية: ٣٦ ÷ ٠٫٠٤ = ٣٦٠٠ ÷ ٤ = ٩٠٠. متساويتان.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'المثلثان أ ب ج وهـ د و متطابقان بحيث أ ب = هـ د، وأ ج = هـ و، وب ج = د و. في المثلث هـ د و: قياس الزاوية هـ = ٣٠° وقياس الزاوية د = ٢٧°. قارن بين:
القيمة الأولى: قياس الزاوية ج
القيمة الثانية: ١١١', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'الزاوية و في المثلث الثاني = ١٨٠ − ٣٠ − ٢٧ = ١٢٣°. وبالتطابق تقابل الزاوية ج الزاوية و (لأن الضلعين المحيطين بهما متناظران)، فزاوية ج = ١٢٣° وهي أكبر من ١١١.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'في رسم دائري لتقديرات ٦٠٠ طالب: ممتاز ٤٥°، جيد جدًا ٧٥°، جيد ١٢٠°، مقبول ٨٠°، ضعيف ٤٠°. إذا كان ترتيب أحمد ٢٢٢ عند ترتيب الطلاب من الأعلى تقديرًا إلى الأدنى، فما تقديره؟', '["مقبول", "جيد", "جيد جدًا", "ممتاز"]'::jsonb, 1, 'عدد طلاب كل تقدير = ٦٠٠ × (الزاوية ÷ ٣٦٠): ممتاز ٧٥، جيد جدًا ١٢٥ (المجموع التراكمي ٢٠٠)، جيد ٢٠٠ (التراكمي ٤٠٠). الترتيب ٢٢٢ يقع بين ٢٠١ و٤٠٠، أي في فئة جيد.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'في رسم دائري لأنواع النفايات: الورقية ٣٥٪ والمعدنية ١٥٪ والباقي بلاستيكية وطعام. إذا تضاعفت نسبة النفايات المعدنية على حساب الورقية، فكم تصبح نسبة النفايات الورقية؟', '["٣٠٪", "٢٥٪", "٢٠٪", "١٥٪"]'::jsonb, 2, 'تضاعف المعدنية من ١٥٪ إلى ٣٠٪ يعني زيادة ١٥٪ تُؤخذ من الورقية: ٣٥ − ١٥ = ٢٠٪.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'إذا كانت س وص زاويتين متكاملتين، وس وع زاويتين متتامتين، فأوجد ص + ع.', '["٢٧٠ − س", "٢٧٠ − ٢س", "٢٧٠ − ٣س", "٢٧٠ − ٤س"]'::jsonb, 1, 'ص = ١٨٠ − س (متكاملتان)، وع = ٩٠ − س (متتامتان)، فالمجموع ص + ع = ٢٧٠ − ٢س.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'ربع دائرة نصف قطرها ٨. أوجد محيط هذا الربع.', '["١٦π + ١٦", "٤π + ١٦", "٨π + ١٦", "٦π + ١٦"]'::jsonb, 1, 'طول القوس = ربع محيط الدائرة = (٢π × ٨) ÷ ٤ = ٤π، ونضيف نصفي القطر المستقيمين ٨ + ٨ = ١٦، فالمحيط = ٤π + ١٦.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'مستطيل أ ب ج د فيه أ د = ٦ سم، وت منتصف الضلع أ د، والمثلث ت ب ج متطابق الضلعين حيث ت ب = ت ج = ٥ سم. أوجد طول أ ب.', '["٦", "٢", "٤", "١"]'::jsonb, 2, 'أ ت = نصف أ د = ٣ سم. المثلث ت أ ب قائم الزاوية في أ (زاوية المستطيل)، فبفيثاغورس: أ ب = √(٥² − ٣²) = √١٦ = ٤ سم.', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'إذا كان محيط مثلث قائم الزاوية ٢٤، قارن بين:
القيمة الأولى: طول الوتر
القيمة الثانية: ٨', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'الوتر أطول أضلاع المثلث القائم، فهو أكبر من ثلث المحيط (٨) دائمًا؛ فلو كان الوتر ٨ أو أقل لكان مجموع الضلعين الآخرين ١٦ أو أكثر وكل منهما أقصر من الوتر، وهذا مستحيل. (مثال: المثلث ٦–٨–١٠ محيطه ٢٤ ووتره ١٠.)', NULL, 'ad070926-2026-4c00-9d00-070920260001', NULL, NULL, NULL, 'active', false);
END IF;
END
$mig$;

-- مزامنة العداد مع الواقع
UPDATE leak_groups
SET question_count = (SELECT COUNT(*) FROM questions WHERE leak_group_id = 'ad070926-2026-4c00-9d00-070920260001')
WHERE id = 'ad070926-2026-4c00-9d00-070920260001';

-- تحقق نهائي
DO $chk$
DECLARE n INT; nq INT; nv INT; np INT;
BEGIN
  SELECT COUNT(*) INTO n FROM questions WHERE leak_group_id = 'ad070926-2026-4c00-9d00-070920260001';
  SELECT COUNT(*) INTO nq FROM questions WHERE leak_group_id = 'ad070926-2026-4c00-9d00-070920260001' AND section = 'quant';
  SELECT COUNT(*) INTO nv FROM questions WHERE leak_group_id = 'ad070926-2026-4c00-9d00-070920260001' AND section = 'verbal';
  SELECT COUNT(*) INTO np FROM questions WHERE leak_group_id = 'ad070926-2026-4c00-9d00-070920260001' AND passage_id IS NOT NULL;
  RAISE NOTICE 'إجمالي: % — كمي: % — لفظي: % — قطع: %', n, nq, nv, np;
  IF n <> 68 THEN RAISE EXCEPTION 'عدد الأسئلة % لا يطابق المتوقع 68', n; END IF;
  IF nq <> 32 OR nv <> 36 THEN RAISE EXCEPTION 'توزيع كمي/لفظي غير مطابق'; END IF;
END
$chk$;

COMMIT;