-- ═══════════════════════════════════════════════════════════════
-- تسريبات القدرات – الثلاثاء ٨ سبتمبر ٢٠٢٦
-- 57 سؤالاً: كمي 19 + لفظي 38 (منها 17 في قطع استيعاب)
-- آمن لإعادة التشغيل: guard على وجود أسئلة المجموعة
-- ═══════════════════════════════════════════════════════════════
BEGIN;

INSERT INTO leak_groups (id, title, leak_date, section, question_count, description, is_active, accent_color)
VALUES ('ad080926-2026-4c00-9d00-080920260001', 'تسريبات القدرات – الثلاثاء ٨ سبتمبر ٢٠٢٦', '2026-09-08', 'mixed', 57, 'أسئلة اختبار القدرات المحوسب ليوم الثلاثاء ٨ سبتمبر ٢٠٢٦ (٢٦ ربيع الأول ١٤٤٨) — القسمان الكمي واللفظي مع الشروح.', true, '#6D28D9')
ON CONFLICT (id) DO NOTHING;

DO $mig$
BEGIN
IF EXISTS (SELECT 1 FROM questions WHERE leak_group_id = 'ad080926-2026-4c00-9d00-080920260001') THEN
  RAISE NOTICE 'أسئلة المجموعة موجودة مسبقاً — تخطي الإدراج';
ELSE
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: محيط خماسي منتظم طول ضلعه ١ سم
القيمة الثانية: محيط دائرة طول نصف قطرها ١ سم', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, 'محيط الخماسي = ٥ × ١ = ٥ سم، ومحيط الدائرة = ٢π × ١ ≈ ٦٫٢٨ سم؛ فالقيمة الثانية أكبر.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'في رسم بياني للنسب المئوية حسب الفئة العمرية: الفئة ٢٥–٣٤: ذكور ٧٠ وإناث ٣٥؛ الفئة ٣٥–٤٤: ذكور ٥٦ وإناث ٤٠؛ الفئة ٤٥–٥٤: ذكور ٩٨ وإناث ٢٥. كم النسبة المئوية للإناث اللاتي أعمارهن من ٣٥ إلى ٤٤؟', '["٥٦٪", "٤٨٪", "٤٠٪", "٦٠٪"]'::jsonb, 2, 'نقرأ عمود الإناث في الفئة ٣٥–٤٤ مباشرة من الرسم: ٤٠٪.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'يبيّن التمثيل عدد الطلاب الحاصلين على كل درجة: الدرجة ١: ٣ طلاب، ٢: ٤، ٣: ٣، ٤: ٦، ٥: ٥، ٦: ٢، ٧: ٣. ما الدرجة التي حصل عليها أكبر عدد من الطلاب؟', '["٣", "٤", "٥", "٦"]'::jsonb, 1, 'أكبر عدد من الطلاب هو ٦، وهو عند الدرجة ٤.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'إذا كان ك × ل × م × ن = صفر، و ل × م × ن × و = ١، فإن .....', '["ل = صفر", "م = صفر", "ك = صفر", "ن = صفر"]'::jsonb, 2, 'من المعادلة الثانية لا يمكن أن يكون أي من ل أو م أو ن صفرًا (وإلا لصار الناتج صفرًا لا ١)، فالصفر في المعادلة الأولى لا بد أن يأتي من ك.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في الشكل المجاور مستقيمان متوازيان بينهما مثلث، الزاوية الخارجية عند رأسه الواقع على المستقيم العلوي ١١٠°، وزاويته الداخلية الأخرى ٥٠°. أوجد قيمة ص (زاويته عند الرأس الواقع على المستقيم السفلي).', '["٥٠", "٧٠", "٦٠", "١١٠"]'::jsonb, 2, 'الزاوية الداخلية عند الرأس العلوي = ١٨٠ − ١١٠ = ٧٠°، ومجموع زوايا المثلث ١٨٠: ص = ١٨٠ − ٧٠ − ٥٠ = ٦٠°.', 'https://czzcmbxejxbotjemyuqf.supabase.co/storage/v1/object/public/question-figures/qudurat_sep08_q005_parallel.png', 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', '٦٢٫٥٪ من ١٦٠ = .....', '["٤٠", "٦٠", "٨٠", "١٠٠"]'::jsonb, 3, '٦٢٫٥٪ = ٥/٨، و(٥/٨) × ١٦٠ = ١٠٠.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في مثلث قائم الزاوية إحدى زاويتيه الحادتين ٤٠°، وس هي الزاوية الخارجية عند رأس الزاوية الحادة الأخرى. قارن بين:
القيمة الأولى: ١٣٠°
القيمة الثانية: س', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 2, 'الزاوية الخارجية للمثلث تساوي مجموع الزاويتين الداخليتين البعيدتين عنها: س = ٩٠ + ٤٠ = ١٣٠°؛ فالقيمتان متساويتان.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'في مثلث زاويتان قياس كل منهما ٥٥°، وس هي الزاوية الخارجية عند الرأس الثالث. أوجد قياس س.', '["١٠٠", "١١٠", "١٢٠", "١٣٠"]'::jsonb, 1, 'الزاوية الخارجية = مجموع الزاويتين الداخليتين البعيدتين = ٥٥ + ٥٥ = ١١٠°.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'أوجد أربعة أمثال نصف العدد ٢.', '["٢", "٤", "٨", "١٦"]'::jsonb, 1, 'نصف العدد ٢ = ١، وأربعة أمثاله = ٤.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'احسب قيمة: ٢¹¹ − ٢¹⁰', '["١", "١١", "٢¹⁰", "١١٠"]'::jsonb, 2, '٢¹¹ = ٢ × ٢¹⁰، فالفرق = ٢ × ٢¹⁰ − ٢¹⁰ = ٢¹⁰.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'شركة عدد موظفيها ٤٢٠، منهم ١٤٠ سعوديًا والباقي من جنسيات أخرى. إذا أرادت الشركة رفع نسبة السعوديين إلى ٥٠٪ عن طريق استبدال بعض الموظفين من الجنسيات الأخرى بسعوديين، فكم سعوديًا توظف؟', '["٧٠", "٧٥", "٨٠", "٨٥"]'::jsonb, 0, '٥٠٪ من ٤٢٠ = ٢١٠ سعوديًا مطلوبًا، والموجود ١٤٠، فتوظف ٢١٠ − ١٤٠ = ٧٠.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'متوازي أضلاع محيطه ٢٠ سم، وطول أحد ضلعيه ٦ سم. أوجد طول الضلع الآخر س.', '["٢", "٣", "٤", "٦"]'::jsonb, 2, 'محيط متوازي الأضلاع = ٢ × (س + ٦) = ٢٠، فـس + ٦ = ١٠ ومنها س = ٤ سم.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'إذا كان ٥² و٧² من عوامل العدد ٣¹³ × ٧ × س، فما أصغر قيمة ممكنة لـس؟', '["١٤٥", "١٥٦", "١٧٥", "١٩٠"]'::jsonb, 2, 'العدد يحوي عاملًا واحدًا من ٧ فيحتاج ٧ أخرى من س، ولا يحوي أي ٥ فيحتاج ٥² من س؛ أصغر س = ٥² × ٧ = ١٧٥.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'مقياس الرسم في خريطة ١ : ٥٠٠٠٠٠٠. إذا كانت المسافة بين مدينتين على الخريطة ١٦ سم، فأوجد المسافة الحقيقية بينهما بالكيلومتر.', '["٨٠٠", "٨٨٠", "٩٠٠", "٩٦٠"]'::jsonb, 0, 'المسافة الحقيقية = ١٦ × ٥٠٠٠٠٠٠ = ٨٠٠٠٠٠٠٠ سم، وبالقسمة على ١٠٠٠٠٠ (عدد السنتيمترات في الكيلومتر) = ٨٠٠ كم.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الجبر', 'اختيار من متعدد', 'قارن بين:
القيمة الأولى: (٠٫٢٥)³ − (٠٫٢٥)⁴
القيمة الثانية: (٠٫٢٥)⁴ − (٠٫٢٥)³', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 0, 'العدد بين ٠ و١ تصغر قيمته كلما زاد أسّه، فـ(٠٫٢٥)³ أكبر من (٠٫٢٥)⁴. إذًا القيمة الأولى موجبة والثانية سالبة (نفس الفرق بإشارة معكوسة)؛ فالأولى أكبر.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'اشترى رجل مجموعة من الألعاب، كل لعبتين بـ٢٫٥ ريال، وباع اللعبة الواحدة بـ٢٫٥ ريال. إذا كان قد اشترى بـ٢٥ ريالًا، فكم لعبة اشترى؟', '["١٠", "١٥", "٢٠", "٢٥"]'::jsonb, 2, '٢٥ ÷ ٢٫٥ = ١٠ مجموعات، وكل مجموعة لعبتان، فعدد الألعاب = ٢٠.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الحساب', 'اختيار من متعدد', 'سيارة تقطع ٧٢ كم في ٣٢ دقيقة. كم كيلومترًا تقطع في الساعة بالسرعة نفسها؟', '["١٣٠", "١٣٥", "١٤٠", "١٥٠"]'::jsonb, 1, 'في الدقيقة الواحدة تقطع ٧٢ ÷ ٣٢ = ٢٫٢٥ كم، وفي ٦٠ دقيقة: ٢٫٢٥ × ٦٠ = ١٣٥ كم.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'دائرة مساحتها ٩٠π ظُلّل معظمها وبقي قطاع غير مظلل زاويته المركزية ٣٦°. قارن بين:
القيمة الأولى: مساحة الجزء غير المظلل
القيمة الثانية: ٩π', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 2, 'مساحة القطاع = (٣٦ ÷ ٣٦٠) × ٩٠π = (١/١٠) × ٩٠π = ٩π؛ فالقيمتان متساويتان.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('quant', NULL, 'الهندسة', 'اختيار من متعدد', 'مثلث أ ب ج قائم الزاوية في ج، قياس الزاوية أ = ٦٠°. النقطة د على الوتر أ ب بحيث تكون الزاوية د ج ب = ٦٠°. قارن بين:
القيمة الأولى: ج د
القيمة الثانية: ج ب', '["القيمة الأولى أكبر", "القيمة الثانية أكبر", "القيمتان متساويتان", "المعطيات غير كافية"]'::jsonb, 1, 'الزاوية ب = ٣٠°. في المثلث د ج ب: زاوية ج = ٦٠ وزاوية ب = ٣٠ فزاوية د = ٩٠°، أي أن ج د عمودي على أ ب، وهو المقابل لزاوية ٣٠° فيساوي نصف ج ب؛ فـج ب أكبر.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'جذور : شجرة', '["سواري : أعلام", "قواعد : أبنية", "أغصان : أوراق", "بحر : أمواج"]'::jsonb, 1, 'الجذور هي الأساس الذي تقوم عليه الشجرة، والقواعد هي الأساس الذي تقوم عليه الأبنية: علاقة أساس وما يقوم عليه.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'دراسة : تخرج', '["مشي : وصول", "سابق : لاحق", "سفر : عبور", "هدف : غاية"]'::jsonb, 0, 'التخرج هو ما تنتهي إليه الدراسة، والوصول هو ما ينتهي إليه المشي: علاقة عمل وغايته التي ينتهي إليها.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'إهمال : إخفاق', '["هدية : محبة", "شك : يقين", "جد : كسل", "نوم : يقظة"]'::jsonb, 0, 'الإهمال سبب يؤدي إلى الإخفاق، والهدية سبب يؤدي إلى المحبة: علاقة سبب ونتيجة؛ أما بقية الخيارات فأضداد.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'التناظر اللفظي', 'اختيار من متعدد', 'المال : الولد', '["الذهب : التجارة", "القلب : الشعور", "الكحل : العطر", "الماء : الحياة"]'::jsonb, 2, 'المال والولد يقترنان في كونهما زينة الحياة الدنيا، والكحل والعطر يقترنان في كونهما زينة أيضًا: علاقة اقتران في صنف واحد.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'السعادة ينبوع ....... الجميع أن يصلوا إليه، وهم لا ....... أنه تحت أقدامهم.', '["يفكر – يتمثلون", "يتمنى – يعلمون", "يسعى – يسمعون", "يكاد – يؤمنون"]'::jsonb, 1, 'الجميع يتمنون الوصول إلى السعادة وهم لا يعلمون أنها قريبة منهم؛ فالزوج المستقيم: يتمنى – يعلمون.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'من أيقن بـ....... جاد بـ.......', '["نفسه – روحه", "يمينه – يساره", "موته – أبنائه", "الخلف – العطية"]'::jsonb, 3, 'الحكمة المعروفة: من أيقن بالخَلَف (أن الله يعوّضه) جاد بالعطية؛ فالإكمال الوحيد المستقيم: الخلف – العطية.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'لا فائدة من الدنيا ....... إذا كان حذاؤك .......', '["الواسعة – ضيقًا", "الضيقة – مناسبًا", "الصغيرة – واسعًا", "الفارغة – واسعًا"]'::jsonb, 0, 'المعنى: سعة الدنيا لا تنفع من كان حذاؤه ضيقًا يؤلمه؛ فالتقابل المقصود: الواسعة – ضيقًا.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'يجب أن يكون توخي الحذر ....... في البيئات .......', '["رئيسًا – المتعاملة", "مطلوبًا – الفوضوية", "ثانويًا – الإنشائية", "ممنوعًا – الهادئة"]'::jsonb, 1, 'الحذر يكون مطلوبًا في البيئات الفوضوية التي تكثر فيها المخاطر؛ فالزوج المناسب: مطلوبًا – الفوضوية.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'إكمال الجملة', 'اختيار من متعدد', 'يكون الإنسان نبيلًا إذا زادت صفة ....... عنده على باقي الصفات؛ لأنه يفضّل ....... على نفسه.', '["الإيثار – غيره", "الصبر – غيره", "الكرم – ماله", "الصدق – نفسه"]'::jsonb, 0, 'تفضيل الغير على النفس هو تعريف الإيثار نفسه؛ فالزوج المناسب: الإيثار – غيره.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'الغضب ريح قوية تشعل مصباح العقل.', '["ريح", "تشعل", "مصباح", "العقل"]'::jsonb, 1, 'الريح القوية تطفئ المصباح ولا تشعله؛ فالخطأ في «تشعل» وصوابها «تطفئ».', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'كلما ازداد استعمال البئر نقص عطاؤها.', '["استعمال", "البئر", "نقص", "عطاؤها"]'::jsonb, 2, 'البئر كلما استُعملت وأُخذ ماؤها زاد عطاؤها وتجدد ماؤها؛ فالخطأ في «نقص» وصوابها «زاد».', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'مأساتك السرعة في الوصول لهدفك، بل عدم وجود هدف تسعى إليه.', '["مأساتك", "السرعة", "وجود", "تسعى"]'::jsonb, 1, 'المأساة ليست في التأخر عن بلوغ الهدف بل في انعدام الهدف أصلًا؛ فـ«السرعة» في غير موضعها والصواب «التأخر».', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'الجلوس الخاطئ والعادات غير الصحية والحيوية تزيد من احتمالية الإصابة بالسمنة.', '["الحيوية", "الخاطئ", "الإصابة", "السمنة"]'::jsonb, 0, 'ما يزيد احتمال السمنة هو الخمول لا الحيوية؛ فالخطأ في «الحيوية» وصوابها «الخمول».', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'الشتات الذهني يُدخل الشخص في حالة من السبات، لذا يجب أن يوفر البيئة المناسبة لذهنه.', '["الذهني", "الشخص", "السبات", "المناسبة"]'::jsonb, 2, 'الشتات الذهني يُدخل صاحبه في حالة فوضى وتشويش لا سبات؛ فالخطأ في «السبات» وصوابها «الفوضى».', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'الخطأ السياقي', 'اختيار من متعدد', 'الطبيب يستخدم الليزر في العمليات الجراحية التي تتطلب وقتًا دقيقًا.', '["الطبيب", "الليزر", "وقتًا", "دقيقًا"]'::jsonb, 2, 'الدقة المطلوبة في الجراحة تكون في العمل لا في الوقت؛ فالخطأ في «وقتًا» وصوابها «عملًا».', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["الكاتب", "المزارع", "النجار", "الحداد"]'::jsonb, 0, 'المزارع والنجار والحداد أصحاب حرف يدوية، أما الكاتب فعمله ذهني.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["صدقة", "رسوم", "ضرائب", "زكاة"]'::jsonb, 0, 'الرسوم والضرائب والزكاة مبالغ مفروضة واجبة الدفع، أما الصدقة فتطوعية.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["سريرة", "كيان", "روح", "شخصية"]'::jsonb, 1, 'السريرة والروح والشخصية أمور باطنة تخص داخل الإنسان، أما الكيان فهو الوجود والذات كلها.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["نشاط", "خمول", "هدوء", "اقتدار"]'::jsonb, 3, 'النشاط والخمول والهدوء حالات تصف درجة الحركة والحيوية، أما الاقتدار فقدرة وكفاءة.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["تصدع", "هدم", "تدمير", "انهيار"]'::jsonb, 0, 'الهدم والتدمير والانهيار سقوط كلي للبناء، أما التصدع فتشقق جزئي لا يسقط معه البناء.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'المفردة الشاذة', 'اختيار من متعدد', 'اختر المفردة الشاذة:', '["استساغ", "عادي", "طبيعي", "مألوف"]'::jsonb, 0, 'عادي وطبيعي ومألوف صفات متقاربة المعنى، أما «استساغ» ففعل بمعنى استحسن وقبل.', NULL, 'ad080926-2026-4c00-9d00-080920260001', NULL, NULL, NULL, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'حسب النص، ما آخر خطوة في إدارة الوقت؟', '["تنظيم الوقت", "ترتيب الوقت", "تخطيط الوقت", "تنسيق الوقت"]'::jsonb, 0, 'النص صريح: تنظيم الوقت يلي مرحلتي تخطيط الوقت وتنسيقه، فهو آخر الخطوات.', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90801-2026-4c00-9d00-000000000001', 'تنظيم الوقت هو مرحلة من مراحل إدارة الوقت، وهو يلي مرحلة تخطيط الوقت وتنسيق الوقت، ويشمل تحديد الأهداف ويتنبأ بالوقت المناسب. وإدارة الوقت هي عملية تنظيم وتخطيط كيفية توزيع وقتك بين المهام والأنشطة المختلفة. وفي أغلب الأحيان من يفشل في إدارة وقته يفشل في حياته. والصندوق عند تنظيمه يمكنه استيعاب العديد من الأشياء، وكذلك الوقت يشبه الصندوق.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'العنوان الأعم للقطعة:', '["تنظيم الوقت", "إدارة الوقت", "ترتيب الوقت", "تنسيق الوقت"]'::jsonb, 1, 'تنظيم الوقت وتخطيطه وتنسيقه كلها مراحل تندرج تحت إدارة الوقت، فهي العنوان الأعم.', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90801-2026-4c00-9d00-000000000001', 'تنظيم الوقت هو مرحلة من مراحل إدارة الوقت، وهو يلي مرحلة تخطيط الوقت وتنسيق الوقت، ويشمل تحديد الأهداف ويتنبأ بالوقت المناسب. وإدارة الوقت هي عملية تنظيم وتخطيط كيفية توزيع وقتك بين المهام والأنشطة المختلفة. وفي أغلب الأحيان من يفشل في إدارة وقته يفشل في حياته. والصندوق عند تنظيمه يمكنه استيعاب العديد من الأشياء، وكذلك الوقت يشبه الصندوق.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'حسب النص، ما العلاقة بين (يفشل في حياته) و(يفشل في إدارة وقته)؟', '["نتيجة لسبب", "سبب لنتيجة", "طردية", "عكسية"]'::jsonb, 0, 'الفشل في الحياة نتيجة، والفشل في إدارة الوقت سببها؛ فالأولى نتيجة للثانية.', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90801-2026-4c00-9d00-000000000001', 'تنظيم الوقت هو مرحلة من مراحل إدارة الوقت، وهو يلي مرحلة تخطيط الوقت وتنسيق الوقت، ويشمل تحديد الأهداف ويتنبأ بالوقت المناسب. وإدارة الوقت هي عملية تنظيم وتخطيط كيفية توزيع وقتك بين المهام والأنشطة المختلفة. وفي أغلب الأحيان من يفشل في إدارة وقته يفشل في حياته. والصندوق عند تنظيمه يمكنه استيعاب العديد من الأشياء، وكذلك الوقت يشبه الصندوق.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'حسب النص، ما معنى (يتنبأ)؟', '["يحدد", "يُقدّر", "يعرف", "يخطط"]'::jsonb, 1, 'التنبؤ بالوقت المناسب هو تقديره قبل حدوثه؛ فالمعنى الأقرب «يُقدّر».', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90801-2026-4c00-9d00-000000000001', 'تنظيم الوقت هو مرحلة من مراحل إدارة الوقت، وهو يلي مرحلة تخطيط الوقت وتنسيق الوقت، ويشمل تحديد الأهداف ويتنبأ بالوقت المناسب. وإدارة الوقت هي عملية تنظيم وتخطيط كيفية توزيع وقتك بين المهام والأنشطة المختلفة. وفي أغلب الأحيان من يفشل في إدارة وقته يفشل في حياته. والصندوق عند تنظيمه يمكنه استيعاب العديد من الأشياء، وكذلك الوقت يشبه الصندوق.', 4, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'أي الآتي يتفق مع النص؟', '["الفاشل ينجح في تنظيم وقته", "الناجح لا يفشل أبدًا", "النجاح في الحياة يتبع النجاح في إدارة الوقت", "الفشل في تخطيط الوقت لا يؤثر في الحياة"]'::jsonb, 2, 'النص يربط الفشل في الحياة بالفشل في إدارة الوقت، وبالمقابل يكون النجاح في الحياة تابعًا للنجاح في إدارة الوقت.', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90801-2026-4c00-9d00-000000000001', 'تنظيم الوقت هو مرحلة من مراحل إدارة الوقت، وهو يلي مرحلة تخطيط الوقت وتنسيق الوقت، ويشمل تحديد الأهداف ويتنبأ بالوقت المناسب. وإدارة الوقت هي عملية تنظيم وتخطيط كيفية توزيع وقتك بين المهام والأنشطة المختلفة. وفي أغلب الأحيان من يفشل في إدارة وقته يفشل في حياته. والصندوق عند تنظيمه يمكنه استيعاب العديد من الأشياء، وكذلك الوقت يشبه الصندوق.', 5, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يُفهم من النص أن:', '["الاهتمام بالوقت أمر ثانوي", "شُبّه الوقت بالصندوق لضيقه", "تنظيم الوقت يُنجز الأعمال", "الوقت لا يمكن تنظيمه"]'::jsonb, 2, 'تشبيه الوقت بالصندوق الذي يتسع للعديد من الأشياء عند تنظيمه يدل على أن تنظيم الوقت يتيح إنجاز أعمال أكثر.', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90801-2026-4c00-9d00-000000000001', 'تنظيم الوقت هو مرحلة من مراحل إدارة الوقت، وهو يلي مرحلة تخطيط الوقت وتنسيق الوقت، ويشمل تحديد الأهداف ويتنبأ بالوقت المناسب. وإدارة الوقت هي عملية تنظيم وتخطيط كيفية توزيع وقتك بين المهام والأنشطة المختلفة. وفي أغلب الأحيان من يفشل في إدارة وقته يفشل في حياته. والصندوق عند تنظيمه يمكنه استيعاب العديد من الأشياء، وكذلك الوقت يشبه الصندوق.', 6, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'لماذا يقصد الشعراء النابغة الذبياني؟', '["طلبًا للشهرة", "طلبًا للرزق", "لينتقد شعرهم", "لتخليد أسمائهم"]'::jsonb, 2, 'النص صريح: كان الشعراء يقصدونه من كل مكان ليعرضوا عليه شعرهم، أي ليحكم عليه وينتقده.', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90802-2026-4c00-9d00-000000000002', 'زياد بن معاوية بن ضباب الذبياني المعروف بالنابغة الذبياني، كان النابغة تُضرب له قبة حمراء من أدم في سوق عكاظ، وكان عندما يلقي شعرًا يحضره كثير من الناس، فيقصده الشعراء من كل مكان ليعرضوا عليه شعرهم. وقد أصبح نابغة بعدما أصبح رجلًا، ولُقب بهذا اللقب لأنه نبغ في الشعر، أي أبدع في الشعر دفعة واحدة.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'علاقة جملة (لأنه نبغ في الشعر) بما قبلها:', '["تعليل", "سبب", "تفصيل", "إجمال"]'::jsonb, 0, 'الجملة تبدأ بـ«لأنه» وتبيّن علة تلقيبه بالنابغة، فهي تعليل لما قبلها.', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90802-2026-4c00-9d00-000000000002', 'زياد بن معاوية بن ضباب الذبياني المعروف بالنابغة الذبياني، كان النابغة تُضرب له قبة حمراء من أدم في سوق عكاظ، وكان عندما يلقي شعرًا يحضره كثير من الناس، فيقصده الشعراء من كل مكان ليعرضوا عليه شعرهم. وقد أصبح نابغة بعدما أصبح رجلًا، ولُقب بهذا اللقب لأنه نبغ في الشعر، أي أبدع في الشعر دفعة واحدة.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يُستنتج من النص أن النبوغ يُقاس بـ:', '["الجاه", "المكانة", "الموهبة", "السن"]'::jsonb, 2, 'سُمّي نابغة لأنه أبدع في الشعر دفعة واحدة، فمقياس النبوغ في النص هو الموهبة والإبداع لا السن أو الجاه.', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90802-2026-4c00-9d00-000000000002', 'زياد بن معاوية بن ضباب الذبياني المعروف بالنابغة الذبياني، كان النابغة تُضرب له قبة حمراء من أدم في سوق عكاظ، وكان عندما يلقي شعرًا يحضره كثير من الناس، فيقصده الشعراء من كل مكان ليعرضوا عليه شعرهم. وقد أصبح نابغة بعدما أصبح رجلًا، ولُقب بهذا اللقب لأنه نبغ في الشعر، أي أبدع في الشعر دفعة واحدة.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يدل النص على:', '["قلة الشعراء", "كثرة الشعراء", "تباين الشعراء في العصر الجاهلي", "تشابه الشعراء في العصر الجاهلي"]'::jsonb, 2, 'وجود شاعر يُحكَّم بين الشعراء ويقصدونه لعرض شعرهم يدل على تفاوت مستوياتهم وتباينهم.', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90802-2026-4c00-9d00-000000000002', 'زياد بن معاوية بن ضباب الذبياني المعروف بالنابغة الذبياني، كان النابغة تُضرب له قبة حمراء من أدم في سوق عكاظ، وكان عندما يلقي شعرًا يحضره كثير من الناس، فيقصده الشعراء من كل مكان ليعرضوا عليه شعرهم. وقد أصبح نابغة بعدما أصبح رجلًا، ولُقب بهذا اللقب لأنه نبغ في الشعر، أي أبدع في الشعر دفعة واحدة.', 4, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'الضمير في كلمة (فيقصده) يعود على:', '["النابغة", "السوق", "الناس", "الشعر"]'::jsonb, 0, 'الشعراء يقصدون النابغة نفسه ليعرضوا عليه شعرهم، فالهاء تعود عليه.', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90802-2026-4c00-9d00-000000000002', 'زياد بن معاوية بن ضباب الذبياني المعروف بالنابغة الذبياني، كان النابغة تُضرب له قبة حمراء من أدم في سوق عكاظ، وكان عندما يلقي شعرًا يحضره كثير من الناس، فيقصده الشعراء من كل مكان ليعرضوا عليه شعرهم. وقد أصبح نابغة بعدما أصبح رجلًا، ولُقب بهذا اللقب لأنه نبغ في الشعر، أي أبدع في الشعر دفعة واحدة.', 5, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'العنوان المناسب للنص:', '["أهمية الري", "أنظمة الري", "تكلفة أنظمة الري", "مشكلة الري"]'::jsonb, 1, 'النص يعرّف أنظمة الري الحديثة ويعدد طرقها ومن يلجأ إليها، فمحوره أنظمة الري.', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90803-2026-4c00-9d00-000000000003', 'أنظمة الري الحديثة هي تلك الأنظمة التي تُستخدم في ري الأراضي بالمناطق الصحراوية، وهذه الأراضي عادةً ما تكون رملية، كما أنها غالبًا ما تكون غير مستوية السطح. وهناك عدة طرق للري الحديث، منها الري باستخدام الرشاشات، والري بالتنقيط، والري السطحي. وعادةً ما تلجأ الدول الفقيرة في الموارد المائية إلى الاعتماد على طرق الري الحديثة لافتقارها لمصدر دائم للمياه العذبة.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'معنى (تفتقر) في النص:', '["تغنى", "تتردد", "تحتاج", "تفلس"]'::jsonb, 2, '«لافتقارها لمصدر دائم للمياه» أي لحاجتها إليه وعدم وجوده عندها؛ فمعنى تفتقر: تحتاج.', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90803-2026-4c00-9d00-000000000003', 'أنظمة الري الحديثة هي تلك الأنظمة التي تُستخدم في ري الأراضي بالمناطق الصحراوية، وهذه الأراضي عادةً ما تكون رملية، كما أنها غالبًا ما تكون غير مستوية السطح. وهناك عدة طرق للري الحديث، منها الري باستخدام الرشاشات، والري بالتنقيط، والري السطحي. وعادةً ما تلجأ الدول الفقيرة في الموارد المائية إلى الاعتماد على طرق الري الحديثة لافتقارها لمصدر دائم للمياه العذبة.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'ذُكر في النص عدة طرق لأنظمة الري الحديثة، كان عددها:', '["١", "٢", "٣", "٤"]'::jsonb, 2, 'الطرق المذكورة: الري بالرشاشات، والري بالتنقيط، والري السطحي — ثلاث طرق.', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90803-2026-4c00-9d00-000000000003', 'أنظمة الري الحديثة هي تلك الأنظمة التي تُستخدم في ري الأراضي بالمناطق الصحراوية، وهذه الأراضي عادةً ما تكون رملية، كما أنها غالبًا ما تكون غير مستوية السطح. وهناك عدة طرق للري الحديث، منها الري باستخدام الرشاشات، والري بالتنقيط، والري السطحي. وعادةً ما تلجأ الدول الفقيرة في الموارد المائية إلى الاعتماد على طرق الري الحديثة لافتقارها لمصدر دائم للمياه العذبة.', 3, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يعود الضمير (الهاء) في (سلطانها) الثانية على:', '["الأندلس", "غرناطة", "جبل طارق", "تلمسان"]'::jsonb, 3, 'الجملة: «ثم تلمسان فأكرمه سلطانها»، فالهاء تعود على أقرب مذكور وهو تلمسان.', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90804-2026-4c00-9d00-000000000004', 'محمد بن عبد الله الأندلسي الشهير بلسان الدين بن الخطيب، وُلد في غرناطة سنة ٧١٣هـ، واستوزره سلطانها يوسف بن إسماعيل ثم ابنه الغني بالله، فعظمت مكانته مما دفع حسّاده إلى الوشاية به، فترك الأندلس خلسة إلى جبل طارق ثم تلمسان فأكرمه سلطانها، ولكنه بعد ذلك سُجن وقُتل. ترك ابن الخطيب آثارًا متعددة، فمن مؤلفاته: الإحاطة في أخبار غرناطة، واللمحة البدرية في الدولة النصرية، وأعمال الأعلام فيمن بويع قبل الاحتلام من ملوك الإسلام، وأوصاف الناس في التواريخ.', 1, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'يُفهم من النص أن لسان الدين بن الخطيب وُلد في:', '["الربع الأول من القرن السابع", "الثلث الثاني من القرن السابع", "الربع الأول من القرن الثامن", "الثلث الثاني من القرن الثامن"]'::jsonb, 2, 'سنة ٧١٣هـ تقع في القرن الثامن الهجري (٧٠١–٨٠٠)، وفي ربعه الأول (٧٠١–٧٢٥).', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90804-2026-4c00-9d00-000000000004', 'محمد بن عبد الله الأندلسي الشهير بلسان الدين بن الخطيب، وُلد في غرناطة سنة ٧١٣هـ، واستوزره سلطانها يوسف بن إسماعيل ثم ابنه الغني بالله، فعظمت مكانته مما دفع حسّاده إلى الوشاية به، فترك الأندلس خلسة إلى جبل طارق ثم تلمسان فأكرمه سلطانها، ولكنه بعد ذلك سُجن وقُتل. ترك ابن الخطيب آثارًا متعددة، فمن مؤلفاته: الإحاطة في أخبار غرناطة، واللمحة البدرية في الدولة النصرية، وأعمال الأعلام فيمن بويع قبل الاحتلام من ملوك الإسلام، وأوصاف الناس في التواريخ.', 2, 'active', false);
  INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, image_url, leak_group_id, passage_id, passage_text, passage_order, status, disabled)
  VALUES ('verbal', NULL, 'استيعاب المقروء', 'اختيار من متعدد', 'نفهم من النص أن لسان الدين بن الخطيب كان:', '["أديبًا ومؤرخًا", "أديبًا وكاتبًا", "وزيرًا ومؤرخًا", "وزيرًا ورئيسًا"]'::jsonb, 2, 'استوزره السلطان (فهو وزير)، ومؤلفاته في أخبار غرناطة والدولة النصرية والتواريخ تدل على أنه مؤرخ.', NULL, 'ad080926-2026-4c00-9d00-080920260001', 'e1a90804-2026-4c00-9d00-000000000004', 'محمد بن عبد الله الأندلسي الشهير بلسان الدين بن الخطيب، وُلد في غرناطة سنة ٧١٣هـ، واستوزره سلطانها يوسف بن إسماعيل ثم ابنه الغني بالله، فعظمت مكانته مما دفع حسّاده إلى الوشاية به، فترك الأندلس خلسة إلى جبل طارق ثم تلمسان فأكرمه سلطانها، ولكنه بعد ذلك سُجن وقُتل. ترك ابن الخطيب آثارًا متعددة، فمن مؤلفاته: الإحاطة في أخبار غرناطة، واللمحة البدرية في الدولة النصرية، وأعمال الأعلام فيمن بويع قبل الاحتلام من ملوك الإسلام، وأوصاف الناس في التواريخ.', 3, 'active', false);
END IF;
END
$mig$;

-- مزامنة العداد مع الواقع
UPDATE leak_groups
SET question_count = (SELECT COUNT(*) FROM questions WHERE leak_group_id = 'ad080926-2026-4c00-9d00-080920260001')
WHERE id = 'ad080926-2026-4c00-9d00-080920260001';

-- تحقق نهائي
DO $chk$
DECLARE n INT; nq INT; nv INT; np INT;
BEGIN
  SELECT COUNT(*) INTO n FROM questions WHERE leak_group_id = 'ad080926-2026-4c00-9d00-080920260001';
  SELECT COUNT(*) INTO nq FROM questions WHERE leak_group_id = 'ad080926-2026-4c00-9d00-080920260001' AND section = 'quant';
  SELECT COUNT(*) INTO nv FROM questions WHERE leak_group_id = 'ad080926-2026-4c00-9d00-080920260001' AND section = 'verbal';
  SELECT COUNT(*) INTO np FROM questions WHERE leak_group_id = 'ad080926-2026-4c00-9d00-080920260001' AND passage_id IS NOT NULL;
  RAISE NOTICE 'إجمالي: % — كمي: % — لفظي: % — قطع: %', n, nq, nv, np;
  IF n <> 57 THEN RAISE EXCEPTION 'عدد الأسئلة % لا يطابق المتوقع 57', n; END IF;
  IF nq <> 19 OR nv <> 38 THEN RAISE EXCEPTION 'توزيع كمي/لفظي غير مطابق'; END IF;
END
$chk$;

COMMIT;