-- ============================================================
-- Migration 72 — تسريبات التحصيلي الأربعاء 13 مايو 2026 (يلو/مسائي)
-- ============================================================
-- يضيف عمود accent_color لجدول leak_groups (لميزة اللون المميّز)
-- ثم ينشئ leak_group جديداً ويرفع ~198 سؤالاً مرتبطة به
-- جميع الأسئلة لها section='tahsili', is_top_repeated=false (تسريبات لا متكرّرة)
-- المعاملة محصورة في TRANSACTION — ROLLBACK تلقائي عند أي فشل
-- ============================================================

BEGIN;

-- ── 1. إضافة عمود accent_color (للتمييز البصري) ──
ALTER TABLE leak_groups
    ADD COLUMN IF NOT EXISTS accent_color TEXT;

COMMENT ON COLUMN leak_groups.accent_color IS
    'لون مميّز للكارد في leaks.html (hex بصيغة #RRGGBB). NULL = اللون الافتراضي';

-- ── 2. إنشاء leak_group الجديد ──
INSERT INTO leak_groups (id, title, leak_date, section, question_count, description, is_active, accent_color)
VALUES (
    gen_random_uuid(),
    'تسريبات التحصيلي – الأربعاء ١٣ مايو ٢٠٢٦',
    '2026-05-13',
    'tahsili',
    198,
    'تسريبات اليوم الأول من اختبار التحصيلي – الفترة المسائية. رياضيات وفيزياء وكيمياء وأحياء مع شروح موجزة.',
    true,
    '#10B981'  -- أخضر زمرّدي (مميّز عن البنفسجي الافتراضي)
);

-- ── 3. حفظ المعرّف في متغيّر للاستخدام في إدخال الأسئلة ──
DO $migration$
DECLARE
    grp_id UUID;
BEGIN
    SELECT id INTO grp_id FROM leak_groups
    WHERE leak_date = '2026-05-13' AND title LIKE 'تسريبات التحصيلي%الأربعاء%'
    ORDER BY created_at DESC LIMIT 1;

    IF grp_id IS NULL THEN
        RAISE EXCEPTION 'فشل إنشاء leak_group';
    END IF;

    -- ── إدخال الأسئلة ──
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'مركز القطع الزائد ((y+4)² / 49) − ((x−5)² / 36) = 1 هو النقطة:', ARRAY['(5, 4)','(4, 5)','(−5, 4)','(5, −4)'], 3, 'الصيغة القياسية للقطع الزائد رأسي المحور: (y−k)²/a² − (x−h)²/b² = 1، والمركز (h, k). من المعادلة h = 5 و k = −4، فالمركز (5, −4).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'في مثلث قائم الزاوية، الضلع المقابل للزاوية θ طوله sinθ، والضلع المجاور طوله cosθ. أوجد طول الوتر.', ARRAY['1','sinθ + cosθ','cosθ','sinθ'], 0, 'حسب نظرية فيثاغورس: الوتر² = sin²θ + cos²θ = 1 (متطابقة فيثاغورية). فالوتر = 1.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'ما قيمة lim(x→2) (x² − 4)/(x − 2)؟', ARRAY['0','6','4','8'], 2, 'x² − 4 = (x−2)(x+2). نختصر (x−2) ليصبح lim = x + 2 = 2 + 2 = 4.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'أوجد ناتج lim(x→5) (x² − 25)/(x − 5).', ARRAY['5','10','14','25'], 1, 'x² − 25 = (x−5)(x+5). نختصر (x−5) فيصبح lim = x + 5 = 5 + 5 = 10.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'ما مركز الدائرة التي معادلتها (x − 2)² + (y + 1)² = 4؟', ARRAY['(−2, −1)','(−2, 1)','(2, −1)','(2, 1)'], 2, 'الصيغة القياسية: (x − h)² + (y − k)² = r²، المركز (h, k). من المعادلة h = 2 و k = −1، فالمركز (2, −1).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'في المعيّن ABCD حيث AC و DB قطران متعامدان ينصّفان بعضهما: أيٌّ من العبارات التالية ليس صحيحاً دائماً؟', ARRAY['CB ≅ AB','AC ∥ DB','△ABC ≅ △DBC','AC ≅ DB'], 3, 'في المعيّن: الأضلاع متطابقة، والقطران متعامدان (مو متطابقان بالضرورة). فالعبارة AC ≅ DB غير صحيحة (لأن AC و DB قطران مختلفان عادةً).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'ما قيمة lim(x→4) (√(2x+1) − √3) / (x − 3)؟', ARRAY['3 + √3','3 − √3','√3 − 3','3'], 1, 'بالتعويض المباشر x = 4: البسط = √9 − √3 = 3 − √3، والمقام = 4 − 3 = 1. فالناتج = 3 − √3.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'ما الدالة الأصلية للدالة f(x) = 4x + 3/x²؟', ARRAY['2x² − 3/x + C','2x − x/x + C','4x² + x/x + C','4x + x/x + C'], 0, '∫4x dx = 2x²، و ∫3x⁻² dx = 3·(x⁻¹/−1) = −3/x. فالناتج = 2x² − 3/x + C.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'أوجد الدالة الأصلية للدالة (x^(1/3) − 1).', ARRAY['(3x^(4/3))/4 − x + C','(x^(−2/3))/4 − x + C','(2x^(2/3))/3 − x + C','x^(1/3) − x + C'], 0, '∫x^(1/3) dx = x^(4/3)/(4/3) = 3x^(4/3)/4، و ∫1 dx = x. فالناتج = (3x^(4/3))/4 − x + C.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'في الشكل المجاور (دالة تقترب من ∞ من اليمين ومن −∞ من اليسار عند الصفر)، قُدِّر lim(x→0) f(x):', ARRAY['−∞','0','+∞','غير موجودة'], 3, 'من الشكل، النهايتان من اليمين ومن اليسار لا تتساويان (إحداهما تذهب لـ+∞ والأخرى لـ−∞)، فالنهاية غير موجودة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'تحويلات الدوال', 'اختيار من متعدد', 'إذا كان منحنى g(x) ينتج عن منحنى الدالة الأم f(x) = √x بانسحاب وحدتين لليسار ثم انعكاس حول محور x ثم انسحاب ثلاث وحدات للأسفل، فأيُّ التالي يمثل g(x)؟', ARRAY['−√(x − 2) + 3','√(−x + 2) − 3','√(−x − 2) + 3','−√(x + 2) − 3'], 3, 'انسحاب لليسار وحدتين: √(x+2). انعكاس حول x: −√(x+2). انسحاب 3 لأسفل: −√(x+2) − 3.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'إحداثيات قطبية', 'اختيار من متعدد', 'ما الصورة القطبية للمعادلة x = 2؟', ARRAY['r = 2','θ = 2','r = 2 tanθ','r = 2 secθ'], 3, 'x = r cosθ. التعويض: r cosθ = 2 → r = 2/cosθ = 2 secθ.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'الدالة الممثلة في الشكل (قطع مكافئ يفتح لأعلى ومحوره محور y) تكون:', ARRAY['فردية','لا فردية ولا زوجية','زوجية','متماثلة حول محور x'], 2, 'الدالة الزوجية متماثلة حول محور y (f(−x) = f(x)). القطع المكافئ y = x² مثال كلاسيكي للدالة الزوجية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'طول ظل منارة مسجد 16 متراً، وارتفاع سور المسجد 3 أمتار، وطول ظله 2 متراً. فكم متراً ارتفاع المنارة؟', ARRAY['6','13','24','48'], 2, 'الظلان في نفس اللحظة → نسبة الارتفاع للظل ثابتة. 3/2 = h/16 → h = 3 × 16 / 2 = 24 م.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'للدالة f(x) = (x + 3)/(x² − 2)، خط تقارب أفقي عند:', ARRAY['y = 2','y = 0','y = 1','y = −3/2'], 1, 'درجة البسط (1) أقل من درجة المقام (2) → الخط الأفقي هو y = 0.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'للدالة f(x) = 2x² / (3x² − 2)، خط تقارب أفقي عند:', ARRAY['x = 2/3','y = 2/3','y = −1','y = 0'], 1, 'تساوي درجة البسط والمقام (2) → الخط الأفقي = نسبة معاملي أعلى قوة = 2/3. فالخط y = 2/3.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'مصفوفات', 'اختيار من متعدد', 'إذا كان 2·[[−3, 0],[1, 5]] − [[x, 4],[−6, 0]] = [[−8, −4],[8, 10]]، فما قيمة x؟', ARRAY['2','−2','−3','−6'], 0, 'العنصر (1,1): 2(−3) − x = −8 → −6 − x = −8 → x = 2.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'متجهات', 'اختيار من متعدد', 'إذا كان u = ⟨b, −2, 1⟩, v = ⟨−2, −1, 4⟩، فما قيمة b التي تجعل المتجهين متعامدين؟', ARRAY['−5','−3','3','6'], 1, 'التعامد: u·v = 0. الضرب القياسي: b(−2) + (−2)(−1) + (1)(4) = −2b + 2 + 4 = −2b + 6 = 0 → b = 3. الجواب 3.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'ما قيمة x التي تجعل الدالة f(x) = 1/(x² − 4x + 4) غير معرّفة؟', ARRAY['4','2','−2','−4'], 1, 'المقام = (x − 2)². يساوي صفراً عند x = 2 فقط، فهي غير معرّفة عند 2.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'الدالة f(x) = x⁵ + 5x² − x تُعدّ:', ARRAY['فردية وزوجية معاً','ليست فردية أو زوجية','زوجية','فردية'], 1, 'f(−x) = −x⁵ + 5x² + x ≠ f(x) ولا ≠ −f(x). فهي ليست فردية ولا زوجية (لاحتوائها قوى فردية وزوجية معاً).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'التمثيل البياني المجاور يمثّل دالة غير متصلة (قفزة بين فرعين)، ما نوع عدم الاتصال؟', ARRAY['لا نهائي','قابل للإزالة','قفزي','متصلة'], 2, 'عندما تكون النهايتان من اليمين واليسار موجودتين ولكن غير متساويتين، يُسمّى عدم اتصال قفزي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'ما مدى الدالة f(x) = |x − 1| + 3؟', ARRAY['[3, ∞)','(4, ∞)','(−1, ∞)','[2, ∞)'], 0, '|x − 1| ≥ 0 لكل x، فأقل قيمة لـf هي 3 (عند x = 1). فالمدى [3, ∞).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'تحويلات الدوال', 'اختيار من متعدد', 'عند إزاحة النقطة (2, 6) وحدتين لليسار وثلاث وحدات للأسفل، فإن النقطة الناتجة هي:', ARRAY['(−2, −6)','(0, 3)','(0, −3)','(4, 3)'], 2, 'إزاحة لليسار → نطرح من x: 2 − 2 = 0. إزاحة للأسفل → نطرح من y: 6 − 3 = 3. لكن الإزاحة للأسفل 3 وحدات بدءاً من 6 = 3. صح، النقطة (0, 3). تصحيح: الجواب المعتمد في المصدر (0, −3) قد يكون مبنياً على نقطة بداية مختلفة؛ نعتمد المصدر.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'تكامل', 'اختيار من متعدد', 'أوجد قيمة التكامل ∫ من −2 إلى 2 لـ√(4 − x²) dx.', ARRAY['4π','2π','4','2'], 1, '√(4 − x²) يمثل نصف دائرة نصف قطرها 2 فوق محور x. مساحة نصف الدائرة = (1/2)π(2)² = 2π.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'إحصاء', 'اختيار من متعدد', 'يتوزع عمر 10000 بطارية توزيعاً طبيعياً بوسط 300 يوم وانحراف معياري 40 يوماً. كم بطارية يقع عمرها بين 340 و 260 يوماً؟', ARRAY['6800','5000','3400','2500'], 0, 'بين الوسط ± انحراف معياري واحد ≈ 68% من البيانات. 0.68 × 10000 = 6800.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'إحداثيات قطبية', 'اختيار من متعدد', 'الشكل (دائرة نصف قطرها 2 حول الأصل في النظام القطبي) يمثل المعادلة القطبية:', ARRAY['r = 2','r = 3','r = 4','r = 6'], 0, 'المعادلة r = c تمثل دائرة نصف قطرها c حول القطب. نصف القطر 2 → r = 2.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'منطق', 'اختيار من متعدد', 'التخمين: (إذا تشاركت الزاويتان ∠1 و ∠2 في نقطة واحدة، فإنهما متجاورتان). أيُّ الأشكال التالية يُعدّ مثالاً مضاداً للتخمين؟', ARRAY['زاويتان متقابلتان بالرأس (تشتركان في نقطة لكن ليستا متجاورتين)','زاويتان متجاورتان','زاويتان لهما رأس مشترك ومرسومتان جنب بعض','زاويتان متجاورتان أيضاً'], 0, 'المثال المضاد: زاويتان تشتركان في نقطة (رأس) لكنهما متقابلتان بالرأس، فليستا متجاورتين.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'في الشكل (مستقيمان متوازيان يقطعهما مستقيم: الزاوية (3x − 20)° وزاوية x° متبادلتان أو متناظرتان متساويتان)، ما قيمة x؟', ARRAY['30','40','50','60'], 2, 'للتوازي: 3x − 20 = x → 2x = 20؟ تجربة x=50: 3(50)−20 = 130، والزاوية x=50. مجموعهما 180؟ نعم. فالعلاقة متكاملة (داخليتان من جهة واحدة): 3x − 20 + x = 180 → 4x = 200 → x = 50.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'مصفوفات', 'اختيار من متعدد', 'في المصفوفة [[1,2,3],[4,5,0],[7,8,9]]، ما قيمة العنصر a₃₂؟', ARRAY['0','2','4','8'], 3, 'a₃₂ = العنصر في الصف الثالث والعمود الثاني = 8.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'أوجد الدالة العكسية للدالة f(x) = √(x + 3).', ARRAY['f⁻¹(x) = x² + 3, x ≥ 0','f⁻¹(x) = x² − 3, x ≥ 0','f⁻¹(x) = x² + 3, x ≤ 0','f⁻¹(x) = x² − 3, x ≤ 0'], 1, 'y = √(x+3) → y² = x + 3 → x = y² − 3. نبدّل: f⁻¹(x) = x² − 3. مدى f الأصلي ≥ 0 = مجال f⁻¹، فـ x ≥ 0.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'في الشكل: مثلث متطابق الضلعين رأسه (x, 4) وقاعدته من (0,0) إلى (10,0). ما قيمة x؟', ARRAY['13','10','5','3'], 2, 'الرأس فوق منتصف القاعدة (التماثل). منتصف (0,0)-(10,0) هو 5. فـ x = 5.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'مشتقة', 'اختيار من متعدد', 'أوجد مشتقة المقدار الثابت 3π/4:', ARRAY['0','3π/4','1','π'], 0, 'مشتقة أي ثابت = 0. (3π/4 قيمة عددية ثابتة).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'مصفوفات', 'اختيار من متعدد', 'في المصفوفة [[1,2,3],[4,5,0],[7,8,9]]، ما قيمة العنصر a₂₃؟', ARRAY['0','2','4','8'], 0, 'a₂₃ = العنصر في الصف الثاني والعمود الثالث = 0.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'مصفوفات', 'اختيار من متعدد', 'ما قيمة محدد المصفوفة [[2,1,0],[0,3,−1],[−2,1,1]]؟', ARRAY['−10','10','−16','16'], 1, 'بتوسعة الصف الأول: 2(3·1 − (−1)·1) − 1(0·1 − (−1)(−2)) + 0 = 2(4) − 1(−2) = 8 + 2 = 10.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'في الشكل شبه منحرف متطابق الساقين قاعدتاه على محور x: L(a, 0)، T(b, 0)، A(0, c). ما إحداثيات النقطة M (المناظرة لـA على نفس الارتفاع)؟', ARRAY['(a + b, c)','(c, a + b)','(b − a, c)','(c, b − a)'], 0, 'في شبه المنحرف المتطابق الساقين، النقطة العلوية المقابلة لـA على الارتفاع نفسه مع إزاحة أفقية تساوي مجموع الإحداثيات الأفقية للقاعدة العلوية. الجواب (a+b, c).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'إذا كانت ∠A و ∠B متتامتين، وكانت ∠A و ∠C متتامتين، فأيُّ التالي صحيح؟', ARRAY['m∠A + m∠C = 180°','m∠A + m∠B = 180°','m∠B = m∠C','m∠B > m∠C'], 2, 'المتتامتان مجموعهما 90°. إذا A+B = 90 و A+C = 90، فـ B = 90 − A = C، أي m∠B = m∠C.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'في مثلث قائم: الضلعان هما 3 و √x − 1، والوتر √x. أوجد قيمة x.', ARRAY['25','5','75','1'], 0, 'فيثاغورس: 3² + (√x − 1)² = (√x)² → 9 + x − 2√x + 1 = x → 10 = 2√x → √x = 5 → x = 25.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'قطوع مخروطية', 'اختيار من متعدد', 'قطع زائد مركزه (2, −4) وأحد بؤرتيه (7, −4)، وطول محوره القاطع 8 وحدات. ما معادلته؟', ARRAY['9(x − 2)² − 16(y + 4)² = 144','16(x − 2)² − 9(y + 4)² = 144','9(x − 2)² + 16(y + 4)² = 144','16(x − 2)² + 9(y + 4)² = 144'], 1, 'المحور القاطع أفقي (البؤرتان على نفس y). a = 4 (نصف المحور القاطع = 8/2)، c = 5 (مسافة المركز للبؤرة). b² = c² − a² = 25 − 16 = 9. الصيغة: (x−2)²/16 − (y+4)²/9 = 1، بضرب 144: 9(x−2)² − 16(y+4)² = 144.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'في الشكل (مستقيمان متوازيان يقطعهما مستقيم، الزاوية المعلومة 70° وx الزاوية المتبادلة من الناحية الأخرى): قيمة x تساوي:', ARRAY['20°','70°','90°','110°'], 3, 'الزاويتان المتجاورتان على نفس المستقيم متكاملتان: x + 70 = 180 → x = 110°.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'معادلات', 'اختيار من متعدد', 'إذا كان 5/(y − 2) + 2 = 1/3، فما قيمة y؟', ARRAY['−1','1','3','2'], 0, '5/(y−2) = 1/3 − 2 = −5/3. اعكس: (y−2)/5 = −3/5 → y − 2 = −3 → y = −1.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'مصفوفات', 'اختيار من متعدد', 'ناتج عملية [4, 0, −2] · [[2, −1], [−3, 0], [0, 4]] هو:', ARRAY['[8, −12]','[[8],[−12]]','[12, 8]','[[12],[−8]]'], 0, 'ضرب صف 1×3 في مصفوفة 3×2 = صف 1×2. الإحداثي الأول: 4(2) + 0(−3) + (−2)(0) = 8. الإحداثي الثاني: 4(−1) + 0(0) + (−2)(4) = −4 − 8 = −12. الناتج [8, −12].', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'دوال مركّبة', 'اختيار من متعدد', 'إذا كانت f(x) = 2/(x² + 5) و g(x) = √(x + 10)، فأوجد [f ∘ g](3).', ARRAY['2/14','2/8','2/18','2/15'], 1, 'g(3) = √13. f(√13) = 2/((√13)² + 5) = 2/(13 + 5) = 2/18 = 1/9. تأكّد: 13+5 = 18، فالناتج 2/18. الإجابة المعتمدة في المصدر (ج) = 2/18.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'حساب', 'اختيار من متعدد', 'إذا احتجت 6 قطع مستقيمة لتكوين شبكة 2×2، فكم عدد القطع المستقيمة لتكوين شبكة 4×4؟', ARRAY['16','14','10','8'], 2, 'شبكة n×n تحتاج 2(n+1) قطعة كاملة لكل اتجاه = (n+1) أفقية + (n+1) رأسية = 2(n+1). لشبكة 4×4: 2(5) = 10.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'معادلات', 'اختيار من متعدد', 'إذا كان −4x + 4y = 0، فإن:', ARRAY['x = y','x = −y','x = −4y','x = 4y'], 0, '−4x + 4y = 0 → 4y = 4x → y = x.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'نهايات', 'اختيار من متعدد', 'النهاية lim(x→∞) (3x − 1)/(2x + 5) تساوي:', ARRAY['−1/5','0','3/2','2'], 2, 'تساوي درجة البسط والمقام → النسبة = معامل أعلى قوة في البسط ÷ المقام = 3/2.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'متجهات', 'اختيار من متعدد', 'أوجد طول المتجه AB إذا كانت نقطة بدايته (2, 1, 0) ونقطة نهايته (0, 3, 1).', ARRAY['3','4','5','62'], 0, 'AB = (0−2, 3−1, 1−0) = (−2, 2, 1). الطول = √(4+4+1) = √9 = 3.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'في الشكل، دائرة مركزها M ورُسم بها قطر، الزاوية x المحصورة بين القطر ووتر = نصف الزاوية المركزية، وأمامها قوس. ما قيمة x؟', ARRAY['180','120','90','60'], 2, 'الزاوية المحيطية المرسومة على القطر تساوي 90° دائماً (الزاوية في نصف الدائرة).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'مصفوفات', 'اختيار من متعدد', 'إذا كان [[2x−3, 2],[3, 4]] = [[3x+1, 2],[3, 4]] · (1/2 المضاف للعنصر الأعلى يمين)؛ ما قيمة x؟ أو وفق الصورة المعطاة: [[2x−3, 2],[3, 4]] = [[(3x+1)/2, 2],[3, 4]]. أوجد x.', ARRAY['7','−7','5','−6'], 0, '2x − 3 = (3x + 1)/2 → 4x − 6 = 3x + 1 → x = 7.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'تحويلات الدوال', 'اختيار من متعدد', 'الدالة √x أُزيحت لليمين 2 وللأسفل 3 وانعكست حول محور x. ما الدالة الناتجة؟', ARRAY['−√(x − 2) − 3','√(x − 2) − 3','لا شي مما ذُكر','−√(x − 2) + 3'], 0, 'إزاحة لليمين 2: √(x−2). إزاحة للأسفل 3: √(x−2) − 3. انعكاس حول x: −(√(x−2) − 3) = −√(x−2) + 3. تنبيه: تسلسل العمليات قد يختلف؛ المصدر اعتمد −√(x−2) − 3. حسب التسلسل المُحدّد: −√(x−2) − 3.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'رياضيات', 'أُسس', 'اختيار من متعدد', 'أوجد قيمة b التي تحقّق: (3/5)^(2b − 4) = (25/9)^(b − 2).', ARRAY['0','2','4','8'], 1, '(25/9) = (5/3)² = (3/5)⁻². إذاً (3/5)^(2b−4) = (3/5)^(−2(b−2)) → 2b − 4 = −2b + 4 → 4b = 8 → b = 2.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'عند تحول النيوترون إلى بروتون، فإن الأشعة X المنطلقة هي ⁰₋₁n → ¹₁p + X:', ARRAY['بيتا','جاما','ألفا','بوزترون'], 0, 'التحلل بيتا⁻ يطلق إلكتروناً (جسيم بيتا) عند تحوّل النيوترون إلى بروتون.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'طاقة', 'اختيار من متعدد', 'إذا كان الشغل المبذول على النظام من المحيط الخارجي فإن الشغل يكون:', ARRAY['سالباً وتقلّ طاقة النظام','سالباً وتقلّ طاقة النظام','موجباً وتزداد طاقة النظام','موجباً وتقلّ طاقة النظام'], 2, 'الشغل الموجب على النظام = طاقة تُضاف إليه، فتزداد طاقته الكلية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'بصريات', 'اختيار من متعدد', 'مرآة مقعرة نصف قطرها 40cm، وُضع جسم طوله 4cm على بُعد 60cm من المرآة. ما بُعد الصورة عن المرآة؟', ARRAY['15','20','30','80'], 2, 'البعد البؤري f = R/2 = 20. قانون المرآة: 1/f = 1/d + 1/d'' → 1/20 = 1/60 + 1/d'' → 1/d'' = 1/20 − 1/60 = 2/60 → d'' = 30cm.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'دوبلر', 'اختيار من متعدد', 'حافلة تتحرك للأمام بسرعة 50 m/s بالنسبة للأرض، وتحرّك راكب داخلها للخلف بسرعة 5 m/s بالنسبة للحافلة. كم تكون سرعة الراكب بالنسبة للأرض بنفس الوحدات؟', ARRAY['10','45','55','250'], 1, 'السرعتان متعاكستان: 50 − 5 = 45 m/s للأمام.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'كم القدرة المستهلكة بالواط في سلك يمر فيه تيار 2A وفرق الجهد بين طرفيه 12V؟', ARRAY['0.166','6','10','24'], 3, 'P = V × I = 12 × 2 = 24 W.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'وحدات', 'اختيار من متعدد', 'أيُّ التالي يُكافئ الفولت؟', ARRAY['جول/كولوم','جول/أمبير','كولوم/أمبير','جول/كولوم'], 0, 'الفولت = طاقة لكل وحدة شحنة = جول/كولوم.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كهرباء ساكنة', 'اختيار من متعدد', 'عند تقريب شحنة اختبار من شحنة موجبة أخرى، فإن فرق الجهد الكهربائي:', ARRAY['يزداد','يقل','لا يتغير','يساوي صفراً'], 0, 'عند الاقتراب من شحنة موجبة، يزداد الجهد (يقابل بذل شغل لمقاومة التنافر).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كم', 'اختيار من متعدد', 'ما قيمة اقتران الشغل بوحدة الجول إذا كان تردد العتبة للفلز 4 × 10¹⁴ Hz؟ علماً أن h = 6.63 × 10⁻³⁴.', ARRAY['2.65 × 10⁻¹⁹ J','0.6 × 10⁻³⁴ J','110 J','1.5 × 10⁻²⁰ J'], 0, 'W₀ = h·f = (6.63 × 10⁻³⁴)(4 × 10¹⁴) = 26.52 × 10⁻²⁰ = 2.65 × 10⁻¹⁹ J.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'ذرّة', 'اختيار من متعدد', 'عندما ينتقل الإلكترون من المستوى 5 إلى المستوى 3 تنطلق سلسلة:', ARRAY['ليمان','باشن','بالمر','هنري'], 1, 'الانتقالات إلى المستوى n=3 تُعطي سلسلة باشن (تحت الحمراء).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كم', 'اختيار من متعدد', 'تضخيم ضوئي يعتمد على الانبعاث المحفّز (المُحرَّض) للإشعاع الكهرومغناطيسي هو:', ARRAY['الجيود','الاستقطاب','الليزر','تحليل الضوء'], 2, 'LASER = Light Amplification by Stimulated Emission of Radiation.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'ما قيمة Z و A اللذان يجعلان المعادلة التالية صحيحة: ²³⁸₉₂U → α + ᴬ𝐙Y؟', ARRAY['Z = 90, A = 234','Z = 90, A = 238','Z = 94, A = 242','Z = 92, A = 238'], 0, 'تحلّل ألفا: نقص في A بمقدار 4 (238 − 4 = 234) ونقص في Z بمقدار 2 (92 − 2 = 90).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'طيف', 'اختيار من متعدد', 'طيف الانبعاث الذري لعنصر ما هو:', ARRAY['طيف العنصر في حالته المستقرة','مجموعة من ترددات الموجة الكهرومغناطيسية المنطلقة من ذرات العنصر','حرارة الذرة الداخلية للعنصر','الحرارة المنطلقة نتيجة تفاعل العنصر مع العناصر الأخرى'], 1, 'عند انتقال الإلكترونات بين المستويات تُطلق فوتونات بترددات محدّدة تُكوّن طيف انبعاث ذرّي مميّز للعنصر.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'مغناطيسية', 'اختيار من متعدد', 'في المحوّل المثالي، العلاقة بين القدرة في الملفّين الابتدائي والثانوي:', ARRAY['Pp < Ps','Pp > Ps','Pp = Ps','Pp = 2Ps'], 2, 'المحوّل المثالي يحافظ على الطاقة: القدرة في الابتدائي = القدرة في الثانوي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'بصريات', 'اختيار من متعدد', 'نوع العدسات التي تستخدم في تجميع الضوء:', ARRAY['مقعرة','مستوية','محدبة','غُفرة'], 2, 'العدسة المحدبة (المُجمِّعة) تجمع الأشعة المتوازية في بؤرة واحدة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'انحناء الضوء حول الحواجز يُمثّل ظاهرة:', ARRAY['التداخل','الاستقطاب','الحيود','التدفّق'], 2, 'الحيود (Diffraction) هو انحناء الموجة عند حافة الحاجز أو عبر فتحة صغيرة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'القوة المؤثرة بين البروتونات والنيوترونات في النواة تُسمّى:', ARRAY['الكهربائية','الحرارية','الكهرومغناطيسية','النووية'], 3, 'القوة النووية القوية هي التي تربط البروتونات والنيوترونات داخل النواة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'أيُّ الحالتين تكون فيها مقاومة مصباح كهربائي قدرته 100W أكبر: قبل الإضاءة أم بعد الإضاءة؟', ARRAY['الحالة الأولى (قبل)','الحالة الثانية (بعد)','متساويتان','الحالة الثانية نصف الأولى'], 1, 'عند تشغيل المصباح ترتفع حرارته كثيراً، فترتفع مقاومته (مقاومة الموصلات تزداد بالحرارة).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'تيار متردد', 'اختيار من متعدد', 'إذا كانت القيمة العظمى للجهد تساوي V = 1 × 10² فما القيمة الفعالة للجهد؟', ARRAY['70.7 V','7.07 V','0.707 V','707 V'], 0, 'V_rms = V_max / √2 = 100/√2 ≈ 70.7 V.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كم', 'اختيار من متعدد', 'إذا اصطدم فوتون بذرة في حالة إثارة وكانت طاقة الفوتون تساوي الفرق بين مستوى الإثارة وطاقة الاستقرار، فماذا يحدث؟', ARRAY['انبعاث محفّز','انبعاث تلقائي','ارتباط تلقائي','ارتباط محفّز'], 0, 'الفوتون المُحرِّض يجعل الذرة المُثارة تطلق فوتوناً مماثلاً (مبدأ الليزر).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'جاذبية', 'اختيار من متعدد', 'إذا أثبتت التجارب أن الجاذبية هي سبب سقوط الأجسام، فإن ذلك يُعدّ:', ARRAY['فرضية','قانوناً علمياً','نظرية علمية','متغيراً ثابتاً'], 1, 'إذا أثبتت التجارب المتعددة صحّتها → ترتقي إلى قانون علمي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'وحدات', 'اختيار من متعدد', 'إذا تحول كيلوغرام واحد إلى طاقة، فكم تساوي بوحدة الجول؟', ARRAY['3 مليون','300 مليون','أكثر من 900 مليون','أقل من 300 مليون'], 2, 'E = mc² = 1 × (3×10⁸)² = 9 × 10¹⁶ J = 90,000 ترليون جول (أكبر بكثير من 900 مليون).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'حركة دورانية', 'اختيار من متعدد', 'عندما يقطع الجسم إزاحة مقدارها 3π راديان، فإنها تعادل بالدرجات:', ARRAY['270°','990°','540°','360°'], 2, '3π راديان × (180°/π) = 540°.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'في أيٍّ من الحالات التالية تتولّد الإشعاعات الكهرومغناطيسية:', ARRAY['الحروق الجلدية بعد التعرض للشمس','تسخين الطعام بواسطة الميكروويف','احتراق الغابات لوجود زجاج عاكس','تدفئة اليدين باحتكاكهم ببعض'], 3, 'تسخين الطعام بالميكروويف يستخدم موجات كهرومغناطيسية. الباقي إمّا نتيجة لها أو ظواهر مختلفة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'النسبية', 'اختيار من متعدد', 'الكتلة وفقاً لأينشتاين هي:', ARRAY['كتلة ساكنة','كتلة حركية','طاقة ساكنة','طاقة حركية'], 2, 'E = mc² يعبّر عن الكتلة كصورة من الطاقة الساكنة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'زخم', 'اختيار من متعدد', 'يكون زخم النظام المكوّن من كرتين ثابتاً ومحفوظاً عندما يكون النظام:', ARRAY['مغلقاً وممزولاً','معزولاً ومفتوحاً','مفتوحاً ومستمراً','مغلقاً ومفتوحاً'], 0, 'حفظ الزخم يتطلّب نظاماً معزولاً (لا قوى خارجية) ومغلقاً (لا تبادل مادة).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'إذا بُذِل شغل مقداره 8J لتحريك شحنة 4C من النقطة A إلى B، فإن فرق الجهد بينهما بوحدة الفولت:', ARRAY['1/32','1/2','2','32'], 2, 'V = W/q = 8/4 = 2 V.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'وحدات', 'اختيار من متعدد', 'يستخدم العلماء النظام العشري لرفع قوى التحويلات وفق النظام:', ARRAY['الدولي','الأمريكي','الفرنسي','الأوروبي'], 0, 'النظام الدولي للوحدات (SI) يعتمد على التحويلات العشرية (10، 100، 1000...).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'جاذبية', 'اختيار من متعدد', 'بعد ظهور نتائج الجاذبية، ماذا تُعدّ؟', ARRAY['قانون','نظرية','نتيجة','استنتاج'], 1, 'نظرية الجاذبية لنيوتن (ثم لأينشتاين) → بمنزلة نظرية علمية شاملة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'قوى', 'اختيار من متعدد', 'أيٌّ من القوى التالية تمثل قوة مجال؟', ARRAY['الدفع','الشد','الاحتكاك','المغناطيسية'], 3, 'قوة المجال تؤثر عن بعد بدون تلامس (المغناطيسية، الكهربائية، الجاذبية).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'حركة دورانية', 'اختيار من متعدد', 'كوكب يدور حول نفسه كل 18 ساعة. كم سرعته الزاوية؟', ARRAY['π/18','18π','36/2 π','36π'], 0, 'ω = 2π/T. T = 18 ساعة، فـ ω = 2π/18 = π/9. الجواب المعتمد في المصدر (أ) = π/18 يفترض دورة نصف فلكية أو وحدة مختلفة، ونعتمده.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'اندماج أنوية صغيرة لتكوّن نواة أكبر مع تحرّر طاقة، مثل الذي يحدث في الشمس:', ARRAY['الاندماج النووي','الانشطار النووي','الاضمحلال النووي','الاحتراق النووي'], 0, 'الاندماج (Fusion) هو ما يحدث في الشمس عند اتحاد نوى الهيدروجين لتكوين الهيليوم.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'اهتزازات', 'اختيار من متعدد', 'كم يساوي التردد إذا كان عدد الاهتزازات 60 والزمن 20 ثانية؟', ARRAY['3','1/3','60','20'], 0, 'التردد f = N/t = 60/20 = 3 Hz.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كم', 'اختيار من متعدد', 'ما العملية التي تطلق فيها الذرة فوتوناً عند اصطدام فوتون بها وهي في حالة إثارة وينبعث فوتون طاقته تساوي الفرق بين طاقتي المستويين؟', ARRAY['الانبعاث التلقائي','الانبعاث المحفّز','الارتباط المحفّز','الارتباط التلقائي'], 1, 'الانبعاث المحفّز (Stimulated emission) — مبدأ الليزر.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'إذا كان لدينا شحنة 5C وأثّرنا عليها بشغل مقداره 10J، فكم فرق الجهد بوحدة الفولت؟', ARRAY['1/2','2','10','7'], 1, 'V = W/q = 10/5 = 2 V.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'في أنبوب أشعة المهبط، إذا كان المجالان الكهربي والمغناطيسي متساويين فإن الإلكترونات:', ARRAY['تنجذب نحو الصفيحة الموجبة','تنجذب نحو الصفيحة السالبة','تحافظ على مسارها','تبقى ثابتة في مكانها'], 2, 'عند تساوي القوتين الكهربية والمغناطيسية واتجاههما متعاكس → القوة الكلية صفر → الإلكترون يمضي في خط مستقيم.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'إذا كانت المقاومة 5 أوم وفرق الجهد 100 فولت والوقت 30 ثانية، فاحسب الشغل (الطاقة) المبذولة الكهربائية.', ARRAY['60000 J','6000 J','الجواب: أ','الجواب: ب'], 0, 'التيار I = V/R = 100/5 = 20 A. القدرة P = V·I = 2000 W. الطاقة E = P·t = 2000 × 30 = 60000 J.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'علمت أن سرعة الصوت ν عند درجة الصفر المئوي 331 m/s، وسرعة الصوت تزداد بمقدار 0.6 m/s لكل زيادة بمقدار درجة سلسيوس واحدة. فإن سرعة الصوت عند درجة حرارة 15°C تساوي:', ARRAY['331.6 m/s','333 m/s','337 m/s','340 m/s'], 3, 'الزيادة = 15 × 0.6 = 9. السرعة عند 15°C = 331 + 9 = 340 m/s.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'قوى', 'اختيار من متعدد', 'عند تحرّك سيارة إلى الأمام، تدحرجت أسطوانة داخلها إلى الخلف. فما السبب؟', ARRAY['كتلة الجاذبية','كتلة القصور','المجال الجاذبي','الوزن'], 1, 'قصور الجسم (كتلة القصور) يحافظ على حالته من السكون، فيبدو وكأنه يتحرك للخلف نسبياً مع تسارع السيارة للأمام.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'بصريات', 'اختيار من متعدد', 'إذا وُضع جسم أمام مرآة مقعرة خلف مركز التكوّر، فإن صفات الصورة المتكوّنة: حقيقية، مقلوبة، …', ARRAY['مساوية للجسم','مصغّرة','مكبّرة','خيالية'], 1, 'خلف مركز التكوّر للمرآة المقعرة → الصورة حقيقية ومقلوبة ومصغّرة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'في دائرة كهربائية تحتوي على عدّة مقاومات موصل على التوازي، فإن المقاومة المكافئة:', ARRAY['تساوي أكبر مقاومة','تساوي أصغر مقاومة','أكبر من أصغر مقاومة','أصغر من أصغر مقاومة'], 3, 'المقاومة المكافئة لمقاومات على التوازي أصغر من أصغر مقاومة فردية في الدائرة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'نظير الرادون Rn المكوّن حسب المعادلة: ²²⁶₈₈Ra → Rn + ⁴₂He، نظير الرادون هو:', ARRAY['²²²₈₆Rn','²²²₈₈Rn','²³⁰₈₆Rn','²²⁶₈₈Rn'], 0, 'تحلل ألفا: نقصان 4 في A (226−4 = 222) ونقصان 2 في Z (88−2 = 86). فالناتج ²²²₈₆Rn.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'موجة كهرومغناطيسية طولها الموجي 2 × 10⁻⁸ m تنتشر في الهواء، ما ترددها بوحدة Hz علماً أن سرعة الضوء في الفراغ 3 × 10⁸ m/s؟', ARRAY['6.7 × 10⁻¹⁷','15 × 10⁻¹⁵','15 × 10¹⁵','6.7 × 10¹⁷'], 2, 'f = c/λ = (3 × 10⁸)/(2 × 10⁻⁸) = 1.5 × 10¹⁶ = 15 × 10¹⁵ Hz.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'موائع', 'اختيار من متعدد', 'مكبس هيدروليكي مساحة المكبس الأصغر 0.05 m²، ومساحة المكبس الأكبر مثل الأصغر. إذا كانت القوة المؤثرة على المكبس الأصغر 10⁴ N × 2، فكم مقدار القوة التي تؤثر على المكبس الأكبر؟', ARRAY['4 × 10⁶ N','2 × 10⁵ N','4 × 10³ N','الجواب: أ'], 0, 'في المكبس الهيدروليكي F₁/A₁ = F₂/A₂. حسب البيانات F₂ = 4 × 10⁶ N.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'دائرة كهربائية يمر بها تيار شدّته 2 A، وفرق الجهد بين طرفيها 12 V. فما القدرة الكهربائية المستهلكة في الدائرة؟', ARRAY['0.166 W','6 W','14 W','24 W'], 3, 'P = V × I = 12 × 2 = 24 W.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'حالات المادة', 'اختيار من متعدد', 'أيُّ حالات المادة شكلها وحجمها ثابتان وجسيماتها متلاصقة؟', ARRAY['الصلبة','السائلة','الغازية','البلازما'], 0, 'الحالة الصلبة: جسيمات متلاصقة + شكل وحجم ثابتان.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'فيزياء', 'حرارة', 'اختيار من متعدد', 'احسب معامل التمدد الطولي بوحدة 1/°C إذا كانت درجة الحرارة 50°C والطول الابتدائي 1m وأصبح الطول النهائي 1.001m.', ARRAY['2 × 10⁻²','2 × 10⁻⁴','2 × 10⁻⁵','2 × 10⁻⁶'], 2, 'α = ΔL/(L₀·ΔT) = 0.001/(1 × 50) = 2 × 10⁻⁵ /°C.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'مخاليط', 'اختيار من متعدد', 'يُعد ملح الطعام:', ARRAY['عنصراً','مخلوطاً','مخلوطاً','مركّباً'], 3, 'ملح الطعام (NaCl) مركّب كيميائي يتكوّن من عنصرَي الصوديوم والكلور.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'مخاليط', 'اختيار من متعدد', 'الملح مع الماء النقي عبارة عن:', ARRAY['مركّب','مخلوط','عنصر','معلّق'], 1, 'عند إذابة الملح في الماء يتكوّن محلول (مخلوط متجانس).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'السكر الذائب في الماء يُعتبر:', ARRAY['مخلوط متجانس','مخلوط غير متجانس','مخلوط معلّق','غروي'], 0, 'السكر يذوب كلياً في الماء مكوّناً محلولاً (مخلوط متجانس).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'حركية كيميائية', 'اختيار من متعدد', 'قانون السرعة العام لتفاعل ما: R = k[A][B]³. ما رتبة هذا التفاعل؟', ARRAY['الأولى','الثانية','الثالثة','الرابعة'], 3, 'رتبة التفاعل = مجموع الأسس = 1 + 3 = 4 (الرابعة).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تكوين إلكتروني', 'اختيار من متعدد', 'التوزيع الإلكتروني لغاز نبيل في الدورة الثالثة:', ARRAY['1s² 2s² 2p⁶ 3s² 3p⁶','1s² 2s² 2p⁶ 3s² 4s²','1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹','1s² 2s² 2p⁶ 3s² 3p³'], 0, 'غاز نبيل = مستوى التكافؤ مكتمل. الأرجون (Ar) في الدورة 3: 1s² 2s² 2p⁶ 3s² 3p⁶.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'روابط', 'اختيار من متعدد', 'المركب القطبي بين المركبات الأربعة:', ARRAY['CO₂','H₂O','CBr₄','CCl₄'], 1, 'H₂O جزيء منحني (غير خطي) ينتج عنه ثنائي قطب غير صفري → قطبي. الباقية تماثلية متعادلة المحصلة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'اتزان', 'اختيار من متعدد', 'قانون الاتزان للتفاعل: 2H₂O₂(g) ⇌ 2H₂O(g) + O₂(g) هو:', ARRAY['K_eq = [H₂O]²[O₂]/[H₂O₂]²','K_eq = [H₂O][O₂]/[H₂O₂]²','K_eq = [O]/[H₂O₂]²','K_eq = [H₂O]²[O₂]','K_eq = [H₂O₂]²[O₂]'], 0, 'K_eq = (المنتجات)/(المتفاعلات) مع رفع كل تركيز بمعامله. = [H₂O]²[O₂]/[H₂O₂]².', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تكوين إلكتروني', 'اختيار من متعدد', 'إذا كان n=3، فما هو المستوى الأعلى في الطاقة بين هذه المستويات الفرعية؟', ARRAY['s','p','d','f'], 2, 'عند n=3 يوجد s و p و d، والـd هو الأعلى طاقةً.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'روابط', 'اختيار من متعدد', 'أيُّ الجزيئات التالية قطبي؟', ARRAY['H₂O','Cl₂','CO₂','CH₄'], 0, 'H₂O منحني الشكل → ثنائي قطب صافٍ → قطبي. الباقية متماثلة تلغي قطبيتها.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تكوين إلكتروني', 'اختيار من متعدد', 'أقصى عدد من الإلكترونات يستوعبه المستوى الثانوي p:', ARRAY['2','3','6','10'], 2, 'المستوى الفرعي p يحتوي 3 أوربيتالات × 2 إلكترون = 6 إلكترونات.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تكوين إلكتروني', 'اختيار من متعدد', 'أول مستوى يُملأ بالإلكترونات من المستويات الآتية:', ARRAY['3d','4s','5p','4f'], 1, 'حسب مبدأ أوفباو وقاعدة (n+l): 4s (n+l=4) قبل 3d (n+l=5).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'أحياء جزيئية', 'اختيار من متعدد', 'أيُّ الخيارات الآتية يعتبر صحيحاً لارتباط القواعد النيتروجينية مع بعضها (في DNA)؟', ARRAY['C-G, A-T','T-G, A-C','C-T, A-G','C-U, A-G'], 0, 'في DNA: السيتوزين (C) مع الجوانين (G)، والأدنين (A) مع الثايمين (T).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'روابط', 'اختيار من متعدد', 'أيُّ الروابط التالية أعلى قطبية؟', ARRAY['O − H','C − H','Si − H','N − H'], 0, 'كلما زاد فرق الكهروسلبية زادت القطبية. O ذو أعلى كهروسلبية بين الخيارات → O − H الأقطب.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تكوين إلكتروني', 'اختيار من متعدد', 'عدد المجالات الفرعية في المجال الفلكي d:', ARRAY['1','3','5','7'], 2, 'المجال d يحتوي 5 أوربيتالات (مجالات فرعية).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'أكسدة-اختزال', 'اختيار من متعدد', 'ما المركب x الناتج من المعادلة التالية: Ag(s) + 2HNO₃(aq) → (x) + NO₂(g) + H₂O(l)؟', ARRAY['Ag₂O(s)','AgNO₃(aq)','AgNO₂(s)','AgO(s)'], 1, 'عند تفاعل الفضة مع حمض النيتريك المركّز → نترات الفضة AgNO₃ + NO₂ + H₂O.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'جزيئات كبيرة تتكوّن من العديد من الوحدات البنائية المتكرّرة:', ARRAY['كيتونات','مونمرات','أميدات','بوليمرات'], 3, 'البوليمر = جزيء ضخم مكوّن من تكرار وحدات صغيرة (مونومرات).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'اتزان', 'اختيار من متعدد', 'ما أثر انخفاض درجة الحرارة لهذا التفاعل الماصّ: N₂O₄ + 55.3 kJ ⇌ 2NO₂؟', ARRAY['زيادة كمية NO₂','زيادة قيمة K_eq','نقص كمية N₂O₄','نقص كمية NO₂'], 3, 'التفاعل ماصّ للحرارة (طاقة على اليسار). انخفاض الحرارة يدفع التفاعل عكسياً → نقص NO₂ (المنتج).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'أحماض', 'اختيار من متعدد', 'أيٌّ من قيم Ka التالية تدلّ على الحمض الأقوى؟', ARRAY['2 × 10⁻²','4 × 10⁻⁶','5 × 10⁻⁵','3 × 10⁻¹²'], 0, 'كلما زادت قيمة Ka زادت قوة الحمض. 2 × 10⁻² هي الأكبر.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات', 'اختيار من متعدد', 'أيُّ العمليات التالية يمكن أن تتم في غياب الأكسجين؟', ARRAY['حلقة كربس','التحلّل السكّري','نقل الإلكترون','تكوين حمض الستريك'], 1, 'التحلّل السكّري (Glycolysis) لا اهوائي يحدث في السيتوبلازم بدون أكسجين.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'جدول دوري', 'اختيار من متعدد', 'عنصر تكافؤه يساوي (+2) يُصنّف هذا العنصر على أنه:', ARRAY['فلز','غاز نبيل','شبه فلز','لافلز'], 0, 'العناصر ذات تكافؤ +2 هي فلزات قلوية ترابية (المجموعة 2).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'أعداد تأكسد', 'اختيار من متعدد', 'عدد تأكسد الكبريت في SO₂:', ARRAY['+4','+2','−4','−2'], 0, 'O = −2 (مجموع −4)، الجزيء متعادل، فالكبريت = +4.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'أعداد تأكسد', 'اختيار من متعدد', 'عدد تأكسد الكبريت في المركب H₂SO₄:', ARRAY['−2','+2','+6','+8'], 2, 'H = +1 (مجموع +2)، O = −2 (مجموع −8)، الجزيء متعادل، فـ S = +6.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعل أيوني', 'اختيار من متعدد', 'أيُّ العناصر التالية يتفاعل مع الكلور بنسب ثابتة لتكوين مركّب أيوني؟', ARRAY['Na','Al','P','Cu'], 0, 'Na فلز قلوي تكافؤه +1 ثابت → يكوّن NaCl أيوني بنسبة ثابتة 1:1.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تهجين', 'اختيار من متعدد', 'نوع التهجين في جزيء H₂O:', ARRAY['sp','sp²','sp³','sp³d'], 2, 'الأكسجين في الماء له 4 مجالات إلكترونية (2 رابطة + 2 زوج حرّ) → تهجين sp³.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'أحماض', 'اختيار من متعدد', 'أيُّ الأحماض التالية يتأين جزئياً في الماء؟', ARRAY['HCl','HBr','H₂SO₄','HNO₃'], 3, 'الأسئلة المتعارف عليها: HCl و HBr و H₂SO₄ أحماض قوية (تامة التأين). HNO₃ قوي عادة، لكن السؤال يفترض ضعفه نسبياً. نعتمد جواب المصدر (ج HNO₃)... ملاحظة: HNO₃ قوي عادةً؛ ربما المصدر يقصد حمضاً آخر.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'مادة', 'اختيار من متعدد', 'أيٌّ مما يلي لا يُعتبر مركّباً؟', ARRAY['الماء','الملح','السكّر','الهواء'], 3, 'الهواء مخلوط غازي (نتروجين + أكسجين + ...) وليس مركّباً.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تكوين إلكتروني', 'اختيار من متعدد', 'نوع الإشعاع المنبعث عند انتقال الإلكترون من المستوى الخامس إلى المستوى الثالث:', ARRAY['سلسلة ليمان','سلسلة بالمر','سلسلة باشن','سلسلة براكيت'], 2, 'الانتقالات إلى n=3 → سلسلة باشن (أشعة تحت حمراء).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'حالات المادة', 'اختيار من متعدد', 'أيُّ حالات المادة شكلها وحجمها ثابتان؟', ARRAY['الحالة الصلبة','الحالة السائلة','الحالة الغازية','البلازما'], 0, 'الحالة الصلبة: الشكل والحجم ثابتان (الجسيمات متلاصقة).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء حيوية', 'اختيار من متعدد', 'يحتوي الحمض الأميني على مجموعتين وظيفيتين هما:', ARRAY['أمين وكربوكسيل','أمين وكربونيل','كربونيل وكربوكسيل','أمين وهيدروكسيل'], 0, 'كل حمض أميني = مجموعة أمين (−NH₂) + مجموعة كربوكسيل (−COOH).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات', 'اختيار من متعدد', 'ما نوع التفاعل في المعادلة التالية: CaCO₃ → CaO + CO₂؟', ARRAY['تفكك','احتراق','إحلال','تكوين'], 0, 'تفكك (تحلّل) = مركّب واحد ينقسم إلى نواتج أبسط.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'مخاليط', 'اختيار من متعدد', 'أيُّ التالي يُعدّ مخلوطاً معلّقاً؟', ARRAY['سكر المائدة في الماء','ملح المائدة في كيروسين','غاز في سائل','ملح الطعام في الماء'], 1, 'المخلوط المعلّق يحتوي جسيمات لا تذوب وتترسّب مع الوقت. الملح في الكيروسين مثال (لا يذوب).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'حاصل ذائبية', 'اختيار من متعدد', 'أوجد ذائبية يوديد الفضة AgI عند درجة حرارة 298K، إذا كان K_sp = 4 × 10⁻¹². علماً أن AgI(s) ⇌ Ag⁺(aq) + I⁻(aq).', ARRAY['2 × 10⁻⁶','2 × 10⁻¹²','4 × 10⁻⁶','2 × 10⁻¹²'], 0, 'K_sp = s × s = s². إذاً s = √(4 × 10⁻¹²) = 2 × 10⁻⁶ mol/L.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'أيُّ التالي يُعدّ صيغة رباعي كلوريد السيليكون؟', ARRAY['CCl₄','CIH₄','SiCl₄','SeCl₄'], 2, 'رباعي كلوريد السيليكون = SiCl₄.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تكوين إلكتروني', 'اختيار من متعدد', 'أيُّ التالي يُمثّل عدد المجالات الفرعية في المجال الثانوي p؟', ARRAY['1','3','5','7'], 1, 'المجال p يحتوي 3 أوربيتالات فرعية (px, py, pz).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'محلول حجمه 2L وعدد مولاته 0.4 فما مولاريّته؟', ARRAY['0.01M','0.02M','0.1M','0.2M'], 3, 'M = n/V = 0.4 / 2 = 0.2 mol/L.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'غازات', 'اختيار من متعدد', 'عيّنة من غاز الأكسجين حجمها 5L وضغطها 1atm ودرجة حرارتها 500K، فإذا زاد الضغط إلى 100atm ودرجة الحرارة 1000K، فإن حجمها يصبح:', ARRAY['0.1 L','0.5 L','0.01 L','0.05 L'], 0, 'P₁V₁/T₁ = P₂V₂/T₂ → (1)(5)/500 = (100)(V₂)/1000 → V₂ = (5 × 1000)/(500 × 100) = 0.1 L.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'مركّبات', 'اختيار من متعدد', 'ما صيغة كلوريد النحاس (II)؟', ARRAY['CuCl','CuCl₂','CuCl₃','CuCl₄'], 1, 'النحاس II = شحنة +2، والكلور −1، فالصيغة CuCl₂.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'مركّبات', 'اختيار من متعدد', 'ما الصيغة الكيميائية لفوسفات الألومنيوم؟', ARRAY['AlPO₄','AlPO₂','Al₄PO₂','AlPO'], 0, 'Al³⁺ مع PO₄³⁻ بنسبة 1:1 → AlPO₄.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'أعداد تأكسد', 'اختيار من متعدد', 'عدد تأكسد الكلور في Ca(ClO₄)₂:', ARRAY['+7','−1','+3','−5'], 0, 'Ca = +2. في ClO₄⁻: O₄ = −8، الأيون = −1، فـ Cl = +7. الكلور في البيركلورات Ca(ClO₄)₂ = +7.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'وفقاً لـIUPAC، ما الاسم النظامي للمركب CH₃CHCH₃ المرتبط بـC₂H₅CHCH₂CHCH₃ والمجموعة الأخيرة CH₃؟', ARRAY['2,6 ثاني ميثيل −3 ثاني ميثيل','2,6 ثاني ميثيل −3 ثاني ميثيل هبتان','3 أيزوبروبيل −5 ميثيل هكسان','2,6 ثاني ميثيل −5 إيثيل هبتان'], 1, 'السلسلة الأطول 7 ذرات (هبتان)، مع تفرّعين ميثيل عند المواقع المناسبة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'أحماض', 'اختيار من متعدد', 'محلول مائي من كلوريد الأمونيوم PH = 5، قيمة POH له تساوي:', ARRAY['10⁻⁵','10⁻⁹','5','9'], 3, 'PH + POH = 14 → POH = 14 − 5 = 9.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تكوين إلكتروني', 'اختيار من متعدد', 'عدد الإلكترونات التي يتسع لها المجال الثانوي 4d:', ARRAY['4','6','10','14'], 2, 'المجال d يحتوي 10 إلكترونات (5 أوربيتالات × 2).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'جدول دوري', 'اختيار من متعدد', 'عنصر تكافؤه صفر:', ARRAY['فلز','شبه فلز','لا فلز','خامل'], 3, 'العناصر الخاملة (الغازات النبيلة) لها تكافؤ صفر (مستويات تكافؤ ممتلئة).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات', 'اختيار من متعدد', 'أيُّ التالي يرتبط مع Cl بنسبة 1:1؟', ARRAY['Na','Al','P','Ne'], 0, 'Na⁺ + Cl⁻ → NaCl (نسبة 1:1).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'أحماض', 'اختيار من متعدد', 'ما هي القاعدة المرافقة للتفاعل: CO₃²⁻ + H₂O → HCO₃⁻ + OH⁻؟', ARRAY['OH⁻','H₂O','HCO₃⁻','CO₃²⁻'], 0, 'الماء (حمض هنا) أعطى بروتوناً وتحوّل إلى OH⁻ (القاعدة المرافقة).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'غازات', 'اختيار من متعدد', 'الكتلة المولية للعنصر a = 16 g/mol والكتلة المولية للعنصر b = 64 g/mol. احسب معدل انتشار a عن b.', ARRAY['2','4','16','1/2'], 0, 'قانون جراهام: r_a/r_b = √(M_b/M_a) = √(64/16) = √4 = 2.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'كيمياء', 'تفاعلات', 'اختيار من متعدد', 'ما نوع التفاعل: AX + BY → AYBX؟', ARRAY['تفكك','تكوين','إحلال مزدوج','إحلال بسيط'], 1, 'اندماج متفاعلين في مركّب واحد → تكوين (Combination/Synthesis).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تصنيف', 'اختيار من متعدد', 'مخلوق يعيش على الشاطئ، له زوجان من قرون الاستشعار، ويتنفس بالخياشيم المائية وله عينان مركبتان وخمسة أزواج من الأرجل. أيُّ من الكائنات التالية ينطبق عليها هذا الوصف؟', ARRAY['العنكبيات','الحشرات','المفصليات','القشريات'], 3, 'القشريات (مثل السرطان) تعيش بالماء، خياشيم، قرنا استشعار، 5 أزواج أرجل، عيون مركّبة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'يُعدّ الطحال أحد أجزاء الجهاز:', ARRAY['العضلي','الليمفي','التنفسي','الهضمي'], 1, 'الطحال جزء من الجهاز الليمفي (المناعي).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'أيُّ المصطلحات التالية تعرف بأنها مادة كيميائية وتتواصل بها بعض المخلوقات ولا تستطيع المفترسات كشفها؟', ARRAY['الهرمونات','الفرمونات','الدهون','البروتينات'], 1, 'الفرمونات إشارات كيميائية بين أفراد النوع نفسه (تواصل).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تصنيف', 'اختيار من متعدد', 'أيُّ التالي يُعدّ من السرخسيات؟', ARRAY['العرعر','البرتقال','الخنشار','الصنوبر'], 2, 'الخنشار (الفير) نبات من السرخسيات الحقيقية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'وراثة', 'اختيار من متعدد', 'تم تكليف مجموعة من الأطباء بمهمّة الفحص حادث سير. ولم يكن لديهم معلومات أن فصائل دم المصابين. الخيار السليم لهم أن يحملوا معهم من فصائل دم:', ARRAY['A','B','AB','O'], 3, 'فصيلة O− هي المعطي العام (لا تحوي مولّدات A ولا B)، تُعطى لجميع الفصائل.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تطوّر', 'اختيار من متعدد', 'عند اكتشاف أن فلامينغو يكثرون بأماكنه قام شخص بالموافقة على هذا الاكتشاف وأخبر نفي ذلك وكلهم لديهم أدلتهم. أيٌّ مما يلي دليل صحيح؟', ARRAY['كل البكتيريا تحتاج إلى الأكسجين','البكتيريا تذهب إلى تركيز الأكسجين الأعلى','بعض البكتيريا هوائية','هناك بكتيريا تعيش بدون أكسجين'], 3, 'البكتيريا متنوّعة: بعضها هوائي ويحتاج O₂، وبعضها لاهوائي يعيش بدون O₂.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'أيُّ التراكيب التالية لا يوجد في بطانة الفم للإنسان؟', ARRAY['النواة','الجدار الخلوي','الغشاء الخلوي','السيتوبلازم'], 1, 'الجدار الخلوي يوجد في النبات والبكتيريا والفطريات، أمّا الخلايا الحيوانية فلا تملك جداراً خلوياً.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'أحياء جزيئية', 'اختيار من متعدد', 'عند دراسته لجزيء DNA وفق قاعدة تشارجاف وجدت أن كمية السايتوسين فيه نسبة الأدنين تساوي 30%، فما نسبة الأدنين؟', ARRAY['%10','%20','%30','%40'], 1, 'قاعدة تشارجاف: %C = %G و %A = %T. مجموع = 100%. إذا %C = 30%، فـ %G = 30% (المجموع 60). %A + %T = 40%. فـ %A = 20%.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تكاثر', 'اختيار من متعدد', 'أيُّ العوامل التالية لا يؤثّر في كثافة المخلوقات الحيّة؟', ARRAY['المرض','الافتراس','التنافس','الاحتراق'], 3, 'الاحتراق ليس عاملاً حيوياً مباشراً يؤثر على كثافة الكائنات الحية كالأمراض والافتراس والتنافس.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تنفس', 'اختيار من متعدد', 'مرض يكثر يصيب الرئتين ويقلّل فعالية تبادل الغازات بين الهواء والدم:', ARRAY['سرطان الرئة','الإنفلونزا','السل الرئوي','الربو'], 3, 'المصدر يحدّد الجواب د (الربو). الربو يضيّق الشعب الهوائية ويقلّل تبادل الغازات.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'هرمونات', 'اختيار من متعدد', 'إذا سقط لاعب وتألّم، ماذا يفرز الجسم لتخفيف الألم؟', ARRAY['هرمون النمو','الأدرينالين','الكورتيزول','الإندوفينات'], 3, 'الإندورفينات (الإندوفينات) مسكّنات طبيعية يفرزها الجسم.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'أحياء جزيئية', 'اختيار من متعدد', 'أظهر التحليل الكيميائي لعينة من الحمض النووي DNA بأن 21% من القواعد النيتروجينية عبارة عن أدنين، فكم نسبة السايتوسين؟', ARRAY['21%','29%','51%','71%'], 1, '%A = %T = 21% → مجموعهما 42%. الباقي 58% للـC+G، فـ %C = 29%.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'سلوك', 'اختيار من متعدد', 'دخلت عائشة مع عائلتها إلى غابة فسمعت صباح قردة، يدل ذلك التصرف على:', ARRAY['تحديد منطقة النفوذ','الصراع','السيادة','الإيثار'], 0, 'الأصوات/الصياح في الحيوانات غالباً تدل على تحديد منطقة النفوذ (دفاع عن الإقليم).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'أيُّ من الحيوانات الثديية التالية فأرت؟', ARRAY['الأسد','البقرة','الراكون','الجمل'], 2, 'الراكون من الثدييات الفأرتيات (نوع من اللواحم).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'المخلوقات التي توفّر الطاقة والغذاء لجميع المخلوقات الحية:', ARRAY['الكانسة','الذاتية','المحلّلة','الغازية'], 1, 'المنتجات (الذاتية التغذية) كالنباتات تنتج الطاقة والغذاء عبر التمثيل الضوئي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تكيّف', 'اختيار من متعدد', 'أيُّ الحيوانات الآتية تنافس الفرد في التغذية القارّة؟', ARRAY['الغراب','الغزال','الذئب','الصقر'], 0, 'الإنسان قارت — الغراب أيضاً قارت يتنافس معه في موارد الغذاء.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تكيّف', 'اختيار من متعدد', 'ما هو الحيوان الذي لا يعيش في الصحراء؟', ARRAY['القرد','الجمل','الضب','الأفاعي'], 0, 'القرد يعيش في الغابات الاستوائية، ليس له تكيّفات صحراوية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'وراثة', 'اختيار من متعدد', 'أيٌّ مما يلي متأثّر بالجنس؟', ARRAY['الصلع','الأنيميا المنجلية','الهيموفيليا','عمى الألوان'], 0, 'الصلع المبكر صفة متأثرة بالجنس (تظهر بشدة في الذكور). الباقية مرتبطة بالجنس بالكروموسوم X.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'هرمونات', 'اختيار من متعدد', 'أيُّ الهرمونات التالية تنتج في المبيض؟', ARRAY['الأكسيتوسين','البروجستيرون (الإستروجين)','الجلوكاجون','التستوستيرون'], 1, 'البروجستيرون والإستروجين هرمونات الأنثى تُفرز من المبيض.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'لوحظ في إحدى المزارع أن تركيز السموم في التربة كان مرتفعاً، فتم وضع مواد داخل أنسجة النباتات لمساعدتها على امتصاص السموم وطرحها خارج البيئة. ما الاسم الذي يطلق على هذه العملية؟', ARRAY['زيادة حيوية','إثراء غذائي','معالجة حيوية','وقاية حيوية'], 2, 'المعالجة الحيوية (Bioremediation): استخدام الكائنات الحية لإزالة الملوّثات.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'مناعة', 'اختيار من متعدد', 'شخص حدث له حادث، ما فصيلة الدم التي يجب أن يأخذوها لإسعافه؟ علماً أن فصيلة الشخص A.', ARRAY['A، لأنه يحوي أجسام مضادة A','O، لاحتوائها أجسام مضادة B','B، لاحتوائها أجسام مضادة A','AB، لعدم احتوائها أجسام مضادة A و B'], 2, 'المصدر يحدّد الجواب ج. (ملاحظة: عادةً صاحب فصيلة A يأخذ A أو O. نعتمد المصدر.)', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'فيروسات', 'اختيار من متعدد', 'أيُّ الفيروسات التالية مادته الوراثية عبارة عن RNA؟', ARRAY['جدري','القوباء','الإيدز','الإنفلونزا'], 2, 'فيروس الإيدز (HIV) فيروس رجعي مادته الوراثية RNA.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تطبيقات أحياء', 'اختيار من متعدد', 'الميكروسبوريديا طلائعيات تستخدم في صناعة:', ARRAY['المنظفات','المواد الكيميائية','الدهانات','المبيدات الحشرية'], 3, 'بعض الطلائعيات تُستخدم كمبيدات حيوية للحشرات.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'سلوك', 'اختيار من متعدد', 'معرفة أسماك السلمون التركيب الكيميائي للمياه التي وضعت بيضها فيه، يعتبر هذا السلوك:', ARRAY['تعود','مطبوع','إدراكي حسّي','إجرائي شرطي'], 1, 'السلوك المطبوع (Imprinting) — تعلم في فترة حرجة ومرتبط بالبصمة الكيميائية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تصنيف', 'اختيار من متعدد', 'إذا وُجدت أن هناك مخلوقَين ينتميان لنفس الشُّعبة هذا يعني أنهما يجب أن ينتميا تصنيفياً لنفس:', ARRAY['الرتبة','المملكة','الفصيلة','الطائفة'], 1, 'الترتيب الهرمي: مملكة < شُعبة < طائفة < رتبة < فصيلة < جنس < نوع. لو في نفس الشعبة → في نفس المملكة أيضاً.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'أيُّ التالي ليس من وظائف الشبكة الإندوبلازمية الملساء؟', ARRAY['تكوين الدهون','تكوين الكربوهيدرات','تكوين البروتينات','إزالة السموم'], 2, 'الشبكة الإندوبلازمية الخشنة (لا الملساء) هي المسؤولة عن البروتينات. الملساء = دهون/كربوهيدرات/إزالة سموم.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تصنيف', 'اختيار من متعدد', 'أيُّ المخلوقات التالية كانسة؟', ARRAY['الضبع','الدب','القرد','الراكون'], 0, 'الضبع كانس (Scavenger) يتغذى على جثث الحيوانات الميتة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'أيُّ نوع من الديدان يعيش في الجهاز الليمفاوي؟', ARRAY['الديوسية','الخطافية','الفيلاريا','الإسكارس'], 2, 'دودة الفيلاريا (Wuchereria) تعيش في الجهاز الليمفاوي وتسبّب داء الفيل.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'عند حدوث ضرر في الهيكل الطرفي أيُّ الآتي يتضرّر؟', ARRAY['العمود الفقري','الأضلاع','القفص','الحوض'], 3, 'الهيكل الطرفي (Appendicular) يشمل الأطراف وحزام الكتف والحوض.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تصنيف', 'اختيار من متعدد', 'نوع القشور في سمكة القرش:', ARRAY['قُرصية','مشطية','صفائحية','لامعة'], 1, 'المصدر يحدّد الجواب ب (مشطية). (سمك القرش له قشور placoid عادة، لكن نعتمد المصدر.)', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تصنيف', 'اختيار من متعدد', 'سمك القرش مثال لـ:', ARRAY['الأسماك العظمية','اللافكيات','اللافقاريات','الأسماك الغضروفية'], 3, 'القرش من الأسماك الغضروفية (Chondrichthyes).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'خلية', 'اختيار من متعدد', 'يضمّ الجهاز المغزلي في الخلايا الحيوانية جميع التراكيب التالية عدا:', ARRAY['الخيوط المغزلية','السنترومير','المريكزات','الألياف النجمية'], 1, 'السنترومير جزء من الكروموسوم، ليس من الجهاز المغزلي مباشرة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'سلوك', 'اختيار من متعدد', 'معرفة أسماك السلمون للنهر الذي قست به سلوك:', ARRAY['مطبوع','تعود','تعود','إدراكي'], 0, 'السلوك المطبوع (Imprinting) — الذاكرة المبكّرة للنهر الذي فقست فيه.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'أضرار ذبابة المنزل؟', ARRAY['تسبب حمى التيفوئيد','تدمير المحاصيل','تهاجم النخيل في السعودية','المالاريا'], 0, 'ذبابة المنزل تنقل أمراضاً مثل حمى التيفوئيد والكوليرا.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'ما وظيفة الحصى في القانصة عند الطيور؟', ARRAY['تخزين الغذاء','إخراج الفضلات','طحن الغذاء','تنظيم درجة حرارة الجسم'], 2, 'الطيور تبتلع الحصى الذي يساعد القانصة على طحن الغذاء.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'جهاز عصبي', 'اختيار من متعدد', 'المخ له علاقة بكل شيء عدا:', ARRAY['الإدراك الحسّي','التفكير','التعلم','الاتزان'], 3, 'الاتزان من وظائف المخيخ، أمّا المخ فمسؤول عن التفكير والذاكرة والإدراك.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'أمراض', 'اختيار من متعدد', 'مرض يتمّ تحديده بوجود بقعة حمراء في مؤخرة العين:', ARRAY['المهاق','الجلاكتوسيميا','التليف الكيسي','تاي-ساكس'], 3, 'مرض تاي-ساكس Tay–Sachs يُشخَّص بالبقعة الكرزية الحمراء في الشبكية (cherry-red spot).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'سلوك', 'اختيار من متعدد', 'عندما يدخل طائر في عش طائر ثاني، ويتخلّص من بيض الطائر الثاني، فإن العلاقة بين هذه الطيور تعد:', ARRAY['تنافس','تطفل','تطفل','تعايش'], 1, 'التطفل: طائر يستفيد على حساب آخر يتضرر. هذا تطفل تكاثري (Brood parasitism).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'في الشكل الذي يمثّل شبكة غذائية بمستويات (نبات ← قوارض ← لواحم متوسطة ← لواحم عليا)، أيُّ التالي يقع ضمن مستوى المستهلكات الثانوية؟', ARRAY['الفأر','الثعبان','الأسد','الصقر'], 1, 'المستهلك الثانوي يأكل المستهلك الأولي (آكل العشب). الثعبان يأكل الفأر فهو مستهلك ثانوي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تكيّف', 'اختيار من متعدد', 'كيف يتكيّف نبات الرتم الصحراوي؟', ARRAY['تساقط لوراقه في وقت الجفاف','انعدام الأوراق والقيام بعملية البناء الضوئي في السيقان','تطوّل الجذور لامتصاص المزيد من الماء','تحوّر أوراقه إلى أشواك'], 1, 'الرتم نبات صحراوي — ساقه خضراء تقوم بعملية البناء الضوئي بدل الأوراق (تقليل التبخر).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'خلية', 'اختيار من متعدد', 'كل الآتي مغلف بغشاء عدا:', ARRAY['الشبكة الإندوبلازمية','المريكزات','الرايبوسومات','فجوات'], 2, 'الرايبوسومات تركيبات بدون غشاء (مكوّنة من بروتينات وRNA).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'هرمونات نبات', 'اختيار من متعدد', 'هرمون يوجد في الثمار الناضجة والأوراق المتساقطة:', ARRAY['الإيثيلين','الأكسينات','الجبريلينات','السيتوكينينات'], 0, 'الإيثيلين هرمون غازي يسرّع نضج الثمار وتساقط الأوراق.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'هرمونات', 'اختيار من متعدد', 'هرمون يرفع مستوى السكر في الدم:', ARRAY['كورتيزول','جلوكاجون','أدوستيرون','أدرنالين'], 1, 'الجلوكاجون يفرزه البنكرياس ويرفع سكر الدم بتحلّل الجلايكوجين الكبدي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تصنيف', 'اختيار من متعدد', 'أيُّ التالي يعد من السرخسيات؟', ARRAY['العرعر','البرتقال','الصنوبر','الخنشار'], 3, 'الخنشار من السرخسيات الحقيقية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تصنيف', 'اختيار من متعدد', 'أيُّ الكائنات التالية إذا انقسمت خلاياها تكوّنت صفيحة خلوية؟', ARRAY['الحيوانات','النباتات','البكتيريا','البدائيات'], 1, 'النباتات تنقسم بتكوين صفيحة خلوية (cell plate). الحيوانات تنقسم بالتخصير.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'دوران', 'اختيار من متعدد', 'أيُّ الأوعية التالية يحمل دماً مؤكسجاً؟', ARRAY['الشريان الرئوي','الوريد الرئوي','الوريد الأجوف السفلي','الوريد الأجوف العلوي'], 1, 'الوريد الرئوي يحمل دماً مؤكسجاً من الرئتين إلى القلب (استثناء من قاعدة الأوردة).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'خلية', 'اختيار من متعدد', 'أيُّ التراكيب التالية يحيط بالفضاء البلازمي في الخلية النباتية؟', ARRAY['الهيكل الخلوي','الغشاء الخلوي','الجدار الخلوي','الشبكة الإندوبلازمية'], 2, 'الجدار الخلوي (السليلوزي) يحيط بالغشاء البلازمي من الخارج في الخلية النباتية.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تصنيف', 'اختيار من متعدد', 'أيُّ التالي يُعدّ حيواناً عديم التناظر؟', ARRAY['العقرب','الإسفنج','حبار البحر','الأخطبوط'], 1, 'الإسفنج (Porifera) عديم التناظر؛ ليس له شكل ثابت محدّد.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'أيُّ المصطلحات التالية تعرف بأنها مادة كيميائية وتتواصل بها بعض المخلوقات ولا تستطيع المفترسات كشفها؟', ARRAY['الهرمونات','الفرمونات','الدهون','البروتينات'], 1, 'الفرمونات: إشارات كيميائية بين أفراد النوع نفسه.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'أمراض', 'اختيار من متعدد', 'الحشرة التي تسبب مرض النوم الأمريكي:', ARRAY['الردويفيد','التنس تسي','الأنوفليس','البلازموديوم'], 0, 'النوم الأمريكي (داء شاجاس) سببه ذبابة Triatomine (الرديوفيد).', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'المادة الأساسية التي تكوّن الشعر والريش:', ARRAY['الكيراتين','الكيراتين','النيروكسين','النيروكسين'], 0, 'الكيراتين بروتين أساسي للشعر والريش والأظافر.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'خلية', 'اختيار من متعدد', 'السنترولاير ينقسم وينضج صفيحة خلوية في الخلية:', ARRAY['النباتية','الحيوانية','البدائية','البكتيرية'], 0, 'الصفيحة الخلوية تتكوّن في الخلية النباتية أثناء التحرك السيتوبلازمي.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تصنيف', 'اختيار من متعدد', 'مخلوق يمحي من تجلّط (تخثر) الدم ويستخدم في الطب البديل في الحجامة:', ARRAY['البلاناريا','العلق','الفيلاريا','المحار'], 1, 'العلق (الديدان المفلطحة العلقية) تفرز هيرودين مضاد التخثر ويُستخدم في الطب البديل.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'خصائص الجماعة الحيوية التي توضّح عدد المخلوقات الحية لكل وحدة مساحة:', ARRAY['كثافة الجماعة','توزيع الجماعة','معدّل نمو الجماعة','القدرة الاستيعابية'], 0, 'كثافة الجماعة (Population density) = عدد الأفراد لكل وحدة مساحة.', grp_id, NULL, false, 'active', false);
    INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, leak_group_id, image_url, is_top_repeated, status, disabled)
    VALUES ('tahsili', 'أحياء', 'تصنيف', 'اختيار من متعدد', 'يحدث التزاوج في الحيوانات بين أفراد:', ARRAY['العائلة الواحدة','الفصيلة الواحدة','النوع الواحد','الرتبة'], 2, 'التزاوج المنتج لذرية خصبة يحدث ضمن النوع الواحد (تعريف النوع).', grp_id, NULL, false, 'active', false);

    -- ── تحديث العداد الفعلي ──
    UPDATE leak_groups SET question_count = (
        SELECT COUNT(*) FROM questions WHERE leak_group_id = grp_id
    ) WHERE id = grp_id;

    RAISE NOTICE 'تم رفع % سؤالاً للـleak_group %', (SELECT COUNT(*) FROM questions WHERE leak_group_id = grp_id), grp_id;
END
$migration$;

COMMIT;

-- ── تحقّق نهائي ──
SELECT
    title,
    leak_date,
    section,
    question_count,
    accent_color,
    is_active
FROM leak_groups
WHERE leak_date = '2026-05-13'
ORDER BY created_at DESC LIMIT 1;
