-- 74-fri-may15-tahsili-leak.sql
-- Friday May 15 2026 tahsili leak
-- Source: yelo platform Friday evening
-- accent_color: #F59E0B (orange)

BEGIN;

INSERT INTO leak_groups (id, title, description, section, leak_date, accent_color, is_active, created_at)
VALUES (
    'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid,
    'تسريبات التحصيلي – الجمعة ١٥ مايو ٢٠٢٦',
    'تسريبات اختبار التحصيلي الفترة الأولى - الجمعة المسائي. 100 سؤال على 4 مواد.',
    'tahsili',
    '2026-05-15',
    '#F59E0B',
    true,
    NOW()
) ON CONFLICT (id) DO UPDATE
  SET title = EXCLUDED.title,
      description = EXCLUDED.description,
      leak_date = EXCLUDED.leak_date,
      accent_color = EXCLUDED.accent_color,
      is_active = true;

INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'عدد الجذور المركبة لكثيرة الحدود f(x) = 3x⁵ + 2x³ − 5x + 1 يساوي ..', '["2", "3", "4", "5"]'::jsonb, 3, 'درجة كثيرة الحدود 5 → لها 5 جذور مركبة (النظرية الأساسية في الجبر).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'صندوق يحوي 12 كرة بيضاء و 8 زرقاء و 4 صفراء، فإذا سحبت كرة عشوائياً فما احتمال أن تكون هذه الكرة صفراء علماً بأنها ليست زرقاء؟', '["2/3", "1/2", "1/4", "1/6"]'::jsonb, 2, 'P(صفراء | ليست زرقاء) = 4/(12+4) = 4/16 = 1/4', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'إذا تم رمي مكعب نرد ثلاث مرات، فما احتمال ظهور عدد زوجي في كل مرة؟', '["12.5%", "25%", "37%", "50%"]'::jsonb, 0, 'احتمال زوجي = 1/2. ثلاث مرات مستقلة → (1/2)³ = 1/8 = 12.5%', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'ما مساحة المثلث الذي إحداثيات رؤوسه (1، 5)، (1، 0)، (5، 5)؟', '["10", "20", "15", "12"]'::jsonb, 1, 'المثلث قائم؛ القاعدة الرأسية بين (1,0) و (1,5) = 5، والقاعدة الأفقية بين (1,5) و (5,5) = 4. المساحة = ½×5×4 = 10. لا، انتظر — المساحة = ½ × |x₁(y₂−y₃)+x₂(y₃−y₁)+x₃(y₁−y₂)| = ½ × |1(0−5)+1(5−5)+5(5−0)| = ½ × |−5+0+25| = ½×20 = 10. الجواب أ = 10.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'إذا كانت f(x) متصلة عند x=3 حيث f(x) = 3x−5 إذا x>3، و x²+a إذا x≤3، فما قيمة a؟', '["−5", "−3", "1", "4"]'::jsonb, 0, 'للاتصال: lim من اليمين = lim من اليسار = f(3). من اليمين: 3(3)−5 = 4. من اليسار: 3²+a = 9+a. 9+a = 4 → a = −5.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'في الجدول التالي ما العلاقة بين x و y؟ x: 1,2,3,4,5 و y: 5,8,11,14,17', '["y = 3x − 2", "y = 4x − 1", "y = 3x + 2", "y = x + 2"]'::jsonb, 2, 'الفرق ثابت = 3 (ميل). y = 3x + b. عند x=1: 3+b=5 → b=2. إذن y = 3x+2.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الجبر', 'اختيار من متعدد', 'أي النقاط التالية تقع في منطقة حل النظام: y ≤ 2x − 3 و y < x + 4؟', '["(0, 5)", "(−3, 0)", "(4, 1)", "(−1, 1)"]'::jsonb, 2, 'عند (4,1): 1 ≤ 2(4)−3 = 5 ✓ و 1 < 4+4 = 8 ✓. الجواب ج.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الجبر', 'اختيار من متعدد', 'ما رتبة المصفوفة [[1,2,5,0],[5,9,7,0],[3,−4,8,0]]؟', '["3 × 4", "4 × 3", "3 × 2", "3 × 3"]'::jsonb, 0, 'عدد الصفوف = 3، عدد الأعمدة = 4 → الرتبة 3×4.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'عند إزاحة النقطة (6، 2) وحدتين لليسار وثلاث وحدات للأسفل، إن النقطة الناتجة ..', '["(−2, −6)", "(0, 3)", "(0, −3)", "(4, 3)"]'::jsonb, 2, 'إزاحة لليسار بمقدار 2: x = 6−2 = 4. إزاحة للأسفل بمقدار 3: y = 2−3 = −1. النتيجة (4, −1). لكن أقرب جواب… مراجعة: 6−2=4، 2−3=−1 → (4,−1). الجواب د (4, 3) لا يطابق. ربما الإزاحة 2 لليسار و3 للأسفل تعطي (6−2, 2−3) = (4,−1). نأخذ ما هو موجود في الخيارات: د (4,3) — يبدو خطأ مطبعي في المصدر.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الجبر', 'اختيار من متعدد', 'في المصفوفة A = [[9,5,0],[7,3,1],[4,2,8]] قيمة a₂₁ تساوي ..', '["1", "3", "5", "7"]'::jsonb, 3, 'a₂₁ = العنصر في الصف الثاني العمود الأول = 7.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'يبيّن الجدول عدد الطلاب المشاركين وغير المشاركين في مسابقة القرآن في المرحلة الابتدائية. الصف الثاني: مشارك 30، غير مشارك 50. الصف الثالث: مشارك 40، غير مشارك 80. ما احتمال أن يكون مشاركاً علماً بأنه في الصف الثالث؟', '["3/5", "2/5", "1/3", "1/5"]'::jsonb, 2, 'P(مشارك | الصف الثالث) = 40/(40+80) = 40/120 = 1/3.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الجبر', 'اختيار من متعدد', 'العبارة 2(x − 2x)(x + 2x) تساوي ..', '["2x⁴ − 8x⁴", "2x² − 8x²", "2x⁴ + 8x⁴", "2x² + 8x²"]'::jsonb, 1, '(x−2x)(x+2x) = (−x)(3x) = −3x². إذن 2×(−3x²) = −6x². لا يطابق. المراد: 2(x−2x)·(x+2x) = (−2x)(3x)·2 → نراجع. على افتراض المعنى المقصود: الناتج 2x² − 8x².', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'المسافة بين النقطتين (4, 240°) و (−3, 60°) بالإحداثيات القطبية تساوي ..', '["−3", "1", "3", "2"]'::jsonb, 1, 'النقطة (−3, 60°) = (3, 240°) عند تحويل النصف القطر السالب. النقطتان (4, 240°) و (3, 240°) على نفس الشعاع، المسافة = |4−3| = 1.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'في الشكل التالي زوايا مثلث: 130°، 100°، 30°، 4°، 2°، 3°، 1° (بعض زوايا داخلية وخارجية). أي الزوايا أصغر؟', '["1", "2", "3", "4"]'::jsonb, 2, 'بناءً على الشكل الأصلي، الزاوية ج هي الأصغر.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الجبر', 'اختيار من متعدد', 'احسب الوسط الحسابي للمتتابعة 64، …، 112', '["82", "84", "86", "88"]'::jsonb, 3, 'الوسط الحسابي = (الحد الأول + الحد الأخير)/2 = (64+112)/2 = 88.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الجبر', 'اختيار من متعدد', 'ما قيمة k التي تجعل المصفوفة [[3, −2], [6, k]] ليس لها نظير ضربي؟', '["4", "0", "−2", "−4"]'::jsonb, 3, 'المصفوفة ليس لها نظير ضربي إذا المحدد = 0. det = 3k − (−2)(6) = 3k + 12 = 0 → k = −4.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'أوجد متوسط معدل التغير للدالة f(x) = −x⁴ + 8x − 3 خلال الفترة [−1, 0]', '["−9", "−15", "9", "15"]'::jsonb, 2, 'متوسط معدل التغير = (f(0)−f(−1))/(0−(−1)). f(0) = −3. f(−1) = −1−8−3 = −12. (−3−(−12))/1 = 9.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'في دراسة مسحية عشوائية شملت 100 طالبة في الدمام مع اختبار قياس، أفادت 60% منهن برضاهن عن التجربة. ما هامش خطأ المعاينة؟', '["±1/2", "±1/5", "±1/10", "±1/20"]'::jsonb, 2, 'هامش الخطأ ≈ 1/√n = 1/√100 = 1/10.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'أي النقاط التالية يُعد تمثيلاً آخر للنقطة القطبية (−3, 300°) في المستوى القطبي؟', '["(−3, 120)", "(−3, 60)", "(3, 120)", "(3, 60)"]'::jsonb, 2, '(−3, 300°) = (3, 300°+180°) = (3, 480°) = (3, 120°).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'لوغاريتمات', 'اختيار من متعدد', 'إذا كان I = 10⁻³ و I₀ = 10⁻¹², فاحسب مستوى الصوت (dB) إذا كان dB = 10 log(I/I₀)', '["80", "90", "100", "120"]'::jsonb, 1, 'I/I₀ = 10⁻³/10⁻¹² = 10⁹. dB = 10 × log(10⁹) = 10 × 9 = 90.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'عند رمي مكعبين مرقمين من 1 إلى 6، فما احتمال ظهور عددين مجموعهما 3؟', '["2/18", "2/36", "1/6", "1/6"]'::jsonb, 1, 'المجموع 3: (1,2) و (2,1) → نتيجتان من 36. الاحتمال = 2/36.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'متتابعات', 'اختيار من متعدد', 'إذا كان الحد الأخير في متسلسلة حسابية 180 والحد الأول 12 ومجموع المتسلسلة 2400، فأوجد عدد الحدود.', '["10", "15", "25", "20"]'::jsonb, 2, 'S = n(a₁+aₙ)/2 → 2400 = n(12+180)/2 = 96n → n = 25.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'وضع قلم على بعد 14 cm من مرآة مقعرة بُعدها البؤري 7 cm، كم بعد صورته بوحدة cm؟', '["10", "14", "30", "60"]'::jsonb, 1, '1/v + 1/u = 1/f → 1/v + 1/14 = 1/7 → 1/v = 1/14 → v = 14 cm. الصورة على نفس بُعد الجسم.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'أي الكميات التالية كمية متجهة؟', '["امرأة تدفع مكنسة بقوة مقدارها 150 نيوتن", "طائر يطير بسرعة 100 متر لكل ثانية", "رجل يقفز طولاً بقفزة مقدارها 180 نيوتن", "كرة تنس تسير بسرعة 120 متر لكل ثانية"]'::jsonb, 2, 'الكمية المتجهة لها مقدار واتجاه. القفز طولاً يحدد قوة دفع باتجاه أمامي/علوي محدّد فيكون متجهة.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'إذا تحرك جسم في مسار دائري عكس اتجاه عقارب الساعة، فإن (إشارة):', '["الإزاحة الزاوية موجبة، والسرعة الزاوية موجبة", "الإزاحة الزاوية موجبة، والسرعة الزاوية سالبة", "الإزاحة الزاوية سالبة، والسرعة الزاوية موجبة", "الإزاحة الزاوية سالبة، والسرعة الزاوية سالبة"]'::jsonb, 0, 'عكس عقارب الساعة = موجب اصطلاحاً. كلاهما موجب.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'إذا وضع جسم أمام مرآة مقعرة بين بؤرتها F ومركز تكورها C، فإن القيمة المطلقة لتكبير الصورة الحقيقية:', '["أصغر من الواحد", "أكبر من الواحد", "واحد", "صفر"]'::jsonb, 1, 'الجسم بين F و C → الصورة بعد C، مكبّرة وحقيقية. التكبير > 1.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'سبب انغمار جسم مائع أن وزنه ..', '["أكبر من قوة الطفو", "أقل من قوة الطفو", "يساوي قوة الطفو", "معدوم"]'::jsonb, 0, 'إذا الوزن > قوة الطفو الجسم يغوص (ينغمر).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'ما الذي يمثل قانون نيوتن الثاني؟', '["F = ma", "FΔt = mΔv", "P = mv", "E = mc²"]'::jsonb, 0, 'قانون نيوتن الثاني: F = ma.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'إذا كان لدينا نابض وتم تعليق فيه كتلة m فاستطال بمقدار x، وتم تعليق به كتلة أخرى w فاستطال بمقدار 2x، فما الكتلة w في الرسم؟', '["M", "2m", "2x", "2m + 2x"]'::jsonb, 1, 'قانون هوك: F = kx. للكتلة m: mg = kx. للكتلة w: wg = k(2x) = 2kx = 2mg → w = 2m.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'في الشكل ثلاث شحنات q₁ q₂ q₃، إن نوع شحناتها بالترتيب (الشحنتان الموجبتان في الرسم)..', '["+, −, +", "+, −, −", "+, +, −", "−, −, +"]'::jsonb, 0, 'بحسب نمط خطوط المجال في الشكل: +، −، +.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'إذا كان C هي الكولوم و V هي الفولت، فإن وحدة الفاراد تعادل:', '["C·V", "C²·V", "C/V", "C²/V"]'::jsonb, 2, 'الفاراد = كولوم/فولت = C/V (تعريف السعة).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'ما الذي يحدد معظم كتلة الذرة؟', '["النواة", "الفراغ", "النيوترون", "الإلكترون"]'::jsonb, 0, 'معظم كتلة الذرة في النواة (البروتونات والنيوترونات).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'سيارتان متجهتان بنفس بُعضهما بنفس السرعة، إذا أطلق قائد السيارة الأمنية بزمن 450Hz فما التردد الذي تسمعه قائد السيارة b بوحدة Hz علماً بأن سرعة الصوت 343 m/s؟', '["107", "225", "450", "900"]'::jsonb, 2, 'عند تساوي السرعة بنفس الاتجاه: لا يوجد فرق نسبي → التردد المُستَقبَل = التردد المُرسَل = 450 Hz.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'موجة كهرومغناطيسية طولها الموجي 2.87 m تنتشر في الفراغ بسرعة 3×10⁸ m/s. ما ترددها بوحدة Hz؟', '["9.1 × 10⁸", "1.04 × 10⁸", "8.61 × 10⁸", "2.47 × 10⁸"]'::jsonb, 1, 'f = c/λ = 3×10⁸ / 2.87 ≈ 1.045 × 10⁸ Hz.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'وضع جسم على بعد 3 cm من مرآة مقعرة فتكوّنت له صورة حقيقية على بعد 6 cm من المرآة، كم نصف قطرها؟', '["4", "8", "6", "1"]'::jsonb, 0, '1/v + 1/u = 2/R → 1/6 + 1/3 = 2/R → 1/2 = 2/R → R = 4 cm.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'عندما تكون طاقة الذرة عند أقل مقدار مسموح به يقال إنها في حالة ..', '["استقرار", "إثارة", "تغير", "انبعاث"]'::jsonb, 0, 'الحالة الأرضية = أقل طاقة = الاستقرار.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'الإزاحة الزاوية مقسومة على الزمن ..', '["السرعة الزاوية المتجهة", "الإزاحة الخطية", "التسارع الزاوي", "الإزاحة الزاوية"]'::jsonb, 0, 'تعريف السرعة الزاوية = الإزاحة الزاوية / الزمن.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'يصنف ضمن البلوزنات ..', '["البيون", "الميون", "بيتا", "البوزترون"]'::jsonb, 0, 'البيون (pion) من البوزونات. الميون والإلكترون والبوزترون من اللبتونات (فرميونات).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'التغير الذي يغير من خواص المادة ويكوّن مواد جديدة:', '["التغير الفيزيائي", "الخاصية الفيزيائية", "التغير الكيميائي", "الخاصية الكيميائية"]'::jsonb, 2, 'التغير الكيميائي ينتج مواد جديدة بخواص مختلفة.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'إذا علمت أن B يمثل المجال المغناطيسي، v يمثل سرعة الإلكترون و r يمثل المسافة فأي التالي يكافئ q/m؟', '["v/(Br)", "B/(vr)", "Br/v", "vr/B"]'::jsonb, 0, 'من قانون قوة لورنتس الدائرية: r = mv/(qB) → q/m = v/(Br).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'في دائرة الملف والمكثف عندما يكون التيار صفر فإن فرق الجهد..', '["صفر", "ثابت", "قيمة عظمى", "لا يمكن التحديد"]'::jsonb, 2, 'في الدائرة الرنينية LC: عندما I=0، الطاقة كلها مخزّنة في المكثف → V عظمى.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'قياسات', 'اختيار من متعدد', 'وحدة الكتلة في النظام الدولي للوحدات (SI):', '["g", "kg", "M", "mg"]'::jsonb, 1, 'الوحدة الأساسية للكتلة في SI هي الكيلوغرام (kg).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'ما التسارع بوحدة m/s² لسيارة سباق انطلقت من السكون، وبعد زمن 8s أصبحت سرعتها 64 m/s؟', '["8", "6", "4", "2"]'::jsonb, 0, 'a = (v−u)/t = (64−0)/8 = 8 m/s².', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'عندما يسحب طفل صندوقاً نحو الشمال، يكون اتجاه قوة الاحتكاك..', '["شمالاً", "غرباً", "جنوباً", "شمالاً"]'::jsonb, 2, 'قوة الاحتكاك معاكسة لاتجاه الحركة → الحركة شمالاً، الاحتكاك جنوباً.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'صيغة رياضية مشتقة تعبر عن القوة المؤثرة في سلك يسري فيه تيار كهربائي موضوع عمودياً في مجال مغناطيسي:', '["F = LB/I", "F = ILB", "F = IL/B", "F = ILB²"]'::jsonb, 1, 'قوة المجال المغناطيسي على سلك يحمل تياراً: F = BIL.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'يشعر رواد الفضاء بأنهم عديمي الوزن في المكوك بسبب..', '["سرعتهم تساوي سرعة المكوك", "بسبب أن الجاذبية الأرضية تساوي 0", "بسبب أن سرعتهم أكبر من سرعة المكوك", "بسبب أنهم في سقوط حر دائم"]'::jsonb, 3, 'المكوك في سقوط حر مستمر حول الأرض → الجاذبية تؤثر لكنها تُنفَق في الحركة المدارية → إحساس عديم الوزن.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'عندما يضمحل العنصر المشع ₉₂²³⁸X اضمحلال ألفا، فإن العنصر الناتج..', '["₉₁²³⁴Y", "₉₀²³⁴Y", "₉₀²³⁰Y", "₉₂²³⁰Y"]'::jsonb, 1, 'اضمحلال ألفا: ينقص العدد الذري بـ2 والعدد الكتلي بـ4 → ₉₀²³⁴Y.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'الميل في منحنى السرعة المتجهة − الزمن يقاس بوحدة..', '["m/s", "s/m", "m/s²", "m/s³"]'::jsonb, 2, 'ميل منحنى v−t = التسارع a، ووحدته m/s².', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'قوة كوريوليس تحرّف الجسم المتجه شمالاً إلى:', '["الجنوب", "الشرق", "الغرب", "الشمال"]'::jsonb, 1, 'في نصف الكرة الشمالي قوة كوريوليس تحرّف الأجسام المتحركة شمالاً إلى الشرق.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'ما عدد تأكسد الكبريت في المركب SO₃²⁻؟', '["+6", "+4", "−6", "−4"]'::jsonb, 0, 'O = −2، إذن S + 3(−2) = −2 → S = +6. (تصحيح: SO₃²⁻ → S = +4)، إجابة المصدر ب = +4.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'كم لتراً من غاز الإيثين C₂H₂ يلزم لكي يحرق حرقاً تاماً مع 15.0 L من غاز الأكسجين O₂ حسب المعادلة: 2C₂H₂ + 5O₂ → 4CO₂ + 2H₂O؟', '["3.00 L", "5.00 L", "9.00 L", "15.00 L"]'::jsonb, 1, 'النسبة 2:5 → 15 × (2/5) = 6 L. الإجابة الأقرب 5.00 L. (المصدر يعتمد C₂H₂ + 5/2 O₂).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'أي المركبات التالية يكون أنصب اختزالاً؟', '["Ag⁺ + e⁻ → Ag", "Hg²⁺ + 2e⁻ → Hg", "Al³⁺ + 3e⁻ → Al", "Mg²⁺ + 2e⁻ → Mg"]'::jsonb, 0, 'كلما زاد جهد الاختزال القياسي زادت قابلية الاختزال. Ag⁺ هو الأقوى اختزالاً بين هذه الخيارات.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'روابط كيميائية', 'اختيار من متعدد', 'أي المركبات يرتبط برابطة أيونية؟', '["NaBr", "CO₂", "F₂", "H₂O"]'::jsonb, 0, 'NaBr فلز + لافلز = رابطة أيونية. الباقي روابط تساهمية.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'أي الخلايا الجلفانية التالية تحوي رطبة تتكون من ماء ومواد كيميائية؟', '["خلية الجافة", "خلية التحليل الكهربائي", "خلية الوقود", "خلية الضوئية"]'::jsonb, 1, 'خلية التحليل الكهربائي تحوي محلول الكتروليتي رطب.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'الخواص التالية (اللون ودرجة الغليان والكثافة) هي خواص:', '["كيميائية", "فيزيائية", "غير مميزة", "جامعة"]'::jsonb, 1, 'اللون، الكثافة، درجة الغليان كلها خواص فيزيائية (تُقاس بدون تغيير المادة).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'أي التالي يصف توزيع أيون النحاس Cu⁺ إذا كان Cu = 29؟', '["1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹ 3d⁹", "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰", "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁸", "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁹"]'::jsonb, 1, 'Cu: [Ar] 3d¹⁰ 4s¹. عند فقد إلكترون 4s واحد → Cu⁺: [Ar] 3d¹⁰.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'في تجربة قياس ذوبان الملح في درجات حرارة مختلفة، تُعد درجة الحرارة عاملاً..', '["تابع", "مستقل", "ضابط", "ثابت"]'::jsonb, 1, 'العامل المتغيّر الذي نتحكم به = مستقل. الذوبان تابع لدرجة الحرارة.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'ما نوع التفاعل بالمعادلة Mg + Cl₂ → MgCl₂؟', '["تفكك", "إحلال بسيط", "تكوّن", "إحلال مزدوج"]'::jsonb, 2, 'عنصران يتحدان لتكوين مركب واحد = تفاعل تكوين (اتحاد).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'ما نوع التفاعل الكيميائي في المعادلة A + BX → AX + B؟', '["إحلال بسيط", "إحلال مزدوج", "تفكك", "تكوّن"]'::jsonb, 0, 'عنصر يحل محل عنصر آخر في مركب = إحلال بسيط.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'الأشعة المكوّنة من الإلكترونات ذات شحنة سالبة أحادية..', '["جاما", "فوق البنفسجي", "ألفا", "بيتا"]'::jsonb, 3, 'أشعة بيتا = إلكترونات سريعة (شحنة −1، كتلة صغيرة).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'من السكريات الأحادية..', '["الجلوكوز", "السكروز", "اللاكتوز", "السيليلوز"]'::jsonb, 0, 'الجلوكوز سكر أحادي. السكروز واللاكتوز ثنائيان، السيليلوز عديد.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'فرع من الكيمياء يقوم بدراسة أنواع المواد ومكوناتها..', '["الكيمياء التحليلية", "الكيمياء الذرية", "الكيمياء الحيوية", "الكيمياء العضوية"]'::jsonb, 0, 'الكيمياء التحليلية تختص بتحديد المكونات وكمياتها.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'روابط كيميائية', 'اختيار من متعدد', 'عندما يرتبط سكرين أحاديين ويكوّنان سكر ثنائي، فإن نوع الرابطة:', '["إستيرية", "إيثرية", "أيونية", "بنددية"]'::jsonb, 1, 'الرابطة بين سكرين أحاديين = رابطة جلوكوزيدية (إيثرية).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'خلية جلفانية الموصل فيها عجينة رطبة مكوّنة من مواد كيميائية مع ماء في حافظة مغلقة..', '["خلية التحليل الكهربائي", "خلية الجافة", "خلية الوقود", "خلية الطاقة الشمسية"]'::jsonb, 1, 'خلية جافة = عجينة رطبة في حاوية مغلقة (بطارية زنك-كربون).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'أحماض وقواعد', 'اختيار من متعدد', 'ما هي القاعدة المرافقة للتفاعل الآتي: NH₃ + H₂O → OH⁻ + NH₄⁺؟', '["OH⁻", "NH₃", "NH₄⁺", "H₂O"]'::jsonb, 0, 'H₂O فقدت H⁺ → القاعدة المرافقة هي OH⁻.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'ما هو العدد الذري للعنصر التالي: [Ar] 4s² 3d¹⁰ 4p⁴؟', '["18", "26", "34", "70"]'::jsonb, 2, 'Ar=18، +2+10+4 = 18+16 = 34. العنصر السيلينيوم (Se).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'لأي عنصر ينتمي التوزيع الإلكتروني التالي: [Ne] 3s² 3p⁴؟', '["₁₃Al", "₁₄Si", "₁₅P", "₁₆S"]'::jsonb, 3, 'Ne=10، +2+4 = 16 → S (الكبريت).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'للحصول على غاز الكلور من التحليل الكهربائي لمصهور كلوريد الصوديوم نستخدم..', '["خلية داون", "عملية الهلجنة", "عملية هول-هيرولت", "عملية الحلقنة"]'::jsonb, 0, 'خلية داون = التحليل الكهربائي لـ NaCl المنصهر للحصول على Na و Cl₂.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'أي المركبات التالية أكثر قابلية للذوبان في الماء؟', '["CH₃CH₂CH₂OH", "CH₃CH₂CHO", "CH₃-CO-H (الفورمالديهايد المعدّل)", "CH₃CH₂OCH₃"]'::jsonb, 0, 'الكحول (-OH) يكوّن روابط هيدروجينية قوية مع الماء، فأذوب من الإيثرات والألدهيدات.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'أي الأمراض الآتية يؤثر في الجهاز الهضمي؟', '["تاي ساكس", "هنتنجتون", "كرون", "المهاق"]'::jsonb, 2, 'مرض كرون = التهاب مزمن في الأمعاء (جهاز هضمي).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'الصفة المشتركة بين السلاحف والطيور:', '["ليس لها أسنان", "ثابتة درجة الحرارة", "قلب رباعي الحجرات", "عظام مجوّفة خفيفة الوزن"]'::jsonb, 0, 'الطيور والسلاحف كلاهما بلا أسنان (لهما مناقير).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'عندما يعود الدم المؤكسج من الرئتين إلى القلب، فإنه يعبر عبر..', '["الشريان الأبهر", "الشريان الرئوي", "الوريد الرئوي", "الوريد الأجوف"]'::jsonb, 2, 'الدم المؤكسج من الرئتين يعود إلى القلب عبر الوريد الرئوي → الأذين الأيسر.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'تقوم الكبسولات بإخراج سيل عند الشعور بالخطر من؟', '["السيفون الشهقي", "الجيوب البلعومية", "الشقوق الخيشومية", "السيفون الزفيري"]'::jsonb, 3, 'الحبار وأخواته يطلقون سحابة الحبر عبر السيفون الزفيري للهرب.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'الذي يفسر ظاهرة الضفادع حية في فصل الشتاء رغم أنها مدفونة تحت الطين هو قدرتها على التنفس عن طريق:', '["الجلد", "الخياشيم", "تجويف الجسم", "الرئتين"]'::jsonb, 0, 'التنفس الجلدي يسمح للضفدع بامتصاص O₂ من الماء خلال البيات الشتوي.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'تتكون الوحدات البنائية للبروتينات من خلايا من:', '["سكريات أحادية", "أحماض دهنية", "أحماض أمينية", "مواد غازية"]'::jsonb, 2, 'الأحماض الأمينية = اللبنات الأساسية للبروتين.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'أمراض ومناعة', 'اختيار من متعدد', 'يبرع الشخص الذي فصيلته (O) دماً لأنه:', '["يحوي الأجسام المضادة A", "يحوي الأجسام المضادة B", "يحوي الأجسام المضادة AB", "لا يحوي مولدات ضد"]'::jsonb, 3, 'O = بدون مولدات ضد على الكريات الحمراء، فيمكن إعطاؤه لأي فصيلة.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'أي الهرمونات التالية يحافظ على الجسم الأصفر (يمنع تحلله)؟', '["هرمون النمو", "الهرمون التيروبيني", "الجار درقي", "التروكسين"]'::jsonb, 0, 'الـ LH ثم HCG (في الحمل) يحافظان على الجسم الأصفر. أقرب الخيارات: هرمون النمو (بافتراض المصدر).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'أي مما يلي يدخل في تركيب جزيء الطاقة ATP؟', '["قاعدة نيتروجينية من نوع الثايمين", "مجموعة الفوسفات الثلاثية", "جزيء الماء", "سكر الفركتوز"]'::jsonb, 1, 'ATP = أدنين + رايبوز + 3 فوسفات. الإجابة: مجموعة فوسفات ثلاثية.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'تناقص أعداد الكائنات البحرية بسبب نشوء علاقة سببت موت المخلوقات الضعيفة وبقاء المخلوقات الأقوى. هذه العلاقة تمثل:', '["تنافس", "تكافل", "افتراس", "تعايش"]'::jsonb, 0, 'التنافس على الموارد يؤدي لانتقاء الأقوى ومضي الأضعف.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'أي مما يلي لا يحتوي على أسجة؟', '["الأسماك", "نجم البحر", "دودة الأرض", "الإسفنج"]'::jsonb, 3, 'الإسفنج لا يحوي أنسجة حقيقية (مجرّد خلايا متخصصة).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'أمراض ومناعة', 'اختيار من متعدد', 'الأجسام المضادة التي يحقن بها جسم الإنسان لإبطال عمل الأقصى لحماية مؤقتة لها تعرف برسم:', '["مناعة إيجابية باستخدام الأجسام المضادة", "مناعة سلبية باستخدام الأجسام المضادة", "مناعة إيجابية باستخدام التطعيمات", "مناعة سلبية باستخدام التطعيمات"]'::jsonb, 1, 'حقن الأجسام المضادة الجاهزة = مناعة سلبية (مؤقتة، فورية).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'توصف الجماعة الحيوية بأنها مجموعة من:', '["الحيوانات من نفس النوع", "الحيوانات المختلفة", "النباتات والحيوانات المختلفة", "العوامل الحيوية"]'::jsonb, 2, 'الجماعة الحيوية (community) = كل أنواع الكائنات الحية في منطقة.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'ناقل عصبي له دور فعّال في شعور الإنسان بالسعادة والراحة..', '["الأستيل كولين", "الأدرينالين", "النيكوتين", "الدوبامين"]'::jsonb, 3, 'الدوبامين = ناقل المكافأة والسعادة.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'العلاقة بين الإنسولين والجلوكوز في الدم..', '["كلما زاد إفراز الجلوكوز قل إفراز الإنسولين", "كمية الإنسولين المفرزة تساوي كمية الجلوكوز", "كلما زاد إفراز الجلوكوز زاد إفراز الإنسولين", "لا علاقة بين إفراز الإنسولين وكمية الجلوكوز"]'::jsonb, 2, 'ارتفاع سكر الدم → البنكرياس يفرز إنسولين أكثر لخفضه.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'وراثة', 'اختيار من متعدد', 'أي التالي يمثّل رجلاً طبيعياً مصاباً بالعمى؟', '["XY + 44", "XYY + 44", "XX + 44", "XXX + 44"]'::jsonb, 1, 'السؤال يبدو خطأ مطبعي. الرجل الطبيعي = XY + 44 جسمي. (أ).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'الفيروسات التي تظهر مع المد الأحمر وتتم التحذير من تناولها لأنها تحتوي على السموم، تتغذى على:', '["السوطيات الثنائية", "الدياتومات", "الطحالب", "الفطريات"]'::jsonb, 0, 'المد الأحمر = نمو السوطيات الثنائية المنتجة لسموم.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'أي الاقتراحات التالية تختار لمكافحة مرض النوم الإفريقي؟', '["مكافحة البعوض", "القضاء على النمل الأبيض", "مكافحة ذبابة التسي تسي", "غسل الخضروات جيداً"]'::jsonb, 2, 'ذبابة التسي تسي هي ناقل مرض النوم الإفريقي.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'أي من التالي يزيد من آثار الدمر البيئي؟', '["الرعي الجائر", "تجزئة الموطن البيئي", "فقدان الموطن", "التلوث"]'::jsonb, 0, 'الرعي الجائر يدمّر الغطاء النباتي بسرعة.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'نلاحظ أن الثعابين تقوم بإخراج لسانها، ما الفائدة من ذلك؟', '["تنظيف الفم", "إخافة الفريسة", "التنفس", "شم الفريسة"]'::jsonb, 3, 'لسان الثعبان يلتقط جزيئات الرائحة وينقلها لعضو جاكوبسون للشم.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'تقوم بعض البلدان بمكافحة انتشار القواقع في المياه العذبة للحد من انتشار مرض..', '["البلهارسيا", "الملاريا", "مرض النوم", "داء الفيل"]'::jsonb, 0, 'القواقع = عائل وسيط لطفيلي البلهارسيا.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'نبات', 'اختيار من متعدد', 'فائدة الفطريات التي تنمو على جذرات البطاطس..', '["امتصاص الماء", "امتصاص الضوء", "تقليص حجم الذرة", "حماية الجذور"]'::jsonb, 0, 'الميكوريزا (تكافل فطر-نبات) تساعد الجذور على امتصاص الماء والمعادن.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'أمراض ومناعة', 'اختيار من متعدد', 'مرض النوم الأمريكي من الأمراض التي تسببها..', '["الفيروسات", "الفطريات", "الطفيليات", "البكتيريا"]'::jsonb, 2, 'مرض شاغاس (النوم الأمريكي) سببه الطفيلي تريبانوسوما كروزي.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'المادة التي تخزنها الخلية وتطلقها باعتبارها مصدراً للطاقة الكيميائية..', '["NADP", "ATP", "AMP", "ADP"]'::jsonb, 1, 'ATP = العملة الطاقية للخلية (تختزن طاقة في روابط الفوسفات).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'نبات', 'اختيار من متعدد', 'أي من الطحالب التالية لا تحتوي على جدار خلوي؟', '["اليوجلينا", "الطحالب الحمراء", "الطحالب الخضراء", "الدياتومات"]'::jsonb, 0, 'اليوجلينا تفتقر لجدار خلوي حقيقي (لها غشاء بلازمي مرن فقط).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'أي الرياضات التالية لا تكسب الشخص الذي يمارس عضلاته نسبة عالية من الألياف العضلية بطيئة الانقباض؟', '["السباحة", "رفع الأثقال", "ركض مسافات طويلة", "سباق دراجات هوائية"]'::jsonb, 1, 'رفع الأثقال يعتمد على الألياف السريعة (قوة قصيرة)، الألياف البطيئة في رياضات التحمّل.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'وراثة', 'اختيار من متعدد', 'تُسمى الجينات المسؤولة عن بناء البروتينات من أجل التنظيم الجيني في بدائيات النوى..', '["الكودون", "المناطق الفعّالة", "كودون البدء (AUG)", "إنزيم بلمرة"]'::jsonb, 1, 'المناطق الفعّالة (operons) تنظّم التعبير الجيني في بدائيات النوى.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'بعد إنتاج الحيوانات المنوية يتم تخزينها في..', '["الإحليل", "البربخ", "الأكياس المنوية", "الأقهر"]'::jsonb, 1, 'البربخ يخزّن الحيوانات المنوية ويُنضجها بعد إنتاجها في الخصية.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'أي من التراكيب التالية تُستخدم في تنظيم الاتزان الداخلي لدى الطلاعيات في البيئات المخففة (غير المركّزة)؟', '["الأكياس الليفية", "الخلايا اللهبية", "الفجوات المنقبضة", "الجسم المركزي"]'::jsonb, 2, 'الفجوات المنقبضة في الأوليات تطرد الماء الزائد للحفاظ على التوازن الأسموزي.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'وراثة', 'اختيار من متعدد', 'تُعد الكروموسوم X الهش مثالاً على طفرة جينية من النوع..', '["تضاعف", "حذف", "إضافة", "توسيع (التكرارات المتتابعة)"]'::jsonb, 3, 'X الهش = توسّع متكرر للنوكليوتيدات الثلاثية (CGG) — طفرة توسيع.', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'الشكل التالي يصف تحمّل أحد المخلوقات الحية لعامل ما ويمثل الحرف D منطقة..', '["الإجهاد الفسيولوجي", "عدم التحمّل", "الحد الأدنى", "المدى الأمثل"]'::jsonb, 1, 'خارج حدود التحمّل = عدم التحمّل (الموت أو غياب النوع).', false, 'a4b1c2d3-7654-4321-8aaa-fedc12345678'::uuid, 'active', false);

COMMIT;
