-- 75b-sat-may16-evening-tahsili-leak.sql
-- Saturday May 16 2026 (Evening) tahsili leak
-- Source: Hamma platform (تسريبات اليوم الرابع المسائي)
-- accent_color: #DB2777 (pink-600 / fuchsia)
-- Total questions: 115

BEGIN;

INSERT INTO leak_groups (id, title, description, section, leak_date, accent_color, is_active, created_at)
VALUES (
    'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid,
    'تسريبات التحصيلي – السبت ١٦ مايو ٢٠٢٦ (المسائي)',
    'تسريبات اختبار التحصيلي الفترة المسائية – السبت ١٦ مايو. مواد: كيمياء + أحياء + فيزياء + رياضيات.',
    'tahsili',
    '2026-05-16',
    '#DB2777',
    true,
    NOW()
) ON CONFLICT (id) DO UPDATE
  SET title = EXCLUDED.title,
      description = EXCLUDED.description,
      leak_date = EXCLUDED.leak_date,
      accent_color = EXCLUDED.accent_color,
      is_active = true;

INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'ما ناتج ضرب المصفوفتين [1  6  -3] و [-8, 1/2, 7]ᵀ إن أمكن؟', '["[-26]", "[26]", "[-8, 3, -21]ᵀ", "غير معروف"]'::jsonb, 0, 'حاصل الضرب 1×3 مع 3×1 = 1×1. الناتج = 1·(-8) + 6·(1/2) + (-3)·7 = -8 + 3 - 21 = -26.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'أي العبارات التالية صحيحة دائماً لأي مثلث؟', '["المثلث مختلف الأضلاع يكون حاد الزوايا", "المثلث المتطابق الضلعين يكون قائم الزاوية", "المثلث المتطابق الأضلاع يكون حاد الزوايا", "المثلث مختلف الأضلاع يكون منفرج أو قائم الزاوية"]'::jsonb, 2, 'المثلث متطابق الأضلاع زواياه الثلاث متساوية وكل منها = 60°، فهو حاد الزوايا دائماً. الباقي عبارات قد تصح وقد لا.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'ما عدد عناصر العينة لتجربة سحب بطاقتين مع الإرجاع من مجموعة بطاقات مرقمة من 1 إلى 6؟', '["64", "36", "24", "16"]'::jsonb, 1, 'كل بطاقة لها 6 احتمالات، ومع الإرجاع: 6 × 6 = 36.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'عند زاويتين متناظرتين عند تقاطع مستقيمين متوازيين مع قاطع، أي زاوية من 1-12 تطابق ∠9 (انظر الشكل الموصوف): ∠12, ∠6, ∠8, ∠3', '["∠12", "∠8", "∠6", "∠3"]'::jsonb, 3, 'بفرض تقاطع 3 مستقيمات (k, l, m, n) في وضع متوازي، الزوايا المتناظرة تكون في نفس الموضع النسبي عند كل قاطع. الزاوية المطابقة لـ∠9 هي ∠3.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'إذا كان √(x⁵) = 32 أوجد قيمة x:', '["2", "4", "1/2", "1"]'::jsonb, 1, '√(x⁵) = x^(5/2) = 32 = 2⁵ → رفع الطرفين للقوة 2/5: x = 2⁵·(2/5) = 2² = 4.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'cos(360° + θ) = ...', '["sin θ", "-sin θ", "cos θ", "-cos θ"]'::jsonb, 2, 'الجيب وجيب التمام دوال دورية بدور 360°. cos(360°+θ) = cos θ.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'أي من العلاقات التالية تمثل دالة في x؟ (أ) x=(y−2)² (ب) جدول قيم: x=-1→y=2، x=0→y=1، x=1→y=0، x=-1→y=4 (ج) x يمثل رقم الهوية الوطنية، y يمثل العمر بالسنوات (د) قطع ناقص محوره الكبير على المحور x', '["x=(y−2)²", "الجدول المعطى", "رقم الهوية والعمر", "القطع الناقص"]'::jsonb, 2, 'الدالة تتطلب أن كل قيمة في المجال (x) لها صورة واحدة فقط في المدى (y). كل رقم هوية له عمر واحد. الجدول يكرر x=-1 بقيمتين (2 و 4) فهو ليس دالة. القطع الناقص و x=(y-2)² كل منهما يعطي x واحد قيمتين من y، لكن السؤال يطلب دالة في x فالأخيرة قد تكون دالة. لكن الأوضح هو ج.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'أي القياسات التالية تمثل أضلاع مثلث؟', '["5, 3, 3", "17, 5, 3", "11, 4, 4", "6, 10, 34"]'::jsonb, 0, 'شرط المثلث: مجموع كل ضلعين > الضلع الثالث. 3+3=6>5 ✓. الباقي يفشل: 5+3=8<17، 4+4=8<11، 10+6=16<34.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'لوغاريتمات', 'اختيار من متعدد', 'ما قيمة log₅(0.04)؟', '["2", "3", "20", "-2"]'::jsonb, 3, '0.04 = 4/100 = 1/25 = 5⁻². إذن log₅(5⁻²) = -2.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'إذا كان x يقبل القسمة على 3 فإن العدد يقبل القسمة على 6. المثال المضاد لهذه العبارة:', '["x = 24", "x = 12", "x = 39", "x = 18"]'::jsonb, 2, 'نريد عدداً يقبل القسمة على 3 ولا يقبل القسمة على 6. 39 = 13×3 (قابل لـ3) لكن 39÷6 = 6.5 (غير قابل لـ6). الباقي يقبل القسمة على 6.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'الإحصاء والاحتمالات', 'اختيار من متعدد', 'عدد الطلاب المشاركين والغير مشاركين في مسابقة القرآن الكريم: الصف الثاني (مشارك=30، غير مشارك=50)، الصف الثالث (مشارك=40، غير مشارك=80). إذا اختير طالب عشوائياً، فما احتمال أن يكون مشاركاً علماً بأنه في الصف الثالث؟', '["3/5", "2/5", "1/3", "1/5"]'::jsonb, 2, 'الاحتمال الشرطي: عدد الصف الثالث = 40+80 = 120، المشاركون منهم = 40. P = 40/120 = 1/3.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'مشتقة الدالة f(x) = -⁵√(1/x³) تساوي:', '["(1/5)·⁵√(1/x⁸)", "(3/5)·⁵√(1/x⁸)", "-(3/5)·⁵√(1/x⁸)", "-(1/5)·⁵√(1/x⁸)"]'::jsonb, 1, 'f(x) = -x^(-3/5). f''(x) = -(-3/5)·x^(-8/5) = (3/5)·x^(-8/5) = (3/5)·⁵√(1/x⁸).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', '∫(4x + 5)dx =', '["4x + 5 + c", "4x² + 5x + c", "2x² + 5x + c", "4"]'::jsonb, 2, 'التكامل: ∫4x dx = 2x²، ∫5 dx = 5x. الناتج: 2x² + 5x + c.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'في مثلث متطابق الضلعين، الزاوية بين الضلعين المتطابقين 40°. إذا كانت إحدى زاويتي القاعدة 8x°، فما قيمة x؟', '["5", "8", "10", "20"]'::jsonb, 0, 'المثلث متطابق الضلعين → زاويتا القاعدة متساويتان. مجموع الزوايا 180°، فالقاعدتان معاً = 180−40 = 140. كل واحدة = 70°. 8x = 70 → x = 8.75. (لكن إن كانت الـ40 إحدى زاويتي القاعدة فالأخرى = 40 أيضاً متماثلتان: 8x=40 → x=5).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'ما الإزاحة التي تنقل النقطة A(-1, 5) إلى النقطة A''(5, -3)؟', '["6 وحدات إلى اليمين و 8 وحدات إلى الأسفل", "8 وحدات إلى أعلى و 6 وحدات إلى اليمين", "6 وحدات إلى اليمين و 8 وحدات إلى الأعلى", "8 وحدات إلى الأسفل و 6 وحدات إلى اليسار"]'::jsonb, 0, 'Δx = 5 - (-1) = 6 (يمين). Δy = -3 - 5 = -8 (أسفل 8 وحدات). إذن: 6 يمين، 8 أسفل.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'أوجد النظير الضربي للعدد √12:', '["-√12", "√12", "-1/√12", "1/√12"]'::jsonb, 3, 'النظير الضربي (المقلوب) لعدد a هو 1/a. النظير الضربي لـ√12 = 1/√12.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'سقط فوتون ترددهف₀ على فلز مقدار اقتران الشغل له hf₀، فإن الإلكترون..', '["يتحرر ولا يمتلك طاقة حركية", "يتحرر ويمتلك طاقة حركية hf₀", "لا يتحرر ولا يمتلك طاقة حركية", "لا يتحرر وتزداد طاقته الحركية بمقدار hf₀"]'::jsonb, 0, 'عندما تساوي طاقة الفوتون مقدار اقتران الشغل (الحد العتبي) → الإلكترون يتحرر بطاقة حركية صفر (KE = hf − hf₀ = 0).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'تحتوي نواة الذرة على:', '["النيوترونات والبروتونات", "النيوترونات والإلكترونات", "البروتونات والإلكترونات", "الفوتونات والنيوترونات"]'::jsonb, 0, 'النواة تتكوّن من بروتونات (+) ونيوترونات (متعادلة). الإلكترونات تدور حول النواة في المدارات.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'تعادل نواة ذرة الهيليوم:', '["ألفا", "بيتا", "جاما", "بروتونات"]'::jsonb, 0, 'جسيم ألفا = نواة ذرة الهيليوم (2 بروتون + 2 نيوترون، شحنة +2).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'عندما يتغير موقع جسم خلال فترة زمنية فإن هذا يعني أن الجسم:', '["ساكن ويتسارع مؤكداً", "ساكن وقد يكون متسارعاً", "متحرك ويتسارع مؤكداً", "متحرك وقد يكون متسارعاً"]'::jsonb, 3, 'تغير الموقع → الجسم متحرك (لا شك). لكن قد يكون بسرعة ثابتة (تسارع=0) أو متسارعاً → التسارع غير مؤكد.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'رافعة ميكانيكية W قدرتها 80000 ترفع لوح خرسانة خلال s 5، ما مقدار الشغل الذي تبذله بوحدة الجول؟', '["8000", "16000", "20000", "400000"]'::jsonb, 3, 'W = P × t = 80,000 × 5 = 400,000 جول.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'تتناسب الطاقة المنبعثة في كل ثانية للموجات الكهرومغناطيسية:', '["طردياً مع درجة حرارة الجسم", "عكسياً مع درجة حرارة الجسم", "طردياً مع الطول الموجي", "عكسياً مع التردد"]'::jsonb, 0, 'قانون ستيفان-بولتزمان: الطاقة المُشعّة ∝ T⁴ (طردياً مع درجة حرارة الجسم).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'أي العبارات التالية صحيحة بالنسبة للموجات الكهرومغناطيسية؟', '["إذا زاد التردد تقل طاقتها", "إذا زاد الطول الموجي تزداد طاقتها", "إذا زاد التردد يزداد الطول الموجي", "إذا زاد التردد يقل الطول الموجي"]'::jsonb, 3, 'c = fλ → التردد والطول الموجي عكسيان. الطاقة E=hf طردية مع التردد.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء', 'اختيار من متعدد', 'كمية الحرارة بوحدة الكيلوجول اللازمة لرفع درجة حرارة 300 g من الماء بمقدار 10°C تساوي: (الحرارة النوعية للماء C = 4180 J/Kg.°C)', '["62.7", "31.3", "25", "12.5"]'::jsonb, 3, 'Q = m·c·ΔT = 0.300 × 4180 × 10 = 12,540 J ≈ 12.5 kJ.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء', 'اختيار من متعدد', 'إذا كانت ΔU التغير في الطاقة الحرارية للجسم، و Q مقدار الحرارة المضافة للجسم، و W الشغل الذي يبذله الجسم، فأي العلاقات الرياضية الآتية تمثل القانون الأول للديناميكا الحرارية؟', '["ΔU = 2Q − W", "ΔU = 2Q + W", "ΔU = Q + W", "ΔU = Q − W"]'::jsonb, 3, 'القانون الأول: ΔU = Q − W (الطاقة الداخلية تزيد بالحرارة الداخلة وتقل بالشغل الذي يبذله الجسم).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'عندما تكون طاقة الذرة عند أقل مقدار مسموح به يقال إنها في حالة:', '["استقرار", "إثارة", "تغيّر", "انبعاث"]'::jsonb, 0, 'الحالة الأرضية = الاستقرار. الإلكترونات في أدنى مستوى طاقة ممكن.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'أي الكميات التالية تساوي q/m بالنسبة للإلكترون (حيث B المجال المغناطيسي، v السرعة، r نصف القطر)؟', '["B/(vr)", "v/(Br)", "rv/B", "Br/v"]'::jsonb, 1, 'للإلكترون في مجال مغناطيسي: qvB = mv²/r → q/m = v/(Br).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'نسبة فرق الجهد بين طرفي موصل إلى شدة التيار المار فيه تمثل:', '["المقاومة الكهربائية", "السعة الكهربائية", "القدرة الكهربائية", "الطاقة الكهربائية"]'::jsonb, 0, 'قانون أوم: R = V/I (المقاومة = فرق الجهد ÷ شدة التيار).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'الجهاز الذي يحوّل الطاقة الكهربائية إلى طاقة حركية دورانية يُسمى:', '["المولد الكهربائي", "المحول الكهربائي", "المحرك الكهربائي", "المكثف الكهربائي"]'::jsonb, 2, 'المحرك الكهربائي يحوّل الطاقة الكهربائية → طاقة حركية دورانية. المولد عكسه (حركة → كهرباء).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'رُفع جسم كتلته 2 kg من الأرض إلى ارتفاع 4 m، فما هي طاقة الوضع التي يكتسبها بوحدة الجول؟', '["80", "20", "5", "0.8"]'::jsonb, 0, 'PE = mgh = 2 × 10 × 4 = 80 جول.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء', 'اختيار من متعدد', 'أي مما يلي يُعتبر كمية متجهة؟', '["الحجم والسرعة", "السرعة وقوة الإعاقة", "قوة الإعاقة والكتلة", "الكتلة والحجم"]'::jsonb, 1, 'الكميات المتجهة لها مقدار واتجاه: السرعة (متجهة) والقوة (متجهة). الكتلة والحجم كميات قياسية.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'أحد العوامل المؤثرة في شدة المجال المغناطيسي المتولّد حول ملف لولبي:', '["فرق الجهد", "مقاومة الملف", "عدد لفّات الملف", "مساحة الملف"]'::jsonb, 2, 'B = μ₀nI حيث n = عدد اللفّات لكل وحدة طول. زيادة اللفّات تزيد المجال.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'دفع ثامر صندوقاً بقوة 50 N بزاوية 60° مع الأفقي، فإن المركبة الأفقية للقوة:', '["50", "60", "25", "10"]'::jsonb, 2, 'Fx = F·cos(60°) = 50 × 0.5 = 25 N.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'جسيمات نووية شحنتها موجبة وتتحرك بسرعة عالية يشبه نواة ذرة الهيليوم:', '["بيتا", "ألفا", "جاما", "بروتون"]'::jsonb, 1, 'جسيم ألفا = نواة الهيليوم (شحنة +2، كتلة 4، يتحرك بسرعة 5-7% من سرعة الضوء).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء', 'اختيار من متعدد', 'تُسمى الممانعة التي يبديها السائل للتدفق والانسياب:', '["التوتر السطحي", "الضغط", "الميوعة", "اللزوجة"]'::jsonb, 3, 'اللزوجة (viscosity) = مقاومة السائل للجريان. العسل عالي اللزوجة، الماء منخفض.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'الأشعة المكوّنة من إلكترون له شحنة سالبة أحادية هي:', '["ألفا", "بيتا", "جاما", "فوق البنفسجية"]'::jsonb, 1, 'جسيم بيتا = إلكترون (شحنة −1، يخرج من النواة عند تحوّل نيوترون إلى بروتون).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'أي التالي صحيح عن البروتون؟', '["يشترك مع النيوترون في الشحنة والكتلة", "يشترك مع الإلكترون في الشحنة والكتلة", "يشترك مع البوزيترون في الشحنة", "يشترك مع الإلكترون في الشحنة والنيوترون في الكتلة"]'::jsonb, 2, 'البروتون شحنته (+1) = شحنة البوزيترون. يشترك مع النيوترون في الكتلة وليس الشحنة (النيوترون متعادل).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'إذا كانت قدرة جسم W 8000 وقام ببذل القدرة في s 5، فما قيمة الشغل بوحدة J؟', '["2000", "1600", "8000", "40000"]'::jsonb, 3, 'W = P × t = 8000 × 5 = 40,000 جول.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'في دائرة كهربائية متسلسلة فيها مقاومتان 2Ω و 1Ω وبطارية فرق جهدها 12V، ما مقدار شدة التيار I بوحدة الأمبير؟', '["18", "15", "9", "4"]'::jsonb, 3, 'المقاومة الكلية = 2+1 = 3Ω. I = V/R = 12/3 = 4 أمبير.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء', 'اختيار من متعدد', 'وُضع قلم على بعد 14cm من مرآة مقعرة بعدها البؤري 7cm، كم بعد صورته بوحدة cm؟', '["10", "14", "30", "60"]'::jsonb, 1, '1/f = 1/do + 1/di → 1/7 = 1/14 + 1/di → 1/di = 1/14 → di = 14 cm.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء', 'اختيار من متعدد', 'أي الكميات التالية كمية متجهة؟', '["امرأة تدفع مكنسة بقوة مقدارها 150 نيوتن", "طائر يطير بسرعة 100 متر لكل ثانية", "رجل يدفع طاولة بقوة مقدارها 180 نيوتن بزاوية 7° مع سطح الأرض", "كرة تنس تسير بسرعة 120 متر لكل ثانية"]'::jsonb, 2, 'الكمية المتجهة تحتاج مقدار + اتجاه. الخيار c يحدد المقدار (180 N) والاتجاه (بزاوية 7° مع الأفقي). الباقي يذكر مقدار فقط.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'إذا تحرك جسم في مسار دائري عكس اتجاه عقارب الساعة، فإن إشارة:', '["الإزاحة الزاوية موجبة، والسرعة الزاوية موجبة", "الإزاحة الزاوية سالبة، والسرعة الزاوية سالبة", "الإزاحة الزاوية موجبة، والسرعة الزاوية سالبة", "الإزاحة الزاوية سالبة، والسرعة الزاوية موجبة"]'::jsonb, 0, 'اصطلاحاً: عكس عقارب الساعة = اتجاه موجب لكل من الإزاحة الزاوية والسرعة الزاوية.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء', 'اختيار من متعدد', 'سبب انغمار جسم في مائع أن وزنه:', '["أكبر من قوة الطفو", "أقل من قوة الطفو", "يساوي قوة الطفو", "معدوم"]'::jsonb, 0, 'مبدأ أرخميدس: إذا كان وزن الجسم > قوة الطفو (وزن المائع المُزاح) → ينغمر. إذا أقل → يطفو، إذا تساوى → متعادل.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'ما الذي يحدد معظم كتلة الذرة؟', '["النواة", "الفراغ", "النيوترون", "الإلكترون"]'::jsonb, 0, 'النواة (بروتونات + نيوترونات) تحوي ~99.9% من كتلة الذرة رغم صغر حجمها (الإلكترونات كتلتها ضئيلة).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'الإزاحة الزاوية مقسومة على الزمن تساوي:', '["السرعة الزاوية المتجهة", "الإزاحة الخطية", "التسارع الزاوي", "الإزاحة الزاوية"]'::jsonb, 0, 'السرعة الزاوية المتجهة ω = Δθ/Δt (الإزاحة الزاوية بالنسبة للزمن).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء', 'اختيار من متعدد', 'التغير الذي يغيّر من خواص المادة ولا يُكوّن مواد جديدة:', '["التغير الكيميائي", "الخاصية الفيزيائية", "التغير الفيزيائي", "الخاصية الكيميائية"]'::jsonb, 2, 'التغير الفيزيائي يغير شكل/حالة المادة دون تكوّن مواد جديدة (تغير الحالة، الذوبان، التبخر).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'عند اقتراب الكوكب من الشمس أثناء دورانه، ماذا يحصل لسرعته؟', '["تزداد", "تنقص", "تتذبذب", "لا تتأثر"]'::jsonb, 0, 'قانون كبلر الثاني (المساحات المتساوية): سرعة الكوكب تزداد عند الاقتراب من الشمس وتقل عند الابتعاد.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'في دائرة الملف والمكثف عندما يكون التيار صفر فإن فرق الجهد:', '["صفر", "ثابت", "قيمة عظمى", "لا يمكن التحديد"]'::jsonb, 2, 'في دائرة LC: عندما يكون التيار صفراً، تكون الطاقة كلها مخزّنة في المكثف → فرق الجهد عند قيمته العظمى.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'ما التسارع بوحدة m/s² لسيارة سباق انطلقت من السكون وبعد زمن قدره 8s أصبحت سرعتها 64 m/s؟', '["8", "6", "4", "2"]'::jsonb, 0, 'a = (vf − vi)/t = (64 − 0)/8 = 8 m/s².', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'صيغة رياضية تعبّر عن القوة المؤثرة في سلك يسري فيه تيار كهربائي موضوع عمودياً في مجال مغناطيسي:', '["F = LB/I", "F = ILB", "F = ILB²", "F = IB/B"]'::jsonb, 1, 'القوة على موصل في مجال مغناطيسي: F = BIL sin θ. عند زاوية 90° → F = BIL.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'يشعر روّاد الفضاء بأنهم عديمي الوزن في المكوك بسبب:', '["سرعتهم تساوي سرعة المكوك", "أن الجاذبية الأرضية تساوي 0", "أنهم في سقوط حر دائم", "أن سرعتهم أكبر من سرعة المكوك"]'::jsonb, 2, 'المكوك ورواده في حالة سقوط حر مستمر حول الأرض → انعدام الوزن الظاهري (لا تأثير قوى التماس).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'عندما يضمحل العنصر المشع 234/92 X اضمحلال ألفا، فإن العنصر الناتج:', '["230/90 Y", "230/92 Y", "234/93 Y", "234/91 Y"]'::jsonb, 0, 'اضمحلال ألفا يفقد 4 من الكتلة و 2 من العدد الذري: 234−4=230، 92−2=90. الناتج 230/90 Y.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'في الشكل تتسارع كرة من السكون بدءاً من C وتدحرجت حتى وصلت A ثم أكملت طريقها حتى توقّفت عند B، ما هي العبارة الصحيحة عن الزخم؟', '["متساوي عند A, B, C", "متساوي عند A, B", "عند B أكبر ما يمكن", "عند A أكبر ما يمكن"]'::jsonb, 3, 'الزخم p = mv. أكبر سرعة عند A (نقطة قاع المنحدر بعد التسارع). عند B الكرة توقّفت → زخم = 0.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'الميل في منحنى السرعة المتجهة − الزمن يُقاس بوحدة:', '["m/s", "s/m", "m/s³", "m/s²"]'::jsonb, 3, 'الميل = Δv/Δt = (m/s)/s = m/s² = وحدة التسارع.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء', 'اختيار من متعدد', 'قوة كوريوليس تحرف الجسم المتجه شمالاً (في نصف الكرة الشمالي) إلى:', '["الجنوب", "الشرق", "الغرب", "الشمال"]'::jsonb, 1, 'في نصف الكرة الشمالي تنحرف الأجسام المتحركة إلى اليمين بسبب دوران الأرض → المتجه شمالاً ينحرف شرقاً.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'ما هي المادة اللازم إضافتها لإنتاج شبه موصل من النوع n؟', '["مانحة ثلاثية تكافؤ", "مانحة خماسية تكافؤ", "مستقبلة ثلاثية تكافؤ", "مستقبلة خماسية تكافؤ"]'::jsonb, 1, 'شبه موصل n يحتاج شوائب مانحة بخمسة إلكترونات تكافؤ (مثل الفسفور) لتوفير إلكترونات حرة زائدة.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'اللون الأرجواني (مغنتا) في طيف الضوء يمتص اللون:', '["الأصفر", "الأزرق", "الأحمر", "الأخضر"]'::jsonb, 3, 'الأرجواني (مغنتا) = أحمر + أزرق (يعكسهما). اللون الذي يمتصه = اللون المكمّل = الأخضر.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'قطار يتحرك بسرعة 80 m/s وداخله شخص يمشي في اتجاه حركة القطار بسرعة 8 m/s. احسب سرعة الشخص بالنسبة للمراقب على الأرض:', '["80", "88", "72", "8"]'::jsonb, 1, 'نسبية السرعات: سرعة الشخص بالنسبة للأرض = سرعة القطار + سرعة الشخص داخل القطار = 80 + 8 = 88 m/s.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'عدد الموجات التي تصل لنقطة محددة بالثانية يُسمى:', '["التردد", "الفوتون", "الموجة", "الضوء"]'::jsonb, 0, 'التردد f = عدد الموجات (الذبذبات) في الثانية. وحدته الهرتز (Hz).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'إذا كان الوزن في الأرض 800 N، فكم الوزن في كوكب آخر له ضعف كتلة الأرض ونفس نصف القطر؟', '["400", "1600", "3200", "800"]'::jsonb, 1, 'g = GM/r². ضعف الكتلة بنفس نصف القطر → ضعف g → ضعف الوزن = 1600 N.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'علاقة المقاومة مع السلك:', '["عكسي مع الطول ومساحة المقطع", "طردي مع الطول ومساحة المقطع", "طردي مع الطول وعكسي مع مساحة المقطع", "طردي مع مساحة المقطع وعكسي مع الطول"]'::jsonb, 2, 'R = ρL/A. المقاومة تزداد بزيادة الطول (طردي) وتقل بزيادة مساحة المقطع (عكسي).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء', 'اختيار من متعدد', 'صورة لجسم معامل التكبير أقل من واحد، أين تتكوّن الصورة؟', '["بين البؤرة والمرآة", "بين البؤرة ومركز التكوّر", "خلف مركز التكوّر", "عند البؤرة"]'::jsonb, 1, 'في المرآة المقعرة: إذا كان الجسم خلف مركز التكوّر، تتكوّن الصورة بين البؤرة ومركز التكوّر مصغّرة (تكبير < 1).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'بذلت سيارة شغلاً مقداره 120 جول، أي التالي صحيح؟', '["تتغير طاقتها الحركية بمقدار 120 جول", "تقل سرعتها بمقدار 120 م/ث", "تتغير طاقة وضعها بمقدار 120 جول", "تزداد سرعتها بمقدار 120 م/ث"]'::jsonb, 0, 'نظرية الشغل والطاقة: الشغل المبذول = التغير في الطاقة الحركية. شغل 120 جول → ΔKE = 120 جول.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'لتحويل الجلفانومتر إلى أميتر يتم توصيله مع:', '["مقاومة صغيرة على التوالي", "مقاومة كبيرة على التوازي", "مقاومة صغيرة على التوازي", "مقاومة كبيرة على التوالي"]'::jsonb, 2, 'الأميتر يقيس تيارات كبيرة فيحتاج مقاومة صغيرة (شنط shunt) على التوازي لتمرير معظم التيار وحماية الجلفانومتر.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'إذا كان مقدار العزم المؤثر عكس عقارب الساعة 70 N·m ومع عقارب الساعة 40 N·m، فإن عزم المحصلة:', '["30 N·m عكس عقارب الساعة", "30 N·m مع عقارب الساعة", "110 N·m عكس عقارب الساعة", "110 N·m مع عقارب الساعة"]'::jsonb, 0, 'العزم المحصل = 70 − 40 = 30 N·m. الاتجاه: عكس عقارب الساعة (لأنه الأكبر).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'روابط كيميائية', 'اختيار من متعدد', 'الرابطة في كلوريد الصوديوم:', '["فلزية", "أيونية", "تساهمية", "هيدروجينية"]'::jsonb, 1, 'كلوريد الصوديوم NaCl يتكوّن من فلز Na (يفقد إلكتروناً) ولا فلز Cl (يكتسب إلكتروناً) → رابطة أيونية.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'فصل مخاليط', 'اختيار من متعدد', 'طريقة لفصل مكونات الحبر المختلفة:', '["الترشيح", "البلور", "الكروماتوغرافيا", "التقطير"]'::jsonb, 2, 'الكروماتوغرافيا تفصل المكونات الملونة حسب سرعة انتقالها على الورق/الجل، وهي الأنسب لفصل أصباغ الحبر.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'الأوكتان من:', '["الألكينات", "الألكاينات", "الألكانات", "الهيدروكربونات"]'::jsonb, 2, 'الأوكتان C8H18 يتبع الصيغة العامة CnH2n+2 → فهو من الألكانات (روابط أحادية فقط).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'أي المجموعات العضوية صيغتها R−CO−NHR:', '["الكحولات", "الإسترات", "الكيتونات", "الأميدات"]'::jsonb, 3, 'المجموعة −CO−NHR تحوي C=O مرتبطة بـN−H → هذه مجموعة الأميد.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'كيمياء حيوية', 'اختيار من متعدد', 'ارتباط جزيئات جلوكوز عديدة يشكل:', '["السكروز", "المالتوز", "نشا", "فركتوز"]'::jsonb, 2, 'النشا polysaccharide يتكون من سلاسل طويلة من وحدات الجلوكوز. السكروز/المالتوز ثنائيات والفركتوز سكر أحادي.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'إذا كان يوجد غاز حرارته 340 K وضغطه ثابت وضاعفنا حجمه، فما هي حرارته الجديدة؟', '["680 K", "80 K", "40 K", "120 K"]'::jsonb, 0, 'قانون شارل (ضغط ثابت): V/T = ثابت. إذا تضاعف V فإن T يتضاعف. 340×2 = 680 K.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'عدد إلكترونات التكافؤ للماغنسيوم 12Mg:', '["2", "1", "3", "4"]'::jsonb, 0, 'التوزيع الإلكتروني لـMg(Z=12): 2,8,2 → المدار الأخير فيه إلكترونان = إلكترونات التكافؤ.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'عدد تأكسد الحديد في المركب FeO هو:', '["+2", "−2", "+3", "−3"]'::jsonb, 0, 'في FeO: الأكسجين دائماً −2 والمركب متعادل → Fe يجب أن يكون +2.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'كل ما يشغل حيزاً في الفراغ وله ثقل:', '["المادة", "الصوت", "الحرارة", "الهواء"]'::jsonb, 0, 'تعريف المادة: كل ما له كتلة (ثقل) ويشغل حيزاً (حجم). الصوت والحرارة طاقة لا مادة، والهواء حالة فقط.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'أي المركبات الآتية أصعب اختزالاً: Ag+ + e− → Ag، Hg2+ + 2e− → Hg، Al3+ + 3e− → Al، Mg2+ + 2e− → Mg', '["Ag+ + e− → Ag", "Hg2+ + 2e− → Hg", "Al3+ + 3e− → Al", "Mg2+ + 2e− → Mg"]'::jsonb, 3, 'كلما زاد نشاط الفلز كلما صعب اختزال أيونه. الماغنسيوم Mg من أنشط الفلزات في القائمة → أيونه الأصعب اختزالاً.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'احسب الكتلة بالجرام لعنصر K إذا كان عدد المولات 2 مول وكتلته المولية 39 جم/مول؟', '["87", "78", "19", "39"]'::jsonb, 1, 'الكتلة = عدد المولات × الكتلة المولية = 2 × 39 = 78 جم.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'ينتج عن التحليل الكهربائي للماء:', '["تغير كيميائي", "تغير فيزيائي", "مركب جديد", "لا يحدث شيء"]'::jsonb, 0, 'التحليل الكهربائي للماء يفكك جزيء H2O إلى عنصري H2 و O2 → تغير كيميائي (تكسير روابط).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'كيمياء حيوية', 'اختيار من متعدد', 'في تفاعل التصبن، يحدث تميه لـ ...', '["البروتين", "الستيرويد", "الجليسريد الثلاثي", "الليبيد الفوسفوري"]'::jsonb, 2, 'التصبن = تميه (hydrolysis) الجليسريد الثلاثي بقاعدة قوية لإنتاج صابون + جلسرين.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'نوع التفاعل في المعادلة: NaOH + HCl → NaCl + H2O', '["إحلال مزدوج", "استبدال", "حذف", "احتراق"]'::jsonb, 0, 'حمض + قاعدة → ملح + ماء. يتبادل الأيونان أماكنهما → إحلال مزدوج (تعادل).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'ماذا تسمى عناصر المجموعة 18 في الجدول الدوري؟', '["الفلزات القلوية", "الغازات الهيدروجينية", "الغازات الخاملة", "العناصر النشطة"]'::jsonb, 2, 'المجموعة 18 = الغازات النبيلة/الخاملة (He, Ne, Ar, Kr, Xe, Rn). مدارها الأخير مكتمل فلا تتفاعل.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'محاليل', 'اختيار من متعدد', 'أي الآتي ليس من الخواص الجامعة للمحاليل:', '["الارتفاع في درجة الغليان", "الضغط الاسموزي", "الضغط الجوي", "الانخفاض في درجة التجمد"]'::jsonb, 2, 'الخواص الجامعة: ارتفاع الغليان، انخفاض التجمد، الضغط الاسموزي، انخفاض ضغط البخار. الضغط الجوي خاصية للجو لا للمحلول.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'تحول المادة من الحالة الصلبة إلى الحالة الغازية دون المرور بالحالة السائلة:', '["التسامي", "الترسب", "التكثف", "التبخر"]'::jsonb, 0, 'التسامي (sublimation): صلب ← غاز مباشرة (مثل اليود والثلج الجاف).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'اتزان كيميائي', 'اختيار من متعدد', 'ما رتبة التفاعل R = k[A]²[B]²:', '["الأولى", "الثانية", "الثالثة", "الرابعة"]'::jsonb, 3, 'رتبة التفاعل = مجموع الأسس = 2+2 = 4 (رابعة).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'عدد النيوترونات في النواة:', '["العدد الذري", "العدد الكتلي", "الكتلي مطروحاً منه الذري", "الذري مطروحاً منه الكتلي"]'::jsonb, 2, 'نيوترونات = كتلي − ذري (لأن الكتلي = بروتونات + نيوترونات والذري = بروتونات).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'من ماذا تتكون النواة؟', '["بروتونات ونيوترونات", "بروتونات وإلكترونات", "إلكترونات فقط", "نيترونات وإلكترونات"]'::jsonb, 0, 'النواة تتكون من بروتونات (+) ونيوترونات (متعادلة). الإلكترونات تدور حول النواة في مدارات.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'يعتبر الـ H2PO3 ...', '["محلول", "مركب", "مخلوط متجانس", "مخلوط غروي"]'::jsonb, 1, 'H2PO3 صيغة كيميائية لمادة نقية بنسب ذرات ثابتة → مركب (وليس مخلوطاً).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'العنصر الأساسي في المركبات العضوية:', '["الهيدروجين", "الأكسجين", "النيتروجين", "الكربون"]'::jsonb, 3, 'الكيمياء العضوية = كيمياء مركبات الكربون. الكربون يكوّن سلاسل وحلقات لا حصر لها.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'نظير الرادون Rn المتكون بانبعاث جسيم ألفا حسب المعادلة: 226/88 Ra → Rn + 4/2 He²⁺ هو:', '["222/86 Rn", "226/89 Rn", "272/67 Rn", "292/69 Rn"]'::jsonb, 0, 'الكتلة: 226 − 4 = 222. العدد الذري: 88 − 2 = 86. الناتج: 222/86 Rn.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'عدد البروتونات في النواة هو العدد:', '["الذري", "الكتلي", "الكتلي مطروحاً منه الذري", "الذري مطروحاً منه الكتلي"]'::jsonb, 0, 'العدد الذري Z = عدد البروتونات في النواة، وهو الذي يميز كل عنصر.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'الكيمياء', 'اختيار من متعدد', 'إذا علمت أن الكتل الذرية للذرات H=1، O=16، فإن كتلة 0.25 مول من الماء بوحدة الجرام:', '["4.5", "9", "16", "18"]'::jsonb, 0, 'M(H2O) = 2(1)+16 = 18 جم/مول. الكتلة = 0.25 × 18 = 4.5 جم.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'تفاعلات كيميائية', 'اختيار من متعدد', 'تسمى عملية تغليف الحديد بفلز أو أكثر مقاومة للتأكسد:', '["التحلل", "الجلفنة", "التأسن", "الترسيب"]'::jsonb, 1, 'الجلفنة: تغليف الحديد بطبقة من الزنك (أو فلز نشط آخر) لحمايته من الصدأ بمبدأ الحماية المهبطية.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'كيمياء', 'كيمياء عضوية', 'اختيار من متعدد', 'فرع الكيمياء الذي يهتم بدراسة مركبات الكربون:', '["الكيمياء غير العضوية", "الكيمياء الحرارية", "الكيمياء العضوية", "الكيمياء الفيزيائية"]'::jsonb, 2, 'الكيمياء العضوية هي دراسة مركبات الكربون (ما عدا أكاسيد الكربون والكربونات).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'الأحياء', 'اختيار من متعدد', 'تفاعل يتم داخل نواة الخلية يسمى تفاعل:', '["كيميائي", "فيزيائي", "نووي", "حيوي"]'::jsonb, 2, 'تفاعل النواة = نووي (مثل الانقسام النووي أو نسخ DNA). الكيميائي خارج النواة في الأيض، والنووي مرتبط بـالكروموسومات.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'انقسام خلوي', 'اختيار من متعدد', 'إذا كانت نواة ثمر تحوي 6 كروموسومات في الطور الاستوائي، فكم تحوي كروموسوم في الطور الانفصالي؟', '["6", "12", "24", "8"]'::jsonb, 1, 'في الانفصالي تنفصل الكروماتيدات إلى قطبي الخلية، فيتضاعف العدد المرئي. 6×2 = 12 كروموسوم (كروماتيد منفصل).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'عدد حجرات قلب البرمائيات:', '["2", "3", "4", "5"]'::jsonb, 1, 'البرمائيات (ضفدع، سلمندر) قلبها مكوّن من 3 حجرات: أذينان وبطين واحد. الأسماك 2، الزواحف 3 (التماسيح 4)، الطيور والثدييات 4.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'عندما يحدث خلل للخط الجانبي للسمكة فإنها تصبح غير قادرة على:', '["الاتزان", "التغذي", "التجديف", "التنفس"]'::jsonb, 0, 'الخط الجانبي عضو حسي يكشف اهتزازات الماء والتيارات → يفقد توازنه عند تلفه.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'أين تحدث عملية التخمر؟', '["النواة", "الميتوكوندريا", "السيتوبلازم", "الغشاء البلازمي"]'::jsonb, 2, 'التخمر تنفّس لاهوائي يتم في السيتوبلازم (لا يحتاج ميتوكوندريا)، ينتج طاقة قليلة من الجلوكوز.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'قشور السردين من القشور:', '["القرصية", "المعينية اللامعة", "الصفائحية", "المشطية"]'::jsonb, 0, 'السردين من الأسماك العظمية ذات القشور القرصية (cycloid) — رقيقة مستديرة. الصفائحية للأسماك الغضروفية والقرشية.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'أي مما يلي من المسكنات (المثبطات) التي تقلل من نشاط الجهاز العصبي؟', '["الكافيين", "النيكوتين", "مشروبات الطاقة", "الكحول"]'::jsonb, 3, 'الكحول مثبط للجهاز العصبي المركزي يبطئ النقل العصبي. الكافيين والنيكوتين منشطات.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'عند مضغ السكر، الإنزيم المؤثر على هضمه:', '["الأميليز", "الليبيز", "البيبسين", "التربسين"]'::jsonb, 0, 'الأميليز اللعابي يبدأ هضم النشا (متعدد سكريات) إلى مالتوز. الليبيز للدهون، البيبسين والتربسين للبروتين.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'سلوك', 'اختيار من متعدد', 'في سباقات الفروسية يلاحظ عدم تأثر الخيول من الحضور الجماهيري، هذا السلوك يسمى:', '["تعلم كلاسيكي شرطي", "تعلم إجرائي شرطي", "إدراكي", "التعود"]'::jsonb, 3, 'التعود (habituation): تعلّم بسيط بفقدان الاستجابة لمثير متكرر غير ضار (الجمهور لا يهدد فيتم تجاهله).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'وراثة', 'اختيار من متعدد', 'إذا كان كلا الوالدين يستطيع ثني لسانه، وهما غير متماثلي الجينات (Tt)، فما الطرز الجينية المحتملة لأبنائهما؟', '["TT فقط", "tt فقط", "TT, Tt, tt", "TT, tt"]'::jsonb, 2, 'Tt × Tt → نسبة 1:2:1 من TT:Tt:tt (مربع بانيت كلاسيكي).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'توزيع الإبل في بيئتها يكون:', '["تكتلي", "منتظم", "عشوائي", "محدود"]'::jsonb, 0, 'الإبل تعيش في قطعان (مجموعات) حول موارد الماء والكلأ → توزيع تكتلي (clumped).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'استعمال بدائيات النوى لإزالة السموم من مياه البحر يطلق عليه:', '["معالجة حيوية", "زيادة حيوية", "تنقية مياه البحر", "تحلية مياه البحر"]'::jsonb, 0, 'المعالجة الحيوية (bioremediation): استخدام كائنات حية لإزالة الملوثات. هنا البكتيريا تحلل السموم.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'وراثة', 'اختيار من متعدد', 'شريط DNA ترتيبه من الأعلى للأسفل C-A-T-G-T، فما الشريط المتمم له؟', '["CUUGU", "GTACA", "CATGT", "GTAGA"]'::jsonb, 1, 'التتامم: A↔T و C↔G. C→G، A→T، T→A، G→C، T→A = GTACA.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'أمراض ومناعة', 'اختيار من متعدد', 'أي الاقتراحات التالية تختار لمكافحة مرض النوم الإفريقي؟', '["مكافحة البعوض", "القضاء على النمل الأبيض", "مكافحة ذبابة التسي تسي", "غسل الخضروات جيداً"]'::jsonb, 2, 'مرض النوم الإفريقي يسببه طفيل التريبانوسوما الذي ينتقل عبر ذبابة التسي تسي → السيطرة على الناقل.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'أمراض ومناعة', 'اختيار من متعدد', 'يحدث مرض الملاريا بانتقال طفيل البلازموديوم بواسطة حشرة ناقلة تسمى:', '["ذبابة تسي تسي", "حشرة ريدفويد", "البرغوث", "أنثى بعوضة الأنوفليس"]'::jsonb, 3, 'أنثى بعوضة الأنوفليس هي العائل الناقل لطفيل البلازموديوم المسبب للملاريا.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'علم الحيوان', 'اختيار من متعدد', 'تستطيع اللاسعات صيد الفرائس من جميع الاتجاهات بسبب وجود:', '["تناظر شعاعي", "عدم وجود أنسجة", "هيكل دعامي مائي", "تناظر جانبي"]'::jsonb, 0, 'اللاسعات (مرجان، قنديل البحر) لها تناظر شعاعي → الخلايا اللاسعة موزعة حول المركز فتصطاد من كل الاتجاهات.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'تستطيع الفقمة تحديد موقع فريستها في المياه المظلمة عن طريق شواربها، ما السبب في ذلك؟', '["الحماية", "العزل", "الإحساس", "التواصل"]'::jsonb, 2, 'شوارب الفقمة عضو حسي شديد الحساسية يلتقط اضطرابات الماء التي تسببها الأسماك → إحساس.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'تشريح', 'اختيار من متعدد', 'يسمّى الجزء الذي يفصل التجويف الصدري عن التجويف البطني في جسم الإنسان:', '["عضلات الصدر", "عضلات البطن", "الحجاب الحاجز", "عظام الأضلاع"]'::jsonb, 2, 'الحجاب الحاجز (diaphragm) عضلة قبّية تفصل التجويفين وتؤدي دوراً رئيسياً في التنفس.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'بيئة', 'اختيار من متعدد', 'نظام المكافحة الحيوية هو إدخال مخلوق حي في بيئة للقضاء على مخلوقات حية أخرى ضارة، هذه العلاقة يمكن أن تكون:', '["تطفل أو تقايض", "تكافل أو تقايض", "تطفل أو افتراس", "افتراس أو تعايش"]'::jsonb, 2, 'المكافحة الحيوية تستغل علاقتي التطفل (طفيليات تهاجم الآفات) أو الافتراس (مفترسات تأكل الآفات).', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'كيمياء حيوية', 'اختيار من متعدد', 'أي مما يلي يدخل في تركيب جزيء الطاقة ATP؟', '["جزيء الماء", "مجموعة فوسفات ثلاثية", "قاعدة نيتروجينية من النوع ثايمين", "سكر الفركتوز"]'::jsonb, 1, 'ATP = أدينوسين (أدينين + رايبوز) + 3 فوسفات. الروابط بين الفوسفات الثلاث هي خازن الطاقة.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'انقسام خلوي', 'اختيار من متعدد', 'انقسام السيتوبلازم في أي مرحلة من دورة الخلية؟', '["C", "G1", "M", "G2"]'::jsonb, 0, 'السيتوكاينيسيس (C) = انقسام السيتوبلازم يحدث بعد الانقسام النووي (M) لإكمال انفصال الخليتين.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'أمراض ومناعة', 'اختيار من متعدد', 'عند البحث عن مسببات شلل الأطفال، أي المواضيع تفيد بحثك؟', '["الأمراض الفيروسية", "الأمراض البكتيرية", "الأمراض فطرية", "الحشرات المسببة للأمراض"]'::jsonb, 0, 'شلل الأطفال (poliomyelitis) يسببه فيروس البوليو → الأمراض الفيروسية.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'أحياء', 'الأحياء', 'اختيار من متعدد', 'افترض أن خلية بكتيرية من نوع سالمونيلا سقطت على غذاء مكشوف وكانت الظروف مناسبة لنموها، كم عدد الخلايا البكتيرية الناتجة بعد ساعتين إذا كانت تتكاثر كل 20 دقيقة؟', '["16", "32", "64", "128"]'::jsonb, 2, 'ساعتان = 120 دقيقة. عدد الانقسامات = 120/20 = 6. الخلايا الناتجة = 2^6 = 64.', false, 'f62fd04b-fcf1-e144-5931-039d178c582e'::uuid, 'active', false);

COMMIT;

-- Total inserted: 115 questions