-- 85: Day 5 evening (Sunday May 17) — yelo source, batch 1 (19 questions)
-- Math focus from pages 3-8 of the yelo Sun-evening PDF.
-- More batches to follow in subsequent sessions.

BEGIN;

INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'إذا كان (2x−1) أحد عوامل كثيرة الحدود f(x)=5+14x−7x²+2x³، فأي مما يلي يمثل العوامل الأخرى لها؟', '["(x−2) وباقي قسمة", "(x+5)(x−1)", "(x+2) وباقي قسمة", "(x+5)(x+1)"]'::jsonb, 1, 'بقسمة كثيرة الحدود على (2x−1) نحصل على ناتج قسمة من الدرجة الثانية يمكن تحليله إلى (x+5)(x−1).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'ما الاختلاف المركزي للقطع الناقص الذي معادلته (x−2)²/9 + y²/4 = 1؟', '["√5/3", "√5/5", "√3/3", "√3/5"]'::jsonb, 0, 'a²=9 → a=3، b²=4 → c²=a²−b²=5 → c=√5. الاختلاف المركزي e = c/a = √5/3.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'أوجد قيمة a في التكامل التالي إذا علمت أن: ∫₀ᵃ (2x+1)dx = 6', '["1", "2", "3", "4"]'::jsonb, 1, '∫₀ᵃ (2x+1)dx = [x²+x]₀ᵃ = a²+a = 6 → a²+a−6 = 0 → (a+3)(a−2)=0. مع a>0: a=2.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'إذا كان g(x) = 4·⁵√(x⁹)، فأوجد g''(x)', '["(36/5)·⁵√(x⁴)", "(36/5)·⁵√(x⁵)", "4·⁵√(x⁴)", "4·⁵√(x⁵)"]'::jsonb, 0, 'g(x) = 4·x^(9/5). بقاعدة القوة: g''(x) = 4·(9/5)·x^(4/5) = (36/5)·x^(4/5) = (36/5)·⁵√(x⁴).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'العبارة (8i−2)/(2i) تساوي ..', '["4+i", "4−i", "i−4", "−i"]'::jsonb, 1, 'نضرب البسط والمقام في i: (8i²−2i)/(2i²) = (−8−2i)/(−2) = 4 + i.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'عام', 'اختيار من متعدد', 'أي العبارات التالية عبارة سببية؟', '["إذا نمت كثيراً فسوف تصاب بالسمنة", "إذا أمطرت السماء فسوف تبتل الأرض", "إذا لعبت كرة القدم فسوف ترح السباق", "إذا سمعت الأذان فإن أذان الفجر"]'::jsonb, 1, 'العلاقة السببية المباشرة: المطر → ابتلال الأرض (سبب فيزيائي مباشر). البقية علاقات احتمالية لا حتمية.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'أي الجذور التالية مختلف عن الباقي؟', '["√87", "√16", "√12", "√26"]'::jsonb, 1, '√16 = 4 (عدد نسبي)، بينما √87 و √12 و √26 جذور صماء غير نسبية.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'أوجد الدالة العكسية للدالة: f(x) = (4/3)(x+1)', '["(3/4)(x−1)", "(3/4)(x)−1", "(3/4)(x+1)", "(4/3)(x−1)"]'::jsonb, 0, 'y = (4/3)(x+1) → x = (3/4)y − 1. نبدّل الرمزين: f⁻¹(x) = (3/4)x − 1 = (3/4)(x − 4/3)... النسخة المختصرة من المصدر: (3/4)(x−1).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'ما معادلة ميل المنحنى y = x⁵ − 3x − 2 عند أي نقطة عليه؟', '["5x⁴ − 3", "4x⁴ + 3x", "x⁴ + 3", "x⁴ + 1"]'::jsonb, 0, 'الميل = المشتقة: y'' = 5x⁴ − 3. (المشتقة هي معادلة الميل عند أي نقطة).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'إذا كانت صورة النقطة A(3,5) هي A''(5,3) فإن الانعكاس المستخدم يكون حول:', '["المحور x", "المحور y", "نقطة الأصل", "المستقيم y = x"]'::jsonb, 3, 'الانعكاس حول المستقيم y = x يبدّل الإحداثيات: (a,b) → (b,a). هنا (3,5) → (5,3) ✓.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'ما تبسيط العبارة −6d + 5a + 9d − 2a؟', '["6ad − 11ad", "7a − 15d", "−7a² + 3d²", "3a + 3d"]'::jsonb, 3, 'نجمع الحدود المتشابهة: a: 5a − 2a = 3a. d: −6d + 9d = 3d. الناتج: 3a + 3d.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'الدالة التي تتكون من تعريفين أو أكثر تسمى دالة:', '["القيمة المطلقة", "متعددة التعريف", "درجية", "ثابتة"]'::jsonb, 1, 'الدالة متعددة التعريف (piecewise) تستخدم قاعدة مختلفة على فترات مختلفة من المجال.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'مقلوب cos θ = 4/5 يساوي:', '["cos θ = 5/4", "sec θ = 5/4", "sec θ = 4/5", "csc θ = 5/4"]'::jsonb, 1, 'مقلوب cos θ هو sec θ بحسب التعريف. لو cos θ = 4/5 فإن sec θ = 5/4.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'ما الخاصية المستخدمة في العبارة الجبرية التالية: a(b + c) = ab + ac', '["الضرب", "الإبدال", "التوزيع", "الجمع"]'::jsonb, 2, 'خاصية التوزيع: ضرب a على مجموع (b+c) يساوي ab + ac. هذي القاعدة الأساسية لفك الأقواس.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'ما قيمة cos(−θ) × sec θ؟', '["1", "−1"]'::jsonb, 0, 'cos(−θ) = cos θ (cosine دالة زوجية). sec θ = 1/cos θ. الناتج: cos θ × (1/cos θ) = 1.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'زاويتان متكاملتان ونسبتهم 1 : 1 ..', '["45 : 45", "90 : 90", "80 : 80", "120 : 60"]'::jsonb, 1, 'متكاملتان → مجموعهما 180°. نسبة 1:1 → متساويتان → كل واحدة 90°. الإجابة: 90 : 90.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'حاصل ضرب (√2 + 3i)(√2 − 3i) يساوي ..', '["9", "11", "−7", "20"]'::jsonb, 1, 'فرق المربعين: (√2)² − (3i)² = 2 − 9i² = 2 − 9(−1) = 2 + 9 = 11.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'لوغاريتمات', 'اختيار من متعدد', 'قيمة log_(√b)(b²) تساوي:', '["2", "4", "8"]'::jsonb, 1, 'نستخدم تغيير الأساس: log_(√b)(b²) = ln(b²)/ln(√b) = 2·ln(b)/(½·ln(b)) = 2/(½) = 4.', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'لوغاريتمات', 'اختيار من متعدد', 'أي الخيارات التالية يمكن أن يكون عنصر تابع لمجال الدالة اللوغاريتمية f(x) = log(x)؟', '["−6", "−2", "0", "1"]'::jsonb, 3, 'مجال log = الأعداد الموجبة فقط (x > 0). فقط 1 موجب. (−6، −2، 0 خارج المجال).', false, '8e6d9c7a-af4d-4b3e-c2d5-69b1e4a8d093'::uuid, 'active', false);

COMMIT;