-- 95: Day 5 morning (hamma) — batch 1: math (20 questions, pages 3-24)

BEGIN;

INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'خطّان متعامدان عند نقطة الأصل تقاطعهما زاويتان متكاملتان ∠1 و ∠2 من نفس الجانب. إذا كان m∠1 = 40°، فما قياس ∠2؟', '["30°", "40°", "50°", "60°"]'::jsonb, 2, 'الخطّان متعامدان يكوّنان زاوية قائمة 90°. ∠1 و ∠2 متكاملتان مع الزاوية القائمة، فمجموعهما = 90°. إذاً m∠2 = 90° − 40° = 50°.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'ما صورة النقطة B(2, 3) الناتجة عن الإزاحة (x, y) → (x + 4, y − 5)؟', '["(6, 0)", "(4, −5)", "(6, −2)", "(−2, 6)"]'::jsonb, 2, 'نطبّق الإزاحة: B(2, 3) → (2 + 4, 3 − 5) = (6, −2).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'في متوازي أضلاع، زاويتان متجاورتان قياسهما x° و (3x)°. ما قيمة x؟', '["35", "40", "45", "60"]'::jsonb, 2, 'في متوازي الأضلاع، الزاويتان المتجاورتان متكاملتان (مجموعهما 180°). إذاً x + 3x = 180 → 4x = 180 → x = 45°.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'إذا كان 2[[−3, 0], [1, 5]] − [[x, 4], [−6, 0]] = [[−8, −4], [8, 10]]، فما قيمة x؟', '["2", "−2", "−3", "−6"]'::jsonb, 0, 'بمقارنة العنصر في الصف 1 العمود 1: 2(−3) − x = −8 → −6 − x = −8 → x = 2.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'إذا كانت C = 4[[2, 3], [−1, 0]] − 3[[−2, 1], [0, −1]]، فما قيمة العنصر C₂₁ (الصف الثاني، العمود الأول)؟', '["−4", "−1", "1", "2"]'::jsonb, 0, 'C₂₁ = 4(−1) − 3(0) = −4 − 0 = −4.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'في مثلث ABC، النقطة F هي مركز المثلث (نقطة تقاطع المتوسطات). إذا كان T منتصف الضلع BC وكان FT = 3، فما طول AF؟', '["12", "9", "6", "4"]'::jsonb, 2, 'المركز الهندسي للمثلث يقسم كل متوسط بنسبة 2:1، حيث الجزء الأطول (من الرأس للمركز) ضعف الجزء الأقصر (من المركز لمنتصف الضلع). إذاً AF = 2 × FT = 2 × 3 = 6.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'لوغاريتمات', 'اختيار من متعدد', 'ما قيمة log₆(∛36)؟', '["2/3", "3/2", "11/3", "6"]'::jsonb, 0, '∛36 = 36^(1/3) = (6²)^(1/3) = 6^(2/3). إذاً log₆(6^(2/3)) = 2/3.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'إذا كان cos θ = √3/2 حيث 0° ≤ θ ≤ 360°، فما قيمة θ؟', '["{30°, 120°}", "{30°, 150°}", "{30°, 300°}", "{30°, 330°}"]'::jsonb, 3, 'cos θ = √3/2 موجبة، فالزاويتان في الربع الأول والرابع. الزاوية المرجعية = 30°، لذا: θ = 30° (الربع الأول) و θ = 360° − 30° = 330° (الربع الرابع).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'لوغاريتمات', 'اختيار من متعدد', 'ما حل المعادلة log₂(4x) + log₂5 = log₂100؟', '["√5", "5", "5√5", "20"]'::jsonb, 1, 'بتجميع اللوغاريتمات: log₂(4x · 5) = log₂100 → 20x = 100 → x = 5.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'لوغاريتمات', 'اختيار من متعدد', 'ما قيمة log₂8؟', '["2⁴", "8²", "8", "3"]'::jsonb, 3, 'log₂8 = log₂(2³) = 3 (لأن 2³ = 8).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'ما قيمة lim_{x→5} (x² − 25)/(x − 5)؟', '["5", "10", "15", "25"]'::jsonb, 1, 'x² − 25 = (x − 5)(x + 5). فالنهاية = lim (x + 5) عند x = 5 = 10.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'ما معادلة خط التقارب الأفقي للدالة f(x) = (8x + 2)/(4x − 1)؟', '["y = 2", "x = 2", "y = 3", "x = 3"]'::jsonb, 0, 'درجة البسط = درجة المقام = 1. خط التقارب الأفقي = نسبة معاملي الحد الأعلى = 8/4 = 2. إذاً y = 2.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'ما قيمة lim_{x→0} (x² · cos x)؟', '["0", "1", "2", "3"]'::jsonb, 0, 'عند x → 0: x² → 0 و cos x → cos 0 = 1. النهاية = 0 × 1 = 0.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'متتابعات', 'اختيار من متعدد', 'إذا كان لدينا المتجهان A = ⟨3, 4⟩ و B = ⟨2, −1⟩، فأوجد 3A − B.', '["⟨7, 13⟩", "⟨1, 5⟩", "⟨11, 13⟩", "⟨7, 3⟩"]'::jsonb, 0, '3A = ⟨9, 12⟩، إذاً 3A − B = ⟨9 − 2, 12 − (−1)⟩ = ⟨7, 13⟩.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'الدالة f(x) = x³ + 5x² − x هي دالة..', '["فردية وزوجية معاً", "ليست فردية وليست زوجية", "زوجية", "فردية"]'::jsonb, 1, 'f(−x) = −x³ + 5x² + x. هذا لا يساوي f(x) (فليست زوجية)، ولا يساوي −f(x) (فليست فردية). إذاً الدالة لا فردية ولا زوجية.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'ما مدى الدالة f(x) = |x − 2| + 3؟', '["(0, ∞)", "[3, ∞)", "(2, ∞)", "(1, ∞)"]'::jsonb, 1, 'القيمة المطلقة |x − 2| ≥ 0 لكل x، وأدنى قيمة لها 0 عند x = 2. فأدنى قيمة لـ f(x) = 0 + 3 = 3. المدى = [3, ∞).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'أوجد مشتقة الدالة f(x) = 3π/4.', '["0", "3π/4", "1", "π"]'::jsonb, 0, '3π/4 ثابت (لا يحوي متغيراً). مشتقة أي دالة ثابتة تساوي صفر.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'ما قيمة x التي تجعل الدالة f(x) = 1/(x² − 4x + 4) غير معرّفة؟', '["4", "2", "−2", "−4"]'::jsonb, 1, 'الدالة غير معرّفة عند المقام = 0. x² − 4x + 4 = (x − 2)² = 0 → x = 2.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'أوجد الدالة العكسية للدالة f(x) = √(x + 3).', '["f⁻¹(x) = x² + 3، x ≥ 0", "f⁻¹(x) = x² − 3، x ≥ 0", "f⁻¹(x) = x² + 3، x ≤ 0", "f⁻¹(x) = x² − 3، x ≤ 0"]'::jsonb, 1, 'نضع y = √(x + 3) → y² = x + 3 → x = y² − 3. نبدّل المتغيّرات: f⁻¹(x) = x² − 3. مدى الدالة الأصلية ≥ 0، فمجال العكسية x ≥ 0.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'متتابعات', 'اختيار من متعدد', 'إذا كان u = ⟨b, −2, 1⟩ و v = ⟨−2, −1, 4⟩، فما قيمة b التي تجعل المتجهين متعامدين؟', '["−5", "−3", "3", "6"]'::jsonb, 2, 'المتجهان متعامدان ⟺ حاصل ضربهما القياسي = 0. u · v = (b)(−2) + (−2)(−1) + (1)(4) = −2b + 2 + 4 = −2b + 6 = 0 → b = 3.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'للدالة f(x) = (x + 3)/(x² − 2) خط تقارب أفقي عند..', '["y = 2", "y = 0", "y = 1", "y = −3/2"]'::jsonb, 1, 'درجة البسط (1) أصغر من درجة المقام (2). في هذه الحالة خط التقارب الأفقي دائماً y = 0.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);

COMMIT;
