-- 96: Day 5 morning (hamma) — batch 2: math (20 questions, pages 25-48)

BEGIN;

INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'ما الدالة الأصلية للدالة f(x) = 4x + 3/x²؟', '["2x² − 3/x + C", "2x² − 3/x² + C", "2x − x/3 + C", "4x + x/3 + C"]'::jsonb, 0, '∫(4x + 3x⁻²)dx = 4·(x²/2) + 3·(x⁻¹/−1) + C = 2x² − 3/x + C.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'إذا كانت ∠1 و ∠2 زاويتان متكاملتان (مجموعهما 180°)، وكان m∠1 = 120°، فما قياس m∠2؟', '["30°", "40°", "50°", "60°"]'::jsonb, 3, 'الزاويتان المتكاملتان مجموعهما 180°. إذاً m∠2 = 180° − 120° = 60°.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'حساب مثلثات', 'اختيار من متعدد', 'إذا كان cos θ = 2/7 و 270° < θ < 360° (الربع الرابع)، فأوجد قيمة tan θ.', '["−3√5/2", "3√5/2", "2/7", "−2/7"]'::jsonb, 0, 'sin²θ = 1 − cos²θ = 1 − 4/49 = 45/49، إذاً sin θ = ±3√5/7. في الربع الرابع sin θ سالب → sin θ = −3√5/7. وعليه: tan θ = sin θ/cos θ = (−3√5/7) ÷ (2/7) = −3√5/2.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'ما معادلة القطع الزائد الذي مركزه (2, −4) وإحدى بؤرتيه (7, −4) وطول محوره القاطع 8 وحدات؟', '["9(x − 2)² − 16(y + 4)² = 144", "16(x − 2)² − 9(y + 4)² = 144", "9(x − 2)² + 16(y + 4)² = 144", "16(x − 2)² + 9(y + 4)² = 144"]'::jsonb, 0, 'المحور القاطع أفقي (المركز والبؤرة على نفس المستوى y). 2a = 8 → a = 4، فـ a² = 16. c = |7 − 2| = 5، إذاً b² = c² − a² = 25 − 16 = 9. الصيغة: (x−2)²/16 − (y+4)²/9 = 1، ضرب الطرفين في 144: 9(x−2)² − 16(y+4)² = 144.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'إذا كانت f(x) = 3/(x² + 5) و g(x) = √(x + 10)، فأوجد (f∘g)(3).', '["√(143/14)", "5/6", "1/6", "(14√3 + 3)/14"]'::jsonb, 2, 'g(3) = √(3 + 10) = √13. ثم f(√13) = 3/((√13)² + 5) = 3/(13 + 5) = 3/18 = 1/6.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'إذا كان A = [[2, 0], [0, 2]] و B = [[3, 0], [0, 3]]، فأوجد 3A − B.', '["B", "A", "A − B", "A + B"]'::jsonb, 0, '3A = [[6,0],[0,6]]. 3A − B = [[6−3, 0−0],[0−0, 6−3]] = [[3,0],[0,3]] = B.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'عام', 'اختيار من متعدد', 'احتجنا إلى 6 قطع مستقيمة لتكوين شبكة 2 × 2 (مرسومة كأطر طولية فقط). كم عدد القطع المستقيمة اللازمة لتكوين شبكة 4 × 4؟', '["16", "14", "10", "8"]'::jsonb, 2, 'شبكة n × n تتكوّن من (n+1) خطّاً أفقياً و(n+1) خطّاً رأسياً، فالمجموع = 2(n+1). عند n=2: 2(3) = 6 ✓. عند n=4: 2(5) = 10.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'إذا كان −4x + 4y = 0، فإن..', '["x = y", "x = −y", "x = −4y", "x = 4y"]'::jsonb, 0, '−4x + 4y = 0 → 4y = 4x → y = x، أي x = y.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'متتابعات', 'اختيار من متعدد', 'أوجد طول المتجه AB إذا كانت نقطة بدايته (2, 1, 0) ونقطة نهايته (0, 3, 1).', '["3", "4", "5", "62"]'::jsonb, 0, 'AB = (0−2, 3−1, 1−0) = (−2, 2, 1). طوله = √((−2)² + 2² + 1²) = √(4+4+1) = √9 = 3.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'عام', 'اختيار من متعدد', 'أيّ التالي مختلف عن الباقي؟', '["√87", "√12", "√16", "√26"]'::jsonb, 2, '√16 = 4 عدد نسبي (الجذر التربيعي لعدد مربّع كامل). أمّا √87 و √12 و √26 فجذورها أعداد غير نسبية (غير مربّعات كاملة).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'خطّان متعامدان يكوّنان زاوية قائمة. إذا قطع خطٌ ثالث أحدهما وشكّل معه زاوية 50°، فما قياس الزاوية x التي يشكّلها هذا الخطّ مع الخطّ الآخر؟', '["40°", "50°", "60°", "90°"]'::jsonb, 0, 'الزاويتان متتامتان (مجموعهما 90°) لأن الخطّين متعامدان. إذاً x = 90° − 50° = 40°.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'إذا كانت g(x) = 4·⁵√(x⁹)، فأوجد g''(x).', '["(36/5)·⁵√(x⁴)", "(36/5)·⁵√(x⁵)", "4·⁵√(x⁴)", "4·⁴√(x⁵)"]'::jsonb, 0, 'g(x) = 4·x^(9/5). g''(x) = 4 · (9/5) · x^((9/5)−1) = (36/5) · x^(4/5) = (36/5)·⁵√(x⁴).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'عام', 'اختيار من متعدد', 'أيّ العبارات التالية تمثّل علاقة سببية حقيقية (سبب ينتج عنه نتيجة)؟', '["إذا نمتَ كثيراً، فسوف تُصاب بالسمنة", "إذا أمطرت السماء، فسوف تبتل الأرض", "إذا لعبتَ كرة القدم، فسوف تربح السباق", "إذا سمعتَ الأذان، فإنه أذان الفجر"]'::jsonb, 1, 'العلاقة السببية تتطلّب أن السبب يؤدّي مباشرة إلى النتيجة. المطر يبلّل الأرض دائماً (علاقة فيزيائية مباشرة). باقي الخيارات إمّا مرتبطة بعوامل أخرى (النوم والسمنة)، أو زائفة (الكرة والسباق)، أو غير حصرية (الأذان للفجر فقط).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'دوال', 'اختيار من متعدد', 'يمثّل المنحنى التالي دالة قيمة مطلقة مفتوحة للأسفل، رأسها عند النقطة (3, 0). ما معادلة الدالة؟', '["f(x) = −|x − 3|", "f(x) = −|x + 5|", "f(x) = −|x| + 5", "f(x) = −|x| − 5"]'::jsonb, 0, 'الدالة |x − h| لها رأس عند (h, 0) وتفتح للأعلى. الإشارة السالبة تجعلها تفتح للأسفل مع نفس الرأس. الرأس (3, 0) → f(x) = −|x − 3|.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'إذا كان lim_{x→1}(x² − bx + 2) = 11، فما قيمة b؟', '["−9", "−8", "10", "12"]'::jsonb, 1, 'الدالة كثيرة الحدود متّصلة عند x=1، فالنهاية = القيمة. (1)² − b(1) + 2 = 11 → 1 − b + 2 = 11 → 3 − b = 11 → b = −8.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'احسب ميل مماس المنحنى f(x) = x² − x عند النقطة x = 1.', '["2", "1", "−1", "−2"]'::jsonb, 1, 'ميل المماس = f''(x) عند تلك النقطة. f''(x) = 2x − 1، فعند x=1: f''(1) = 2(1) − 1 = 1.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'أوجد مشتقة الدالة f(x) = −x² + 6x عند النقطة (1, 5).', '["4", "−4", "2", "−2"]'::jsonb, 0, 'f''(x) = −2x + 6. عند x = 1: f''(1) = −2(1) + 6 = 4.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'تفاضل وتكامل', 'اختيار من متعدد', 'ما قيمة lim_{x→∞} (x² − 3x³)/(2x³ + 5)؟', '["3/2", "1", "−1", "−3/2"]'::jsonb, 3, 'عند x → ∞، الحدود الأعلى رتبة تسيطر: في البسط −3x³، في المقام 2x³. النسبة = −3/2.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'هندسة', 'اختيار من متعدد', 'أوجد الاختلاف المركزي للقطع الناقص (x − 2)²/9 + y²/4 = 1.', '["√5/3", "√3/5", "√13/3", "5/9"]'::jsonb, 0, 'a² = 9 (الأكبر، تحت x)، b² = 4. a = 3، b = 2. c = √(a² − b²) = √(9 − 4) = √5. الاختلاف المركزي e = c/a = √5/3.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'الخاصيّة المستخدمة في العبارة a(b + c) = ab + ac هي..', '["الإبدال", "التجميع", "التوزيع", "الإغلاق"]'::jsonb, 2, 'خاصيّة التوزيع (Distributive Property) تنصّ على أن: a(b + c) = ab + ac. أي ضرب a يتوزّع على كلّ من b و c.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);

COMMIT;
