-- 97: Day 5 morning (hamma) — batch 3: math + physics (10 unique questions, pages 49-72)
-- Many physics questions were duplicates with Sunday evening yelo (SQL 85-89) → skipped.

BEGIN;

INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'رياضيات', 'جبر', 'اختيار من متعدد', 'ما تبسيط العبارة: −2a + 9d + 5a − 6d؟', '["6ad − 11ad", "7a − 15d", "−7a² + 3d²", "3a + 3d"]'::jsonb, 3, 'نجمع الحدود المتشابهة: حدود a: −2a + 5a = 3a. حدود d: 9d − 6d = 3d. فالتبسيط = 3a + 3d.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'موجات', 'اختيار من متعدد', 'الديسبل (dB) هو وحدة قياس..', '["مستوى الصوت", "حدّة الصوت", "تردد الصوت", "طول موجة الصوت"]'::jsonb, 0, 'الديسبل (Decibel) وحدة لوغاريتمية تقيس مستوى شدّة الصوت بالنسبة لقيمة مرجعية. التردد يُقاس بالـ Hz، وحدّة الصوت تعتمد على التردد، وطول الموجة بالأمتار.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'من غير الممكن قياس زخم جسيم وتحديد موقعه بدقة في الوقت نفسه. يمثّل ذلك..', '["مبدأ هايزنبرغ للشك", "مبدأ باولي", "مبدأ أوفباو", "قاعدة هوند"]'::jsonb, 0, 'مبدأ الشك (Uncertainty Principle) لهايزنبرغ: لا يمكن قياس الزخم والموقع لجسيم بدقة لانهائية في نفس اللحظة (ΔxΔp ≥ ħ/2). أساس ميكانيكا الكم.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'قياسات', 'اختيار من متعدد', 'الترتيب الصحيح لوحدات قياس: (1) شريط متر، (2) ميزان زنبركي، (3) قارورة ماء، (4) ساعة هو..', '["1-لتر، 2-كيلوجرام، 3-متر، 4-ثانية", "1-كيلوجرام، 2-متر، 3-لتر، 4-ثانية", "1-متر، 2-كيلوجرام، 3-لتر، 4-ثانية", "1-ثانية، 2-لتر، 3-متر، 4-كيلوجرام"]'::jsonb, 2, 'شريط متر يقيس الطول → متر. الميزان الزنبركي يقيس الكتلة/الوزن → كيلوجرام. قارورة الماء تقيس الحجم → لتر. الساعة تقيس الزمن → ثانية. الترتيب: متر، كيلوجرام، لتر، ثانية.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء نووية', 'اختيار من متعدد', 'عند اضمحلال جسيمات ألفا في نواة (A, Z)، فإن العدد الذري Z والعدد الكتلي A الناتجين هما..', '["Z + 2 ، A + 4", "Z − 2 ، A + 4", "Z + 2 ، A − 4", "Z − 2 ، A − 4"]'::jsonb, 3, 'جسيم ألفا = نواة هيليوم ⁴₂He (بروتونان ونيوترونان). عند انبعاثه: العدد الذري ينقص بـ2 (Z − 2)، والعدد الكتلي ينقص بـ4 (A − 4). مثال: ²³⁸U → ²³⁴Th + α.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'ما الميزة التي تميّز المواد الموصلة عن المواد العازلة؟', '["وجود إلكترونات حرّة", "شحنة موجبة", "الإلكترونات مرتبطة بقوّة", "شحنة سالبة"]'::jsonb, 0, 'المواد الموصلة (كالمعادن) فيها إلكترونات تكافؤ حرّة الحركة بين الذرات، تتدفّق بسهولة عند تطبيق جهد كهربائي. المواد العازلة إلكتروناتها مرتبطة بقوّة بنوياتها، فلا توصّل.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'فيزياء حديثة', 'اختيار من متعدد', 'ظاهرة تُستخدم لتعريف العناصر باستخدام تردّد ضوء معيّن..', '["التأثير المغناطيسي", "الانبعاث الحراري", "طيف الانبعاث الذرّي", "السالبية الكهربائية"]'::jsonb, 2, 'طيف الانبعاث الذرّي (Atomic Emission Spectrum): عند إثارة الذرات تبعث ضوءاً بترددات محدّدة فريدة لكل عنصر، تشكّل بصمة طيفية تسمح بتعريفه.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرومغناطيسية', 'اختيار من متعدد', 'الجهاز الذي يحوّل الطاقة الكهربائية إلى طاقة حركية دورانية يسمّى..', '["المولّد الكهربائي", "المحوّل الكهربائي", "المحرّك الكهربائي", "المكثف الكهربائي"]'::jsonb, 2, 'المحرّك الكهربائي (Electric Motor) يحوّل الكهرباء → حركة دوران (مثل مراوح، خلّاطات). العكس: المولّد يحوّل الحركة → كهرباء. المحوّل يغيّر الجهد. المكثف يخزّن الشحنة.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'كهرباء', 'اختيار من متعدد', 'وحدة الفاراد (Farad) للسعة الكهربائية تكافئ..', '["أمبير·ثانية لكل فولت (A·s/V)", "نيوتن لكل متر", "كولوم لكل نيوتن", "جول لكل ثانية"]'::jsonb, 0, 'السعة C = Q/V (شحنة لكل جهد) → الفاراد = كولوم/فولت = (أمبير × ثانية)/فولت. الكولوم نفسه = أمبير·ثانية.', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);
INSERT INTO questions (section, subject, topic, question_type, question_text, choices, correct_index, explanation, is_top_repeated, leak_group_id, status, disabled) VALUES ('tahsili', 'فيزياء', 'ميكانيكا', 'اختيار من متعدد', 'انطلق رجل بدراجته فقطع 400 م جنوباً، ثم واصل السير 300 م شرقاً. ما مقدار الإزاحة المحصّلة بوحدة المتر؟', '["300", "400", "500", "600"]'::jsonb, 2, 'الإزاحتان متعامدتان (جنوب + شرق = 90°). المحصّلة = √(400² + 300²) = √(160000 + 90000) = √250000 = 500 م. (مثلث 3-4-5).', false, '7d5c8a6b-9e3f-4a2d-b1c4-58a0d3f7e982'::uuid, 'active', false);

COMMIT;
